### ISSUE TITLE
显示查询图标导致部分应用中剪切板出现问题，以及代理问题

### ISSUE THREAD

**Issue by Abrygzy** [tisfeng/Easydict#10]
## 描述问题

**问题1**: 在开启实验功能 “划词后自动显示查询图标” 后，在部分应用中如果 划词 -> 复制 -> 划另外一个词 之后，会导致上一步复制的结果无法粘贴，利用其他应用查看剪贴板记录时，发现在那一条确实存在，且之后没有新的剪切记录。关闭该试验功能后复制粘贴恢复正常。此bug在vscode, obsidian中出现，但在edge浏览器中未出现。

**问题2**: 似乎只有使用代理之后，才能在划词翻译时顺利自动识别源语言，并展开翻译详情。
<img width="427" alt="image" src="https://user-images.githubusercontent.com/53932200/216773669-f4cf91cb-35e7-4e6b-94ed-53b763773b77.png">
当不使用网络代理时，一方面需要手动指定语言（只测试了英语）才能显示详细的单词翻译，另一方面此时单词翻译详情不会自动展开。
<img width="414" alt="image" src="https://user-images.githubusercontent.com/53932200/216773711-0efc830c-6151-488c-91a3-a8d740d5c343.png">

## 运行环境

- Device: MacBook Pro (intel, 13-inch, 2020)
- macOS: 13.2
- Easydict Version: 1.2.1

**Comment by tisfeng** [comment]
收到，感谢反馈，稍后我检查一下。

**Comment by tisfeng** [comment]
很奇怪，我试了一下，你说的两个问题我这边都无法复现 😓

问题1：我调试看了，确认 vscode 和 obsidian 都是通过 Auxiliary 实现取词的，按理说这种实现方式是不会影响剪贴板的。你可以再多尝试几个应用，看看哪些应用存在这种问题，我收集分析一下。

另外，麻烦你再次复现一下这个问题，然后导出日志发给我，我检查一下看看。
<img width="418" alt="image" src="https://user-images.githubusercontent.com/25194972/216799354-d4d2f221-32b1-42e7-89d4-e65bc869785a.png">

**Comment by Abrygzy** [comment]
感谢您的回复！ 
我尝试了电脑上的部分软件，目前存在此问题的软件为Logseq, Vscode, Obsidian, Apple Email, QQ (新版客户端)；
其余软件则没有这样的问题，包括Word, Edge,Pages, Keynote, Excel, 备忘录, 微信, Onenote等。
我使用了键盘监控软件Keycastr，发现在开启实验功能 “划词后自动显示查询图标”后，双击取词似乎会进行一次复制操作，但实际上没有复制到任何东西。
此外我发现这一问题的出现，似乎与软件 “判断是否为整个单词的机制”有关，因为以上bug似乎只出现在我双击选词，或者用光标选中整个单词的情况下，如果只选择单词的部分字母，则粘贴不会有问题。
以上操作可能不好描述，我将操作录屏，并导出了对应的日志，希望可以有帮助。
[Easydict log 2023-02-05 11-57-51-713.zip](https://github.com/tisfeng/Easydict/files/10610190/Easydict.log.2023-02-05.11-57-51-713.zip)

https://user-images.githubusercontent.com/53932200/216800805-4bbe6649-7bee-4c32-a786-2c0765833dbd.mov

**Comment by tisfeng** [comment]
感谢反馈，我仔细查了一下，这个问题确实存在，但比较奇怪的是，在我的电脑上 Logseq, VScode, Obsidian, QQ 都很正常，只有系统 Email 会出现这个问题。原因是 Email 不支持 Auxiliary，导致取词失败，这时就执行了备用的模拟快捷键取词。而这种方式目前存在问题，稍后我会修复。

但还是不清楚，为什么我的电脑上 VScode 这些应用取词表现都没有问题，可能我的 Apple M1，和 intel 不一样？ 🤔

**Comment by tisfeng** [comment]
问题2：麻烦看一下你的系统首选语言是哪些，是不是只有中文？ 你添加一个英语试试。

如果系统识别文本语言不是首选语言，则会尝试调用 API 识别，看一下你能否正常访问百度翻译 https://fanyi.baidu.com/#en/zh/good 

你这个问题描述，看起来像是查询语种识别的过程中卡住了，默认设置的最大查询时间是 30s，超时还是会采用系统语种识别的，你试试看，或者可以录个视频给我。

**Comment by Abrygzy** [comment]
我之前的系统首选语言确实不包括英文，目前我已经添加。从链接看百度翻译可以正常访问。
目前看确实像是识别中卡住了，因为我不开代理时、指定翻译语言是英文时，查词时达到最大查询时间，查询结果才会跳出来。我的操作录屏如下，视频最后的30s左右就是我在等待翻译结果弹出：

https://user-images.githubusercontent.com/53932200/217436868-5f751d8e-53d9-4332-9af1-2dbeed186638.mov

此外当不挂网络代理，不指定翻译语言是英文时，等待30s之后翻译仍不会自动弹出。

**Comment by tisfeng** [comment]
明白了，你这个问题卡住，应该是请求 Google 语种识别时卡住了。。这点很奇怪，因为我这边测试如果不开代理，请求 Google 会直接失败，但后续会尝试百度语种识别，所以不会存在卡住问题 😓 。 稍后我会优化代码，提供关于语种识别的选项，让用户可以选择使用 Google 还是百度语种识别进行优化。

**Comment by tisfeng** [comment]
> 不开代理时、指定翻译语言是英文时，查词时达到最大查询时间，查询结果才会跳出来

看了下代码，这个问题确实是 bug 导致，稍后我会修复。

**Comment by Abrygzy** [comment]
> 另外，如果修改了系统首选语言，好像是需要重启电脑才能生效，不然应用读取到的系统语言还会是之前的。

在录屏时，我已经修改首选语言并且重启。但我的首选语言除了中文与英文之外还有希腊语，不知道会不会造成影响。

**Comment by tisfeng** [comment]
这个倒不会。首选语言可以添加多种语言，Easydict 在识别文本语言时，会优先考虑首选项语言，给予它们更高的权重。比如查询单词 `heel`，这个词可能是英语，也可能是荷兰语，Easydict 倾向于把它识别为英语（因为英语更常用更普遍），但如果你的首选语言是荷兰语，那它就会识别为荷兰语。但即使你首选项中有希腊语，如果 heel 单词本身没有希腊语的可能性，那它就不可能被识别为希腊语。

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已修复了上面问题。但由于不同设备的环境比较复杂，你可以再测试验证一下。

**Comment by Abrygzy** [comment]
感谢，之前的问题在我的设备上已经完全解决

**Comment by xyjigsaw** [comment]
你好，我也出现这个问题了

**Comment by tisfeng** [comment]
@xyjigsaw 你好，具体什么问题？请详细说明。

如果是其他类似问题，请另外开 issue，若是相关问题，可以进行关联，这个问题已经解决了。
