### ISSUE TITLE
🐞 反馈问题：划词翻译快捷键失效

### ISSUE THREAD

**Issue by MoienBowen** [tisfeng/Easydict#102]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 问题描述

本来想尝试设置与 DeepL 一样的快捷键 command + c + c，发现 Easydict 不允许设置该快捷键组合（可以添加快捷键冲突检测？）。

稍后看到此前 issue，表示理解。 https://github.com/tisfeng/Easydict/issues/5

但我将快捷键设置为 option + c 后，无法正常获取选中内容。(仅应用首次后，首次调用有效。)

PS. 1.3.1 的 release notes 有错别字， 中午 -> 中文。

**Comment by Jerry23011** [comment]
Release Note 中错别字已修复，感谢纠正🙏

**Comment by tisfeng** [comment]
目前快捷键功能是借用了第三方库实现的，自带了一些检测阻止规则，如果要实现一个非常规的快捷键组合，如 Cmd+C+C，就得自己手动去实现。

`option + c` 如果没有冲突，应该是支持的，我试了一下，这个快捷键可以正常使用。

“无法正常获取选中内容”，这个具体是指什么，是所有应用中都不能取词吗？是否和其他软件快捷键冲突了？

“仅应用首次后，首次调用有效。”，重启应用是否恢复正常？这个比较奇怪，如果是和用户特定电脑环境有关，就很难查。

> 但我将快捷键设置为 option + c 后，无法正常获取选中内容。(仅应用首次后，首次调用有效。)

**Comment by MoienBowen** [comment]
我刚试了一下，我在 safari 里面（比如就是这个 issue 的页面）选取文字，然后 option + c，会唤起 easydict，但是文本框为空。
同时，我又试了一下选中我目前正在键入的这部分（在回复的输入框里），选取文字并使用相同快捷键，会唤起 easydict，且待翻译文本框中可以正常显示选取内容。
我又尝试更换了一个奇怪的快捷键，option + shift + G, 一切正常，看起来是快捷键冲突了。

**Comment by tisfeng** [comment]
还有问题吗，如果没有，我就关闭  issue 了。

**Comment by mortence** [comment]
我也有一样的问题， 设置 option + c 后在 chrome 里面可以唤出窗口，但是窗口中没有选中的词。换成 option + e 后就可以正常使用。像图片中这样，我选中了“ assigned”，唤出的窗口输入框是空白的，需要自己手动复制粘贴
![image](https://github.com/tisfeng/Easydict/assets/9278362/ac74442d-342b-4bdf-a4ec-2859ea25fa36)

**Comment by tisfeng** [comment]
这种情况，大概率是和电脑上其他应用的快捷键冲突了。
