### ISSUE TITLE
🚀 功能建议：希望统一所有窗口

### ISSUE THREAD

**Issue by MoienBowen** [tisfeng/Easydict#103]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 功能描述

希望可以使用 迷你窗口 的快捷键召唤出刚刚使用过的窗口（比如截图翻译），而不是一个独立的迷你窗口实例。

### 使用场景（可选）

- 使用截图翻译后（未 pin），进行其它操作。
- 想找回刚刚的翻译结果，无从下手。
- 使用迷你窗口快捷键，召唤出的为独立实例，而为此前的截图翻译实例。只能再次截图翻译。

### 期望结果

期望统一所有实例，无论是划词、截图，还是手动键入，都是同一个实例，这样快捷键召唤出的也是同一个。

**Comment by tisfeng** [comment]
因为设计中，【迷你窗口】和【侧悬浮窗口】是两个完全独立的窗口，应该有着不同的使用场景和功能，虽然目前暂时还未清晰区分开来。

如果你想打开截图翻译窗口，可以使用【输入翻译】，快捷键或点击菜单图标选项都行。

提供两个独立类型的窗口，是为了应对同时有多个查询需求场景的，例如，我本来在使用【迷你窗口】 翻译查看一篇文章，中途遇到了一个不熟悉的单词，这时候就可以钉住 【迷你窗口】，然后使用快捷键取词唤起【侧悬浮窗口】来查询单词。

> Easydict 有 3 种窗口类型，可以分别为它们设置不同的服务。
> 
> 迷你窗口：鼠标自动取词时显示。
> 侧悬浮窗口：快捷键取词和截图翻译时显示。
> 主窗口：默认关闭，可在设置中开启，程序启动时显示。（稍后会增强主窗口功能）

**Comment by tisfeng** [comment]
你这个建议也不错，对一些用户来说，可能并不需要两个窗口，那样对他们来说反而增加了复杂度。

我考虑一下，看是否可以提供一个选项，让用户选择全部只使用【侧悬浮窗口】，符合简洁的定位。

> 期望统一所有实例，无论是划词、截图，还是手动键入，都是同一个实例，这样快捷键召唤出的也是同一个。

**Comment by MoienBowen** [comment]
我理解你的场景了，确实不错。
其实主要问题是，悬浮侧窗口一点焦点转移，就再也找不回来了。比如我截图翻译文本（不 pin，有时候遮挡其它窗口），这时候鼠标点一下其它地方，翻译结果就消失了。
能不能添加个设置（类似于召唤悬浮窗口），召唤出来最近一次的悬浮侧窗口，并显示最近一次的翻译结果。

**Comment by Jerry23011** [comment]
> 能不能添加个设置（类似于召唤悬浮窗口），召唤出来最近一次的悬浮侧窗口，并显示最近一次的翻译结果。

我这边通过菜单栏点`输入翻译`或使用键盘快捷键`⌥A`即可调出上一次的翻译结果，不知道是否符合你的需求

**Comment by MoienBowen** [comment]
我知道问题出在哪里了，我大部分时间使用"显示迷你窗口"进行翻译，然而这个迷你窗口翻译的结果没办法召回。
可能您的设计思路是，每次使用这个快捷键，都是准备翻译新的东西，所以没有保存之前结果？
如果能同样调出上次的结果，那就太棒了。

**Comment by Jerry23011** [comment]
无论是侧悬浮窗口还是迷你窗口都可以打开上次的翻译结果呀

**Comment by MoienBowen** [comment]
确实，可能我之前操作有误，抱歉。
已关闭 issue。
