### ISSUE TITLE
🐞 反馈问题：自动清除换行符的逻辑仍有待改进

### ISSUE THREAD

**Issue by MoienBowen** [tisfeng/Easydict#104]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

https://github.com/tisfeng/Easydict/issues/16

如上，虽然 1.3.0 已经添加了此功能，但是目前自动清除换行符的逻辑仍有待改进。

### 重现步骤

部分论文中，由于翻页或者双行的问题，导致统一段落被分为两部分。目前版本中，疑似截图所选部分如果最后没有句号（或英文句号），不会触发清楚换行符功能。

此外，有些换行场景会将长单词分成两部分，比如：第一行结尾 easy-，第二行开头 dict。目前无法自动合并两部分并删除 -。

### 期望结果

解决以上两种场景。

macOS 捷径中调用的系统 OCR 即使最终没有句号，也可以较好的整合本文。印象中您也是使用系统 OCR，个人比较好奇您调用的 和 捷径中的 具体什么区别。如果有答案求解答。

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
拼接算法是比较复杂的，需要考虑各种使用场景，目前这个确实还需要不断完善。麻烦提供一下论文测试用例，稍后我优化看看。

> 疑似截图所选部分如果最后没有句号（或英文句号），不会触发清楚换行符功能


这个可以，这个处理应该比较简单。

> 此外，有些换行场景会将长单词分成两部分，比如：第一行结尾 easy-，第二行开头 dict。目前无法自动合并两部分并删除 -。

**Comment by tisfeng** [comment]
捷径是苹果封装好的黑盒成品，我这个只是调用了系统 OCR 的底层 API，具体文本换行拼接算法是自己实现的 https://github.com/tisfeng/Easydict/issues/16#issuecomment-1533270397

**Comment by MoienBowen** [comment]
换行的例子暂时找不到了，那个论文没存档。
不过‘-’的例子有一个：参考链接中论文，第 6 页右下角最后一段。
使用 easydict 的截图，原文中 “consump- tion“，而使用捷径中的 OCR, 该词被正确识别为“consumption”。所以 issue 中我也表示好奇捷径中的实现方式。

https://www.researchgate.net/profile/Elias-Bou-Harb/publication/365184574_A_Security_Assessment_of_HTTP2_Usage_in_5G_Service_Based_Architecture/links/636917e4431b1f53007a8321/A-Security-Assessment-of-HTTP-2-Usage-in-5G-Service-Based-Architecture.pdf

**Comment by tisfeng** [comment]
我比较好奇，按理说使用预览打开 PDF ，是可以直接选择文本的，为什么这种场景你们会使用  OCR  方式？虽然 OCR 识别准确度比较高了，但难免还是会出错的，因为我只有在不支持选中文本的情况下才用  OCR  的，我很好奇 😯

<img width="1355" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/eaab267a-e059-4968-b29e-a8a85bcb008e">

**Comment by MoienBowen** [comment]
有些 PDF 无法正确选取文本（选到某个地方就跳到另一个地方，造成文本不连续），我手边没有样本，不好意思。因此养成了截图识别的习惯。

**Comment by tisfeng** [comment]
ok，了解了。

**Comment by tisfeng** [comment]
新版本 [1.3.2](https://github.com/tisfeng/Easydict/releases/tag/1.3.2) OCR 已对以上两种场景进行了优化。
