### ISSUE TITLE
🐞 反馈问题：服务设置开关颜色和背景颜色有些难区分

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#106]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

在深色模式下，服务的开关关闭时和背景颜色几乎相同（数码取色器看就差了一点点）
这样会又些看不清开关本身和边缘的区别

### 重现步骤

- 系统改为深色模式
- 打开 Easydict 偏好设置
- 进入 服务
- 可以看到在任意服务开关的颜色和背景较难区分
<img width="462" alt="截屏2023-05-22 20 21 02" src="https://github.com/tisfeng/Easydict/assets/89069957/59d09258-c96e-4327-b671-046e1fd62826">

### 期望结果

在开关关闭时开关本身颜色能够和背景颜色区分开

### 解决方案（可选）

我自己编辑了一下颜色，取了两种
<img width="462" alt="截屏2023-05-22 20 21 05" src="https://github.com/tisfeng/Easydict/assets/89069957/71b00f73-56d8-441f-93fb-83f3436eb09f">
<img width="462" alt="截屏2023-05-22 20 25 17" src="https://github.com/tisfeng/Easydict/assets/89069957/100b3fc9-ac1b-48e0-8a2d-5b621acf57eb">

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR!

**Comment by tisfeng** [comment]
其实，这里应该调整背景颜色的，保持  1.3.0  版本效果，不然看起来会不协调。但有点奇怪，你电脑上这个界面效果和我这边看起来不一样？？

这是  1.3.0  版本效果

<img width="386" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/d2735ed2-9dcd-4ef9-b2aa-3863b632b883">

这是目前调整图片后的效果，稍后我再调一下颜色值吧。

<img width="386" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/fbca0cb8-9b91-42a5-add8-7c93a10f4c05">

**Comment by Jerry23011** [comment]
颜色不一样可能是系统设置中的 允许基于墙纸调整窗口色调 开关影响的

**Comment by tisfeng** [comment]
这个暂时先不关  issue，等合并后发新版本再关，避免有些用户没注意到关闭的  issue，又提了重复的。

**Comment by Jerry23011** [comment]
> 这个暂时先不关 issue，等合并后发新版本再关，避免有些用户没注意到关闭的 issue，又提了重复的。

本来想加 `fixed in next release` 的😄

**Comment by tisfeng** [comment]
修改后

<img width="386" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/55b93dc4-31e0-4b05-9fd3-e8dd7b7a1c04">

**Comment by tisfeng** [comment]
新版本 [1.3.2](https://github.com/tisfeng/Easydict/releases/tag/1.3.2) 已修复该问题。
