### ISSUE TITLE
外接显示器后，翻译时无法把界面固定在主屏幕

### ISSUE THREAD

**Issue by wobangnidashui** [tisfeng/Easydict#11]
如题，输入时每次都会跳动到副屏幕

**Comment by tisfeng** [comment]
如果是指 https://github.com/tisfeng/Easydict/issues/4 这个问题，那将会在下个版本进行优化。

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已支持了可选择浮窗出现的位置。
