### ISSUE TITLE
🐞 反馈问题：Microsoft Word中选中文本出现复制提示音

### ISSUE THREAD

**Issue by dukechain2333** [tisfeng/Easydict#111]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

在Word中每次选中文本都会触发系统的复制提示音，但是我并不打算翻译这段文字，剪贴板中似乎也没有出现划的这一段。

### 重现步骤

无

### 期望结果

在其他应用中，例如Chrome，选中文本并不会出现复制提示音，word也不应该有呀。

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
某些特殊应用空复制确实可能出现提示音，但如果你在设置中开启了【禁用空复制提示音】选项，理论上就不会有提示音了。

但奇怪的是，在我电脑上测试，Microsoft Word 本身是支持空复制的，就是说即使关闭【禁用空复制提示音】选项，也不会有提示音。

很诡异的问题，可能和这个问题 https://github.com/tisfeng/Easydict/issues/84#issuecomment-1537177866 类似， 又是和用户电脑环境有关？

**Comment by tisfeng** [comment]
@Jerry23011  麻烦你测试跟进一下这个问题。

**Comment by Jerry23011** [comment]
> @Jerry23011 麻烦你测试跟进一下这个问题。

好的

**Comment by Jerry23011** [comment]
@dukechain2333 方便问一下你的 Word 是什么版本吗？我的是 App Store 的 `16.73 (23051401)`，macOS `13.4 (22F66)`

**Comment by dukechain2333** [comment]
> @dukechain2333 方便问一下你的 Word 是什么版本吗？我的是 App Store 的 `16.73 (23051401)`，macOS `13.4 (22F66)`

和您一样

**Comment by Jerry23011** [comment]
您有尝试打开“禁用空复制提示音“选项吗？
<img width="300" alt="SCR-20230526-jskj" src="https://github.com/tisfeng/Easydict/assets/89069957/df07142a-d5d4-4d3b-9150-664bcd9dd726">

**Comment by dukechain2333** [comment]
> 确认一下，您有尝试打开“禁用空复制提示音“选项吗？ <img alt="SCR-20230526-jskj" width="300" src="https://user-images.githubusercontent.com/89069957/241104861-df07142a-d5d4-4d3b-9150-664bcd9dd726.png">

emmm我一直是开着的

**Comment by Jerry23011** [comment]
我现在在Word里面只有 关于Word 这个界面中拖动窗口或其中的视图才会出现提示音，但是 Xcode 中并没有 Debug 信息🥲
<img width="300" alt="SCR-20230526-jtrc" src="https://github.com/tisfeng/Easydict/assets/89069957/4fc797e1-166d-4024-9e47-4c5185e3e21a">

**Comment by dukechain2333** [comment]
> 

我在拖动窗口时也会出现提示赢

**Comment by dukechain2333** [comment]
> > 
> 
> 我在拖动窗口时也会出现提示赢

而且我不仅是拖动关于Word窗口会有提示音，拖动Word主体窗口也会有提示音

**Comment by dukechain2333** [comment]
这个问题好像在微信里也有，也是选中文本后触发复制提示音

**Comment by dukechain2333** [comment]
这个到底是feature还是bug呀，我的理解是在按下翻译图标的时候才会调用系统复制吧，为啥我还没摁就会调用呀。

**Comment by Jerry23011** [comment]
> 我的理解是在按下翻译图标的时候才会调用系统复制吧，为啥我还没摁就会调用呀。

这个还是要问问 @tisfeng

**Comment by dukechain2333** [comment]
`getSelectedTextByKey` 在调用这个函数的时候会出多余的提示音，`getSelectedTextByAuxiliary`正常

**Comment by Jerry23011** [comment]
是的，因为 `getSelectedTextByKey` 是模拟⌘C，`getSelectedTextByAuxiliary` 是用过Auxiliary原生取词

**Comment by tisfeng** [comment]
> 这个到底是feature还是bug呀，我的理解是在按下翻译图标的时候才会调用系统复制吧，为啥我还没摁就会调用呀。

这种情况属于误触发 https://github.com/tisfeng/Easydict/issues/92#issuecomment-1544169707 

由于目前取词方式还不完善，所以偶尔会误触发，经优化后，通常误触发也不会造成什么影响，你这种属于极特殊情况。

**Comment by tisfeng** [comment]
@dukechain2333  确认过这个复制提示音是 Easydict 导致的吗？ 因为有些其他应用也使用模拟快捷键方式取词，也可能导致这个问题。

如果确实是 Easydict 导致，你能尝试手动编译运行 debug 看一下问题所在吗？我这边不能复现，没办法调试。

**Comment by dukechain2333** [comment]
> @dukechain2333 确认过这个复制提示音是 Easydict 导致的吗？ 因为有些其他应用也使用模拟快捷键方式取词，也可能导致这个问题。
> 
> 如果确实是 Easydict 导致，你能尝试手动编译运行 debug 看一下问题所在吗？我这边不能复现，没办法调试。

能确认是由Easydict导致的。关掉就没这个问题了。

我试图自己找到问题，但是我并没有相关开发经验，我没能找到滑词后调用的代码，或许您能告诉我一下在哪里，我再去看看？

我怀疑问题处在调用`getSelectedTextByKey`这个函数过早。因为我还没有点击浮动图标（仅仅只是选中了句子）就出现了提示音，这应该是执行了模拟`cmd+c`导致的。

**Comment by tisfeng** [comment]
@dukechain2333  你用最新的 dev 分支调试，`autoGetSelectedText` 这是自动取词的方法，你在这里打断点查看

https://github.com/tisfeng/Easydict/blob/c9258fea695bf7c715204930c6951313e3473ca3/Easydict/Feature/EventMonitor/EZEventMonitor.m#L263

**Comment by dukechain2333** [comment]
> 

我又去检查了一遍，发现问题了：）

和一个叫PasteNow的剪贴板软件冲突

**Comment by dukechain2333** [comment]
emmmm但是为啥冲突的方式是发出系统提示音这个不太清楚

**Comment by tisfeng** [comment]
具体怎么冲突了？是进行了什么操作吗，还是某个设置和 PasteNow 冲突了？

**Comment by dukechain2333** [comment]
> > 
> 
> 我又去检查了一遍，发现问题了：）
> 
> 和一个叫PasteNow的剪贴板软件冲突

他俩少任何一个都不会有这个问题，但是只要一起开就有提示音了。但是只会在模拟cmd+c的时候冲突，或许是因为他也是在靠模拟cmd+c复制？

**Comment by tisfeng** [comment]
有可能，因为目前能用的取词方式就那几个，都有些局限性。

建议你也向 PasteNow 作者反馈一下这个问题，直接给他这个 issue 链接，他应该就能明白。

**Comment by tisfeng** [comment]
[2.7.2](https://github.com/tisfeng/Easydict/releases/tag/2.7.2) 版本已修复该问题。
