### ISSUE TITLE
🐞 反馈问题：隐藏状态栏图标重启后失效

### ISSUE THREAD

**Issue by Lxnii** [tisfeng/Easydict#112]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

隐藏状态栏图标重启后失效。

<img width="807" alt="Screenshot 2023-05-25 at 22 49 47" src="https://github.com/tisfeng/Easydict/assets/27051542/c4c080ef-de5d-4123-8e8f-55a47cb2f2fa">

### 重现步骤

开启了隐藏状态栏选项，重启后失效。

### 期望结果

开启隐藏状态栏图标，重启后依然会隐藏状态栏图标。

### 设备信息 && 操作系统版本（可选）

Mac mini M2 Pro, macOS 13.4

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by qq3450095290** [comment]
我也遇到了同样的问题，刚才电脑重启后，状态栏图标无法隐藏，设置里没有相关选项
M1 Pro，macOS 13.3.1
Easydict 1.3.1

**Comment by tisfeng** [comment]
@qq3450095290  设置里没有相关选项，这个是指什么？给个截图看看

> 刚才电脑重启后，状态栏图标无法隐藏，设置里没有相关选项

**Comment by tisfeng** [comment]
@Jerry23011 你测过这个问题吗

**Comment by Jerry23011** [comment]
没有，我 Mac 一般几周都不重启一次😂

**Comment by qq3450095290** [comment]
@tisfeng 您好，我早上把电脑重启了，再打开查看软件的设置，发现设置里又出现了可以隐藏状态栏图标的选项 😂

**Comment by tisfeng** [comment]
这个问题有点奇怪，我也复现过一次，但是看代码似乎又没什么问题。再看看。

**Comment by tisfeng** [comment]
这个看起来是奇怪的小概率问题，先关闭了，后面如果能稳定复现，再开 issue 来查。
