### ISSUE TITLE
🚀 功能建议：希望能增加Force Click/三指查词功能

### ISSUE THREAD

**Issue by szjhpz** [tisfeng/Easydict#113]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

可否考虑一下增加替换Mac自带的Force Click/三指查词功能

这种方式下可以直接点击单词, 或者选择句子后Force Click/三指点击, 完全和系统自带的方式一样, 只不过调用的是Easydict, 自定义的程度更高, 还能够接入AI.

但我估计难度应该很大吧, 要替换系统级的功能.

Respect.

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
这个可能只在基于 WebKit 的应用中可行？🤔
https://developer.apple.com/library/archive/documentation/AppleApplications/Conceptual/SafariJSProgTopics/RespondingtoForceTouchEventsfromJavaScript.html

**Comment by tisfeng** [comment]
我不太能理解，"Force Click/三指查词功能" 具体是指什么，能否给几个具体示例？

这个功能，对于 Easydict 有什么具体应用场景？ 现有的功能不能满足需求吗

**Comment by szjhpz** [comment]
Force Click/三指查词:
<img width="617" alt="image" src="https://github.com/tisfeng/Easydict/assets/38840430/9d6251f0-ea37-415a-acb5-30a7180776a0">

现有的能满足, 只是我用原生的比较多, 原生的最大亮点是不需要自己选中词汇, 只要对着要查询的单词点一下就可以,效果如下:
<img width="399" alt="image" src="https://github.com/tisfeng/Easydict/assets/38840430/5992523c-da4f-4710-b819-82624ed08fb7">

多个单词, 需要左键选择, 然后Force Click点查
<img width="396" alt="image" src="https://github.com/tisfeng/Easydict/assets/38840430/3d51b40e-cc15-49a5-9bfb-6f4a4449813a">

没有应用场景, 提一个建议而已, 不期望能被采纳.

> 我不太能理解，"Force Click/三指查词功能" 具体是指什么，能否给几个具体示例？
> 
> 这个功能，对于 Easydict 有什么具体应用场景？ 现有的功能不能满足需求吗

**Comment by tisfeng** [comment]
@szjhpz  了解了，这个想法不错，但感觉可能实现不了，除非是系统级应用，或者类似浏览器这种提供了扩展程序的应用。

不过，这个功能后续或许可以在 Easydict 中用到，优化一下应用内右击取词查询动作。

<img width="456" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/e5b79020-d6e5-4bdb-8bb5-cd2002930357">

**Comment by Jerry23011** [comment]
但是说实话就算是 macOS 本身的 Force Touch 都不是很稳定

**Comment by szjhpz** [comment]
> 但是说实话就算是 macOS 本身的 Force Touch 都不是很稳定

这倒是, 在我的11.5.2上, safari里可以左键选择后force touch查, 预览里, 左键选择后仍然只能查鼠标对着的那一个.

好像后续版本修复了.

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本增加了一个应用内查询功能。

Force Touch 我尝试过，但是失败了，即使在 Easydict 应用内想实现这个功能都很难，可能要一些神奇的魔法，暂时我没有思路。

如果你有在其他的开源应用中见过，可以通知一下我，我去学习学习。

> 新增 Easydict 应用内查询。

![](https://raw.githubusercontent.com/tisfeng/ImageBed/main/uPic/image-20231019101421740-1697681661-1697681993.png)
