### ISSUE TITLE
🐞 Bug Report: 按下输入翻译 快捷键会导致Easydict退出 

### ISSUE THREAD

**Issue by lzyjxqt** [tisfeng/Easydict#114]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Problem description

Mac OS版本 13.3.1 (a)
Easydict 版本 1.3.1
输入翻译快捷键 Option+A 或者 Option+Q都试过

### Reproduction steps

None

### Expected result

None

### Device information and OS version (optional)

M1 Mac OS版本 13.3.1 (a) Easydict 版本 1.3.1

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR!

**Comment by Jerry23011** [comment]
Hi，你说的退出是按下快捷键之后 Easydict 的菜单栏图标直接退出吗？如果能提供录屏那就更好了

**Comment by lzyjxqt** [comment]
> Hi，你说的退出是按下快捷键之后 Easydict 的菜单栏图标直接退出吗？如果能提供录屏那就更好了

就是闪退了，见视频

https://github.com/tisfeng/Easydict/assets/12902930/83b52e55-1d62-4a78-8f25-f66ac5ce1620

**Comment by Jerry23011** [comment]
不知道为什么，我无法播放
<img width="965" alt="截屏2023-05-29 18 02 53" src="https://github.com/tisfeng/Easydict/assets/89069957/3e5020dc-2057-4073-aba8-c47c6d028fa2">

**Comment by lzyjxqt** [comment]
> 不知道为什么，我无法播放 <img alt="截屏2023-05-29 18 02 53" width="965" src="https://user-images.githubusercontent.com/89069957/241705800-3e5020dc-2057-4073-aba8-c47c6d028fa2.png"> https://github-production-user-asset-6210df.s3.amazonaws.com/12902930/241701780-83b52e55-1d62-4a78-8f25-f66ac5ce1620.mp4

估计是githubusercontent.com被墙了。。。

试试这个
https://public.tiandi.party/file/Easydict闪退.mp4

**Comment by Jerry23011** [comment]
> 就是闪退了

你说的退出是按下快捷键之后 Easydict 的菜单栏图标直接退出吗？

> 估计是githubusercontent.com被墙了。。。

是我 Safari 的问题，现在都能看见了

最后，
这个问题在 Mac 重启之后还可以复现吗？

**Comment by tisfeng** [comment]
@lzyjxqt 麻烦提供一下崩溃日志，我来看看，菜单图标 -> 帮助 -> 导出日志

**Comment by lzyjxqt** [comment]
> > 就是闪退了
> 
> 你说的退出是按下快捷键之后 Easydict 的菜单栏图标直接退出吗？
> 
> > 估计是githubusercontent.com被墙了。。。
> 
> 是我 Safari 的问题，现在都能看见了
> 
> 最后， 这个问题在 Mac 重启之后还可以复现吗？

可以复现

@tisfeng 
日志 here

[Easydict log 2023-05-29 21-55-17-154.zip](https://github.com/tisfeng/Easydict/files/11592255/Easydict.log.2023-05-29.21-55-17-154.zip)

**Comment by tisfeng** [comment]
看了一下日志，确实发生了崩溃，但这个日志有点太简陋，看不出来具体在哪里崩溃的 😓， 这个问题，需要更多的上下文信息。

你这是第一次使用就崩溃吗？还是说之前使用正常，后面升级了才导致问题？

有点像出现了脏数据，你把应用删了，重新安装试一下。

```
reason:
========uncaughtException异常错误报告========
name:NSInvalidArgumentException
reason:
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]
callStackSymbols:
0   CoreFoundation                      0x00000001a891b19c __exceptionPreprocess + 176
1   libobjc.A.dylib                     0x00000001a843a4d4 objc_exception_throw + 60
2   CoreFoundation                      0x00000001a8a059d4 -[__NSCFString characterAtIndex:].cold.1 + 0
3   CoreFoundation                      0x00000001a8a12c2c -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
4   CoreFoundation                      0x00000001a882eb90 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
5   CoreFoundation                      0x00000001a882ea24 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52
6   Easydict                            0x0000000104d95ee8 Easydict + 89832
7   Easydict                            0x0000000104d938d0 Easydict + 80080
8   libdispatch.dylib                   0x00000001a8612874 _dispatch_call_block_and_release + 32
9   libdispatch.dylib                   0x00000001a8614400 _dispatch_client_callout + 20
10  libdispatch.dylib                   0x00000001a8622bf8 _dispatch_main_queue_drain + 928
11  libdispatch.dylib                   0x00000001a8622848 _dispatch_main_queue_callback_4CF + 44
12  CoreFoundation                      0x00000001a88e3c88 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
13  CoreFoundation                      0x00000001a88a14a8 __CFRunLoopRun + 1992
14  CoreFoundation                      0x00000001a88a058c CFRunLoopRunSpecific + 612
15  HIToolbox                           0x00000001b20d5df4 RunCurrentEventLoopInMode + 292
16  HIToolbox                           0x00000001b20d5c30 ReceiveNextEventCommon + 648
17  HIToolbox                           0x00000001b20d5988 _BlockUntilNextEventMatchingListInModeWithFilter + 76
18  AppKit                              0x00000001ababff58 _DPSNextEvent + 636
19  AppKit                              0x00000001ababf0f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
20  AppKit                              0x00000001abab3558 -[NSApplication run] + 464
21  AppKit                              0x00000001aba8a9a8 NSApplicationMain + 880
22  dyld                                0x00000001a846bf28 start + 2236
```

**Comment by lzyjxqt** [comment]
> 看了一下日志，确实发生了崩溃，但这个日志有点太简陋，看不出来具体在哪里崩溃的 😓， 这个问题，需要更多的上下文信息。
> 
> 你这是第一次使用就崩溃吗？还是说之前使用正常，后面升级了才导致问题？
> 
> 有点像出现了脏数据，你把应用删了，重新安装试一下。
> 
> ```
> reason:
> ========uncaughtException异常错误报告========
> name:NSInvalidArgumentException
> reason:
> *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]
> callStackSymbols:
> 0   CoreFoundation                      0x00000001a891b19c __exceptionPreprocess + 176
> 1   libobjc.A.dylib                     0x00000001a843a4d4 objc_exception_throw + 60
> 2   CoreFoundation                      0x00000001a8a059d4 -[__NSCFString characterAtIndex:].cold.1 + 0
> 3   CoreFoundation                      0x00000001a8a12c2c -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
> 4   CoreFoundation                      0x00000001a882eb90 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
> 5   CoreFoundation                      0x00000001a882ea24 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52
> 6   Easydict                            0x0000000104d95ee8 Easydict + 89832
> 7   Easydict                            0x0000000104d938d0 Easydict + 80080
> 8   libdispatch.dylib                   0x00000001a8612874 _dispatch_call_block_and_release + 32
> 9   libdispatch.dylib                   0x00000001a8614400 _dispatch_client_callout + 20
> 10  libdispatch.dylib                   0x00000001a8622bf8 _dispatch_main_queue_drain + 928
> 11  libdispatch.dylib                   0x00000001a8622848 _dispatch_main_queue_callback_4CF + 44
> 12  CoreFoundation                      0x00000001a88e3c88 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
> 13  CoreFoundation                      0x00000001a88a14a8 __CFRunLoopRun + 1992
> 14  CoreFoundation                      0x00000001a88a058c CFRunLoopRunSpecific + 612
> 15  HIToolbox                           0x00000001b20d5df4 RunCurrentEventLoopInMode + 292
> 16  HIToolbox                           0x00000001b20d5c30 ReceiveNextEventCommon + 648
> 17  HIToolbox                           0x00000001b20d5988 _BlockUntilNextEventMatchingListInModeWithFilter + 76
> 18  AppKit                              0x00000001ababff58 _DPSNextEvent + 636
> 19  AppKit                              0x00000001ababf0f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
> 20  AppKit                              0x00000001abab3558 -[NSApplication run] + 464
> 21  AppKit                              0x00000001aba8a9a8 NSApplicationMain + 880
> 22  dyld                                0x00000001a846bf28 start + 2236
> ```

之前正常，升级了之后出现崩溃的。
卸载重新安装后正常了

**Comment by tisfeng** [comment]
这种问题，[1.3.1 更新日志](https://github.com/tisfeng/Easydict/releases/tag/1.3.1) 有写，但会导致应用崩溃我是没想到的 😥

> ⚠️ 新版本修改了一些配置字段，因此可能导致不兼容问题。更新后如遇到设置失效，或显示不支持繁体中文提示，请重启应用，并重新进行相应的设置或选择翻译语言。

**Comment by lzyjxqt** [comment]
> 这种问题，[1.3.1 更新日志](https://github.com/tisfeng/Easydict/releases/tag/1.3.1) 有写，但会导致应用崩溃我是没想到的 😥
> 
> > ⚠️ 新版本修改了一些配置字段，因此可能导致不兼容问题。更新后如遇到设置失效，或显示不支持繁体中文提示，请重启应用，并重新进行相应的设置或选择翻译语言。

@tisfeng 问题解决了，谢谢，晚安！

**Comment by tisfeng** [comment]
这个应该和 https://github.com/tisfeng/Easydict/issues/117 是一样的问题。
