### ISSUE TITLE
🐞 Bug Report: 输入翻译-百度输入，点击任意结果会导致Easydict闪退

### ISSUE THREAD

**Issue by lzyjxqt** [tisfeng/Easydict#115]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Problem description

输入翻译-百度输入，点击任意结果会导致Easydict闪退
<img width="324" alt="1" src="https://github.com/tisfeng/Easydict/assets/12902930/2be99d8e-4a92-47fc-aae2-b21b87419b24">
[Easydict log 2023-05-31 14-31-10-142.zip](https://github.com/tisfeng/Easydict/files/11609430/Easydict.log.2023-05-31.14-31-10-142.zip)

### Reproduction steps

None

### Expected result

None

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR!

**Comment by Jerry23011** [comment]
我可以复现 @tisfeng 
<img width="1512" alt="截屏2023-05-31 17 20 58" src="https://github.com/tisfeng/Easydict/assets/89069957/f543bdd5-f520-4e58-9d30-ec43f62f6a7d">

**Comment by tisfeng** [comment]
收到，稍后就修复。周末发个新版吧。

**Comment by tisfeng** [comment]
新版本 [1.3.2](https://github.com/tisfeng/Easydict/releases/tag/1.3.2) 已修复该问题。
