### ISSUE TITLE
🐞 反馈问题：开启「清空查询内容」选项后，按快捷键「输入翻译」会自动退出 App

### ISSUE THREAD

**Issue by Lxnii** [tisfeng/Easydict#117]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

开启「清空查询内容」选项后，按快捷键「输入翻译」会自动退出 App。

<img width="858" alt="Screenshot 2023-06-01 at 21 46 26" src="https://github.com/tisfeng/Easydict/assets/27051542/36a4c3a2-7c90-48f5-8eef-d48dd38fbfbc">

### 重现步骤

开启「清空查询内容」选项后，按快捷键呼出输入翻译界面。

如果没出现自动退出，可以完全退出 App 后重新打开后再尝试用快捷键呼出输入翻译。

### 期望结果

不会自动退出App。

### 设备信息 && 操作系统版本（可选）

M2 Pro macOS 13.4

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
感谢反馈，确实存在这个问题，周末会发个修复版本。

当前版本，建议先通过菜单图标进入设置页，取消【清空查询内容】选项。

**Comment by tisfeng** [comment]
新版本 [1.3.2](https://github.com/tisfeng/Easydict/releases/tag/1.3.2) 已修复该问题。
