### ISSUE TITLE
🚀 功能建议：设置-悬浮窗口位置-增加『屏幕中部』选项

### ISSUE THREAD

**Issue by weiwenduo** [tisfeng/Easydict#118]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

在设置-悬浮窗口位置-增加『屏幕中部』选项。在调出悬浮窗口时，窗口的位置置于屏幕中部（水平居中）。

### 使用场景（可选）

在阅读一些文档或网页时，文字大多是在屏幕的中部。如果增加『屏幕中部』的选项，这样在调出窗口后，就不用专门往右侧看了（超级懒）。

PS: 屏幕尺寸小的情况下可能不会有体会，目前我使用27寸的显示器，转头是无法避免的。

PPS: 尝试使用『上次位置』选项来实现这个需求场景，但是在双屏的情况，窗口位置记录是有问题的。在一个屏幕上调出窗口后关闭，另一个屏幕再次调出，窗口的一半会在屏幕的外面。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
可以，居中显示这个可以有。

**Comment by tisfeng** [comment]
关于这个，稍后我去看一下。

> 尝试使用『上次位置』选项来实现这个需求场景，但是在双屏的情况，窗口位置记录是有问题的。在一个屏幕上调出窗口后关闭，另一个屏幕再次调出，窗口的一半会在屏幕的外面。

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已实现该功能。

> 新增侧悬浮窗口显示位置-屏幕中间。 https://github.com/tisfeng/Easydict/issues/118
