### ISSUE TITLE
反馈问题：菜单栏 UI

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#12]
## 描述问题

Hi，又来反馈 UI 问题了😄
这里发现菜单栏的图标在选中的时候貌似不太一样，个人认为其他软件的样式看起来能更协调一点
<img width="99" alt="截屏2023-02-13 20 35 49" src="https://user-images.githubusercontent.com/89069957/218459683-ee315f16-417c-41b6-b41c-486cad137ef7.png">
<img width="116" alt="截屏2023-02-13 20 36 45" src="https://user-images.githubusercontent.com/89069957/218459738-95d0f74a-fbef-4ed8-8cc6-d2c8e5bde5b1.png">

## 运行环境

- Device:  MacBook Pro 14‘
- macOS: 13.2
- Easydict Version:  1.2.1

**Comment by tisfeng** [comment]
[新版本 1.2.3 ](https://github.com/tisfeng/Easydict/releases)  已修复状态栏图标问题。

**Comment by Jerry23011** [comment]
感谢
新改的非常漂亮
