### ISSUE TITLE
🐞 反馈问题：会对微信多选和图片或视频预览

### ISSUE THREAD

**Issue by daxiong888** [tisfeng/Easydict#123]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

影响微信画框多选多条消息

https://github.com/tisfeng/Easydict/assets/20814367/9a6abe90-9c98-4d82-8d37-3d212a477944

### 重现步骤

1、打开微信任意聊天界面
2、画框选中多条消息

### 期望结果

正常应该是可以选中多条消息的，但由于软件影响无法选中

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
感谢反馈，确实有这个问题，因为微信不支持 Accessibility 取词 https://github.com/tisfeng/Easydict/issues/84#issuecomment-1537278946 ，导致 Easydict 只能使用模拟快捷键 Cmd+C 方式取词，而微信在选中多条消息后，如果 Cmd+C 就会复制聊天消息，并自动退出复制编辑模式。

你可以试一下关闭 Easydict 取词，在微信选中多条消息，然后手动 Cmd+C 看看效果。

看了一下，果然 PopClip 也默认在微信中关闭了。这问题微信要背一半的锅。

目前没什么好的解决方法，下个版本将会默认关闭模拟快捷键 Cmd+C 取词，需要手动开启。后面会添加一个黑名单功能，禁止某些应用 Cmd+C 取词。

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已修复该问题。
