### ISSUE TITLE
🚀 功能建议：OCR之后马上再次OCR，第一次的窗口遮挡屏幕

### ISSUE THREAD

**Issue by 18013725279** [tisfeng/Easydict#126]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

使用OCR翻译后，马上紧接着进行第二次OCR， 第一次的窗口不会自动关闭，导致遮挡了屏幕，能否改进一下？设备：MacBook PRO M1 MAX，系统：Ventura 13.4

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR!

**Comment by 18013725279** [comment]
很抱歉，我并不会写代码😂

**Comment by tisfeng** [comment]
看到勾选了 PR 选项，我还挺期待的。。

OK，那还是我来吧 😌

<img width="301" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/6162f8e6-a1c1-431f-86b2-85249356dcfe">

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已修复该问题。

> 优化 OCR 窗口显示，OCR 时先关闭之前的 OCR 窗口。https://github.com/tisfeng/Easydict/issues/126
