### ISSUE TITLE
🐞 反馈问题：OpenAI 自定义域名

### ISSUE THREAD

**Issue by huzhongyang** [tisfeng/Easydict#127]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

使用 OpenAI 自定义域名会出现这个问题
<img width="412" alt="image" src="https://github.com/tisfeng/Easydict/assets/33920770/509f3160-bb73-4cc4-8444-383406f028d0">

### 重现步骤

easydict://writeKeyValue?EZOpenAIDomainKey=api.openai-sb.com/v1/chat/completions
easydict://writeKeyValue?EZOpenAIAPIKey=sb-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### 期望结果

无

### 设备信息 && 操作系统版本（可选）

MacBook Pro Intel Core i7, 13.4 (22F66)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
从报错信息来看，可能是你自定义域名的服务端部署出了问题，客户端 Easydict 这边的 request Content-Type 是 `application/json`，responese Content-Type 是 `text/event-stream`，我对服务端不太了解，你可以对照检查一下。

如果有疑问，可以看看这里 https://github.com/tisfeng/Easydict/issues/28#issuecomment-1556223040

> 关于部署自定义域名，可以参考这个 vercel 反代项目 [vercel-reverse-proxy](https://github.com/gaboolic/vercel-reverse-proxy)

**Comment by tisfeng** [comment]
另外，EZOpenAIDomainKey 只需要自定义域名 host，如默认 `api.openai.com`，因此你这个似乎应该是 `api.openai-sb.com`， 不要带后面的 path，path 我这边会自动拼接的。

> easydict://writeKeyValue?EZOpenAIDomainKey=api.openai-sb.com/v1/chat/completions

**Comment by huzhongyang** [comment]
嗯, 就是这个问题. 感谢作者解答 🙏
