### ISSUE TITLE
功能建议：能否允许设置弹窗的宽度和透明度

### ISSUE THREAD

**Issue by yetone** [tisfeng/Easydict#13]
## 功能描述

现在弹窗在我的电脑上特别窄，不太易于阅读内容，我找了好久也没找到相关设置，希望可以允许设置弹窗宽度。

最后感谢作者开发了这么牛逼的工具！对我这种英语苦手来说太有帮助了！！！

<img width="881" alt="image" src="https://user-images.githubusercontent.com/1206493/219604626-e552142d-4344-4f97-b17a-986f7497fa85.png">

**Comment by tisfeng** [comment]
可以，稍后我设置一下允许手动调整弹窗宽度。透明度是指什么？

**Comment by tisfeng** [comment]
半透明，理论上可以，可能还需要配合添加一个关于透明度的设置项。但目前代码写得比较乱，调整它会涉及很多图层的背景色，还要适配深色模式，会比较麻烦。。

目前还有一些重要排期需求，这个我先记下了，后面腾出手来可以做。当然，如果有人能提 PR，我很乐意接受 😌

**Comment by yetone** [comment]
@tisfeng 好的，我研究一下代码，谢谢您！

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已支持了手动调整迷你窗口宽度。

**Comment by yetone** [comment]
@tisfeng 太强了！感谢！！！
