### ISSUE TITLE
🐞 反馈问题：“Shortcuts Events”遇到一个错误：未能完成该操作。操作不被允许 (-1753)

### ISSUE THREAD

**Issue by dluffymonkey** [tisfeng/Easydict#132]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

MacOS翻译报错：“Shortcuts Events”遇到一个错误：未能完成该操作。操作不被允许 (-1753)
<img width="412" alt="image" src="https://github.com/tisfeng/Easydict/assets/8476885/22b8c06d-f920-48c3-9dfa-879c00736d14">

手动在快捷指令里面执行翻译操作也报错
<img width="866" alt="image" src="https://github.com/tisfeng/Easydict/assets/8476885/f55a6779-ee14-42a9-ada4-90d2d15ced36">

### 重现步骤

手动输入翻译

### 期望结果

MacOS翻译正常

### 设备信息 && 操作系统版本

Apple M1 Pro, macOS 13.4

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
可以先参考 #94

**Comment by dluffymonkey** [comment]
hello，@Jerry23011 ，看了这[这篇文章](https://bobtranslate.com/faq/apple-translate-error.html#%E9%97%AE%E9%A2%98-4)问题已经解决了，非常感谢，应该是系统反应不允许走代理的原因，我把代理关闭了就没有问题了，以前用的Clash Pro，设置里面自动设置好了sequoia.apple.com, seed-sequoia.siri.apple.com绕过代理，所以一直没有发现问题，今天改用Surge了，所以出现上述问题。按照[这个方法](https://github.com/ripperhe/Bob/issues/405)解决了
