### ISSUE TITLE
🐞 Bug Report: "Not authorized to send Apple events to Shortcuts Events. (-1743)" while using System translation

### ISSUE THREAD

**Issue by Kay1892** [tisfeng/Easydict#133]
I can't get the system translate function to work. I followed the steps in the README, but it still couldn't work. I may be missing some steps I don't know. 
<img width="149" alt="SCR-20230627-ktgf" src="https://github.com/tisfeng/Easydict/assets/72806930/6e5087bd-4590-4ac7-80b8-af8417e77f76">

Apple M1 Pro, 13.4.1

<img width="555" alt="SCR-20230627-kpxk" src="https://github.com/tisfeng/Easydict/assets/72806930/0e747fd0-56cc-466e-8f90-64b6ec904f4e">

**Comment by Jerry23011** [comment]
Hi @langmuir1892,

Are you using any system proxy? Please check [this article](https://bobtranslate.com/faq/apple-translate-error.html)

Also, please check the following issues as they might help you: #94 #132

**Comment by langmuir1892** [comment]
Problem resolved after following the instuctions in [this article](https://bobtranslate.com/faq/apple-translate-error.html).

Thank you.

**Comment by Jerry23011** [comment]
Great to hear that!
