### ISSUE TITLE
🐞 Bug Report: 莫名其妙地自己打开了夜间模式

### ISSUE THREAD

**Issue by chachako** [tisfeng/Easydict#134]
### Please confirm the following:

- [x] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Problem description

<img width="1065" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/c2b109d3-0f70-44e9-816b-d04c0c9b88af">

### Reproduction steps

未知，尝试过退出重新打开也是一样的显示

### Expected result

跟随系统

**Comment by Jerry23011** [comment]
看起来有点像 #37

**Comment by tisfeng** [comment]
@chachako  可以详细描述一下这个问题吗？具体如何出现的，是打开设置页就这样？之前是否切换过深色模式？设置页其他页面也有这个问题吗？查询窗口页面呢？重启后，这个问题是否可以百分百复现？

**Comment by tisfeng** [comment]
之前我自己也偶然遇到过几次这种问题，但都没办法复现。设置页使用了第三方库，不确定是不是它的锅，这个比较难查。

后面会重写设置页面，但这个可能要等，等到下一个大版本更新。

**Comment by chachako** [comment]
> 具体如何出现的，是打开设置页就这样？之前是否切换过深色模式？

没有切换过系统深色模式，今天打开就这样了，系统是日间模式。

> 设置页其他页面也有这个问题吗？查询窗口页面呢？重启后，这个问题是否可以百分百复现？
是的，其他界面也有这个问题，整个 easydict 都变成深色了。具体等我明天打开电脑再验证一次。

**Comment by chachako** [comment]
@tisfeng 看起来重新打开电脑后问题还存在
<img width="1230" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/2c25ad42-d7bf-49d8-8f27-df1c0bbf3818">
现在的情况大概就是所有 APP 就只有 easydict 是夜间模式（

**Comment by tisfeng** [comment]
很奇怪，你是说你电脑上其他应用都正常，只有 Easydict 的深色模式异常？

可能是对深色模式的判断出了问题，这个问题我无法复现，其他用户也没有遇到过，不确定是代码有问题，还是特定用户的电脑系统环境问题。

先尝试排除你电脑环境问题：
1. 提供一下你的电脑型号和系统版本。
2. 手动切换浅色/深色模式，Easydict 的 UI 是否会跟随变化？
3. 是否使用第三方软件管理深色模式？这可能会导致一些冲突问题。
4. 这是第一次使用吗？之前 Easydict 深色模式是否正常？
5. 有试过 Easydict 之前版本会出现这个问题吗？

**Comment by kuschzzp** [comment]
<img width="591" alt="image" src="https://github.com/tisfeng/Easydict/assets/38914005/ebad04b6-53bf-4c56-9b6f-bfbeb17b48b1">

你好，我也有同样的问题，我是第一次使用这款软件，安装完成进入设置就是这样子的，点啥都是这种颜色，看不太清楚黑色区域的字。

电脑：2021 M1 macbook pro、macOS Ventyra 13.4.1

**Comment by chachako** [comment]
我是 monterey,好像是重启才有这个问题，这两天电脑没重启，显示正常。改天电脑关机了再看看（

**Comment by tisfeng** [comment]
我今天也遇到这个问题了，但看起来像是系统的深色模式出现了异常，明明开启了深色模式，但某种程度上似乎又没有生效，比如【系统设置】应用没有进入深色模式，Chrome 等应用也是。

Easydict 查询页面的外观，是使用代码控制，严格跟随系统深色模式的，但偏好设置页面由于使用了第三方库，因此导致了部分显示深色模式，部分显示浅色模式（系统API导致）。

先观望看看。

<img width="1537" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/b9d3c51d-1311-4a50-999b-56b8ad60b6ca">

**Comment by chachako** [comment]
>  ![image](https://github.com/tisfeng/Easydict/assets/58068445/71b28a5d-4e45-4560-a192-cdd03815a5ff)


<img width="483" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/b26bc20e-4247-479d-99da-fa56c03adda3">

我突然发现好像就我右边有这个 scrollbar? ~~是 bug 还是 feature~~

**Comment by Jerry23011** [comment]
> 我突然发现好像就我右边有这个 scrollbar?

这个是 macOS 系统设置
<img width="500" alt="image" src="https://github.com/tisfeng/Easydict/assets/89069957/7bf66233-df04-462a-b6df-0fd2fc0ce183">

**Comment by kuschzzp** [comment]
@tisfeng 作者考不考虑增加手动切换风格呢？

**Comment by tisfeng** [comment]
@kuschzzp  理论上可以加，但我不确定用户是否真的需要这个选项？ 因为 Easydict 外观是跟随系统的外观模式，就是说用户完全可以控制 Easydict 是显示深色模式还是浅色模式。如果再添加一个手动切换外观选项，一是增加了设置复杂度，二是可能会导致 Easydict 外观和系统的整体配色不搭，比如浅色的查询窗口悬浮在深色的 Chrome 背景页面上，感觉会很怪。

<img width="1455" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/7ff7587d-f301-4442-b268-42486a466dc4">

<img width="1466" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/782bcb01-4c32-4af1-8fd1-15ddde1a8341">

**Comment by tisfeng** [comment]
> 我今天也遇到这个问题了，但看起来像是系统的深色模式出现了异常，明明开启了深色模式，但某种程度上似乎又没有生效，比如【系统设置】应用没有进入深色模式，Chrome 等应用也是。
> 
> Easydict 查询页面的外观，是手动使用代码控制跟随系统深色模式的，但偏好设置页面由于使用了第三方库，因此导致了部分显示深色模式，部分显示浅色模式（系统 API 导致）。
> 
> 这个问题很诡异，先观望看看。
> 
> <img alt="image" width="1537" src="https://user-images.githubusercontent.com/25194972/250357961-b9d3c51d-1311-4a50-999b-56b8ad60b6ca.png">

查了一下，这个问题原因找到了，可能是使用第三方软件切换了深色模式导致，参考这里 [macOS 深色模式下无效，仍显示浅色，请问是何原因？](https://v2ex.com/t/772278)，在我电脑上是 NightOwl 导致。

但很奇怪，这个问题似乎也是小概率偶发，我用 NightOwl 也蛮久了，目前只出现过两次这种问题，也没找到具体复现步骤和根本原因。

解决方法是在终端写入以下命令，然后重启电脑。

> defaults delete -g NSRequiresAquaSystemAppearance

**Comment by chachako** [comment]
> 查了一下，这个问题原因找到了，可能是使用第三方软件切换了深色模式导致，参考这里 [macOS 深色模式下无效，仍显示浅色，请问是何原因？](https://v2ex.com/t/772278)，在我电脑上是 NightOwl 导致。
> 

我前几天确实是装了 One Switch 然后卸载了 NightOwl 也卸载了... 还真有可能是这个的原因

**Comment by tisfeng** [comment]
@chachako @kuschzzp  请确认一下上面的解决方式是否有效，如果没问题，就关闭 issue 了。

**Comment by kuschzzp** [comment]
@tisfeng 目前正常了

**Comment by chachako** [comment]
问题又出现了... NightOwl 和 One Switch 都卸载了

现在系统版本是 **Ventura 13.5**

<img width="582" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/2ef9ad19-7c57-47ba-9bb9-b1f6742c9648">

还是一样所有应用都只有 Easydict 检测成了夜间模式

> defaults delete -g NSRequiresAquaSystemAppearance

运行这个命令失败：

```
2023-08-07 11:22:57.010 defaults[1588:16449]
Domain (kCFPreferencesAnyApplication) not found.
Defaults have not been changed.
```

**Comment by tisfeng** [comment]
> defaults delete -g NSRequiresAquaSystemAppearance

这个命令只能执行一次的，只有在有值的时候才有效，没有值就会提示 `Domain (kCFPreferencesAnyApplication) not found`

**Comment by tisfeng** [comment]
你试一下这个命令，它会强制启用浅色模式，可能要重启应用，你试一下。

```
defaults write -g NSRequiresAquaSystemAppearance -bool Yes 
```

**Comment by chachako** [comment]
> 你试一下这个命令，它会强制启用浅色模式，可能要重启应用，你试一下。
> 
> ```
> defaults write -g NSRequiresAquaSystemAppearance -bool Yes 
> ```

太诡异了，我昨天睡眠了没关机，今天起来又正常了😵‍💫 等我下次遇到的时候试试这个

**Comment by tisfeng** [comment]
清理 issue，没有后续反馈的就先关闭了，如果再遇到问题，请另外提 issue。

目前设置页已用 SwiftUI 重写了，建议使用新的设置页。
