### ISSUE TITLE
🚀 功能建议：识别代码文档翻译，把多余的注释符号去掉

### ISSUE THREAD

**Issue by chachako** [tisfeng/Easydict#135]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

<img width="396" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/bed44182-bbdd-401a-83e4-6c09d150eae6">

如图，bob 支持这个功能，在翻译一些文档的时候还是很方便的

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
可以，我还在思考如何做这个功能，后面想重新设计右上角的快捷按钮功能。

**Comment by abigmiu** [comment]
驼峰转换也可以考虑下。

![image](https://github.com/tisfeng/Easydict/assets/43983920/981fb28b-40c9-4941-b75c-dafa15ba310d)

**Comment by tisfeng** [comment]
英文翻译结果转驼峰格式吗，这个可以加，但我有点担心这些功能太杂了。

**Comment by chachako** [comment]
> 驼峰转换也可以考虑下。
> 
> ![image](https://user-images.githubusercontent.com/43983920/272163792-981fb28b-40c9-4941-b75c-dafa15ba310d.png)

+1+1

> 但我有点担心这些功能太杂了。

感觉可以做个开关默认不开启。

不过这部分逻辑感觉可能很容易造成混淆，比如 `Migrate SwipeableState to AnchoredDraggableState` 会不会处理成  `Migrate Swipeable State to Anchored Draggable State` 翻译

或许只在文本完全是驼峰时才转换？

**Comment by tisfeng** [comment]
其实很多小工具都有类似功能，比如下面截图使用的 [Boop](https://github.com/IvanMathy/Boop)

转驼峰这种功能，对写代码还是挺有用的，如果后面添加的话，应该会设置成可选项，图标放在翻译结果下面的链接🔗后面，这样方便在 Easydict 中直接使用。

功能实现不会很复杂，就是将英文文本以单词为单元进行切割，第一个单词首字母小写，其他单词首字母大写。

<img width="629" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/a5a2db24-264e-4623-b834-23d160bb0ef3">

<img width="629" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/6a5da70e-62dd-4e47-81f5-bce4a2353433">

**Comment by chachako** [comment]
> 转驼峰这种功能，对写代码还是挺有用的，如果后面添加的话，应该会设置成可选项，图标放在翻译结果下面的链接🔗后面，这样方便在 Easydict 中直接使用。

唔...可能我描述的有误。

实际上我想要的是（https://github.com/tisfeng/Easydict/issues/135#issuecomment-1744281589 描述的应该也是这种情况）：

假设输入的是 `AnchoredDraggableState` 那么应该翻译为 "锚定可拖动状态"，也就是驼峰转换为空格再翻译（`Anchored Draggable State`）。

但如果输入的是 `Migrate SwipeableState to AnchoredDraggableState` 则应该翻译为 "将 SwipeableState 迁移到 AnchoredDraggableState"，也就是什么都不转换，直接翻译原句。

**Comment by tisfeng** [comment]
明白了，你说的对原输入文本进行处理后，再翻译。

这个想法很不错，有兴趣来 PR 吗？或者等后面我来做也行。

**Comment by chachako** [comment]
> 这个想法很不错，有兴趣来 PR 吗？或者等后面我来做也行。

等我之后有机会学习了 OC 一定 🥲

**Comment by tisfeng** [comment]
加了，现在如果输入内容为单个单词，会尝试以驼峰和下划线形式进行分词，然后再查询

<table>
    <td> <img src="https://github.com/tisfeng/Easydict/assets/25194972/f6cc7959-1a54-4670-b2c2-a90422152ac1.png">
    <td> <img src="https://github.com/tisfeng/Easydict/assets/25194972/87370c34-c356-49c5-a5ea-670a5cc86a22.png">
</table>

**Comment by chachako** [comment]
太棒了！那源码文档的注释处理是不是应该也能完成了～坐等新版本

**Comment by tisfeng** [comment]
之前想过这个功能，但是具体如何实现有点困惑，因为不同编程语言的注释符号不同，比较麻烦，同时也担心会误删除查询内容，我不太想额外添加一个设置项了。。

你有什么建议吗？

**Comment by chachako** [comment]
不加设置的话感觉确实没法做到十全十美，不过一般情况下我认为像 bob 那样有个快捷开关就挺好的，担心的话可以默认关闭。如果考虑加设置选项应该会方便得多，像这样
<img width="728" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/28ffdcbd-fa05-43a0-afee-4401693b9f8b">

**Comment by tisfeng** [comment]
了解。 

我想了想，正好下个版本会开放 OpenAI  https://github.com/tisfeng/Easydict/issues/28#issuecomment-1527827829 ，正好会空出 beta 这个选项，可以用上这个，开启 beta 时就自动去除注释符号。 等后整理设置项 UI 时再单独弄一个选项。

稍微看了一下，各个语言注释符号使用最多的是：`//`, `/* */` 和 `#`，那暂时就只处理这几个。

**Comment by chachako** [comment]
其实还有换行符，多行注释文本只删除注释符号换行符没删除的话翻译结果还是怪怪的（

**Comment by tisfeng** [comment]
你说的换行符，请问这个具体指什么，能给个示例吗

**Comment by chachako** [comment]
像很多注释其实都有行数限制，这个时候不就换行继续写了吗。

// These values will persist after the process is killed by the system
// and remain available via the same object.

像这种如果是按照下面的话翻译的话就不对
> 
> These values will persist after the process is killed by the system
> and remain available via the same object.

正确应该是一句话翻译

> These values will persist after the process is killed by the system and remain available via the same object.

**Comment by tisfeng** [comment]
> 我想了想，正好下个版本会开放 OpenAI https://github.com/tisfeng/Easydict/issues/28#issuecomment-1527827829 ，正好会空出 beta 这个选项，可以用上这个，开启 beta 时就自动去除注释符号。 等后整理设置项 UI 时再单独弄一个选项。

使用命令开启 beta 即可。后续 beta 也可能会增加一些其他类型实验性的功能，观察一段时候后，如果没问题就会移除 beta，直接放到正式版。

```
easydict://writeKeyValue?EZBetaFeatureKey=1
```

**Comment by chachako** [comment]
看起来还是有点问题：
```
    /**
     * Creates a {@code UUID} from the string standard representation as
     * described in the {@link #toString} method.
     *
     * @param  name
     *         A string that specifies a {@code UUID}
     *
     * @return  A {@code UUID} with the specified value
     *
     * @throws  IllegalArgumentException
     *          If name does not conform to the string representation as
     *          described in {@link #toString}
     *
     */
```
the string representation as 后面没有和
described in 连接起来：

<img width="410" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/06aee653-e0dd-4dc3-b29e-e1461903cc4c">

正确来说应该是：
<img width="407" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/8598b6ff-5829-435a-b1f1-67bdb90a02ed">

**Comment by tisfeng** [comment]
确实没有考虑到这种 /**/ 多行注释且需要清除换行符的情况。

仔细看了一下代码，`[/*]+` 这个正则式都写错了，还好没有直接发布。。

我看看怎么改，稍后会发布一个修复版本。

<img width="910" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0e05bdd2-fd31-41bd-a11b-1a482bdc201b">

**Comment by tisfeng** [comment]
[2.0.2](https://github.com/tisfeng/Easydict/releases/tag/2.0.2) 版本已修复该问题。

**Comment by chachako** [comment]
<img width="388" alt="image" src="https://github.com/tisfeng/Easydict/assets/58068445/2a9afbcc-50cc-43de-adda-decd3aef14d8">
这种情况不处理吗

**Comment by tisfeng** [comment]
主要没考虑到这种情况，，各种场景太多了，如果有小伙伴来 PR 测试处理就好了， 我一个人写起来有点心累 😢

稍后我尝试处理一下吧。

**Comment by Kerwin1202** [comment]
@tisfeng  2.4  这种就不行，可以考虑用正则 切单词就行 大写切
<img width="403" alt="image" src="https://github.com/tisfeng/Easydict/assets/16319833/e9ac6e45-06d4-475f-8039-9f6556a4c048">

**Comment by tisfeng** [comment]
这个 issue 功能已完成，后面的内容有点偏离主题了，新的问题请另外开 issue，方便跟踪管理。
