### ISSUE TITLE
🚀功能建议：希望可以自定义输出文字大小，对于视力缺陷人士更友好

### ISSUE THREAD

**Issue by foxllhl** [tisfeng/Easydict#137]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

希望可以自定义输出文字大小，对于视力缺陷人士更友好

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
我在想这种功能是不是应该算到 [Accessibility](https://developer.apple.com/accessibility/#dynamic-type) 里面

**Comment by tisfeng** [comment]
[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本已支持修改显示字体大小。
