### ISSUE TITLE
🐞 反馈问题：您安裝的是 macOS 10.14.6。應用程式需要 macOS 11.0 或以上版本

### ISSUE THREAD

**Issue by PingStyle** [tisfeng/Easydict#138]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

您安裝的是 macOS 10.14.6。應用程式需要 macOS 11.0 或以上版本

您好
我是使用舊的mac 2015
升到太高版本會造成系統lag

請問使用舊版本os
還有機會可以安裝Easydict嗎
謝謝

### 重现步骤

如上

### 期望结果

如上

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
应该不行，除非有小伙伴愿意提交 PR，并且提供当前代码中系统 Symbol Image 的平替图标 https://github.com/tisfeng/Easydict/issues/49#issuecomment-1510609495

> 因为不会设计图标，就用了系统的 Symbol Image ，被迫升到 11.0 了 😓
