### ISSUE TITLE
🐞 Bug Report: 划词翻译无法自动展开上次翻译接口

### ISSUE THREAD

**Issue by JK-Wang** [tisfeng/Easydict#140]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Problem description

更新到 1.3.4 之后会出现 Select Tranlate 无法自动展开翻译结果的问题
1.3.1 及之前的版本应该是会记忆各 tab 的展开状态

<img width="655" alt="image" src="https://github.com/tisfeng/Easydict/assets/32212764/cb86a43e-78c2-4b60-ae87-dd6ca9f92e45">

<img width="641" alt="image" src="https://github.com/tisfeng/Easydict/assets/32212764/2c9b717c-db4d-49ef-a0ec-fa768ed6692c">

### Reproduction steps

1. 选词翻译，展开某个翻译结果
2. 再次选词翻译

### Expected result

可以记忆不同翻译接口的展开状态

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR!

**Comment by JK-Wang** [comment]
更具体一点的话，应该是在 1.3.1 发版之后，fdfe43cb7cf64885b1930fce40e61709284f9ef9 这个提交之前出现的问题

**Comment by Jerry23011** [comment]
我这里测试也没有问题

**Comment by JK-Wang** [comment]
我现在用的是 release 1.3.4 版本，我重装一下试试

**Comment by JK-Wang** [comment]
这个问题删除重装之后好了。不知道会不会是升级导致的特定bug，也可能是环境问题

话说重装前另外一个issue里说的开机自启未生效我也遇到了，我检查过开机启动项和 plist 都是符合预期的。现在重装了等我下次重启再看看开机自启会不会生效，感觉应该是没问题了
