### ISSUE TITLE
🐞 反馈问题：划词弹出多个窗口

### ISSUE THREAD

**Issue by boomker** [tisfeng/Easydict#141]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

当我在浏览器双击 一个单词,  然后点击悬浮图标之后, 会弹出两个翻译窗口, 这让我有些迷茫, 希望保持只会弹出一个窗口
我贴一下截图:
<img width="606" alt="image" src="https://github.com/tisfeng/Easydict/assets/19751472/aed79fe7-79ea-405e-a7e3-04787a948e93">

### 重现步骤

上面已经描述了我的复现操作,  当然发现有时候只会弹出一个窗口, 但多数会弹出两个

### 期望结果

划词翻译时, 点击悬浮图标 之后, 希望保持只会弹出一个窗口

### 设备信息 && 操作系统版本

MBP,  macOS  Big Sur 11.7.8

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
你好，请问之前版本正常吗？还是升级后才出现这问题？有尝试过卸载重装吗？

这个现象很奇怪，你测试过出现异常的概率是多少吗？这个两个窗口的服务以及顺序是否相同？ 如果可以，还是希望你能提供详细的复现步骤，之前没遇到过这种问题，我也无法复现调试。

> 发现有时候只会弹出一个窗口, 但多数会弹出两个

**Comment by tisfeng** [comment]
另外，请确定你电脑上只存在一个 Easydict，不要同时安装正式版本和开发者版本，不然可能会出现这种问题。

**Comment by boomker** [comment]
可能和我的使用方式有关系吧, 在`easydict`后台启动后, 我再用`Alfred` 切换到输入翻译窗口, 然后从此划词翻译点击图标就会弹出两个 窗口, 其中一个应该是输入翻译的窗口.  我希望划词翻译仅弹出一个, 无论我是否打开过输入翻译功能, 而且即便点击窗口左上角关闭按钮, 下次还能弹出两个, 太抓狂😫了

**Comment by Jerry23011** [comment]
这个其实是一个主窗口一个测悬浮
复现方法
1. 在启动台中打开 Easydict 主窗口
2. 使用菜单栏选择输入翻译调出测悬浮窗口即可实现同样效果

<img width="672" alt="截屏2023-07-09 23 11 57" src="https://github.com/tisfeng/Easydict/assets/89069957/37f694a9-19bf-4b83-9239-50bb6acf6c3c">

**Comment by boomker** [comment]
是的.
还是让用户面对一个窗口比较方便聚焦, 希望可以做下调整

**Comment by tisfeng** [comment]
了解了，这种情况下，确实可能会导致这个问题 😓 

最初设定是通过快捷键，鼠标自动划词，或是菜单栏图标触发，没考虑到会有这样的使用方式。稍后我改进一下吧。

**Comment by JiannaiJ** [comment]
直接快捷键划词翻译就会出现两个窗口(主窗口和悬浮窗)

**Comment by tisfeng** [comment]
了解，下个版本会修改。

**Comment by geoqiao** [comment]
问题描述：遇到同样的问题，划词后产生两个悬浮窗口

app版本：1.3.4

macOS版本：13.5

其他描述：印象中刚升级1.3.4的时候并没有这个问题，最近才有的。尝试了卸载重装，但是还是100%出现两个弹窗。

<img width="699" alt="image" src="https://github.com/tisfeng/Easydict/assets/105639506/55669d99-8d9e-4016-bab5-a2f3ba894d6c">

**Comment by tisfeng** [comment]
收到，下个版本会修改。
