### ISSUE TITLE
🚀 Feature Request: Microsoft Bing Translator

### ISSUE THREAD

**Issue by Svec-Tomas** [tisfeng/Easydict#143]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Feature description

I would love to add if possible Microsoft Bing Translator. There should be available free API here:

https://github.com/plainheart/bing-translate-api

### Use case (optional)

From my experience I get the best translation results from DeepL and then on second place is Bing Translator. I am using English to Slovak most of the time.

### Proposed solution (optional)

I didn't see anyone before asking for this in english. Also not sure if Google Bard has any free API, if so, it would be great to have it included as well!

### Are you willing to submit a PR to implement this feature

- [ ] I'm willing to submit PR!

**Comment by Jerry23011** [comment]
> Also not sure if Google Bard has any free API

Google Bard doesn't provide API access at the moment.

**Comment by tisfeng** [comment]
@Svec-Tomas  Bing Translator is OK, if you can submit a PR, I will be happy to accept it.

In addition, Google has Generative Al [PaLM](https://developers.generativeai.google/tutorials/setup), but you need to apply for a waitlist  . This seems very interesting, and I am looking forward to your PR.

**Comment by Svec-Tomas** [comment]
I will check how to submit a PR, as it will be first time for me, I have never done it before. Thanks a lot tisfeng!

**Comment by Svec-Tomas** [comment]
I am really lost, can you or someone please guide me how to submit a PR?

**Comment by Jerry23011** [comment]
> I am really lost, can you or someone please guide me how to submit a PR?

Can you code in Objective-C? Submitting a PR means to contribute code to this project.

**Comment by Svec-Tomas** [comment]
No, I really can not code, sorry. I am just an ordinary user, who wanted to have there also Bing Translator. That's why I did not understand probably how to submit a Pull Request :(

**Comment by Svec-Tomas** [comment]
Can someone else do it instead of me, please?

**Comment by ChoiKarl** [comment]
> @ChoiKarl Are you interested in this feature? If interested, take a look, there's no time rush.

@tisfeng 公司G了，接下来要准备换工作和漫长的找工作过程🤣，人麻了，要是对时间不care的话，我可以看看。

**Comment by tisfeng** [comment]
默哀，，这个功能不着急，那就交给你了。

**Comment by Svec-Tomas** [comment]
Thanks a lot to everyone! 👍

**Comment by tisfeng** [comment]
This feature has been completed by @ChoiKarl  and will be released in the next version.

**Comment by Svec-Tomas** [comment]
That's fantastic, thanks a lot! 🙏😍

**Comment by tisfeng** [comment]
Hi, the [2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) version has Bing translation support.
