### ISSUE TITLE
🚀 功能建议：希望尽快推出windows版本，以及付费功能

### ISSUE THREAD

**Issue by neo233233233** [tisfeng/Easydict#147]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

如题，除了识别精度准确度这种可以不断完善的技术问题，目前ocr市场，个人感觉没有比easydict好用的翻译工具，若有windows版本，将是绝杀

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
#34 #57
