### ISSUE TITLE
🚀 功能建议：希望“快捷功能”增加一个“显示 Apple Dictionary快捷图标”

### ISSUE THREAD

**Issue by qq420100523** [tisfeng/Easydict#148]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

“快捷功能”增加一个“显示 Apple Dictionary快捷图标”，方便在划词查询后调用系统字典查询单词

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
了解，不说我差点忘了，系统词典还没添加 😓

**Comment by tisfeng** [comment]
添加了苹果的系统词典，效果不错 😌

<img width="456" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/2f94ea1c-a50c-4432-9bf5-b415620b2e04">

<img width="1075" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/66bff7c3-a719-4a4c-a02e-5b87b74b35e2">

**Comment by tisfeng** [comment]
还没写完，但感觉应该可以。 你好，你这些词典资源哪里来的，给个链接，我试一下看看。

**Comment by qq420100523** [comment]
> 还没写完，但感觉应该可以。 你好，你这些词典资源哪里来的，看起效果很不错，给个链接，我试一下看看。

大部分都我转换mdx的，推荐你下载这部试试
https://placeless.net/blog/macos-dictionaries
这部非常完美

**Comment by tisfeng** [comment]
Ok，感谢！

**Comment by qq420100523** [comment]
> Ok，感谢！

作者，新版本什么时候出呢，非常想体验这个集成系统词典功能，或者先给我个内测也行，我又转换了好几本大词典，可以帮忙测试一下🤣

**Comment by tisfeng** [comment]
大体上弄好了，但是还有一些细节需要调整。

 本来如果只是支持系统自带的词典就还好，但现在想要支持用户自己导入的词典，就会比较麻烦，因为自定义词典每个都有自己的 css，相互之间可能导致冲突，甚至影响到系统词典的显示，而这一块的调整涉及到了 html 和 js，我不太懂，就很抓瞎 😢

稍微再整理一下代码，明天后天我会把这部份功能的代码推上去。

<img width="442" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/affba38a-6f78-4dd9-910f-e74d77c80d0b">

**Comment by tisfeng** [comment]
@qq420100523  你好，你熟悉 html 吗，可以帮忙一起来优化这个功能？

**Comment by qq420100523** [comment]
> @qq420100523 你好，你熟悉 html 吗，可以帮忙一起来优化这个功能？

我也仅限于瞎琢磨而已，达不到帮忙的水平😅
另：系统词典对于js的支持也很有限，就我了解，只支持在html标签内绑定事件执行行内js代码，不支持script标签内嵌或文件导入方式的js代码。

**Comment by tisfeng** [comment]
@qq420100523 你好，代码推上去了，main 和 dev 分支都是同步的，你可以尝试自己编译运行，测试。

Easydict 的【苹果词典】整体架构基本已完工，但还有很多细节需要完完善。

目前【苹果词典】借用了系统词典 App 的部份功能，例如会自动加载词典 App 中所有启用的词典，查询结果显示顺序也遵从词典 App 设置中的排序。

<img width="466" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/74bf803f-1e24-404b-ae8f-c29780667481">

**Comment by tisfeng** [comment]
@qq420100523 <script> 内嵌 JS 代码也是支持的，例如 https://github.com/tisfeng/Easydict/blob/77243186c92460a633d1e5c1eff6e9089ff3ac21/Easydict/Feature/Service/Apple/AppleDictionary/EZAppleDictionary.m#L200

> 系统词典对于js的支持也很有限，就我了解，只支持在html标签内绑定事件执行行内js代码，不支持script标签内嵌或文件导入方式的js代码。

比较麻烦的是，似乎不支持外置的图片和音频，如果想在 Easydict 使用外带图片音频的词典，可能需要参考柯林斯词典，提供一个设置页。

<img width="1706" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/42dac6f7-6a7d-4f13-b384-8b8a23561ca8">

<img width="734" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f0e3946a-d7c2-4caa-a9c1-1ec623461a46">

**Comment by tisfeng** [comment]
另外，我想参考系统词典 App，实现单个词典折叠功能，但这个需要调整插入的 css，以及要写 JS 代码，我不太熟悉。

@qq420100523  可以帮忙看看吗？欢迎提交 PR。

<img width="1707" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/213a1458-0651-40bf-a23e-792f51cb912d">

**Comment by qq420100523** [comment]
> 比较麻烦的是，似乎不支持外置的图片和音频，如果想在 Easydict 使用外带图片音频的词典，可能需要参考柯林斯词典，提供一个设置页。
> 
你是指mdx转换成苹果词典不支持外置的图片和音频吗？支持的，可以参考一下帖子：https://kaihao.io/2018/mdict-to-macos-dictionary/
因为mdx词典使用的路径是以/开头，而苹果词典是相对路径，需要处理一下，去掉/，如：
`sed -i "" 's:src="/:src=":g' oald8.xml`
而音频的话，需要转一下格式，苹果词典不支持.spx，可以转成.mp3

**Comment by qq420100523** [comment]
> 另外，我想参考系统词典 App，实现单个词典折叠功能，但这个需要调整插入的 css，以及要写 JS 代码，我不太熟悉。
html5有一个<details> 标签，可以实现类似的折叠功能，不需要css和js代码，是html5纯原生的，可以参考一下。https://www.runoob.com/tags/tag-details.html

**Comment by tisfeng** [comment]
不是的，苹果词典可以支持外置图片和音频，这个我知道，你仔细看截图就明白，我是说第三方应用，比如 Easydict，可能没办法支持外置的图片和音频，因为这些资源的文件路径不好处理。这个我后面再研究一下。

![image](https://github.com/tisfeng/Easydict/assets/25194972/765af760-52b8-4fdc-9d13-fc2bf0b87ad6)

**Comment by tisfeng** [comment]
details 这个我也略微知道一点 https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/details

但问题是，实际情况比较复杂，details 需要改动，左右两侧要有分割线，并且分割线的宽度要和词典标题自适应，默认展开的三角形是黑色，如果要适配深色模式，也要改。

<img width="466" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/01717f3c-054a-41d7-9553-06d34e7dfaaf">

**Comment by tisfeng** [comment]
在添加了 details 后，还需要额外处理点击三角形的事件，无论是展开还是隐藏，都要重新计算 iframe 的高度，这个不写 js 能实现吗？我试过，好像不行，可能是我不太懂。

另一个比较坑的一点是，details 的三角形在 Safari 和 Chrome 上渲染不一样，同一份代码，在 Chrome 是正常的，但在 Safari 上三角形是在中间 😰

<img width="1703" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/3a6bef61-28cb-4e90-8895-f25c0b811b58">

**Comment by qq420100523** [comment]
> 另一个比较坑的一点是，details 的三角形在 Safari 和 Chrome 上渲染不一样，同一份代码，在 Chrome 是正常的，但在 Safari 上三角形是在中间 😰
> 
刚好看到这个帖子，自定义details 的三角形：https://www.51cto.com/article/706468.html

**Comment by tisfeng** [comment]
@qq420100523  你好，如果你对 html 这块比较熟，麻烦帮忙看看代码，在本地编译运行，调试一下上面我说的几个问题，我是真不太懂 html，写起来太累了 🫠

**Comment by qq420100523** [comment]
> 不是的，苹果词典可以支持外置图片和音频，这个我知道，你仔细看截图就明白，我是说第三方应用，比如 Easydict，可能没办法支持外置的图片和音频，因为这些资源的文件路径不好处理。这个我后面再研究一下。
> 
我明白你的意思了，不过看苹果的三指lookup也是没有实现对音频的支持，如果要读取到真实的资源文件，可能你需要先获取到这个词典的绝对路径，再对src路径进行补充才行。

**Comment by qq420100523** [comment]
> @qq420100523 你好，如果你对 html 这块比较熟，麻烦帮忙看看代码，在本地编译运行，调试一下上面我说的几个问题，我是真不太懂 html，写起来太累了 🫠

我也不熟html，更没编译mac的程序经验😅

**Comment by tisfeng** [comment]
@qq420100523 你好，我打包了一个版本，你可以测试一下各个词典的展示效果，有问题或建议都可以反馈。

[Easydict 1.4.0.zip](https://github.com/tisfeng/Easydict/files/12346254/Easydict.1.4.0.zip)

**Comment by qq420100523** [comment]
> @qq420100523 你好，我打包了一个版本，你可以测试一下各个词典的展示效果，有问题或建议都可以反馈。
> 
> [Easydict 1.4.0.zip](https://github.com/tisfeng/Easydict/files/12346254/Easydict.1.4.0.zip)
试用了一下，下面是我的一点建议
![113919463fc3218b0d06213bf02236bd.png](https://ice.frostsky.com/2023/09/19/113919463fc3218b0d06213bf02236bd.png)
![cb66cd0e1b0b1cf8effb782978894e41.png](https://ice.frostsky.com/2023/09/19/cb66cd0e1b0b1cf8effb782978894e41.png)

**Comment by qq420100523** [comment]
![c39cfe512a97ebd64462e93b5c1e6b2a.png](https://ice.frostsky.com/2023/09/19/c39cfe512a97ebd64462e93b5c1e6b2a.png)

**Comment by tisfeng** [comment]
@qq420100523 感谢反馈，上面是之前的版本，后面我又优化迭代了几个版本：

- 修复了最小高度问题
- 简单实现了自动适配深色模式
- 右上角添加了快捷打开苹果词典图标

<div>
<img width="45%" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/c0fa59f0-35b5-479c-8f49-ecc431fd45cf">
<img  width="45%" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/988afdd3-db42-42b9-881e-6677f00653be" >
</div>

**Comment by qq420100523** [comment]
> @qq420100523 感谢反馈，上面是之前的版本，后面我又优化迭代了几个版本：
> 
> * 修复了最小高度问题
> * 简单实现了自动适配深色模式
> * 右上角添加了快捷打开苹果词典图标
> 
> <img alt="image" width="45%" src="https://user-images.githubusercontent.com/25194972/268991021-c0fa59f0-35b5-479c-8f49-ecc431fd45cf.png"> <img alt="image" width="45%" src="https://user-images.githubusercontent.com/25194972/268990314-988afdd3-db42-42b9-881e-6677f00653be.png">

看起来完成度很高，什么时候放出一版试用呢😆

**Comment by tisfeng** [comment]
快了，等我做一下收尾工作。

关于单词头的显示，一是为了和目前已有的有道词典渲染格式保持一致，二来，有些词典的内容比较复杂，不容易一眼看出查询的单词。

<img width="446" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/dc4eaf2a-a10b-4234-aca2-c9542bece452">

**Comment by qq420100523** [comment]
有了苹果词典的加持，查词的专业性上提升了一大

> 用你提到的颜色转换代码试了一下，效果可以，但还是赶不上苹果自定义的，不知道它这个到底如何实现的，我琢磨了好久，还是没搞明白。
> 
> 我对这个 css 不了解，如果你熟悉的话，可以帮忙调一下吗？
> 
> ```
> filter: invert(0.8235) hue-rotate(180deg) saturate(300%);
> ```
> 
> <img alt="image" width="952" src="https://user-images.githubusercontent.com/25194972/268997368-5d10c328-960b-4aff-b77d-482411b9916a.png">

我感觉是saturate(300%)饱和度太高的问题，我试试调底一点看看效果

**Comment by tisfeng** [comment]
可以，感觉这个效果已经比较接近了，这种使用 css 适配深色模式的方式，比我之前的方案效果好，也更简单高效。暂时就这个了，后续可以再慢慢优化。

<img width="1710" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/5e3cb185-2394-4111-b760-fd8d95ad9f90">

**Comment by tisfeng** [comment]
争取这周末发个新版。

你可以先试试 [Easydict.zip](https://github.com/tisfeng/Easydict/files/12673627/Easydict.zip)

**Comment by tisfeng** [comment]
@qq420100523  发现一个问题，filter 会导致图片失真，应该排除在外的，但我尝试了一番，不知道怎么修改 😢

<img width="959" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/906428db-bba5-4950-aae0-fffc5ffb8d15">

**Comment by qq420100523** [comment]
> @qq420100523 发现一个问题，filter 会导致图片失真，应该排除在外的，但我尝试了一番，不知道怎么修改 😢
> 
我也试了一下，filter是属于简单暴力的方式对元素进行滤镜处理，还是比不过苹果的处理。要是能支持苹果的那种方式才是比较完美的。

**Comment by tisfeng** [comment]
基本整理完了，文档也写好了，过两天就发新版本。

@Jerry23011  有空帮忙过一下整体功能，也检查一下文档有没有问题，及时查漏补缺。

[苹果系统词典](https://github.com/tisfeng/Easydict/tree/dev#%E8%8B%B9%E6%9E%9C%E7%B3%BB%E7%BB%9F%E8%AF%8D%E5%85%B8) 这部份是新加的，重点看一下，最好照着流程过一遍，这些操作在我电脑上没问题，但不确定其他用户的电脑环境是否一致。

**Comment by Jerry23011** [comment]
> 也检查一下文档有没有问题
英文文档没更新，我回头可以整一下

**Comment by tisfeng** [comment]
赞，这个就麻烦你了。

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已添加苹果词典。
