### ISSUE TITLE
🐞 Bug Report: 点击菜单图标之后 选择功能的时候好卡，不跟手

### ISSUE THREAD

**Issue by himonster1** [tisfeng/Easydict#149]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Problem description

<img width="215" alt="image" src="https://github.com/tisfeng/Easydict/assets/77065609/7b03c2a4-b87f-4f5d-b0e6-d28183380968">
这个界面，点击菜单图标之后，我鼠标已经放到红框位置了，但是选中的UI图标还在第一个要卡一下才会到红框位置，就是卡卡的，不跟手

### Reproduction steps

点一下 菜单图标，然后鼠标上下来回动动，鼠标动的快了，UI就跟不上了

### Expected result

希望变得流畅

### Proposed solution (optional)

<img width="585" alt="image" src="https://github.com/tisfeng/Easydict/assets/77065609/d6ed3b4c-8854-4d16-bcfe-4678f3f6d8f3">

### Device information and OS version

Intel，macos12.6.7

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR!

**Comment by tisfeng** [comment]
你好，这是否和 https://github.com/tisfeng/Easydict/issues/17 一样的问题？

**Comment by himonster1** [comment]
是的

**Comment by tisfeng** [comment]
关闭重复 issue #17
