### ISSUE TITLE
功能建议：增加popclip插件

### ISSUE THREAD

**Issue by jajunz** [tisfeng/Easydict#15]
虽然已经有划词后自动显示翻译图标的功能，但仅限于浏览器中使用，在第三方文本中则无法划词翻译，建议增加popclip插件。

**Comment by tisfeng** [comment]
Easydict 的实现原理和 PopClip 类似，理论上是能够在所有应用中触发自动划词的，至少在我的电脑上，所有应用都能够正常使用。

但鉴于设备环境的复杂性，程序在不同电脑上运行表现确实可能不一样，例如这个问题  https://github.com/tisfeng/Easydict/issues/10#issuecomment-1416916726 ，需要进一步排查。

麻烦提供一下你的设备型号和系统版本，以及无法划词的应用列表，我仔细看看。

**Comment by tisfeng** [comment]
配合 PopClip 使用 https://github.com/tisfeng/easydict#%E9%85%8D%E5%90%88-popclip-%E4%BD%BF%E7%94%A8
