### ISSUE TITLE
🚀 功能建议：增加快捷键以“复制首个翻译结果”

### ISSUE THREAD

**Issue by rainzm** [tisfeng/Easydict#151]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

增加快捷键以“复制首个翻译结果”

### 使用场景（可选）

目前 Easydict 可以自动复制首个翻译结果，很多时候，比如选中翻译的结果通常不需要复制，否则会污染粘贴板。

但是我又需要 “快捷复制首个翻译结果” 这个功能，因为我使用 Easydict 的一大场景是在编程或者其他写作的时候，做英文编写的辅助。

这个过程中，我倾向于不使用鼠标，使用快捷键打开 Easydict 的翻译框，输入并回车，然后通过快捷键复制到结果，然后切换回写作。

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
Hi @rainzm 

看到你愿意提交 PR！如果没问题的话，我可以把这个 issue assign 给你吗😄

**Comment by rainzm** [comment]
我蛮有兴趣的。不过我没写过object-c，所以需要你的一些指导：

1. object-c 是不是用 xcode 开发最方便呢？
2. 目前已经有的功能“自动复制第一个翻译结果”的代码在哪个地方？
3. 帮我指出一个现在已经有的快捷键的代码

我想会对我的参与有很大的帮助，谢谢。

**Comment by Jerry23011** [comment]
> 我蛮有兴趣的。不过我没写过object-c，所以需要你的一些指导：

我也不会 objc，这个还是需要找 @tisfeng 

> object-c 是不是用 xcode 开发最方便呢？

这个项目就是用 Xcode 搭建的

> 目前已经有的功能“自动复制第一个翻译结果”的代码在哪个地方？

这个在 EZSettingViewController.m 中，具体的细节请问 @tisfeng

**Comment by tisfeng** [comment]
@rainzm  你好，我想了一下，如果 “复制首个翻译结果” 是个高频操作，确实可以考虑添加一个快捷键。

另外，从你描述的应用场景来看，我觉得也可以在设置页添加一个类似 “自动复制除【自动划词翻译】外的第一个翻译结果” 的设置选项，这样似乎更方便？

我很少使用这样功能，你可以考虑测试一下，看看那个方案更好。

> 目前 Easydict 可以自动复制首个翻译结果，很多时候，比如选中翻译的结果通常不需要复制，否则会污染粘贴板。
>
> 但是我又需要 “快捷复制首个翻译结果” 这个功能，因为我使用 Easydict 的一大场景是在编程或者其他写作的时候，做英文编写的辅助。

<img width="627" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/04d1ff24-a98f-406e-8c99-0f152800d838">

**Comment by rainzm** [comment]
另外，对于这个功能，我觉得提供快捷键把主动性给到用户更好。虽然多了一步操作，但也许能覆盖更多的场景，因为总有时候不需要或者不想要复制。

**Comment by tisfeng** [comment]
@rainzm 很棒，思路没问题，只是有一点，获取第一个翻译结果，可以使用已有的 `self.firstService` 属性，这个值不一定是数组 allShowingResults 的第一个，因为第一个服务可能未启用查询，内容为空。

问题不大，尽量参考已有的功能代码，多调试就好了。

加油。

**Comment by rainzm** [comment]
好的~ 所以`self.firstService`指的是第一个查询成功的翻译服务是嘛？

**Comment by tisfeng** [comment]
是的，但要注意，只有当服务查询成功后，里面才会有翻译结果。

**Comment by tisfeng** [comment]
[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已添加。
