### ISSUE TITLE
🚀 功能建议：翻译之后的面板，在下次翻译的时候是否应该自动隐藏？

### ISSUE THREAD

**Issue by himonster1** [tisfeng/Easydict#152]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

我先通过截图翻译，软件会自动跳出来翻译面板，里面是翻译内容。也就是这个

<img width="381" alt="image" src="https://github.com/tisfeng/Easydict/assets/77065609/b2ac565a-e9f4-4fe2-b1c4-b79ee1db56b5">

当我下一次截图翻译的时候，这个面板并不会自动消失，有时候会挡住想要截图的部分

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
Hi @himonster1 

这个看起来和 #126 很像，你可以确实一下是否是一个问题吗

**Comment by himonster1** [comment]
是的

**Comment by rainzm** [comment]
Duplicate of #126
