### ISSUE TITLE
ocr 快捷键可以是一样的两个按键

### ISSUE THREAD

**Issue by linzzzzllll** [tisfeng/Easydict#154]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

ocr 快捷键可以是一样的两个按键

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR!

**Comment by sdfsdf3asdasd** [comment]
是的体验会好很多目前bob可以

**Comment by tisfeng** [comment]
你是意思是，类似支持快捷键 `Cmd + Cmd` 触发 OCR ？

> ocr 快捷键可以是一样的两个按键

**Comment by linzzzzllll** [comment]
是的> 你是意思是，类似支持快捷键 `Cmd + Cmd` 触发 OCR ？
> 
> 
> 
> > ocr 快捷键可以是一样的两个按键

**Comment by linzzzzllll** [comment]
我现在是按两下 option 来使用 pop 很方便

**Comment by tisfeng** [comment]
之前提过 https://github.com/tisfeng/Easydict/issues/5#issuecomment-1646774854 ，类似 `Cmd + Cmd` 这种非常规快捷键，可是可以支持，但我觉得太麻烦了，目前使用的快捷键第三方库不支持，需要自己手动去扩展，或者换其他的库，很累。

另外，我看你勾选了【我愿意提交 PR!】，如果你能提交 PR，我很乐意接受。

**Comment by tisfeng** [comment]
[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本已支持 double tap 快捷键。
