### ISSUE TITLE
🚀 功能建议：根据系统版本使用 “设置“ 或 ”偏好设置“

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#159]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

在运行 macOS 13+ 的系统版本上使用”设置“&”Settings“，在 macOS 12 及以下的系统上使用”偏好设置“&”Preferences“
这样会更符合 Apple 对系统最新的调整

### 使用场景（可选）

<img width="231" alt="SCR-20230814-ticw" src="https://github.com/tisfeng/Easydict/assets/89069957/bd0b2c9f-b975-430d-a9ec-07becb48918f">

在菜单栏弹窗中的偏好设置，在用户的系统版本为 macOS 13+ 时可以改为“设置”

### 实现方案（可选）

[这个项目](https://github.com/sindresorhus/Settings)实现了类似效果

https://github.com/sindresorhus/Settings/blob/b99f45cba818a9d483fb58e9b31de5dee799e315/Sources/Settings/SettingsTabViewController.swift#L97

### 是否愿意提交 PR 实现该功能

- [x] 我愿意提交 PR!

**Comment by tisfeng** [comment]
看了一下当前电脑系统的一些软件，都是【设置...】，关于这一点，我个人的要求不强烈， 改一下可以，可能一些文档也要改，暂时不改也行，都这么久快习惯了。。

你要是想改，就提个 PR 改吧。

<img width="177" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f30755f7-2948-4126-911e-4a7d4be4e266">

<img width="205" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/fd404a2a-a665-4ccf-941f-0af1c8b5ce76">

**Comment by Jerry23011** [comment]
我研究一下这个 storyboard 上怎么判断系统版本显示不同的 string，后面还涉及到中英的本地化

**Comment by Jerry23011** [comment]
> 我准备清理 issue 了，请问这个设置显示，你是否有计划修改？

是的，但是 Storyboard 貌似无法实现，我想要不然都改成设置，要不然等一些界面重写之后再说

**Comment by tisfeng** [comment]
可以，那就改成设置吧。

**Comment by tisfeng** [comment]
[2.0.2](https://github.com/tisfeng/Easydict/releases/tag/2.0.2) 版本已发布。
