### ISSUE TITLE
功能建议：OCR后能自动清除换行符

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#16]
## 功能描述
增加一个自定义选项，使得OCR之后能自动清除换行符后再翻译。
<img width="766" alt="image" src="https://user-images.githubusercontent.com/51783873/220383009-781b3afd-60b7-4338-b3fd-a3d4ab27bb6a.png">
## 使用场景（可选）

大部分的OCR翻译场景其实都是翻译成段的句子，而这种情况下默认清楚换行符也许是更好的选择。比如知名的OCR工具白描就默认清除了换行符。这样才能翻译出一整个完整的句子。
<img width="1909" alt="截屏2023-02-21 下午11 13 00" src="https://user-images.githubusercontent.com/51783873/220383711-72b3c7e5-38c1-435b-84cd-3a1c28129297.png">

**Comment by tisfeng** [comment]
感谢反馈，确实，OCR 后自动清除换行更符合实际应用场景，稍后我优化一下。

**Comment by tisfeng** [comment]
优化了一下，感觉效果还可以 😌

<img width="1716" alt="image" src="https://user-images.githubusercontent.com/25194972/220942645-1b2dd50c-4c34-401e-9c52-033b2445bddd.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/25194972/220942702-43d40f5c-1f10-4333-b23e-c116fa30fd13.png">

**Comment by tisfeng** [comment]
当然，包括中英文，只要 OCR 句末不是断句结束符 [ 。？!.?！] ，都会自动清除换行符。

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/25194972/221415400-c75453e0-1c8c-4801-a91b-755e49372f59.png">

**Comment by MoienBowen** [comment]
补充：
建议使用 macOS 系统 OCR, 会自动过滤无效换行符。

具体可以使用 shortcuts 的 extract text from 功能，测试样本可以选择英文论文 pdf。

**Comment by tisfeng** [comment]
你好，新版本已修复该问题  https://github.com/tisfeng/Easydict/releases/tag/1.3.0

**Comment by tisfeng** [comment]
> 补充： 建议使用 macOS 系统 OCR, 会自动过滤无效换行符。
> 
> 具体可以使用 shortcuts 的 extract text from 功能，测试样本可以选择英文论文 pdf。

之前没看明白，后面尝试了一下，感觉这种方式确实还可以，不愧是快捷指令。

但经过测试后发现，相比用代码手动实现，它还是太简单粗暴了：

1. 不能指定 OCR 的识别语言，这在识别一些字符相似较高的语言文本中很有用，比如日语，如果不指定识别语言，快捷指令很可能会按中文来识别，导致识别准确度不高。
2. 它这个换行符处理是挺方便，但本质上还是拼接算法，结果也不一定完全正确。这个算法，我自己也能一步步实现，而且可以根据场景、语言等参数进行优化。

我用前面的图片试了一下快捷指令，它这换行就不太行 🙁

<div>

<img width="370" alt="image" src="https://user-images.githubusercontent.com/25194972/235965980-12ef8c83-86a8-41ba-93f7-573c306e0aed.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/25194972/235966738-76d95b66-bd71-4249-b3d9-b5911be778c8.png">

</div>

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/25194972/235965598-f4e167b6-8d59-4cb0-96e6-8a6f62265e7e.png">
