### ISSUE TITLE
🚀 Feature Request: Update README for Microsoft Translate

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#162]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Feature description

TODO: Update README for the upcoming Microsoft translate.

Tracking in PR #161 
Relevant issue #143 

### Resources
[Language support](https://www.microsoft.com/zh-cn/translator/languages/)
[Bing Translator website](https://www.bing.com/translator)

**Comment by tisfeng** [comment]
@Jerry23011 你好，https://github.com/tisfeng/Easydict/pull/161 代码已经合并到 dev 了，麻烦有空更新一下文档，在 dev 分支上更新就好。

**Comment by Jerry23011** [comment]
大概明天晚上搞定
