### ISSUE TITLE
🚀 功能建议：AI 翻译和自定义字典

### ISSUE THREAD

**Issue by 0xCryptoHuang** [tisfeng/Easydict#163]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 添加字典功能

最新版没有ai的翻译，能不能出一个自己添加字典的功能，可以添加一些mdx格式的字典库

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
Duplicate of #28 and #25

**Comment by tisfeng** [comment]
@0xCryptoHuang 你好，下个版本会开放 OpenAI 翻译，当前版本请参照 #28 手动开启。

关于自定义词典，可以参考 https://github.com/tisfeng/Easydict/issues/148 ，最新的 dev 代码已经支持了苹果系统词典，而 mdx 词典可以使用 [pyglossary](https://github.com/ilius/pyglossary) 转换为苹果词典。 

稍后我会专门写个文档，介绍 Easydict 如何使用苹果词典。
