### ISSUE TITLE
🐞 反馈问题：请问如何恢复被隐藏的状态栏图标

### ISSUE THREAD

**Issue by lzyjxqt** [tisfeng/Easydict#173]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

设置了隐藏状态栏图标之后，再想修改设置就没有入口，试了cmd+` 也没调出来

### 重现步骤

设置了隐藏状态栏图标之后，再想修改设置就没有入口，试了cmd+` 也没调出来

### 期望结果

恢复被隐藏的状态栏图标

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
Hi @lzyjxqt
你可以尝试从启动台点击 Easydict 重新启动，即可调出窗口

**Comment by tisfeng** [comment]
@lzyjxqt  为什么要用 cmd+` 🙄

 `Cmd + ,` 才是打开设置页，这是 macOS 通用的设置快捷键。

![](https://i.imgur.com/vrnDoY6.png)
