### ISSUE TITLE
🚀 功能建议：请问可以支持一下取词功能吗？就像欧路词典的取词功能一样

### ISSUE THREAD

**Issue by itangqiao** [tisfeng/Easydict#174]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

<img width="1091" alt="image" src="https://github.com/pot-app/pot-desktop/assets/44393379/90fa14be-c069-4871-b585-1215ed3c576c">

就像这样，移入就可以自动显示单词意思了~

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
听起来不错，我研究一下～

**Comment by tisfeng** [comment]
之前尝试了一下，但这个功能可能不好实现，尤其是有些应用不支持系统的 Accessibility 取词。

另外，这个功能的触发方式也不好设置，可能要借助 option 或 command 键，感觉不是很好。

因此建议还是直接使用 OCR 截图翻译吧。
