### ISSUE TITLE
🐞 反馈问题：在 Xcode 15.0 项目 Build Failed

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#175]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

在升级到 Xcode 15 后项目无法 build，Xcode 会有 `DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead` 字样的报错

### 重现步骤

- clone 项目到本地
- 使用 Xcode 15 打开
- 项目无法 build，Xcode 报错
<img width="1512" alt="截屏2023-09-20 11 17 26" src="https://github.com/tisfeng/Easydict/assets/89069957/2c0569d0-1025-41f2-9dce-5d6a5971f9a2">

### 期望结果

可以在 Xcode 15 中直接 build 项目

### 设备信息 && 操作系统版本

MacBook Pro 14' macOS 13.5.2

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
行，等我晚上升级一下 Xcode 看看。

**Comment by Jerry23011** [comment]
辛苦🙏🏻

我看 Stackoverflow 上有人提了相关的问题，不知道能不能有所帮助

**Comment by Jerry23011** [comment]
@tisfeng 我现在刚刚开始尝试迁移 string catalog，但是拉取最新的 dev 之后发现 build 没有问题，但是运行的时候会报错 `Thread 1: signal SIGABRT`

<details> <summary> Console 信息 </summary>
dyld[72412]: Library not loaded: @rpath/AFNetworking.framework/Versions/A/AFNetworking
  Referenced from: <06D5B9F3-DB0F-3CE7-9A7D-AD90B2AE7D61> /Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/MacOS/Easydict-Debug
  Reason: tried: '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/usr/lib/swift/AFNetworking.framework/Versions/A/AFNetworking' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' (code signature in <6777C7B0-825F-3E2C-8D9B-6BEDE1D37571> '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/MacOS/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/MacOS/../Frameworks/AFNetworking.framework/Versions/A/AFNetworking' (code signature in <6777C7B0-825F-3E2C-8D9B-6BEDE1D37571> '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/AFNetworking.framework/Versions/A/AFNetworking' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' (code signature in <6777C7B0-825F-3E2C-8D9B-6BEDE1D37571> '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/MacOS/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/AFNetworking.framework/Versions/A/AFNetworking' (no such file), '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/MacOS/../Frameworks/AFNetworking.framework/Versions/A/AFNetworking' (code signature in <6777C7B0-825F-3E2C-8D9B-6BEDE1D37571> '/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/Easydict-Debug.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))

**Comment by tisfeng** [comment]
@Jerry23011 可能是缓存问题，第三方库的内容不一致导致，你 clean 一下，把 DerivedData 清空再编译。

<img width="866" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/4b05d510-4209-445c-8882-6dabdf2614a9">

**Comment by Jerry23011** [comment]
我的 Derived Data 已经全部清了，而且也在 Xcode 中 Clean build folder 了，但是还是不好用
<img width="942" alt="截屏2023-09-23 21 40 34" src="https://github.com/tisfeng/Easydict/assets/89069957/01cc4b5d-e50c-4c2a-9749-11fec255fb5e">

**Comment by tisfeng** [comment]
我之前好像改过签名，你检查一下 `Signing & Capabilities` 设置。

**Comment by Jerry23011** [comment]
> 我之前好像改过签名，你检查一下 `Signing & Capabilities` 设置。

这个我也都看了，我都改成 Sign to run locally 了，签名应该造成不了影响

**Comment by tisfeng** [comment]
> 参考这个 [CocoaPods/CocoaPods#12012 (comment)](https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1653051943) 修复了，代码已推到 dev。

我前面修改完 Podfile 后，执行了 pod update，目前在我电脑上一切运行正常。项目中 pod 部份都是用 git 管理的，按理说只要我们保持代码同步，这里应该也不会有问题。

但 CocoaPods 比较复杂，你可以在本地手动执行一下 pod update 试试。

**Comment by Jerry23011** [comment]
> 但 CocoaPods 比较复杂，你可以在本地手动执行一下 pod update 试试。

刚刚试了一下，还是跑不起来，我可以先提一个迁移后的 PR，你先看看能不能在你那里跑起来，有没有什么问题

**Comment by Jerry23011** [comment]
我看了一下报错的这个路径：`/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/AFNetworking.framework/Versions/A/AFNetworking`
我的 DerivedData 里是有这个文件的，但是路径不一样，多了一层文件夹：`/Users/jerry/Library/Developer/Xcode/DerivedData/Easydict-djhvqbaptyctzqewbdkjmpawtuov/Build/Products/Debug/AFNetworking/AFNetworking.framework/Versions/A/AFNetworking`

**Comment by Jerry23011** [comment]
@tisfeng 我删除了本地的库，清除了所有缓存，重新 clone 了一遍项目就能跑了，也不知道为什么😂

**Comment by tisfeng** [comment]
OK，跑起来就行，苹果 Xcode 各种坑太多了。
