### ISSUE TITLE
🚀 功能建议：采用 Xcode 15 引入的 String Catalog 进行本地化

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#176]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

Xcode 15 加入了新的本地化方式 String Catalog，每次 build 的时候都可以自动检索代码中的字符串然后自动添加到 catalog 里，无需手动添加 string，只需要在不需要翻译的字符串加 comment 说明无需翻译
<img width="1512" alt="截屏2023-09-21 12 55 45" src="https://github.com/tisfeng/Easydict/assets/89069957/511f0374-dd34-4d6c-b9c9-f3b25805cf37">
<img width="1512" alt="截屏2023-09-21 12 56 02" src="https://github.com/tisfeng/Easydict/assets/89069957/b544d8b6-9ac7-4f57-9173-e457da4fc2ec">

### 使用场景（可选）

在 Xcode 15+ 进行开发时让 Xcode 自动同步本地化字符串

### 实现方案（可选）

从 Localizable.string/Localizable.stringdict 迁移到 String Catalog

[Developer Doc](https://developer.apple.com/documentation/xcode/localizing-and-varying-text-with-a-string-catalog)
[WWDC Video session](https://developer.apple.com/videos/play/wwdc2023/10155)

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR!

**Comment by tisfeng** [comment]
这个好！那就麻烦你迁移一下了。

**Comment by Jerry23011** [comment]
> 这个好！那就麻烦你迁移一下了。

没问题，大概这周末提 PR

**Comment by choykarl** [comment]
现在必须要使用xcode15才能打开工程了么

**Comment by tisfeng** [comment]
是的，新引入的 String Catalog 需要 Xcode 15， 这个提交 4ac786a4ddbb8ebae8926ab84c22fca2cbe8ccb7 之前可以用 Xcode 14。

稍后我弄个 String Catalog 之前的代码分支，只为了方便简单调试，不会维护功能。
