### ISSUE TITLE
功能建议：配置代理功能

### ISSUE THREAD

**Issue by vvanglro** [tisfeng/Easydict#18]
## 功能描述
首先非常感谢您能开源如此优秀的软件~

配置代理功能, 比如一些海外的翻译google, 这样有代理的情况下, google翻译就可以很好的使用.
可以在软件系统设置里开放一个配置代理功能, 然后在服务里有个选择是否使用代理的按钮.
或者直接在服务里可以单独配置代理功能.

**Comment by tisfeng** [comment]
你好，和众多 macOS 软件一样，Easydict 默认是支持系统代理的，也就是如果你使用了代理软件，那就可以正常用 Google 翻译，并不需要额外复杂的代理配置。

**Comment by vvanglro** [comment]
是的，这样是可以使用，但是比如我使用clash，每次我还得设置成系统代理后才能正常使用(系统代理不可能一直开着，影响其它网络请求)，如果软件增加一个配置填写代理地址的功能会好很多。

**Comment by tisfeng** [comment]
明白了，你的这个需求其实应该由代理软件处理，而且这种需求很普遍，所以类似 Clash 等代理软件都支持规则模式，你可以配置任意 URL 甚至 App 走代理或直连。

**Comment by vvanglro** [comment]
从软件使用体验方面看，如果软件自己本身能支持填写配置代理的话，我觉得更棒～
这个feature可以后面在考虑是否需要添加吧

**Comment by tisfeng** [comment]
了解，因为我日常都是开着代理软件的，规则模式完全能满足我的需求，目前项目还有其他重要功能需要实现，所以暂时不会加这个功能。以后若是遇到有需要使用这个场景的，可能会考虑添加。

**Comment by cn-qlg** [comment]
+1，电脑虽然开着代理，但是默认不是全局的，日常只有浏览器需要代理，然后一般通过插件来切换代理，其他软件不走代理。

**Comment by tisfeng** [comment]
目前的代理软件，如 Surge 或 ClashX 等应该都有【规则判定】类似模式，可以非常方便地配置某些 IP 请求走代理或者直连，我觉得这个功能很好用，完全能解决某些翻译服务需要走代理的需求场景。

<img width="628" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/3aeb9f0c-298b-498b-966c-0e2933a81683">

**Comment by tisfeng** [comment]
对于我来说，代理软件完全能实现这个需求，所以我不太能理解，一个翻译软件为什么要专门配置代理功能 🫠

**Comment by CreatorZZY** [comment]
> 对于我来说，代理软件完全能实现这个需求，所以我不太能理解，一个翻译软件为什么要专门配置代理功能 🫠

并不是所有人都是用全局代理的。

**Comment by tisfeng** [comment]
> > 对于我来说，代理软件完全能实现这个需求，所以我不太能理解，一个翻译软件为什么要专门配置代理功能 🫠
> 
> 并不是所有人都是用全局代理的。

你是否使用过规则判定模式？

**Comment by gufeng0** [comment]
> > > 对于我来说，代理软件完全能实现这个需求，所以我不太能理解，一个翻译软件为什么要专门配置代理功能 🫠
> > 
> > 
> > 并不是所有人都是用全局代理的。
> 
> 你是否使用过规则判定模式？

我用的就是规则模式，但不知道是不是因为我找的规则并不好，漏网之鱼设置的是全部走代理，这样就会导致漏网之鱼里面也有很多误判，规则+全局其实也有很多不方便的地方，虽然这是免费开源项目，不好过多要求作者，但还是希望作者能考虑下增加这个功能
