### ISSUE TITLE
开机启动失效

### ISSUE THREAD

**Issue by nullcoke** [tisfeng/Easydict#183]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

尝试重新安装后仍然无法开机启动
![CleanShot 2023-10-17 at 10 17 12](https://github.com/tisfeng/Easydict/assets/78184805/cd491a8d-1388-497c-bb90-8486ae55ebde)
![CleanShot 2023-10-17 at 10 16 39](https://github.com/tisfeng/Easydict/assets/78184805/63a4b4d5-dad5-430f-9491-73fc307b6148)

### 重现步骤

无

### 期望结果

开机自启

### 设备信息 && 操作系统版本

Macbook Air M2, macOS 14.0

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by RD-aiot** [comment]
我也遇到了

**Comment by tisfeng** [comment]
我又去试了，在我电脑上无论正式版或是开发版，都是可以正常工作的，我的系统也是 macOS 14.0。

你在设置页开启或关闭【开机自启动】时，登录项中 Easydict 是否会变化？ 你试过手动添加  Easydict 作为登录项吗？

另外，请确保当 Easydict 申请 "System Events" 执行权限时，你给了它权限，具体可在【自动化】下面看到。

<img width="751" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/e7aeaa66-ecdd-41e5-8fef-9f0ee152ac44">

**Comment by tisfeng** [comment]
@Jerry23011 麻烦你有空也测试一下这个问题，跟进一下。

**Comment by nullcoke** [comment]
> 我又去试了，在我电脑上无论正式版或是开发版，都是可以正常工作的，我的系统也是 macOS 14.0。
> 
> 你在设置页开启或关闭【开机自启动】时，登录项中 Easydict 是否会变化？ 你试过手动添加 Easydict 作为登录项吗？
> 
> 另外，请确保当 Easydict 申请 "System Events" 执行权限时，你给了它权限，具体可在【自动化】下面看到。
> 
> <img alt="image" width="751" src="https://user-images.githubusercontent.com/25194972/276269212-e7aeaa66-ecdd-41e5-8fef-9f0ee152ac44.png">

设置页开启/关闭开机启动时有变化，尝试手动添加登录项也无效，System Events权限给了，自动化里面可以看到该项。我尝试关闭自动化里面的项目后重新启用一下就正常了，好奇怪: (

**Comment by nullcoke** [comment]
感谢 : )
