### ISSUE TITLE
🐞 反馈问题：用popclip取词，乱码

### ISSUE THREAD

**Issue by jiangaq** [tisfeng/Easydict#184]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

用popclip取词，乱码
<img width="308" alt="image" src="https://github.com/tisfeng/Easydict/assets/26076033/a20e9aca-9f9c-445e-90e9-49197cc008bd">

### 重现步骤

如题

### 期望结果

如题

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
看起来像是奇怪的小概率问题， 很可能是系统 bug。我稍后查一下。

对于这种奇怪的小概率问题，请尝试重启应用，卸载后重新安装应用，或者重启设备，看是否能解决问题。

**Comment by jiangaq** [comment]
是可能因为有格式的文本，用popclip就会这样，建议把所有编辑区的文本都去格式化

**Comment by tisfeng** [comment]
不是格式化问题。

查了一下，可能是一些 Unicode [私人使用区](https://zh.wikipedia.org/wiki/Unicode%E5%AD%97%E7%AC%A6%E5%B9%B3%E9%9D%A2%E6%98%A0%E5%B0%84) 特殊字符导致，例如  ，输入查询后，就会导致这种问题，且后续所有的文本显示都会是乱码。 感觉这是苹果的锅 😓

临时解决办法就是重启应用。

我想办法处理一下，下个版本应该会修复它。

<img width="467" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/d08fada6-3b75-4300-a456-d6258700ceff">

**Comment by tzcskys** [comment]
不仅仅是popclip取词，正常easydict自带的划词翻译也会有这个问题，（翻译是正常的，只是上面的原文展示是乱码），最近一周才出现的。
<img width="452" alt="Picture 1" src="https://github.com/tisfeng/Easydict/assets/57978010/de677ad9-033b-4b53-8df6-ce3ef8e0d307">

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已修复改问题。
