### ISSUE TITLE
🐞 反馈问题：option+D快捷键划词翻译，有时会同时打开迷你窗口和侧悬浮窗口

### ISSUE THREAD

**Issue by JintaoLee-Roger** [tisfeng/Easydict#185]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

在进行快捷键划词翻译时，仅使用一次快捷键划词翻译后，迷你窗口就会打开（出现在后台，三指上滑后会看到一个窗口，即使之前已经关闭了）。多使用几次快捷键划词翻译，有时会出现一个侧悬浮窗口，有时侧悬浮窗口和迷你窗口会同时出现。

### 重现步骤

版本：1.3.4

首先关闭所有Easydict窗口的窗口，然后选择一个词，按住option+D划词翻译，此时会出现一个侧悬浮窗口，之后三指上滑就会发现迷你窗口已经被打开。

<img width="553" alt="image" src="https://github.com/tisfeng/Easydict/assets/38800137/e2c73742-9999-4d29-b562-e5bd2563d696">

多使用几次option+D，就会出现迷你窗口和侧悬浮窗口都被调到了前面。

<img width="965" alt="image" src="https://github.com/tisfeng/Easydict/assets/38800137/c830b70d-9f00-47ee-9cf3-cf5ee23f0896">

### 期望结果

我希望迷你窗口在没有手动通过 option+A 调出来时，永远保持关闭状态。且在使用 option+D 时，无论发生什么情况（无论是否取到了词，取词的内容是否合理），迷你窗口都不要出现。

### 设备信息 && 操作系统版本

MacBook Air 2022,  macOS 14.0 (23A344)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
你另外一个窗口不是迷你窗口，迷你窗口左上角有 pin 图标的，你这个是主窗口。

你看一下这个问题是否和 https://github.com/tisfeng/Easydict/issues/141 一样？

**Comment by JintaoLee-Roger** [comment]
是一样的问题，谢谢
