### ISSUE TITLE
1.3.4 版本，未包含🍎 苹果系统词典功能 🥺

### ISSUE THREAD

**Issue by ysmintor** [tisfeng/Easydict#186]
release 最新的 1.3.4 是不是还没有包含系统（苹果）词典的功能？ 
功能介绍readme 页面说是有，但安装后并没有发现

**Comment by tisfeng** [comment]
README 上的介绍是新版本的，原计划上周末发布，但是由于发版前又测出了几个 bug 😓，因此需要延期修复一下，这周一定一定发布！

这个包有苹果词典功能 https://github.com/tisfeng/Easydict/issues/148#issuecomment-1727741626 ，或者你可以直接用最新 dev 代码在本地编译。

**Comment by ysmintor** [comment]
@tisfeng got it. 感谢作者
