### ISSUE TITLE
🐞 反馈问题：2.0.0 启动不了

### ISSUE THREAD

**Issue by bihell** [tisfeng/Easydict#187]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

启动不了,提示不安全但是『open anyway』之后还是无法启动

### 重现步骤

CPU：ARM 系统版本 14.0 (23A344)

1. 下载 https://github.com/tisfeng/Easydict/releases/download/2.0.0/Easydict.dmg
2. 解压以后程序拖到app目录
3. 双击启动，提示『“Easydict.app” can’t be opened because Apple cannot check it for malicious software.』
4. 进入到系统设置Privacy & Security ,然后选择 Open Anyway,然后再一次提示不安全以后点打开。。。
5. 然后就没然后了，程序没起来

### 期望结果

启动起来

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
可能是签名出了问题，我正在看 😢

**Comment by Kerinlin** [comment]
同样问题

**Comment by PrintNow** [comment]
![image](https://github.com/tisfeng/Easydict/assets/28396104/dcf6f044-76ab-4ff8-9f60-6db7d41a0bbc)

我更新之后也打不开了

**Comment by lifedever** [comment]
我也是

**Comment by WhyMeta** [comment]
一样，启动不了，没有任何提示，macOS Sonoma 14.0 
<img width="1030" alt="image" src="https://github.com/tisfeng/Easydict/assets/6345591/331de75c-10ca-487f-9d8e-94bfeddb7727">

**Comment by tisfeng** [comment]
程序有 bug，没考虑到一些特殊情况，会导致应用启动崩溃，我正在修复，稍后会发布一个 2.0.1 修复版本。 😭

**Comment by zhouyzhao** [comment]
安装了2.0.1版本，依然打开不了

**Comment by tisfeng** [comment]
打开控制台，看一下详细的日志

**Comment by tisfeng** [comment]
我试了一下，我这边没问题了，从 1.3.4 更新到 2.0.1 成功了。

**Comment by zhouyzhao** [comment]
我这里是，刚打开电脑，就跳出一个更新，然后他就自动更新，然后我发现点开不了。然后我就上来看了，下了你们最新的版本，刚电脑重启了，还是没反应，我看控制台，没有easyduct的应用呢，不知怎么看

**Comment by tisfeng** [comment]
我刚才是删除 2.0.0 版本，直接下载 1.3.4，然后手动更新到 2.0.1 的，因为 2.0.0 版本启动会崩溃，无法让它更新。

如果之前是 1.3.4 版本，没有更新到 2.0.0，那应该是可以直接更新成功的。

**Comment by zhouyzhao** [comment]
我刚才把整个软件删了，再安装了一个1.3.4版本的，然后可以打开，它跳出了更新，然后我看版本号是2.0.1，但更新完，打不开了，（我的系统版本是：（macos 13.5.1）

**Comment by tisfeng** [comment]
GitHub 发布页面好像出问题了，无法修改 2.0.1 为最新版本。。 暂时先直接去这里手动更新 https://github.com/tisfeng/Easydict/releases

**Comment by tisfeng** [comment]
> 我刚才把整个软件删了，再安装了一个1.3.4版本的，然后可以打开，它跳出了更新，然后我看版本号是2.0.1，但更新完，打不开了，（我的系统版本是：（macos 13.5.1）

那你尝试先删除电脑的 Easydict，直接下 2.0.1

**Comment by zhouyzhao** [comment]
可以了，原来是那个紧急更新那里描述太短了，我一直点进去了2.0.0的下载页面

**Comment by danielhu19** [comment]
2.0.1可以打开了，但是系统字典怎么显示不了？
<img width="476" alt="image" src="https://github.com/tisfeng/Easydict/assets/86143910/57013aaa-75d2-4f1f-b003-66263f1f1b34">

**Comment by tisfeng** [comment]
刚去掉了链接，这个可能导致误点击。

吸取教训，不该在这个时间发布新版本，应该深更半夜发布的，这样出问题也不会影响用户 🥹

**Comment by tisfeng** [comment]
> 2.0.1可以打开了，但是系统字典怎么显示不了？ <img alt="image" width="476" src="https://user-images.githubusercontent.com/86143910/277993669-57013aaa-75d2-4f1f-b003-66263f1f1b34.png">

你点开箭头看看，应该是系统词典查不到 GitHub 这个词，你可以直接在系统词典中查一下。

**Comment by tisfeng** [comment]
<img width="456" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/a853cc5c-d728-45f6-8b04-8cc47c1e37fe">

**Comment by danielhu19** [comment]
找到原因了，可能是我下的[朗文-6](https://forum.freemdict.com/t/topic/6544/10)资源的问题，换了一个5已经好了。感谢！

**Comment by tisfeng** [comment]
我这里 https://github.com/tisfeng/Easydict/blob/main/docs/How-to-use-macOS-system-dictionary-in-Easydict-zh.md 提供了一些词典资源，如果大家有好的词典，也可以通过 issue 分享出来。

**Comment by flyfishflying** [comment]
> 安装了2.0.1版本，仍然打开不了

是的2.0.1仍然打不开

**Comment by tisfeng** [comment]
看了一下崩溃日志，确实有极小概率出现崩溃问题，大约 1%，比较奇怪，稍后我去排查一下。

你可以尝试先删除电脑上的 Easydict，重新下载 2.0.1 版本试试。
如果不行，那就下载旧版本 1.3.4，然后尝试手动更新到 2.0.1。
如果还是不行，那就暂时先用 1.3.4，这个版本是稳定的，稍后我会发布一个新的修复版本。

**Comment by flyfishflying** [comment]
Thank you. Your email is received and will be handled  as soon as possible!
