### ISSUE TITLE
功能建议：打开Input Translate清除上次的文本记录

### ISSUE THREAD

**Issue by soulofshadow** [tisfeng/Easydict#19]
alt+a 弹出的窗口，会保留上次翻译的结果。这样每次翻译都要先 cmd+a + delete 再输入。。

alt+d 如果没有选择文本的话，也会弹出窗口并且有系统提示声，建议如果没选择文本，不弹出窗口，也不要有那个很难听的系统提示声。而且这个弹出的窗口位置我发现在光标之上。

然后我想问一下 floating 窗口和 mini窗口我找到了，但是没找到那个main窗口 哈哈哈😂😂😂

然后选择语言能建议改成首字母大写吗。。。个人好看一点🥹就是“auto”变成“Auto”, 
而且个人觉得一般最常用的翻译的也就几个语言，建议就跟浏览器的书签一个逻辑，设置几个常用的语言Pin在这个列表的最上方方便选取，这样那个国旗flag也可以去掉了，个人觉得好看一点哈哈哈哈哈哈。颜值就是王道

<img width="442" alt="image" src="https://user-images.githubusercontent.com/95683271/221386855-b57092ca-70ae-4355-9960-6c38cafe31fa.png">

Macbook Pro 13
macOS 12.6.3
Easydit 1.2.3

**Comment by tisfeng** [comment]
感谢反馈。

> alt+a 弹出的窗口，会保留上次翻译的结果。这样每次翻译都要先 cmd+a + delete 再输入。。

默认保留，这是为了以便查看之前的查询结果，如果你想清空内容，可以点击输入框右下角的清除按钮。

我之前想过添加一个单独的 "Show Floating Window"，用来查看之前的查询结果，而把目前的 "Input Translate" 改为显示查询窗口并自动清空输入，但考虑到这两个操作比较相似，如果再加一个动作以及配置相应的快捷键，就比较复杂冗余，也会给用户带来使用上的疑惑和混乱，所以最后还是没加 😤

<img width="224" alt="image" src="https://user-images.githubusercontent.com/25194972/221401364-2e03274d-30c4-45aa-9c7a-a95623568953.png">

**Comment by tisfeng** [comment]
> alt+d 如果没有选择文本的话，也会弹出窗口并且有系统提示声，建议如果没选择文本，不弹出窗口，也不要有那个很难听的系统提示声。而且这个弹出的窗口位置我发现在光标之上。

弹窗位置出现在光标之上，这个是不太对，我改一下。

Option + D 这个原设定是想让用户先手动选中文本，然后再通过快捷键取词查询，但为了节省快捷键，所以我设置如果没有选中文本，就直接显示查询窗口，意思是你可以把它当作 "Input Translate" Option + A 来用，，你不提我都快忘了当初有这样的设计了 😂 不过经你这么一提醒，我感觉这里可以稍微优化一下，如果没有选中文本，Option + D 就清空输入并显示查询窗口，这样既能实现你前面提的需求，也不会破坏现有功能设计。

至于 "那个很难听的系统提示声"，是因为某些软件不支持空 Cmd+C 操作，稍后我优化一下，尽量不让它发出这个提示音。

**Comment by tisfeng** [comment]
> 然后我想问一下 floating 窗口和 mini窗口我找到了，但是没找到那个main窗口 哈哈哈😂😂😂

main 窗口目前功能还不够强大，所以我默认隐藏了。后面主窗口会提供对照翻译模式和沉浸翻译模式，到时候再放开。

<img width="898" alt="image" src="https://user-images.githubusercontent.com/25194972/221404055-144738e9-ad4b-497e-81d3-fec16c18fa57.png"> 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/25194972/221404071-cf988cf9-1bbc-4263-86ec-ba8e84248beb.png">

**Comment by tisfeng** [comment]
> 然后选择语言能建议改成首字母大写吗。。。个人好看一点🥹就是“auto”变成“Auto”,

这个我觉得可以，Auto 好像是要好看一点。

> 设置几个常用的语言Pin在这个列表的最上方方便选取

这个可以，我也有计划后面设置一个常用语言选项，方便操作。

> 那个国旗flag也可以去掉

你是指这个选择语言列表的国旗 flag 吗？我想的是，这里的国旗 flag 方便和 Auto 后面的国旗 flag 形成联动，方便查看。其实如果为了简洁，去掉国旗 flag 也可以，但不确定这是否也是其他用户的想法？ 如果有必要，稍后我可能会考虑添加一个隐藏国旗 flag 的选项。

<img width="388" alt="image" src="https://user-images.githubusercontent.com/25194972/221404358-364b0155-9108-4c0d-9676-20e3af951eb7.png">

**Comment by soulofshadow** [comment]
谢谢大大的回复，我这也只是个人的用户看法哈哈哈哈。
openAI是新加的吗？666

> > alt+d 如果没有选择文本的话，也会弹出窗口并且有系统提示声，建议如果没选择文本，不弹出窗口，也不要有那个很难听的系统提示声。而且这个弹出的窗口位置我发现在光标之上。
> 
> 弹窗位置出现在光标之上，这个是不太对，我改一下。
> 
> Option + D 这个原设定是想让用户先手动选中文本，然后再通过快捷键取词查询，但为了节省快捷键，所以我设置如果没有选中文本，就直接显示查询窗口，意思是你可以把它当作 "Input Translate" Option + A 来用，，你不提我都快忘了当初有这样的设计了 😂 不过经你这么一提醒，我感觉这里可以稍微优化一下，如果没有选中文本，Option + D 就清空输入并显示查询窗口，这样既能实现你前面提的需求，也不会破坏现有功能设计。
> 
这个可以， 这样基本 只要想要翻译文本，不管是输入还是选词，只要是文本，一个Option + D。而只要是图片OCR一个Option + S。 感觉使用更清晰诶！！！！✌️👍

**Comment by soulofshadow** [comment]
> 你是指这个选择语言列表的国旗 flag 吗？我想的是，这里的国旗 flag 方便和 Auto 后面的国旗 flag 形成联动，方便查看。其实如果为了简洁，去掉国旗 flag 也可以，但不确定这是否也是其他用户的想法？ 如果有必要，稍后我可能会考虑添加一个隐藏国旗 flag 的选项。

**Comment by tisfeng** [comment]
OpenAI 还在测试中，不太稳定，限制比较多，可能要过一段时间才会开放。

用国旗 flag 表示语言，主要也是没有更好的方式了，这里的语言显示按钮宽度不太够，也考虑到 UI 美观设计，就只好用国旗 emoji 了 😔

<img width="362" alt="image" src="https://user-images.githubusercontent.com/25194972/221421411-9f869bcc-1124-44aa-b02b-84f9922f69da.png">

**Comment by wobangnidashui** [comment]
我也觉得输入翻译时默认清空记录比较好，一般情况应该是更希望输入新词翻译，而不是去看老的翻译记录。  @tisfeng

**Comment by tisfeng** [comment]
下个版本会优化取词功能，如果没有选中文本，Option + D 就清空输入并显示查询窗口。

**Comment by Cople** [comment]
> OpenAI 还在测试中，不太稳定，限制比较多，可能要过一段时间才会开放。
> 
> 用国旗 flag 表示语言，主要也是没有更好的方式了，这里的语言显示按钮宽度不太够，也考虑到 UI 美观设计，就只好用国旗 emoji 了 😔
> 
> <img alt="image" width="362" src="https://user-images.githubusercontent.com/25194972/221421411-9f869bcc-1124-44aa-b02b-84f9922f69da.png">



> > 然后选择语言能建议改成首字母大写吗。。。个人好看一点🥹就是“auto”变成“Auto”,
> 
> 这个我觉得可以，Auto 好像是要好看一点。
> 
> > 设置几个常用的语言Pin在这个列表的最上方方便选取
> 
> 这个可以，我也有计划后面设置一个常用语言选项，方便操作。
> 
> > 那个国旗flag也可以去掉
> 
> 你是指这个选择语言列表的国旗 flag 吗？我想的是，这里的国旗 flag 方便和 Auto 后面的国旗 flag 形成联动，方便查看。其实如果为了简洁，去掉国旗 flag 也可以，但不确定这是否也是其他用户的想法？ 如果有必要，稍后我可能会考虑添加一个隐藏国旗 flag 的选项。
> 
> <img alt="image" width="388" src="https://user-images.githubusercontent.com/25194972/221404358-364b0155-9108-4c0d-9676-20e3af951eb7.png">

国旗可不可以放到语言前面，排版整齐看起来会更美观点？

**Comment by tisfeng** [comment]
你好，新版本已添加输入翻译时是否清空输入内容选项 https://github.com/tisfeng/Easydict/releases/tag/1.3.1
