### ISSUE TITLE
🐞 反馈问题：快捷键按键识别异常 Option+D识别为 Cmd+C

### ISSUE THREAD

**Issue by KrabsWong** [tisfeng/Easydict#192]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

修改快捷键的时候，发现 Opt+D 识别成了 Cmd+C。

<img width="372" alt="image" src="https://github.com/tisfeng/Easydict/assets/12368943/3591f0e9-7df9-4729-a8a3-1f65bd45e7e1">

### 重现步骤

偏好设置 -> 划词翻译 -> 录入 Opt+D -> 弹出报错

### 期望结果

可以正确识别快捷键

### 设备信息 && 操作系统版本

Apple M1 Pro, macOS 14.0

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by Jerry23011** [comment]
我尝试复现了一下但是没成功，不知道是不是系统版本的原因，我在 macOS 13.6.1
@KrabsWong 请问你的 Easydict 版本是多少呢

**Comment by KrabsWong** [comment]
> 我尝试复现了一下但是没成功，不知道是不是系统版本的原因，我在 macOS 13.6.1 @KrabsWong 请问你的 Easydict 版本是多少呢

不好意思回复晚了。
我这边使用的是 2.0.1 版本，看样子应该是最新版

**Comment by Jerry23011** [comment]
好的，那你是所有的app中划词都会出现这个问题吗？

**Comment by KrabsWong** [comment]
> 好的，那你是所有的app中划词都会出现这个问题吗？

这个错误是在设置快捷键的时候发生的，（虽然默认就是 Cmd+D）

**Comment by Jerry23011** [comment]
> > 好的，那你是所有的app中划词都会出现这个问题吗？
> 
> 这个错误是在设置快捷键的时候发生的，（虽然默认就是 Option+D）
> 
> 刚刚试了下，在打开设置界面的时候，按 Option+D 的时候，会同时触发 Cmd+C。

可以测试一下你是否有其它软件占用了这个快捷键，我这边是无法复现的

其中一个方法就是[使用安全模式启动](https://support.apple.com/zh-cn/guide/mac-help/mh21245/mac)，这样 macOS 会禁用所有启动项，然后打开 Easydict 尝试同样的操作

**Comment by KrabsWong** [comment]
> > > 好的，那你是所有的app中划词都会出现这个问题吗？
> > 
> > 
> > 这个错误是在设置快捷键的时候发生的，（虽然默认就是 Option+D）
> > 刚刚试了下，在打开设置界面的时候，按 Option+D 的时候，会同时触发 Cmd+C。
> 
> 可以测试一下你是否有其它软件占用了这个快捷键，我这边是无法复现的
> 
> 其中一个方法就是[使用安全模式启动](https://support.apple.com/zh-cn/guide/mac-help/mh21245/mac)，这样 macOS 会禁用所有启动项，然后打开 Easydict 尝试同样的操作

稍后我试试看，给你反馈。多谢

**Comment by KrabsWong** [comment]
在安全模式下重新测试了下，只打开里 EasyDict，但是问题依然在。

我这边可以稳定复现的路径如下

1. 打开偏好设置
2. 直接点击图示区域（不删除原有快捷键）
<img width="417" alt="image" src="https://github.com/tisfeng/Easydict/assets/12368943/77685db2-e74e-4838-bcbb-902af533f4b9">
3. 会弹出错误，提示和 CMD+C 冲突

如果在录入键位之前，现把原有快捷键删除，再设置的时候就不会报错了。

**Comment by Jerry23011** [comment]
好的我大概知道这个是什么问题了

你在设置的是划词翻译的快捷键，所以当原快捷键和你想设置的新快捷键相同时（例如⌥D），你在设置快捷键的同时触发了一个划词翻译，而在 Easyict 这个 app 本身是通过模拟 ⌘C 划词，所以Easyict判断你想设置的快捷键是⌘C

你可以试试在现有快捷键的基础上（⌥D）设置一个其它快捷键，比如⌥S，看看还会不会有这个问题

@tisfeng @Kyle-Ye 请问二位，这种情况可以在代码层面避免嘛

**Comment by KrabsWong** [comment]
> 你可以试试在现有快捷键的基础上（⌥D）设置一个其它快捷键，比如⌥S，看看还会不会有这个问题

那这么说起来，就合理里。
“你可以试试在现有快捷键的基础上（⌥D）设置一个其它快捷键，比如⌥S，看看还会不会有这个问题”，这个是测试过的，不会有问题。

**Comment by tisfeng** [comment]
> 好的我大概知道这个是什么问题了
> 
> 你在设置的是划词翻译的快捷键，所以当原快捷键和你想设置的新快捷键相同时（例如⌥D），你在设置快捷键的同时触发了一个划词翻译，而在 Easyict 这个 app 本身是通过模拟 ⌘C 划词，所以 Easyict 判断你想设置的快捷键是⌘C，进而报错
> 
> 你可以试试在现有快捷键的基础上（⌥D）设置一个其它快捷键，比如⌥S，看看还会不会有这个问题
> 
> @tisfeng @Kyle-Ye 请教一下二位，这种情况可以在代码层面避免嘛

赞，没想到这都被你们发现了，确实存在这个问题，稍后我修复一下。

**Comment by tisfeng** [comment]
也不是，只是因为某些控件不支持 Accessibility，比如设置快捷键的控件，苹果词典的 WKWebView 等。

> Easyict 这个 app 本身是通过模拟 ⌘C 划词

**Comment by tisfeng** [comment]
[2.0.2](https://github.com/tisfeng/Easydict/releases/tag/2.0.2) 版本已修复该问题。

**Comment by tisfeng** [comment]
Fixed in 0fe84d18

**Comment by KrabsWong** [comment]
> Fixed in [0fe84d1](https://github.com/tisfeng/Easydict/commit/0fe84d18c552720e77a09a8db243ace4e09ce8b9)

这里是修复的 SwiftUI App 模式下 CMD+D 冲突的问题吧？
刚才试了下，2.6.1 版本中 SwiftUI App 设置快捷键会有问题

**Comment by tisfeng** [comment]
不是，上面是修复了旧版本的设置页快捷键问题，而新的设置页使用 SwiftUI 重写时没考虑到这一点，这个问题将会在下个版本修复。

**Comment by tisfeng** [comment]
@AkaShark 你可以单独开一个 PR 修复这个问题，不用放到 https://github.com/tisfeng/Easydict/pull/425

**Comment by AkaShark** [comment]
> @AkaShark 你可以单独开一个 PR 修复这个问题，不用放到 #425

okay 可以先review下https://github.com/tisfeng/Easydict/pull/425 这个问题我这俩天修下重新PR下

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已修复。
