### ISSUE TITLE
🐞 反馈问题：部分情况下的元素异常遮挡问题

### ISSUE THREAD

**Issue by Kyle-Ye** [tisfeng/Easydict#193]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

<img width="472" alt="image" src="https://github.com/tisfeng/Easydict/assets/43724855/e480bc4f-452a-46be-b475-ecce9d688595">

<img width="526" alt="image" src="https://github.com/tisfeng/Easydict/assets/43724855/6ee83acf-61f0-466b-801e-187114ff3dbd">

### 重现步骤

1. 仅使用苹果翻译 
2. 选择合适长度的语句进行翻译
3. 系统设置 - 通用 - 显示滚动条 - 始终

<img width="207" alt="image" src="https://github.com/tisfeng/Easydict/assets/43724855/290f7e6e-8df8-4a97-9ff1-641918dbe57e">

### 期望结果

UI 正常显示（功能按钮位于下方而非遮挡）

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR!

**Comment by Kyle-Ye** [comment]
<img width="1131" alt="image" src="https://github.com/tisfeng/Easydict/assets/43724855/0fef4287-3794-4e38-9c4d-167b3ae0dd9a">

计算高度时使用的宽度是 324，但最终生效约束下的宽度为 313，导致了布局异常。

https://github.com/tisfeng/Easydict/blob/8f8a61fb345b6c96fb651ef999d70845ad5154e0/Easydict/Feature/ViewController/View/WordResultView/EZWordResultView.m#L911-L924

**Comment by Kyle-Ye** [comment]
宽度计算逻辑和实际不匹配导致，某次更新中为外层的 NSScrollView 添加了 verticalScroller，导致宽度减少了11
```objc
scrollView.hasVerticalScroller = YES;
```

修复方案建议：
1. 关闭垂直滚动条
```
scrollView.hasVerticalScroller = NO;
```
优点：滚动条的加入不仅导致了这里宽度计算的不一致异常，还破坏了 UI 对齐的美感 （Chrome 图标和左边的置顶图标在README的截图中显示在没有滚动条的情况下是和文本框的两侧对齐的）
缺点：在含有多种翻译方式的情况下缺少滚动条不利于用户交互

2. 更新宽度计算逻辑
获取当前容器宽度而非 Window 宽度或者在当前的宽度计算实现中加入滚动条宽度的考虑

@tisfeng 作者可以帮忙评估下上下文完成决策后我再提相关 PR 吧

**Comment by tisfeng** [comment]
还真是，没想到还有个始终显示滚动条情况，这个高度计算我修改调试过很多次了，难怪之前没有发现 😓

**Comment by tisfeng** [comment]
回顾了一下这里的改动 a282429317d0b96f1499a8fad0425e384b8a6a55 ，最开始就是

```objc
CGFloat width = self.width - exceptedWidth;
```
看提交日志，好像后面发现有问题才改的，但我刚回退之前的代码，测试了一下好像也没有问题。。

> fix(UI): calculate EZLabel width incorrectly when resizing window suddenly

那暂时就先改回来，观察一段时间看看。

**Comment by Kyle-Ye** [comment]
> 那暂时就先改回来，观察一段时间看看。

或者有考虑后续改为 SwiftUI 这类 DSL 方案吗？😀 See #194

**Comment by tisfeng** [comment]
SwiftUI 也可以，但我很久没写这个了，只在之前刚出的时候写过一点，当时遇到了很多坑，觉得还不成熟，就搁置了。

如果你认为目前 SwiftUI 已经比较成熟了，那你可以尝试先用它在项目中写一些新的页面，我们先观察、适应一下，看看实际效果如何。

**Comment by Kyle-Ye** [comment]
> SwiftUI 也可以，但我很久没写这个了，只在之前刚出的时候写过一点，当时遇到了很多坑，觉得还不成熟，就搁置了。
> 
> 如果你认为目前 SwiftUI 已经比较成熟了，那你可以尝试先用它在项目中写一些新的页面，我们先观察、适应一下，看看实际效果如何。

iOS 上的 SwiftUI 基本已经足够成熟可以完成完整项目(iOS 16+)，macOS 上的 SwiftUI 仍有部分已知 Bug，完整工程使用需谨慎。 
https://github.com/feedback-assistant/reports/issues

但是如果不是整个 App 100% SwiftUI 化，而是部分界面/UI元素使用 SwiftUI 是没啥问题的。

老 OS 上的各种 SwiftUI bug 如果熟悉内部原理，也基本都有方案可以绕过。

**Comment by tisfeng** [comment]
暂时先保持 macOS 11.0+ 的 Target，之前看到有部份用户还在这个系统版本。

稍后我统计一下具体的用户数量，如果不多的话，可以考虑提到 macOS 12，我们大约保持最新版本 -2 就行。

**Comment by tisfeng** [comment]
[2.0.2](https://github.com/tisfeng/Easydict/releases/tag/2.0.2) 版本已修复该问题。
