### ISSUE TITLE
🐞 反馈问题：英文界面下部分元素没有对齐

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#196]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

英语下设置中的 Frist Language 和 Second Language 没有和其他元素对齐
<img width="895" alt="en" src="https://github.com/tisfeng/Easydict/assets/89069957/13fdb80e-186e-45e0-91a5-7c027ef8e4e9">

### 重现步骤

- 将语言调整为英语
- 打开设置
- 看到 Frist Language 和 Second Language 都是 leading 对齐

### 期望结果

统一 First Language &  Second Language 与其他元素的对齐方式

### 设备信息 && 操作系统版本

Apple M1 Pro, macOS 13.6.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
还真是，忘记调约束了。。稍后我改一下。

**Comment by tisfeng** [comment]
[2.0.2](https://github.com/tisfeng/Easydict/releases/tag/2.0.2) 版本已修复该问题。
