### ISSUE TITLE
无法打开“Easydict.dmg”，因为它来自身份不明的开发者。macos无法验证此 App 是否包含恶意软件。

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#2]
## 描述问题
>无法打开“Easydict.dmg”，因为它来自身份不明的开发者。macos无法验证此 App 是否包含恶意软件。
无法打开 “Easydict.app"，因为 Apple 无法检查其是香包含恶意软件。此软件需要更新。请联系开发者了解更多信息。

虽然还是能强行突破系统安全性安装，但还是希望能解决一下这个问题，不然会劝退掉大部分人。
这么好的软件不火真是太可惜了！

**Comment by tisfeng** [comment]
感谢反馈！因为我自己是关闭安全性检查的，所以没考虑到这一点，稍后我研究一下，看是不是要去苹果公证一下。

**Comment by tisfeng** [comment]
尝试了一下，发现要解决这个问题，需要用到苹果公证，要去注册一个 $99 的苹果开发者账号，我暂时并没有上架 App Store 的计划。。

先这样吧，我写个简短教程放在这 issue 下，置顶，方便引导新手用户，稍后也会更新一下 README。

**Comment by tisfeng** [comment]
#### 签名问题⚠️

Easydict 是开源软件，本身是安全的，但由于苹果严格的检查机制，打开时可能会遇到警告拦截。

- 如果遇到下面[无法打开问题](https://github.com/tisfeng/Easydict/issues/2)，请参考苹果使用手册 [打开来自身份不明开发者的 Mac App](https://support.apple.com/zh-cn/guide/mac-help/mh40616/mac)

> 无法打开“Easydict.dmg”，因为它来自身份不明的开发者。macOS 无法验证此 App 是否包含恶意软件。

- 如果提示应用已损坏，请参考 [macOS 绕过公证和应用签名方法](https://www.5v13.com/sz/31695.html)

> “Easydict” 已损坏，无法打开。你应该将它移到废纸篓。

在终端里输入以下命令，并输入密码即可。

```bash
sudo xattr -rd com.apple.quarantine /Applications/Easydict.app
```

**Comment by tisfeng** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/25194972/219873635-46e9d318-7237-462b-be69-44ad7a3ea760.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/25194972/219873670-7ce67946-87c2-4d45-84fd-3cc59936f7be.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/25194972/219873722-2e780565-fe26-4ce3-9648-f1cbdd393843.png">

<img width="751" alt="image" src="https://user-images.githubusercontent.com/25194972/219873809-2b407852-7f77-4aef-9206-3f6393cb7c31.png">

**Comment by hoochanlon** [comment]
> 感谢反馈！因为我自己是关闭安全性检查的，所以没考虑到这一点，稍后我研究一下，看是不是要去苹果公证一下。

这个报错在Mac上基本也是个普遍现象。做公证一年也不便宜，每年积累起来成本也太高了。先暂时用命令解决吧。

**Comment by hoochanlon** [comment]
> <img alt="image" width="296" src="https://user-images.githubusercontent.com/25194972/219873635-46e9d318-7237-462b-be69-44ad7a3ea760.png">
> 
> <img alt="image" width="296" src="https://user-images.githubusercontent.com/25194972/219873670-7ce67946-87c2-4d45-84fd-3cc59936f7be.png">
> 
> <img alt="image" width="296" src="https://user-images.githubusercontent.com/25194972/219873722-2e780565-fe26-4ce3-9648-f1cbdd393843.png">
> 
> <img alt="image" width="751" src="https://user-images.githubusercontent.com/25194972/219873809-2b407852-7f77-4aef-9206-3f6393cb7c31.png">

对了，答主可以用html的`<a>`标签，简单缩略一下图片长度，小图叠加起来篇幅略长。

**Comment by tisfeng** [comment]
感谢提示！

**Comment by tisfeng** [comment]
[2.6.0](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 版本已发布，新版本使用了开发者 @CanglongCl 提供的苹果开发者账号进行公证，应该不会报恶意软件警告了。
