### ISSUE TITLE
反馈问题：隐藏菜单栏图标后，无法再找回设置菜单了

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#20]
## 描述问题
之前在 #6 中加入了隐藏状态栏图标，但有个问题没有考虑到：在隐藏之后如何再调出来设置菜单？

我暂时想到两种解决方法：

1. 一种是是第一次冷启动App时，默认显示设置界面，比如mos、alttab。
2. 另一种方法是，在查词面板加入一个设置按钮，或是在左上角菜单栏加入一个偏好设置。

**Comment by tisfeng** [comment]
不用，其实只要唤醒了查询窗口，就可以通过快捷键 `Cmd + ,` 打开设置页，然后从设置页把菜单栏图标显示出来。

<div style="display:flex;align-items:flex-start;">
  <img src="https://user-images.githubusercontent.com/25194972/221406290-b743c5fa-75ed-4a8a-8b52-b966ac7daa68.png" style="margin-right:50px;" width="50%">
  <img src="https://user-images.githubusercontent.com/25194972/221406302-1a5fd751-012d-42b5-9834-09d2d5913ad6.png" width="30%">
</div>

**Comment by tisfeng** [comment]
可以，感谢提醒。
