### ISSUE TITLE
🚀 功能建议：支持彩云小译

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#206]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

使用 Swift 编写支持彩云小译  https://github.com/tisfeng/Easydict/issues/194#issuecomment-1783672702

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by Kyle-Ye** [comment]
好的，我后面研究下，这周不一定有时间写哈

**Comment by tisfeng** [comment]
这个也不急，你有空的时候优先做一下就可以。

**Comment by Kyle-Ye** [comment]
还没有开始，本来打算这周末开始写的，我提高下优先级争取这周末前提PR吧

**Comment by tisfeng** [comment]
可以，辛苦了。
