### ISSUE TITLE
🐞 反馈问题：PopClip 划词搜索失败

### ISSUE THREAD

**Issue by geekbb** [tisfeng/Easydict#207]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

PopClip 划词搜索失败
有两台MAC，PopClip功能正常：
- 第一台第一次安装[Easydict]，PopClip划词有图标，点击图标正常弹出翻译窗口
- 第二台电脑，安装过上一版本，覆盖安装[Easydict]，PopClip划词有图标，点击图标后无法弹出翻译窗口（期间重新卸载安装，重新开启权限还是不行）猜测用到权限“隐私与安全性——辅助功能，隐私与安全性——录屏。

### 重现步骤

https://github.com/tisfeng/Easydict/assets/46196358/dde33dd1-eaa0-4725-bea9-2b17c03465e7

### 期望结果

怀疑是权限问题，请告知要开启哪些权限？

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
使用 PopClip 划词，是不需要额外权限的，之前使用快捷键方式可能和其他应用冲突，导致一些问题，请尝试使用最新的 shell script 

https://github.com/tisfeng/easydict/tree/dev#%E9%85%8D%E5%90%88-popclip-%E4%BD%BF%E7%94%A8

**Comment by geekbb** [comment]
> 新的 shell script

换了新的 shell script后问题解决👍

**Comment by geekbb** [comment]
> 使用 PopClip 划词，是不需要额外权限的，之前使用快捷键方式可能和其他应用冲突，导致一些问题，请尝试使用最新的 shell script
> 
> https://

https://github.com/tisfeng/Easydict/assets/46196358/f318741d-37d5-4f7f-84d1-d8df4b5c278d

github.com/tisfeng/easydict/tree/dev#%E9%85%8D%E5%90%88-popclip-%E4%BD%BF%E7%94%A8

但好像不太稳定，是字符多了获取失败？

**Comment by tisfeng** [comment]
有点奇怪，稍后我查一下。

**Comment by geekbb** [comment]
> 有点奇怪，稍后我查一下。

https://github.com/tisfeng/Easydict/assets/46196358/12befddf-b2c6-480a-be2b-90a7e8ff3d54


另一个表现

**Comment by tisfeng** [comment]
查了一下，easydict://xxx  这个 URL Scheme 在某些场景下确实可能出现问题，请改用另一个完整的 URL Scheme  easydict://query?text=xxx 

新的 shell script 如下：

```shell
# popclip
name: Easydict
icon: iconify:ri:translate
interpreter: zsh
shell script: |
  result=$(ps aux | grep Easydict.app | wc -l)
  if [[ $result -lt 2 ]];then
    open /Applications/Easydict.app
    sleep 1
  fi
  open "easydict://query?text=$POPCLIP_TEXT"
```

**Comment by tisfeng** [comment]
[2.0.2](https://github.com/tisfeng/Easydict/releases/tag/2.0.2) 版本已修复该问题。
