### ISSUE TITLE
🚀 功能建议：单词本功能

### ISSUE THREAD

**Issue by zero47** [tisfeng/Easydict#208]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

希望添加单词本功能，可以在划水时一键复习

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
收到，这个后面会加的。

Duplicated  https://github.com/tisfeng/Easydict/issues/33

**Comment by xinx1n** [comment]
如果能接入欧陆词典之类的生词本就最好了，手机也能复习。

**Comment by tisfeng** [comment]
欢迎 PR 😶
