### ISSUE TITLE
功能建议：查询图标可以选择在那些应用程序中生效

### ISSUE THREAD

**Issue by rogeryk** [tisfeng/Easydict#21]
## 功能描述
并不是在所有的场景下都需要翻译，有时选中后出现的翻译 icon 会引起误操作，
希望可以选择划词翻译在那些应用程序中生效

**Comment by RogerYK** [comment]
PopClip 似乎是支持这个功能的

**Comment by tisfeng** [comment]
感谢反馈，这个可以的，稍后我参考一下 PopClip。
