### ISSUE TITLE
🐞 反馈问题：打开设置的快捷键 Cmd + , 失效

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#210]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

查了一下，是之前 a76d42bc5e66404ca4fe271ddf662652eaa9ba88 这个提交导致。

<img width="652" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/2513a5e9-00f1-4aa7-97a6-cbda45bbfa98">

### 重现步骤

显示查询窗口时，快捷键 Cmd + , 失效。

### 期望结果

快捷键 Cmd + , 能正常使用。

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
我忘记把 dev 代码推上去了，你再试一下。

**Comment by Kyle-Ye** [comment]
> 我忘记把 dev 代码推上去了，你再试一下。

还是无法复现 & 看起来你更新的代码也和这部分无关，@Jerry23011 能帮忙确认下吗？

**Comment by Jerry23011** [comment]
> > 我忘记把 dev 代码推上去了，你再试一下。
> 
> 还是无法复现 & 看起来你更新的代码也和这部分无关，@Jerry23011 能帮忙确认下吗？

我这边也无法复现，简体中文/英文下都是正常的

**Comment by tisfeng** [comment]
奇怪了，可能我的电脑环境有点问题，我再仔细看看。

**Comment by tisfeng** [comment]
我还是有点疑惑，按理说，这个确实是问题，但不知道为什么在你们电脑上没有出现。

这个地方使用了两个功能一样的设置菜单项，不太合理（这个是历史遗留问题），而且还设置了两个一样的快捷键 `Cmd + ,`。

难道说，在不同电脑环境上，快捷键 `Cmd + ,` 响应的控件事件不一样？

**Comment by tisfeng** [comment]
[2.0.2](https://github.com/tisfeng/Easydict/releases/tag/2.0.2) 版本已修复。
