### ISSUE TITLE
🚀 功能建议：希望支持除了openai以外第三方的apikey配置

### ISSUE THREAD

**Issue by albert-liangd** [tisfeng/Easydict#213]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

希望支持一下 第三方的openapi key的配置与用户自定义服务的调用

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
如果你是指类似 Azure OpenAI 接口，那目前已经是支持的  https://github.com/tisfeng/Easydict#openaichatgpt%E7%BF%BB%E8%AF%91

> 希望支持一下 第三方的openapi key的配置与用户自定义服务的调用

**Comment by tisfeng** [comment]
对于其他 LLM 服务，目前建议使用 [one-api](https://github.com/songquanpeng/one-api) 转换为 OpenAI 的 API 形式接入。

<img width="1023" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/5d35b385-e64f-4950-add2-1317bd16e4ad">

**Comment by albert-liangd** [comment]
我通过该方法实现其他类似于openai的第三方服务的接入
