### ISSUE TITLE
🐞 反馈问题：无法配置API

### ISSUE THREAD

**Issue by EncoreEureka** [tisfeng/Easydict#214]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

无法配置API
<img width="817" alt="Screenshot 2023-11-04 at 11 14 12" src="https://github.com/tisfeng/Easydict/assets/125462655/df226fd3-32f7-4ec6-b3f1-06bb27e909a6">

### 重现步骤

<img width="817" alt="Screenshot 2023-11-04 at 11 14 12" src="https://github.com/tisfeng/Easydict/assets/125462655/5825723b-07c1-4232-94db-46ec40ffc3aa">

### 期望结果

配置API

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
不是在终端，而是在 Easydict 输入框输入命令。。

稍后我更新一下文档，可能这里写得不够清晰 😥

<img width="458" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/6134adaf-f57a-47ed-8fc0-34a6f9ed4b25">

**Comment by tisfeng** [comment]
@EncoreEureka 你好像暴露了你的 APIKey，建议重置一下。

**Comment by EncoreEureka** [comment]
好的，谢谢！
