### ISSUE TITLE
升级到2.0.1之后，OpenAI翻译报错："发生SSL错误，无法建立到该服务器的安全连接。"

### ISSUE THREAD

**Issue by WhyMeta** [tisfeng/Easydict#215]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

升级到2.0.1之后，OpenAI翻译报错："发生SSL错误，无法建立到该服务器的安全连接。"(1.3.4正常)，
尝试过 #28 easydict://writeKeyValue?EZBetaFeatureKey=0 和 easydict://writeKeyValue?EZBetaFeatureKey=1 重新关闭打开，但无效。
非节点问题，ChatGPT正常、Lark机器人正常。(除了肉身翻，其它什么全局、软路由全都试过)
<img width="565" alt="iShot_2023-11-06_12 16 02" src="https://github.com/tisfeng/Easydict/assets/6345591/327f0ee8-a9ec-4a9b-bad2-119288fb5998">
<img width="440" alt="iShot_2023-11-06_12 12 21" src="https://github.com/tisfeng/Easydict/assets/6345591/460e9e28-24c2-4d43-b44f-25430978bcc4">

### 重现步骤

1. 1.3.4 `easydict://writeKeyValue?EZBetaFeatureKey=1` 启用OpenAI，设置打开OpenAI
2. 1.3.4直升2.0.1
3. 翻译

### 期望结果

正常翻译

### 设备信息 && 操作系统版本

13-inch, 2020, Two Thunderbolt 3 ports

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by muweigg** [comment]
+1

**Comment by WhyMeta** [comment]
不是软件的问题，找到原因了，应该是最近大量中转IP被墙的原因？试过很多鸡场的ipv4都失败了，但是用ipv6没有问题
<img width="1043" alt="iShot_2023-11-06_15 02 03" src="https://github.com/tisfeng/Easydict/assets/6345591/1669ded8-5c7c-43c1-8bfe-a1e0d807979c">
