### ISSUE TITLE
🚀 功能建议：翻译窗口出现时，能够默认钉住

### ISSUE THREAD

**Issue by Nat30** [tisfeng/Easydict#216]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

翻译窗口出现时，能够默认钉住。因为此时可能需要再在其他软件中进行对比确认，如果翻译窗口失焦则立即消失了。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
设定就是这样，面向一种轻量级使用场景，查询完后隐藏。

显示窗口时，你可以用快捷键 `Cmd + P` 钉住。钉住这并不是一个常态功能，在需要时使用就可以。

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本已实现。

**Comment by Nat30** [comment]
感谢！
