### ISSUE TITLE
🐞 反馈问题：ORC识别总是会把英文识别为中文。

### ISSUE THREAD

**Issue by icbyhero** [tisfeng/Easydict#217]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

最近总是会出现把英文识别为中文的情况
<img width="420" alt="image" src="https://github.com/tisfeng/Easydict/assets/34714930/89752d8d-8ee9-4f2c-b4d1-56460c8f9d19">

### 重现步骤

快捷见直接ORC 识别文字，识别文字均为英文，更换了语种识别，还是依旧会出现该问题，之前都是正常的。

### 期望结果

识别准确语言

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
看起来有点奇怪，按理说语种识别模块应该是没有问题的，建议只使用系统的语种识别，其他服务可能不稳定。

你这种情况，可能是和个人电脑系统环境有关，麻烦你详细一下复现问题的步骤，最好录个视频。

是所有场景都会识别有误吗，划词或手动输入有问题吗？是所有的文本都会被识别为中文吗，其他语言有问题吗？

 > 之前都是正常的

这个之前具体是什么时候，上一个版本吗？

你是否尝试过重启应用，或卸载应用重装，或者重启电脑，看看些操作是否有效。

<img width="456" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/e84b073e-41d8-4c8a-ad77-59ab382a676a">

**Comment by tisfeng** [comment]
另外，如果你手动修改了文本的识别语言，那应用将会优先使用用户的选择，即使你将文本从英语修改为简体中文，除非再次手动修改回来，否则后续该文本会一直被视作简体中文。

<img width="457" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/8ebc0631-e644-4910-8649-03521ac77445">

**Comment by icbyhero** [comment]
抱歉， 我刚看到您的邮件。

看起来有点奇怪，按理说语种识别模块应该是没有问题的，建议只使用系统的语种识别，其他服务可能不稳定。

——仅使用系统的，是不稳定，不是一直会出错。

你这种情况，可能是和个人电脑系统环境有关，麻烦你详细一下复现问题的步骤，最好录个视频。

——最近比较忙，等我过段时间再录制一下视频吧。并且我现在又正常了。

是所有场景都会识别有误吗，划词或手动输入有问题吗？是所有的文本都会被识别为中文吗，其他语言有问题吗？

——我只遇到过英文，没有测试过其他语言，

之前都是正常的

这个之前具体是什么时候，上一个版本吗？

——不太能确定第一次出现是什么时候了，因为之前出现我都是手主动点为英文的。

你是否尝试过重启应用，或卸载应用重装，或者重启电脑，看看些操作是否有效。

——没有尝试，因为是偶现，我的翻译频率不是很高，我都会手动修正，  就是开着应用，过段时间可能又准确了，或者我换个语种识别就正确了（但是过一段时间问题依旧）

另外，如果你手动修改了文本的识别语言，那应用将会优先使用用户的选择，即使你将文本从英语修改为简体中文，除非再次手动修改回来，否则后续该文本会一直被视作简体中文。

——我没有翻译过中文，所以应该不存在这种情况。


再次感谢您的及时回复，

顺颂商祺

2023年11月10日 22:39，Tisfeng ***@***.***> 写道：

手动修改了文本的识别语言，那应用将会优先使用用户的选择，即使你将文本从英语修

**Comment by icbyhero** [comment]
“划词或手动输入有问题吗 ” 这两个一直没有问题，都是正常的。

**Comment by tisfeng** [comment]
后面再观望一下，暂时没看出问题。

**Comment by tisfeng** [comment]
你好，这个问题还会出现吗，如果没有，就先关闭 issue 了。
