### ISSUE TITLE
🚀 功能建议：新增DeepL 第三方接口

### ISSUE THREAD

**Issue by lol2025** [tisfeng/Easydict#219]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

不是deeplx方式，类似ChatGPT一样官方中转接口，deepl api不好获取价格贵，已经有第三方中转接口，只需要加个填写接口地址的功能，开发者可以白嫖。https://deepl-pro.com

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
看了一下，它的 [公告信息](https://docs.deepl-pro.com/) 怎么打不开，有点不靠谱，而且怎么连个官网介绍都没有。。

**Comment by tisfeng** [comment]
[2.4.0](https://github.com/tisfeng/Easydict/releases/tag/2.4.0) 版本已支持自定义 DeepL 接口地址，详情请看 README。
