### ISSUE TITLE
🚀 功能建议：快捷键支持double tap调用

### ISSUE THREAD

**Issue by masac11** [tisfeng/Easydict#220]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

希望快捷键支持double tap调用
<img width="313" alt="image" src="https://github.com/tisfeng/Easydict/assets/28709431/e4c6287f-f9a8-497e-a559-c30a0e463e69">

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
目前使用的快捷键第三方库，不支持修饰键双击功能，且这个库已经停止维护了，后面计划用 Swift 重写这部份功能。

有没有小伙伴来 PR 😃

**Comment by tisfeng** [comment]
[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本已支持 double tap 快捷键。
