### ISSUE TITLE
🚀 功能建议：支持繁体中文

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#228]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

我看了一下，除了简中和英文，似乎使用繁体中文的用户也挺多，感觉可以支持。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
@Jerry23011  你那边腾讯翻译做完了吗，如果完成了，有空可以做一下这个。

**Comment by Jerry23011** [comment]
还没有，不过本地化流程我很熟悉，干脆直接另开一个 issue 找人做本地化好了，回头我再写一些文档

**Comment by tisfeng** [comment]
这样也行，不过我有点担心非苹果开发者可能对 [String Catalog](https://developer.apple.com/documentation/xcode/localizing-and-varying-text-with-a-string-catalog) 和 Xcode 的操作不熟悉。

如果可以，我希望你稍后能提供一个 Easydict 支持繁体中文的 PR 示范，然后关联到 https://github.com/tisfeng/Easydict/issues/229 ，方便其他人参考。

**Comment by Jerry23011** [comment]
繁体中文说实话我觉得我不太能胜任，一些术语上差得还是挺大的
我正好完成了一个文档，已经PR，不过我可以做一个Canadian English的PR作为以后的参考

**Comment by tisfeng** [comment]
也可以。

后面繁体中文本地化，可以找一下这几位用户 
https://github.com/tisfeng/Easydict/issues?q=is%3Aissue+%E7%B9%81%E4%BD%93+is%3Aclosed ，之前提过繁体有关的需求，可以征求一下他们的意见。

**Comment by Jerry23011** [comment]
@sh95014 您好，不知道有興趣為這個 project 做一下正體中文的 localization 嗎

**Comment by tisfeng** [comment]
由于本地化的改动暂时不适合合并到主分支 https://github.com/tisfeng/Easydict/pull/231#issuecomment-1817874952 ，我新建了一个 localization 分支，后续关于本地化的 PR 请都提交到这个分支上。

**Comment by tisfeng** [comment]
目前设置页早已用 SwiftUI 重写，现在可以很方便支持各个语言本地化了，也不需要另外使用 localization 分支，就在最新的 dev 分支就行。

@Jerry23011 你有空可以接手一下这个吗

**Comment by Jerry23011** [comment]
OK，我来 migrate 一下

**Comment by Jerry23011** [comment]
I redid the Traditional Chinese localization with ChatGPT and Claude in #650. These two models performed well with appropriate prompts.

**Comment by tisfeng** [comment]
你好，[2.9.0](https://github.com/tisfeng/Easydict/releases/tag/2.9.0) 版本已添加该功能。
