### ISSUE TITLE
反馈问题：划词翻译弹出的窗口过于冗长

### ISSUE THREAD

**Issue by ViGeng** [tisfeng/Easydict#23]
## 描述问题

在划词翻译时，弹出的窗口过长，会影响main task的界面。理论上是可以通过关闭一些翻译服务来裁剪界面的，但是又牺牲了一些其他参考性（比如在输入翻译时希望获得很多的翻译参考选择）。

可能提供一个【划词翻译开启的服务】设置能够缓解这种问题？
又或者提供固定大小的float window，用户如果不能一眼看见所有信息，可以通过滑动窗口来浏览更多信息？
又或者固定窗口的位置，不跟随鼠标指针也是一种选项？

Anyway, 感谢作者提供的应用！点个赞！

<img width="706" alt="image" src="https://user-images.githubusercontent.com/31836829/222950694-c2b46d77-4d74-48bc-b849-075950e89c26.png">

## 运行环境

environment independent

**Comment by tisfeng** [comment]
看 README，设置页，可以调整不同窗口的服务 🤨

<img width="336" alt="image" src="https://user-images.githubusercontent.com/25194972/222950990-6a64a16b-f6d0-48fd-a2f6-65fdc6400810.png">

**Comment by ViGeng** [comment]
> 
sorry，没有仔细看就提出了naive的issue，谢谢高效率回复！
