### ISSUE TITLE
🐞 反馈问题：在Microsoft word 或者 Powerpoint中无法自动弹出查询的图标

### ISSUE THREAD

**Issue by Sh3r10ckk** [tisfeng/Easydict#236]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

在Microsoft word 或者 Powerpoint中选中文字后，不会自动弹出查询的图标，但是快捷键翻译可以正常使用。

### 重现步骤

1.选中一段word或者PowerPoint中的文字，不会自动跳出查询图标（别的应用中选中会自动跳出）
2.使用快捷键翻译可以正常取词翻译
3. 如果使用popclip则查询图标在这两个应用中可以正常弹出

### 期望结果

解决word和ppt中选中文字后查询图标不会自动弹出查询图标的问题

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
我用 App Store 版本的 Word 和 PPT 试了一下，在我电脑上都是可以的正常取词，而且是 Accessibility 类型取词成功。

<img width="717" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f6696a6e-da99-45a2-ac76-a1c76cf29cdd">

<img width="812" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/96de243f-97fe-4fa4-9aca-8f11e313b07f">

**Comment by tisfeng** [comment]
另外我记得之前已经修复过 Word https://github.com/tisfeng/Easydict/issues/84#issuecomment-1532717508 ，难道是苹果哪个地方又改了？

@Sh3r10ckk 你是从哪来下载的 Word，电脑型号和系统版本提供一下，需要补充更多上下文的信息。

@Jerry23011 麻烦你也测一下这个问题。跟进一下。

**Comment by Sh3r10ckk** [comment]
> 另外我记得之前已经修复过 Word [#84 (comment)](https://github.com/tisfeng/Easydict/issues/84#issuecomment-1532717508) ，难道是苹果哪个地方又改了？
> 
> @Sh3r10ckk 你是从哪来下载的 Word，电脑型号和系统版本提供一下，需要补充更多上下文的信息。
> 
> @Jerry23011 麻烦你也测一下这个问题。跟进一下。

word：app store版本16.79.1
mac：m1pro mbp
dict：2.0.4
完全卸载easydict后并重新安装后，此问题已解决
