### ISSUE TITLE
🚀 功能建议：建议增加调整字体大小选项

### ISSUE THREAD

**Issue by lyz21** [tisfeng/Easydict#237]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

目前该软件的翻译结果字体大小不可调整，这导致在使用较大的显示器时，字体会格外的小，希望可以增加一项设置，以供用户自定义调整字体大小。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by NeverAgain11** [comment]
@tisfeng 这功能没有开发中的话，我可以试试看。

**Comment by tisfeng** [comment]
可以，那太棒了！

参考这里 https://github.com/tisfeng/Easydict/issues/194#issuecomment-1783265016 ，如果方便的话，优先使用 Swift 开发，PR 提交到 dev 分支。

**Comment by NeverAgain11** [comment]
设置页面加了调整翻译页面字体大小的选项，翻译后的文案大小也能调整了，还有两个问题。
1、苹果词典的翻译字体大小还不知道该怎么改。
2、翻译名称那一栏的大小还没改。

**Comment by tisfeng** [comment]
可以，你先把代码推上来，dev 分支弄个 PR，稍后我跑一下代码，看看你说的问题。

**Comment by tisfeng** [comment]
[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本已支持修改显示字体大小。
