### ISSUE TITLE
功能建议：增加翻译服务的私有API接口

### ISSUE THREAD

**Issue by ViGeng** [tisfeng/Easydict#24]
## 功能描述

类似bob，可以提供私有API的调用，这样提供的翻译服务质量应该会更好一点（无论从精确度上还是调用次数上）

<img width="729" alt="image" src="https://user-images.githubusercontent.com/31836829/222951182-d03f1a92-8b35-41df-b081-74f5f69288bb.png">

感谢聆听！

**Comment by ViGeng** [comment]
可以加个donate，不能总用爱发电

**Comment by tisfeng** [comment]
感谢反馈，这个功能后面会做，目前开发人手不足，一步步来 😤

**Comment by tisfeng** [comment]
> 可以加个donate，不能总用爱发电

我考虑一下，确实，大部份开源都是用爱发电 😔

**Comment by tisfeng** [comment]
新版本优化了 DeepL 翻译，体验上已经接近官方 API。

DeepL 作为我常用翻译服务之一，但它网页免费版有频率限制，这点很烦，所以我增加了对 DeepL 官方 API 支持，暂时还没写界面，需要通过命令方式启用。

在输入框输入下面代码，xxx 是你的 DeepL AuthKey，然后 enter

```
easydict://writeKeyValue?EZDeepLAuthKey=xxx
```

默认是使用免费版网页 API，在网页 API 失败时会使用个人的 AuthKey （如果有）

<br>

如果你想优先使用个人的 AuthKey 也行
```
easydict://writeKeyValue?EZDeepLTranslationAPIKey=1
```

<br>

或只使用 个人 AuthKey
```
easydict://writeKeyValue?EZDeepLTranslationAPIKey=2
```

**Comment by tyhunter** [comment]
可以考虑下像这个bob的插件一样，支持deepl的接口域名吗
https://github.com/clubxdev/bob-plugin-deeplx
原因是现在个人的API没有外币信用卡无法购买，只能通过之前大佬遗留的Docker自建一个接口，但它提供的网页版的接口，不是APIKEY的形式

**Comment by tisfeng** [comment]
可是可以，但目前 Easydict 本身就支持免费的 DeepL 接口，虽然有频率限制，但本质上和这个项目 https://github.com/OwO-Network/DeepLX 是一样的，而且还不用自己去本地部署。 还是说你目前使用遇到了什么问题吗？

考虑到 DeepL 的律师函警告，未来 Easydict 可能会移除默认免费的网页版接口，也改成这种由用户手动部署本地接口方式，但那是后话了。

**Comment by akring** [comment]
看了一下百度的 API，作者是直接用了「文本翻译-词典版」的付费接口吗？那真的是用爱发电了

**Comment by tisfeng** [comment]
没，这里用的是百度网页版 API，里面带词典信息，之前百度的词典 API 还需要企业申请认证 😓

倒是 [Raycast-Easydict](https://github.com/tisfeng/Raycast-Easydict) 的百度翻译是官方 API，用的是我自己的 key。

**Comment by Jerry23011** [comment]
这个 issue 现在是不是算已经完成了呢
