### ISSUE TITLE
🚀 功能建议：支持OpenAI自定义域名为http

### ISSUE THREAD

**Issue by zzlphysics** [tisfeng/Easydict#245]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

我使用的本地LLM提供了类openAI接口，但是在使用时显示：
The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
似乎默认只支持https。请求增加对http的支持。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
行，我加一下。

**Comment by tisfeng** [comment]
[2.2.0](https://github.com/tisfeng/Easydict/releases/tag/2.2.0) 版本已支持 HTTP 接口。
