### ISSUE TITLE
🚀 Feature Request: 支持 https://api2d.com/ 上的apikey

### ISSUE THREAD

**Issue by Andrewshilexiaoxi** [tisfeng/Easydict#246]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Feature description

支持https://api2d.com/上的key

### Are you willing to submit a PR to implement this feature

- [X] I'm willing to submit PR!

**Comment by tisfeng** [comment]
你好，我看 [one-api](https://github.com/songquanpeng/one-api) 支持 api2d 服务，如果 api2d 不是标准的 OpenAI 接口，建议通过 one-api 将第三方服务接口转为标准的 OpenAI 接口，这样就能直接在 Easydict 使用了。
