### ISSUE TITLE
OpenAI翻译怎么禁用打字机效果，翻译的时候有点墨迹

### ISSUE THREAD

**Issue by ddzy** [tisfeng/Easydict#249]

**Comment by choykarl** [comment]
openai返回结果就是一段一段返回的，如果等结果全部返回后再展示就会显得翻译过程很慢。

**Comment by ddzy** [comment]
> openai返回结果就是一段一段返回的，如果等结果全部返回后再展示就会显得翻译过程很慢。

好吧，个人体验挺差的，这个打字机效果导致翻译的窗口一跳一跳的🙍‍♂️
