### ISSUE TITLE
🐞 反馈问题：EasyDict 运行一段时间后 Mac 出现画面卡顿现象

### ISSUE THREAD

**Issue by xlyslr** [tisfeng/Easydict#250]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

EasyDict 运行一段时间后，Mac 会出现画面卡顿，重启 EasyDict 后就会恢复。卡顿期间 CPU、GPU 都不高，内存压力也没上升。有遇到类似情况的吗

### 重现步骤

运行一段时间就会复现

### 截图

无

### 期望结果

可以看下需要提供哪些信息帮助分析。

### 设备型号 && 系统版本

MacBook Pro 16 ,2019,MacOS 14.1.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
没有用户反应过这种情况，Easydict 理论上也不会导致系统卡顿。不知道你说的卡顿具体是什么，你录个视频来看一下。

> Mac 会出现画面卡顿

重启 Easydict 后，后面就都不卡了？你能确定是 Easydict 导致的卡顿吗？你可以尝试减少服务，测试一下看到底哪个服务导致问题。

> 重启 EasyDict 后就会恢复

**Comment by tisfeng** [comment]
请提供更多的上下文信息，否则开发者无法定位问题。

或者可以先尝试重启应用，重启电脑，或卸载重装应用，看能否解决问题 🤔

**Comment by xlyslr** [comment]
> 没有用户反应过这种情况，Easydict 理论上也不会导致系统卡顿。不知道你说的卡顿具体是什么，你录个视频来看一下。
> 
> > Mac 会出现画面卡顿
> 
> 重启 Easydict 后，后面就都不卡了？你能确定是 Easydict 导致的卡顿吗？你可以尝试减少服务，测试一下看到底哪个服务导致问题。
> 
> > 重启 EasyDict 后就会恢复

不确定是 Easydict 导致的，但是近期只是新增了这一个软件。我之前怀疑过 goland，但是发现重启也不会减轻。后来重启 Easydict 就发现明显问题消失了。我现在一有顿挫感就重启 Easydict😂。目前，后台运行的有 mos、ishot、rectangle，不知道会不会有冲突

**Comment by WangLeto** [comment]
snipaste，飞书，微信，arc浏览器。难道跟截图工具（snipaste）还有冲突？

**Comment by xlyslr** [comment]
> snipaste，飞书，微信，arc浏览器。难道跟截图工具（snipaste）还有冲突？

arc +1

**Comment by Jerry23011** [comment]
> 难道跟截图工具（snipaste）还有冲突？

我的截图用的 Shottr，目前还没发现这个问题

**Comment by xlyslr** [comment]
> 是一开启 Easydict 立刻就会出现这个问题吗？还是等一段时间才有呢？

一段时间之后才有

**Comment by Jerry23011** [comment]
> 一段时间之后才有

我来开 Shottr + Easydict 试试

**Comment by xlyslr** [comment]
我截图和 Easydict 有相同授权的软件，看下有没有帮助
<img width="472" alt="image" src="https://github.com/tisfeng/Easydict/assets/14070517/3617e7b9-ee13-4158-9aa6-db9faa8393c4">
<img width="482" alt="image" src="https://github.com/tisfeng/Easydict/assets/14070517/88ca1836-3884-4f39-980e-b7b04e7bc3d0">
<img width="477" alt="image" src="https://github.com/tisfeng/Easydict/assets/14070517/39b08c55-9201-42d9-8e98-e0f08f386ca8">

**Comment by tisfeng** [comment]
@Jerry23011 后面如果有人反馈，你就跟进一下，看能不能定位到问题。

**Comment by WangLeto** [comment]
下次遇到应该先试试关闭划词翻译，看下表现。怀疑是跟划词翻译功能有关 🤔

**Comment by WangLeto** [comment]
@tisfeng 需要连续使用一段时间后才会偶现，并不是立即触发的

**Comment by WangLeto** [comment]
看了眼代码，没看懂（
但是感觉跟 EZEventMonitor.m 应该是有关系的，估计是某些边界 case 下有逻辑泄露，导致一直在执行 CGEventTapCreate 之类的。

**Comment by z-weliu** [comment]
我也遇到过这个问题，排除很久才发现是 Easydict 导致的，每次出现的时间长短不一，有时候开着两个小时就会发现变慢了，有时候可能两天后才会变慢，退出 Easydict 就好了。
@tisfeng 请问出现的时候如何收集 debug 信息，方便你分析？

macOS: 13.5.1 
Easydict: 2.3.0

**Comment by Vaayne** [comment]
我也遇到过这个问题，排除很久才发现是 Easydict 导致的，每次出现的时间长短不一，有时候开着两个小时就会发现变慢了，有时候可能两天后才会变慢，退出 Easydict 就好了。
@tisfeng 请问出现的时候如何收集 debug 信息，方便你分析？

macOS: 13.5.1
Easydict: 2.3.0

**Comment by tisfeng** [comment]
如果出现异常问题，你可以打开【活动监视器】取样，它会自动收集一段时间的日志信息。

<img width="1133" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0b30112d-77ca-4ee5-9a4d-85ee9a2ebc9c">

**Comment by Vaayne** [comment]
[Sample of Easydict.txt](https://github.com/tisfeng/Easydict/files/13710484/Sample.of.Easydict.txt)

@tisfeng I have some samples; I hope this will help.

**Comment by tisfeng** [comment]
看了一下日志，没看出什么名堂 😥

主要是我这边测试都是正常的，你们说的卡顿没办法复现，不知道问题出在哪。

可能是监听鼠标键盘事件这里有坑，但我没查到相关资料，不知道怎么优化。

如果这个问题真的很严重，后面会考虑提供设置选项，停止监听鼠标键盘事件。

**Comment by WangLeto** [comment]
试了下本地运行这个项目，有点好奇 monitorCGEventTap 是有啥作用，我把两处调用注释掉重新运行，功能还是正常的（测了下鼠标悬浮到 icon 上和点击 icon 查词）。为什么注释写 `Monitor CGEventTap must be required after using Accessibility successfully`
<img width="622" alt="image" src="https://github.com/tisfeng/Easydict/assets/25009314/b50b1904-615a-41be-8235-46c4209e3a69">
<img width="733" alt="image" src="https://github.com/tisfeng/Easydict/assets/25009314/4c55bdfc-5028-43ea-a024-d78e3657fa77">

**Comment by WangLeto** [comment]
哦，看起来是在监听划词后一段时间内的键盘操作，防止词典干扰对其他软件的操作？不过我之前采样中的 `add_events_to_tap` 和 `CGEventTapCreate`，可以确认是一个东西吗，搜了下似乎没找到关于二者关系的说明（不要误伤）

**Comment by tisfeng** [comment]
你点进去看看 monitorCGEventTap 方法内容，它监听了 kCGEventKeyDown 事件，这个方法需要辅助功能权限，这是为了能够在用户按下键盘按键时隐藏查询图标，不然使用快捷键触发某些应用时，会导致 Easydict 查询图标一直显示。

当然了，代码中还有其他方法隐藏查询图标。

**Comment by WangLeto** [comment]
咦，这个逻辑有点……为什么不持续监听，而是不断地重建销毁事件监听呢。逻辑如（类似 JavaScript 语法伪代码）：
```
const listenKeyDownForIconPop = {
  keyDownAt,
  keyCode, // 如果需要判断具体按键是什么
}

键盘监听回调(按键) {
  listenKeyDown.keyDownAt = 当前时间()
  listenKeyDown.keyCode = 按键
}

划词回调() {
  setTimeout(() => {
    if 当前时间() - listenKeyDownForIconPop.keyDownAt < 阈值时间如500ms
      return  // 如果选词后500ms内有按键就不展示
    展示图标()
  }, 500ms) // 延时500ms判断
}
```
这样你就监听一次就完事辣

**Comment by tisfeng** [comment]
可以，但没必要，这个监控事件只是为了隐藏查询图标，如果没显示图标，就没必要监听。另外，我也担心长时间监听，可能会有什么副作用。

**Comment by WangLeto** [comment]
现在的实现其实等价于持续监听，因为是在下一次启动监听时销毁上一次的监听的。😂

**Comment by tisfeng** [comment]
我也发现了，之前忘记在隐藏图标时销毁了 🥹 

刚加上了，你用最新的 dev 代码试一下。

**Comment by WangLeto** [comment]
行，我编译一版本地长期用下，看看是否复现

**Comment by WangLeto** [comment]
似乎不太行。用 dev 里的代码，仍然出现了 WindowServer 里大量的 add_events_to_tap。而且我打印了一下日志，可以确认 eventTap 的销毁逻辑是正常被执行了的，每次划词成功后都能找到对应的销毁方法被执行了 😰。现在我怀疑，作者不复现，难道是只有 m 芯片的 mac 有这个问题
<img width="402" alt="image" src="https://github.com/tisfeng/Easydict/assets/25009314/deb78ab2-26dc-4cee-b17f-d326ca7e8235">

**Comment by tisfeng** [comment]
我电脑也是 Apple M1 Pro

**Comment by WangLeto** [comment]
昨天我把两处 `[self monitorCGEventTap];` 的调用代码注释掉然后构建了一个 release 版本，使用到目前为止没有再复现卡顿问题。

**Comment by tisfeng** [comment]
有点神奇，主要 monitorCGEventTap 方法也没发现问题，内存泄漏也没有 😑

**Comment by tisfeng** [comment]
直接去掉 monitorCGEventTap 有点不妥，我先加个限制条件，在关闭显示查询图标时，就不执行这个方法。

我打来个测试包，如果有人电脑运行 Easydict 出现这个问题，用这个包，可以在设置中关闭【鼠标自动划词】选项，测试一段时间，如果确认是这个方法导致问题，后面我再想办法处理一下。

[Easydict.zip](https://github.com/tisfeng/Easydict/files/13752622/Easydict.zip)

**Comment by Mr-zhaohy** [comment]
相同的问题，每次用个半天就会变卡，重启EasyDict之后正常 M1 Max  macOS14

**Comment by tisfeng** [comment]
> 直接去掉 monitorCGEventTap 有点不妥，我先加个限制条件，在关闭显示查询图标时，就不执行这个方法。
> 
> 我打了一个测试包，如果有用户的电脑运行 Easydict 出现这个问题，可以用这个包，在设置中关闭【鼠标自动划词】选项，测试一段时间，如果确认是这个方法导致问题，后面我再想办法处理一下。
> 
> [Easydict.zip](https://github.com/tisfeng/Easydict/files/13752622/Easydict.zip)

如果有卡顿问题的，请用这个包试一下，如果还有问题，也请反馈一下。

如果几天后没有反馈，我就视作问题已解决了。

**Comment by tisfeng** [comment]
2.5.0 版本已经做了一些优化，如果遇到卡顿问题，请尝试在设置中关闭【鼠标自动划词】选项。

该问题没有后续反馈，就先关闭了。

**Comment by hiberabyss** [comment]
使用 2.7.2 版本，运行一段时间后还会出现系统比较卡顿的情况。此时 WindowServer 的 cpu 使用率会比较高。

重启 EasyDict 之后就恢复正常了。

**Comment by Jerry23011** [comment]
@hiberabyss 可以发一下你的 macOS 版本吗？我记得之前一些macOS 版本 WindowServer 是有问题的

**Comment by hiberabyss** [comment]
处理器是 m1 pro。
macOS 版本是 14.5

**Comment by Jerry23011** [comment]
和我的环境一模一样，请问还有其他同时开启需要录制屏幕权限的软件吗？

**Comment by hiberabyss** [comment]
有 iBar，iShot Pro 和飞书。

**Comment by Jerry23011** [comment]
在不运行那三个的时候也会出现这个问题吗

**Comment by hiberabyss** [comment]
> 在不运行那三个的时候也会出现这个问题吗

这个没试过。
准备通过脚本定时重启 easydict 来避免这个问题。

**Comment by hiberabyss** [comment]
大概率和飞书视频会议有关系。每次用飞书开完会后系统就变卡顿。

**Comment by JiangHanfeng** [comment]
最新的版本依然存在这个问题

**Comment by Jerry23011** [comment]
@JiangHanfeng 你使用飞书吗？

**Comment by guanguans** [comment]
我这边的情况是，用触控板上下滚动页面，一卡一顿的，很难受。重启 Easydict 就好了。过一段时间就又开始又卡顿了。用外接鼠标始终不会卡顿。

macOs：Ventura 13.6.7 (22G720)
Easydict：2.8.0

**Comment by tisfeng** [comment]
有点神奇，我也经常使用触摸板，没有遇到类似问题 🙃

**Comment by SovereignRemedy** [comment]
同样的情况 运行两三天之后就卡顿 但是关闭ed立刻缓解

15.1.1 (24B91)
Easydict：2.10.1

**Comment by tisfeng** [comment]
如果感觉电脑卡顿，请用活动监视器看看 Easydict 的内存和 CPU 占用情况，看有没有异常。

某些情况下确实可能导致问题，但这个一时半会没办法解决 😥

**Comment by quwang123** [comment]
我也遇到了类似的问题、重启 easydict 以后就不卡了

**Comment by tisfeng** [comment]
> 问题依旧存在 Easydict 2.13.0 macOS 15.4 基本每天都会发生 [@tisfeng](https://github.com/tisfeng)

你好，有发现这些异常情况吗 https://github.com/tisfeng/Easydict/issues/250#issuecomment-2543846453

**Comment by Mr-zhaohy** [comment]
> > 问题依旧存在 Easydict 2.13.0 macOS 15.4 基本每天都会发生 [@tisfeng](https://github.com/tisfeng)
> 
> 你好，有发现这些异常情况吗 [#250 (comment)](https://github.com/tisfeng/Easydict/issues/250#issuecomment-2543846453)

刚才发生时只看到WindowServer内存占用比较高，退出ED恢复正常

**Comment by Mr-zhaohy** [comment]
> > 问题依旧存在 Easydict 2.13.0 macOS 15.4 基本每天都会发生 [@tisfeng](https://github.com/tisfeng)
> 
> 你好，有发现这些异常情况吗 [#250 (comment)](https://github.com/tisfeng/Easydict/issues/250#issuecomment-2543846453)

Analysis of sampling Easydict (pid 18501) every 1 millisecond
Process:         Easydict [18501]
Path:            /Applications/Easydict.app/Contents/MacOS/Easydict
Load Address:    0x100e08000
Identifier:      com.izual.Easydict
Version:         2.13.0 (47)
Code Type:       ARM64
Platform:        macOS
Parent Process:  launchd [1]
Target Type:     live task

Date/Time:       2025-04-22 17:40:30.426 +0800
Launch Time:     2025-04-21 20:51:45.910 +0800
OS Version:      macOS 15.4.1 (24E263)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         116.6M
Physical footprint (peak):  121.9M
Idle exit:                  untracked

[“Easydict”的取样.txt](https://github.com/user-attachments/files/19847373/Easydict.txt)

**Comment by tisfeng** [comment]
看了一下你提供的取样，没发现异常信息 😑

**Comment by ruhengChen** [comment]
@tisfeng 
我也遇到了，提供日志以供分析

[Sample of Easydict.txt](https://github.com/user-attachments/files/21202012/Sample.of.Easydict.txt)
[Sample of Easydict(normal).txt](https://github.com/user-attachments/files/21202013/Sample.of.Easydict.normal.txt)

以下是 AI 分析
<img width="834" height="741" alt="Image" src="https://github.com/user-attachments/assets/241fbe65-9521-4694-ba4b-76662b0c9d87" />

**Comment by tisfeng** [comment]
看了一下取样日志，你这个主要还是内存泄露。

> EasyDict 运行一段时间后，Mac 会出现画面卡顿，重启 EasyDict 后就会恢复。卡顿期间 CPU、GPU 都不高，内存压力也没上升。

某些情况下应用存在内存泄露，这是一个已知问题 https://github.com/tisfeng/Easydict/issues/81 ，我们还在定位问题所在。

但根据用户反馈，内存并不是导致卡顿的主要原因，即使内存占用正常，也可能出现卡顿。

**Comment by WangLeto** [comment]
昨天升级 Tahoe，今天白天工作卡得……不确定是不是 EasyDict 的问题，重启关闭以后再用一段时间观察一下

**Comment by tisfeng** [comment]
我也发现了，可能是 macOS 新系统某些 API 有些问题，再加上之前我用了  Xcode 26 beta 版本打包，导致内存泄露问题很明显 https://github.com/tisfeng/Easydict/issues/970

稍后我用旧版本 xcode 发一个新版本。

**Comment by ZxyGch** [comment]
我是 15.6.1 也遇到了这个问题，非常卡，即使卸载了也无法立即解决，只有卸载+重启后才彻底解决

**Comment by ZxyGch** [comment]
内存，CPU 都完全正常
