### ISSUE TITLE
🚀 功能建议：单词模式下，对于语法变形单词支持

### ISSUE THREAD

**Issue by GrittyB** [tisfeng/Easydict#252]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

查询单词返回结果的判断时，可能是使用了完全匹配？对有语法变形的单词查询不太友好。
比如：hoped，如果找不到匹配的单词，可以给出原形hope，在mac自带的查询，以及苹果词典中，会给出它的原型形式
<img width="492" alt="image" src="https://github.com/tisfeng/Easydict/assets/74409416/80f91954-82b6-4776-9c97-b0a889496014">
<img width="496" alt="image" src="https://github.com/tisfeng/Easydict/assets/74409416/3a381221-5f64-42f1-97b4-697bf97b8363">
<img width="802" alt="image" src="https://github.com/tisfeng/Easydict/assets/74409416/e013eb36-0c81-4a69-b699-bf9f9acaa6ce">
<img width="802" alt="image" src="https://github.com/tisfeng/Easydict/assets/74409416/3089689b-d41c-4622-94fe-b78a4653ac6e">

### 实现方案（可选）

是否可以直接返回苹果词典第一个查询到的单词结果？

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR!

**Comment by tisfeng** [comment]
我研究一下。

**Comment by tisfeng** [comment]
[2.4.0](https://github.com/tisfeng/Easydict/releases/tag/2.4.0) 版本已支持单词变形形式查询。
