### ISSUE TITLE
🐞 反馈问题：用brew安装，打开设置，界面显示一黑一白

### ISSUE THREAD

**Issue by shuaixiaomi** [tisfeng/Easydict#253]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

<img width="591" alt="image" src="https://github.com/tisfeng/Easydict/assets/77660384/c7eb4307-0e9f-4eea-b068-6fc2ec872b31">

### 重现步骤

用brew安装的 ，打开就这样了

### 截图

<img width="591" alt="image" src="https://github.com/tisfeng/Easydict/assets/77660384/2533a0b6-85ca-4bbd-8b35-971eeca636ee">

### 期望结果

正常使用

### 设备型号 && 系统版本

mac11.6.4

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by nocturne2014** [comment]
通过Release发布包安装最新版本，同样存在此问题。

<img width="350" alt="Snipaste_2023-12-05_11-47-22" src="https://github.com/tisfeng/Easydict/assets/7165548/2804bd92-883d-4a23-b172-342d1a47ba50">

**Comment by tisfeng** [comment]
要想彻底解决这个问题，可能要等后面重写设置页了，那需要一段时间。

**Comment by atinst** [comment]
今天初次使用该软件，使用的是.dmg安装方式，安装后首次打开该软件的设置界面出现了和楼主一样的黑色Bug。

**Comment by atinst** [comment]
![image](https://github.com/tisfeng/Easydict/assets/32417799/62361f41-86bb-4ab6-b451-db8ac3e1ffb4)


> 要想彻底解决这个问题，可能要等后面重写设置页了，那需要一段时间。

今天遇到了新的问题，翻译界面也与系统设置颜色不同。

**Comment by atinst** [comment]
> 要想彻底解决这个问题，可能要等后面重写设置页了，那需要一段时间。

是否能在软件内增加一个开关，手动选择是否跟随系统深色模式设置？

**Comment by tisfeng** [comment]
没想到这问题这么奇怪，行，后面加一下。

**Comment by tisfeng** [comment]
@NeverAgain11 麻烦你在设置页加一下这个，提供一个选项允许用户选择外观模式：跟随系统，浅色和深色，默认跟随系统。

**Comment by NeverAgain11** [comment]
> @NeverAgain11 麻烦你在设置页加一下这个，提供一个选项允许用户选择外观模式：跟随系统，浅色和深色，默认跟随系统。

没问题

**Comment by tisfeng** [comment]
[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本已支持用户选择外观模式。
