### ISSUE TITLE
🚀 功能建议：支持配置火山引擎个人 AK & SK

### ISSUE THREAD

**Issue by iamxfour** [tisfeng/Easydict#255]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

是否有计划支持可以配置火山引擎个人的 AK & SK 以用于翻译或是 OCR？目前的处理方式速度比较慢

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
这里有两个服务 Swift  PR 示例：
- 彩云小译： https://github.com/tisfeng/Easydict/pull/218
- 腾讯翻译：https://github.com/tisfeng/Easydict/pull/240

**Comment by tisfeng** [comment]
你好，请问这个怎么样了？

**Comment by tisfeng** [comment]
之前我测试发现，火山翻译目前的实现有小概率会导致程序崩溃，但一直没找到修复方法。

因此，如果这个功能完成了，我希望能尽快合并上线，避免影响到这部分使用火山翻译的用户。

**Comment by iamxfour** [comment]
最近工作有一些高优且复杂的事情在处理，一月中旬以前以前没时间处理，预期会在一月底完成

**Comment by tisfeng** [comment]
ok

**Comment by tisfeng** [comment]
这周末会发一个新版本，请问这个能一起上吗？

**Comment by tisfeng** [comment]
行吧，那就年后。

**Comment by tisfeng** [comment]
你好，请问这个功能有在做吗？

**Comment by iamxfour** [comment]
没有，抽不出时间，我关了吧，抱歉

**Comment by NeverAgain11** [comment]
@tisfeng 现在工作比较忙😓，抽不出时间，抱歉。

**Comment by tisfeng** [comment]
ok.

@CanglongCl 你可以做这个吗

**Comment by CanglongCl** [comment]
> ok.
> 
> @CanglongCl 你可以做这个吗

先给我吧，我下周看看~

**Comment by tisfeng** [comment]
@Jerry23011 你有空可以接手这个吗？修改只支持 API key 请求方式，完成后可以将之前的 objc webView 方式移除。

**Comment by Jerry23011** [comment]
> @Jerry23011 你有空可以接手这个吗？修改只支持 API key 请求方式，完成后可以将之前的 objc webView 方式移除。

正好放假，我来试试

**Comment by tisfeng** [comment]
下个版本将会移除火山翻译网页 API，将只支持官方 API key 方式。

**Comment by tisfeng** [comment]
你好，[2.9.0](https://github.com/tisfeng/Easydict/releases/tag/2.9.0) 版本已添加该功能。
