### ISSUE TITLE
🚀 功能建议：希望制作一个PopClip插件

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [tisfeng/Easydict#256]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

希望制作一个PopClip插件
https://www.popclip.app/extensions/
竞品bob有，这也就是我停留bob的唯一原因了吧

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
配合 PopClip 使用

 https://github.com/tisfeng/Easydict#%E9%85%8D%E5%90%88-popclip-%E4%BD%BF%E7%94%A8

**Comment by shoudeyunkaijianyueming** [comment]
不行啊，安装不上，不懂变成，无法安装，能不能您提供一个成品？Easydict.popclipext

**Comment by tisfeng** [comment]
我认为这种安装扩展的方式，比手动下载一个 popclipext 文件，再点击安装要方便。

行吧，我看你勾选了提交 PR，那你可以来 PR 提供一个文件安装。
