### ISSUE TITLE
🐞 反馈问题：截图功能偶发性bug

### ISSUE THREAD

**Issue by shadowchowwc** [tisfeng/Easydict#257]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

使用截图功能时，如果点击触控板拖拽截图则正常，但是会卡顿，如果使用三指拖拽截图，则截图范围会变小，但不会卡顿。不过这只是偶发的，重启软件后恢复正常了，只是单纯的反馈一下，谢谢。

### 重现步骤

使用截图功能时，如果点击触控板拖拽截图则正常，但是会卡顿，如果使用三指拖拽截图，则截图范围会变小，但不会卡顿。不过这只是偶发的，重启软件后恢复正常了，只是单纯的反馈一下，谢谢。

### 截图

没有截图，也没有崩溃日志。

### 期望结果

希望可以排查一下是不是软件的bug，谢谢。

### 设备型号 && 系统版本

Apple M2, macOS Ventura 13.4

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
触发截图动作时，确实有小概率会出现卡顿，但由于这部分代码是基于另一个开源库改造的，比较复杂，不好排查。

"截图范围会变小"，请问这个具体是指什么？

> 如果使用三指拖拽截图，则截图范围会变小

**Comment by tisfeng** [comment]
问题无法稳定复现，再观望观望。

**Comment by tisfeng** [comment]
问题无法稳定复现，先关闭了。
