### ISSUE TITLE
🐞 反馈问题：用openai出现 Request failed: method not allowed (405)

### ISSUE THREAD

**Issue by jiangaq** [tisfeng/Easydict#258]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

已经设置了自定义域名和key了
用bob就没出错

### 重现步骤

`

### 截图

`

### 期望结果

`

### 设备型号 && 系统版本

macos 13.6.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
能整点详细的信息吗？每次看到这种没头没脑的 issue 就头大。

先确定设置步骤有没有问题，再确定 key 有没有问题，最后请提供详细的测试报错信息。

> 设置了自定义域名和key

**Comment by jiangaq** [comment]
<img width="763" alt="CleanShot 2023-12-17 at 14 21 43@2x" src="https://github.com/tisfeng/Easydict/assets/26076033/c2f8e1e7-33c7-4950-ba78-22c03280fbba">
key设置的对吗？

**Comment by tisfeng** [comment]
注意，EZOpenAIEndPointKey 这个值需要完整的请求 URL，例如 OpenAI 官方接口应该是 https://api.openai.com/v1/chat/completions

**Comment by tisfeng** [comment]
这个还有问题吗，没问题我就关了。
