### ISSUE TITLE
🐞 反馈问题：鼠标滑动空白处时会自动复制内容

### ISSUE THREAD

**Issue by dqzboy** [tisfeng/Easydict#261]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

鼠标滑动空白处时会自动复制内容，但是粘贴其实啥也没有

### 重现步骤

在那种有复制弹窗提醒的网站上可以明显看到复制的提示；或者打开一个网页，然后在空白处滑动，右上角的编辑按钮就会一闪一闪的显示

### 截图

这是我找的一个网站测试的：地址https://www.77388.cn/Plus/1680.html
<img width="440" alt="image" src="https://github.com/tisfeng/Easydict/assets/42825450/40b438e3-cfc9-42f2-9ea9-bc91cee86f93">

### 期望结果

不确定这是什么情况，但是关闭easydict后就正常了

### 设备型号 && 系统版本

M3，14.2

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
试了一下，确实存在这个问题，因为鼠标滑动后 Easydict 会尝试取词，调用了苹果系统官方的 Accessibility API，问题出在这个网站上，它似乎设置拦截了系统的取词方法，在取词失败时会进行自定义操作，这里的表现就是流氓弹窗。

第一次就这么恶心的拦截功能，比 CSDN 还恶心。

**Comment by tisfeng** [comment]
这个网站右下角怎么一直有奇怪弹窗，和拦截功能一样令人恶心，还没办法关掉，技术不是这么用的。

**Comment by dqzboy** [comment]
> 试了一下，确实存在这个问题，因为鼠标滑动后 Easydict 会尝试取词，调用了苹果系统官方的 Accessibility API，问题出在这个网站上，它似乎修改拦截了系统的取词方法，在取词失败时会进行自定义操作，这里的表现就是流氓弹窗。
> 
> 第一次见这么恶心的拦截功能，比 CSDN 还恶心。

哈哈，win 上不会出现这个情况，我在那个知乎上空白处滑动一下，然后右上角那个编辑就会闪一下，只是知乎那个没弹窗

**Comment by tisfeng** [comment]
这个问题，很大程度上归因于这个奇葩网站滥用技术，因此不会处理。

**Comment by dqzboy** [comment]
> 这个问题，很大程度上归因于这个奇葩网站滥用技术，因此不会处理。

嗯嗯，不影响使用，软件功能很棒

**Comment by tisfeng** [comment]
这个是正常现象，某些场景下系统 Accessibility 方法取词失败，会尝试模拟快捷键 Cmd+C 取词，这个操作 会触发【编辑-复制】动作，在某些应用上就会闪一下，详情请看 https://github.com/tisfeng/Easydict/issues/84

> 右上角那个编辑就会闪一下
