### ISSUE TITLE
🐞 反馈问题：苹果自带词典软件安装朗文词典后，在黑色系统主题下取词的显示问题

### ISSUE THREAD

**Issue by Alfie728** [tisfeng/Easydict#262]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

如下列截图所示，我在苹果自带词典中安装了项目文档中提供的朗文词典。在黑色系统主题下点按查询时css样式有问题，很不方便阅读。想问一下应该如何修改DefaultStyle.css解决这个问题呢？

### 重现步骤

利用自带词典点按取词

### 截图

<img width="402" alt="Screenshot 2023-12-12 at 23 09 02" src="https://github.com/tisfeng/Easydict/assets/150578647/0d06f97f-1ea4-433f-8c24-1b931116b5c2">
<img width="778" alt="Screenshot 2023-12-12 at 23 09 17" src="https://github.com/tisfeng/Easydict/assets/150578647/def3c142-f875-4764-93b8-fa6d97fb2d4f">

### 期望结果

修改DefaultStyle.css

### 设备型号 && 系统版本

M2 Pro macOS 14.1.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
具体词典内容改造，请自行研究，HTML 方面的内容我也不是很了解 😓

参考 https://placeless.net/blog/macos-dictionaries

<img width="883" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/a28938e8-ca0c-4465-af1e-f9504f5e82cc">

**Comment by tjwangji** [comment]
在info.plist中的</dict>下
添加
<key>DCSDictionaryUseSystemAppearance</key>
<true/>
然后再到字典目录，编辑DefaultStyle.css，在最后添加
/* 白底黑字 */
body {
    background-color: #ddd;
}
或者
/* 黑底白字 */
body {
  color: #ddd;
  background-color: #222;
}
或者也可以自定义你习惯的颜色

**Comment by tisfeng** [comment]
这个问题和应用本身无法，先关闭了。

**Comment by Konfido** [comment]
遇到同样的问题，用下面的方法解决了 （on Mac with M1 chips）

无需编辑DefaultStyle.css，只用在Info.plist中，将"DCSDictionaryUseSystemAppearance"项的值改选为"NO"并保存，然后重启软件以使设置生效（eg：想在浏览器中使用点按查询，就重启下浏览器）

**Comment by lajujuberry** [comment]
> 遇到同样的问题，用下面的方法解决了 （on Mac with M1 chips）
> 
> 无需编辑DefaultStyle.css，只用在Info.plist中，将"DCSDictionaryUseSystemAppearance"项的值改选为"NO"并保存，然后重启软件以使设置生效（eg：想在浏览器中使用点按查询，就重启下浏览器）
> 
> <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/25447610/327355912-82f10228-3045-4186-b41f-89e56ad5202a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTgwMjEsIm5iZiI6MTczNTgxNzcyMSwicGF0aCI6Ii8yNTQ0NzYxMC8zMjczNTU5MTItODJmMTAyMjgtMzA0NS00MTg2LWI0MWYtODllNTZhZDUyMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDExMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMTE4NGQxZGExNDhiY2M3YmI2NjgxNjBlMjFkNzFjYjliODNiMzViZDA0ZjdlNWZhZTA5MThmZjEyMGZiZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hogK74k7UsfgExzYUzIA6ZMyJ3oMtkn3cgnbZd6Lwf0">

朋友你好，请问Info.plist具体在何处？
