### ISSUE TITLE
🐞 反馈问题：和 edge 的截图有冲突

### ISSUE THREAD

**Issue by pipashu** [tisfeng/Easydict#263]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

开启 easydict 的时候，edge 的自带截图在截图后就消失了，退出 easydictedge 截图功能正常。

### 重现步骤

开启 easydict，运行 edge 的截图命令。

### 截图

![WX20231216-091314@2x](https://github.com/tisfeng/Easydict/assets/27265628/247ad4ae-95a5-4db9-a26e-175a4f406f06)

### 期望结果

不影响 edge 截图的实用。

### 设备型号 && 系统版本

Apple M1, macOS 14.0

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
我一般不用 edge，不知道这个浏览器的一些奇怪特性。

在我电脑上测试，即使关闭 Easydict，使用 edge 的截图也会导致 edge 自身闪退，这看起来是 edge 浏览器自身的问题。

不确定 edge 的截图功能是否和快捷键冲突，你可以关闭 Easydict 的截图快捷键试一下。

如果还有问题，请提供更多的测试信息。

**Comment by pipashu** [comment]
> 我一般不用 edge，不知道这个浏览器的一些奇怪特性。
> 
> 在我电脑上测试，即使关闭 Easydict，使用 edge 的截图也会导致 edge 自身闪退，这看起来是 edge 浏览器自身的问题。
> 
> 不确定 edge 的截图功能是否和快捷键冲突，你可以关闭 Easydict 的截图快捷键试一下。
> 
> 如果还有问题，请提供更多的测试信息。

我试过了，关闭Easydict后 edge 截图就正常了，后来我再次打开Easydict，关闭“划词后自动显示查询图标”，edge 的截图功能也正常了，看来是“划词后自动显示查询图标”这里的问题。

**Comment by tisfeng** [comment]
@Jerry23011 帮忙测一下这个问题，我电脑上的 edge 一截图就会闪退，不知道什么问题。

**Comment by Jerry23011** [comment]
OK，这就测一下

**Comment by Jerry23011** [comment]
> 我电脑上的 edge 一截图就会闪退，不知道什么问题。

我也。。

https://github.com/tisfeng/Easydict/assets/89069957/8cb9968f-bd52-44ba-9a40-a699eea993ad

**Comment by tisfeng** [comment]
edge 看来真有问题，你们可以向官方反馈一下。

**Comment by tisfeng** [comment]
在我电脑上，edge 划词功能是支持系统的 Accessibility 取词，这是苹果官方 API，如果真的和 edge 截图冲突，那肯定也是 edge 的功能实现不规范，是它的锅。

> 关闭“划词后自动显示查询图标”，edge 的截图功能也正常了，看来是“划词后自动显示查询图标”这里的问题。

**Comment by tisfeng** [comment]
如果只是想关闭 edge 应用的划词功能，可以去设置中的【禁止名单】加一下它。

**Comment by AkaShark** [comment]
When I tried Edge in this version, i did not find anything crash.
![CleanShot 2023-12-25 at 14 28 40@2x](https://github.com/tisfeng/Easydict/assets/26460192/7dc2ca56-1881-4b7b-9770-408ca5ed2475)

**Comment by tisfeng** [comment]
我也是这个版本，但每次使用截图功能必定崩溃。

这个问题有点怪，可能是 edge 和电脑上其他应用冲突了，我懒得查了，后面看看有没有其他用户反馈吧。

<img width="913" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/3ccdd1df-b9b8-45fb-be56-3227de2b11eb">

**Comment by tisfeng** [comment]
清理 issue，没有后续反馈的就先关闭了，如果再遇到问题，请另外提 issue。
