### ISSUE TITLE
🐞 反馈问题：查询macOS字典的速度较慢

### ISSUE THREAD

**Issue by kun4399** [tisfeng/Easydict#265]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

当macOS字典查询时，有些单词的查询速度明显慢于三指取词。似乎一般是查询结果比较长的那种单词？

### 重现步骤

用macOS字典查单词

### 截图

![录屏2023-12-17-10 58 06](https://github.com/tisfeng/Easydict/assets/95582144/239b9850-a753-4684-b7a4-b67713e2d687)

### 期望结果

解决查询速度慢的问题

### 设备型号 && 系统版本

Apple M1 Pro, macOS 14.2

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
你这个视频看着像 0.5 倍播放速度。。

单词内容多，慢一点是正常的，但一般也不会很慢，大块头词典我用朗文查询单词 take，一般也就 2s 左右。

大块头词典多，查询速度肯定变慢。

https://github.com/tisfeng/Easydict/blob/main/docs/How-to-use-macOS-system-dictionary-in-Easydict-zh.md#%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E7%AC%AC%E4%B8%89%E6%96%B9%E8%AF%8D%E5%85%B8

> 朗文、柯林斯和牛津，这三本大块头词典都很好，但由于词条内容实在太过丰富，可能会影响 Easydict 查询加载速度，因此建议选择其中一本自己喜欢的就好。

**Comment by kun4399** [comment]
嗯嗯， 我只是想问一下，有没有可能做到像系统查询速度那样快。 因为在使用系统自带的三指查词的时候速度还是很快的，尤其是字典数量较多的情况下，差距还是挺明显的。 这个视频速度确实慢了， 不知道为什么转为gif以后就像是0.8倍速。

**Comment by kun4399** [comment]
嗯嗯，还想问一下， 有没有可能做到像系统查询单词那样的速度， 尤其是在字典比较多的情况下， 三指查词的速度明显快很多。 视频速度确实像是0.8倍速， 我也不知道为什么转换为gif图像后就会变慢

**Comment by tisfeng** [comment]
不确定，因为苹果没有提供查词典的官方 API，Easydict 这里用的是私有接口，去查询系统词典的数据，然后还要对数据做各种处理，整过程性能损耗比较严重。

要想优化，感觉有点难。后面有空再看。

**Comment by kun4399** [comment]
哦哦明白了
