### ISSUE TITLE
🐞 Bug Report: 

### ISSUE THREAD

**Issue by jackviv** [tisfeng/Easydict#266]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)

### Problem description

2.3.0
mac os 13.3.1
打开软件后 自动调用更新功能，检测有新版本，点击更新，必崩。
而且在调用翻译后，频繁崩溃，几乎到了不可用的状态。

### Reproduction steps

已经重装，最新版本 bug依旧。

### Screenshot

导出日志看了下，包含个人隐私 没办法上传

### Expected result

修复bug

### Device type and OS version

mac os 13.3.1 Intel 

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by tisfeng** [comment]
请看 https://github.com/tisfeng/Easydict/issues/267#issuecomment-1859044233
