### ISSUE TITLE
🚀 功能建议：新增的翻译服务能否默认关闭，并且排序在末尾

### ISSUE THREAD

**Issue by jh-leong** [tisfeng/Easydict#269]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

问题：在每一次更新中，如果新增了翻译服务，新增的服务都会默认开启，并且在服务排序中置顶；
影响：影响用户原有的设置，导致每次更新都要重新去设置中关闭和排序；
期望：新增的翻译服务默认关闭，并且排序在末尾

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
可以，后面我改一下。

**Comment by AkaShark** [comment]
Hi I am interested in this project, and I used Bob before. If this issue is open? Can I try to add this feature?

**Comment by tisfeng** [comment]
Thank you for your interest, this feature is already implemented, if you are interested in this project, you can help with other issues, especially the ones with the `PR-wanted` tag.

**Comment by AkaShark** [comment]
okay~

**Comment by tisfeng** [comment]
发布后才发现，[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本好像改错了，对于新增的翻译服务，我本来想改成默认关闭查询功能，结果改成默认关闭显示，得用户自己去设置页添加了 😢

问题也不大，后面我再改改。

**Comment by tisfeng** [comment]
[2.6.0](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 新版本已修复该问题。
