### ISSUE TITLE
🚀 功能建议：朗读开关

### ISSUE THREAD

**Issue by yhan219** [tisfeng/Easydict#272]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

允许关闭朗读，现在默认开启，有时候大晚上没注意打开突然朗读了单词吓一跳。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
设置中不是有开关吗？
