### ISSUE TITLE
🐞 反馈问题：静默截图OCR

### ISSUE THREAD

**Issue by andyrubin69** [tisfeng/Easydict#273]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

使用静默截图OCR扫描代码片段，扫描出来的结果：①代码中的括号，标点都是中文下的括号和标点。②，部分单词会首字母转大写。

### 重现步骤

使用静默截图OCR扫描代码片段

### 截图

![code](https://github.com/tisfeng/Easydict/assets/149977411/4af2c9d7-83c5-4587-af6e-c22a16df063b)

<img width="1127" alt="2023-12-22_14-29-53" src="https://github.com/tisfeng/Easydict/assets/149977411/a10f758a-2566-4ad7-9b66-5c38b55eb31a">

### 期望结果

代码中的标点符号按英文来设置，单词不进行大小写转换。

### 设备型号 && 系统版本

Apple M1 Pro, macoS 14.0

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
这个是字体识别问题，图片中那个字体的 l 本来就比较怪，有时候会识别有误。

> ②，部分单词会首字母转大写。

**Comment by tisfeng** [comment]
这个确实可以处理一下，你来提 PR 吗？

> ①代码中的括号，标点都是中文下的括号和标点。

**Comment by tisfeng** [comment]
你好，这个问题你要提交 PR 解决吗，还是说勾选错了？ 😓

<img width="466" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/ec921f1e-e501-4327-b30d-255de467fb2c">

**Comment by andyrubin69** [comment]
不好意思，应该是勾选错了，很抱歉。

Tisfeng ***@***.***>于2024年1月7日 周日20:17写道：

**Comment by tisfeng** [comment]
想了想，这个是系统 OCR 接口问题，暂时先不考虑优化。
