### ISSUE TITLE
🚀 功能建议：软件很棒,如果有pc的就很好了

### ISSUE THREAD

**Issue by linzzzzllll** [tisfeng/Easydict#275]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

BetterAndBetter

### 使用场景（可选）

BetterAndBetter

### 实现方案（可选）

BetterAndBetter

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
当前只专注 macOS，其他跨平台建议使用其他软件，例如 [pot-desktop](https://github.com/pot-app/pot-desktop) 。
