### ISSUE TITLE
🚀 功能建议：建议开放配置文件可视化

### ISSUE THREAD

**Issue by CY-Christin** [tisfeng/Easydict#278]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

目前的几个可配置选项只能在 readme 中查看对应的 key 进行配置，希望可以开放完整的配置文件，方便查看对应的 key 和修改 value。而且对于 openai 这种可以预设提示词的也可以自己输入提示词达到不同的效果（例如实现直译和意译）。

### 使用场景（可选）

可以直接在软件内修改对应设置，无需打开 readme 查看对应的值

### 实现方案（可选）

可以在设置中内置可查看窗口或者像 vscode 一样可以直接编辑配置文件，在最后加上一个像 nginx 的配置文件合法检测，方便及时发现问题并修正。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
在做了在做了 https://github.com/tisfeng/Easydict/issues/227#issuecomment-1849027631 ，催一下 @Kyle-Ye

**Comment by tisfeng** [comment]
目前服务 API key 基本都支持界面配置了，就关闭了。
