### ISSUE TITLE
🐞 反馈问题：选中一段文字时，移动鼠标到Easydist弹出的小图标上面时，翻译窗口自动打开了

### ISSUE THREAD

**Issue by alexya** [tisfeng/Easydict#279]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 问题描述

选中一段文字时，移动鼠标到Easydist的小图标上面时，翻译窗口自动打开了。以前的版本，是需要“点击”才会弹出翻译窗口的。

### 重现步骤

- 在浏览器里面，比如Chrome，选择任意 字符串
- 会自动出现一个 Easydict的小图标
- 移动鼠标到小图标上面
- Easydict的翻译窗口自动打开了

### 截图

N/A

### 期望结果

希望能够移动鼠标到Easydict弹出的小图标上面时，能够通过“点击”打开翻译窗口。至少，提供一个设置选择。
在设置里面，找了半天，没有找到。

### 设备型号 && 系统版本

Apple M3 Pro, 14.2.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by alexya** [comment]
刚发完帖子，就找到那个选项了。
`Click to query`

**Comment by AkaShark** [comment]
> 有没有办法关闭呢？没找到设置...

![CleanShot 2024-01-02 at 18 01 25@2x](https://github.com/tisfeng/Easydict/assets/26460192/72d34eb2-759c-46f7-8aa7-a019b491b8b2)
是说的滑词展示小图标么
