### ISSUE TITLE
【Swift 重构】使用 Swift 重写 EZConfiguration

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#284]
参见  https://github.com/tisfeng/Easydict/pull/283#issuecomment-1872201448

**Comment by NeverAgain11** [comment]
我可以，不过最近有点事，可能会慢点。

**Comment by tisfeng** [comment]
ok

**Comment by tisfeng** [comment]
你好，这个 PR https://github.com/tisfeng/Easydict/pull/323 计划引入第三方库 [Defaults](https://github.com/sindresorhus/Defaults) 来管理保存设置项，EZConfiguration 可能也需要作出一些修改，你看一下有没有什么问题。

**Comment by NeverAgain11** [comment]
没啥问题，EZConfiguration 里面有很多 log 打印，还需要吗

**Comment by tisfeng** [comment]
和之前保持一致就行，有时候会需要一些统计信息，例如用户的偏好语言，如果使用某个语言的用户人数较多，我们的代码可以考虑针对这个语言优化一下，以及提供本地化语言支持等。

**Comment by tisfeng** [comment]
这个 PR https://github.com/tisfeng/Easydict/pull/323 我已经合并了，你可能需要实现观察各个 key 的改变 https://github.com/sindresorhus/Defaults?tab=readme-ov-file#observe-changes-to-a-key ，确保修改 key 值后会执行对应的事件。
