### ISSUE TITLE
【Swift 重构】用 Swift/SwiftUI 重写设置页

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#285]
## 起因

目前项目中支持的需要 API key 的服务越来越多，而使用 URL Scheme 命令方式配置 key 很不方便 #227 #278 ，因此决定重写设置页，以提供更便捷的 UI 方式来配置 key。

## 现状

目前最新 dev 分支 debug 环境下有个【SwiftUl App 模式启动】选项 https://github.com/tisfeng/Easydict/pull/212 ，开启后菜单项和设置页会使用新的 SwiftUl 实现显示，但这部分功能还不完整。

## 计划

接下来我计划使用 Swift/SwiftUI 重写整个设置页，补全目前缺失的功能。

这里拆分一下 issue，大家可以先挑选自己感兴趣和擅长的功能来做，剩下的我视情况分配。

- [x] #284
- [x] #286 
- [x] #287
- [x] #288 
- [x] #289 
- [x] #290 
- [x] #324 
- [x] #352

<img width="536" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/7c76dc22-b9e8-43e6-b4cc-ed4c68de0c00">

**Comment by liyafly** [comment]
hello 有人认领吗？ 我有兴趣，熟悉swift，SwiftUI还在学习，怎么认领呢，想从简单的入手。

**Comment by tisfeng** [comment]
欢迎，你可以试试 https://github.com/tisfeng/Easydict/issues/286 和 https://github.com/tisfeng/Easydict/issues/287 ，可以先把界面架子搭起来，有些涉及其他复杂的功能先放一边，慢慢完善。

**Comment by liyafly** [comment]
> 欢迎，你可以试试 #286 和 #287 ，可以先把界面架子搭起来，有些涉及其他复杂的功能先放一边，慢慢完善。

好的，谢谢。我先试试，目前也只能在工作之余做一些，有人做了就可以先PR。

**Comment by tisfeng** [comment]
Almost done, so closed.
