### ISSUE TITLE
【Swift 重构】SwiftUI 补全设置-通用

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#287]
<img width="536" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/ff8166fb-e479-405f-92d8-4fc36e184917">

<img width="617" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/d50650ee-77f9-47c7-b8e6-3104dac07b19">

**Comment by CanglongCl** [comment]
closed with #323 
for shortcuts, track in #290
