### ISSUE TITLE
【Swift 重构】SwiftUI 添加设置-禁止名单

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#289]
<img width="486" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/043fafec-110c-45a1-bb15-54edea4bac80">

**Comment by tisfeng** [comment]
这个页面，谁有兴趣写一下吗？

**Comment by tisfeng** [comment]
@phlpsong 你有空可以做一下吗

**Comment by phlpsong** [comment]
Sure, I can take this.
