### ISSUE TITLE
【Swift 重构】使用新的 Swift 快捷键第三方库替换 MASShortcut

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#290]
目前项目中快捷键第三方库使用的是 objc 写的 [MASShortcut](https://github.com/cocoabits/MASShortcut) ，这个库已经停止维护了， 并且不支持 double tap #220 。

虽然有小伙伴通过修改源码的方式支持了 double tap  #277 ，但这终结不是长远之计，因此后面还是希望使用新的 Swift  快捷键第三方库替换 [MASShortcut](https://github.com/cocoabits/MASShortcut)。

**Comment by tisfeng** [comment]
@AkaShark 你可以负责替换这个吗？

**Comment by AkaShark** [comment]
okay 话说有推荐的较为成熟的Swift的快捷键的库不，没有的话我明天的呀

**Comment by tisfeng** [comment]
我对 Swift 第三方库不太了解， [KeyHolder](https://github.com/Clipy/KeyHolder) 这个看起来好像还不错，或许可以尝试一下。

<img width="836" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/2da2cf17-7f5d-4bcc-be78-ed2db39cf466">

**Comment by AkaShark** [comment]
我是刚接触Swift😂，可以明天我研究下的~

**Comment by tisfeng** [comment]
[KeyHolder](https://github.com/Clipy/KeyHolder) 如果没问题，你可以在新的设置页 GeneralTab 里面用 SwiftUI 方式添加这些快捷键。

<img width="617" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/af62239f-b255-45f5-87a8-215285e87ebb">

**Comment by AkaShark** [comment]
okay

**Comment by liyafly** [comment]
hi 老兄，我刚查到 [KeyboardShortcuts](https://github.com/sindresorhus/KeyboardShortcuts) 这个库 看着还不错 你可以试一下。如果有困难，我愿意和您一起补齐这个功能。

**Comment by AkaShark** [comment]
> hi 老兄，我刚查到 [KeyboardShortcuts](https://github.com/sindresorhus/KeyboardShortcuts) 这个库 看着还不错 你可以试一下。如果有困难，我愿意和您一起补齐这个功能。

Thanks for your suggestion, but I‘m using [KeyHolder](https://github.com/Clipy/KeyHolder) to replace the shortcut.

**Comment by tisfeng** [comment]
设置和菜单界面部分已经完成，你后面只要把快捷键添加上去就可以。

**Comment by AkaShark** [comment]
okay, I've been busy lately, I will finish this in the next week

**Comment by tisfeng** [comment]
👌

**Comment by donfishman** [comment]
Swift快捷键的库有[KeyboardShortcuts](https://github.com/sindresorhus/KeyboardShortcuts)，还有一个HotKey,也不错
