### ISSUE TITLE
pod install 出现警告

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#292]
> [DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".

<img width="1009" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/e4c7d436-4a11-4362-8274-888955aba3f5">

**Comment by tisfeng** [comment]
看了一下，Gemfile 格式有点问题，这是目前项目中 Gemfile


```
source 'https://rubygems.org' do
  gem 'cocoapods', '1.14.2'
end

```

这是官方文档  https://guides.cocoapods.org/using/a-gemfile.html

```shell
source 'https://rubygems.org'

gem 'cocoapods'
gem 'cocoapods-keys'

gem 'fui', '~> 0.3.0'
gem 'xcpretty'
gem 'second_curtain', '~> 0.2.3'
gem 'fastlane'
```

**Comment by AkaShark** [comment]
okay 这个我稍后改下的
