### ISSUE TITLE
🐞 Bug Report: The shortcut keys in the popup menu item are misaligned.

### ISSUE THREAD

**Issue by phlpsong** [tisfeng/Easydict#298]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)

### Problem description

The shortcut keys like `⌘Q` in the popup menu item are misaligned.

### Reproduction steps

Open the status bar icon, and check the menu item.

### Screenshot

<img width="258" alt="Screenshot 2024-01-03 at 15 15 18" src="https://github.com/tisfeng/Easydict/assets/103433299/f086c168-9626-4471-95b9-968de7c3fb52">

### Expected result

Aligned well

### Device type and OS version

MacOS 14.2.1, Easydict 2.4.1

### Are you willing to submit a PR to fix this issue?

- [X] I'm willing to submit a PR

**Comment by tisfeng** [comment]
看了，但没看懂，⌘Q 快捷键有问题？

**Comment by phlpsong** [comment]
<img width="312" alt="截屏2024-01-03 20 29 29" src="https://github.com/tisfeng/Easydict/assets/103433299/26ff123d-2c28-4fe9-87dd-ef4cee253cb4">

As you can see in the screenshot, `⌘` and `Q` are not aligned vertically right.  Other shortcut keys are the same.

**Comment by tisfeng** [comment]
我是真没看懂哪个地方有问题 😓  

⌘ 和 Q 也没有要垂直右对齐，最主要的是，这里并没有自定义布局，而是用的系统的 NSMenuItem，快捷键也就设置了一下 keyEquivalent 

<img width="1026" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/7eb471fd-f10a-4af7-941e-f570002b1430">

**Comment by phlpsong** [comment]
The menu item in the storyboard is fine.  You can check and compare the screenshot in ReadMe with the current appearance.

It's a side effect of the function `increaseMenuItemHeight`  in `EZMenuItemManager`.

**Comment by phlpsong** [comment]
I tried to use another workaround in `increaseMenuItemHeight`, which could fix this issue.

After change:

<img width="192" alt="截屏2024-01-03 20 57 28" src="https://github.com/tisfeng/Easydict/assets/103433299/c2925652-e4d0-47bc-8bc5-61077f37402a">

**Comment by tisfeng** [comment]
明白了，这里确实有问题，可能是看习惯，一下都没注意到快捷键 ⌘ 和 Q  顶部居然没对齐 😢

可以的，那你修复一下吧。

<img width="234" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/fdd55fb3-0f12-4df3-9a09-536838ded974">

<img width="236" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/98c61203-64ee-4533-846e-aa1b76c72cb1">

**Comment by phlpsong** [comment]
OK, got it.

**Comment by tisfeng** [comment]
[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本已修复该问题。
