### ISSUE TITLE
希望能添加个自定义开关，关掉右上角的图标网页搜索

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#3]
## 功能描述

希望能提供一个选项关掉这个图标，这个Safari图标有点逼死强迫症，跟系统的Safari长得不太一样，而且点进去会跳转到默认浏览器（但这个默认浏览器并不是Safari而是Chrome）就很难受。这个功能一般也不太会用到，希望能提供个按钮关掉它。
<img width="436" alt="image" src="https://user-images.githubusercontent.com/51783873/214082900-7d500cf9-bdde-4ead-b38c-2a142829606a.png">

**Comment by tisfeng** [comment]
感谢反馈，其实本意我是想弄个表达【在浏览器中打开谷歌搜索】的 icon，但由于自己不会 UI 设计，就挑选了一个表示浏览器的 Safari 图标，又因为当前系统的 Safari 图标留白了很多，会和 Easydict 的白色背景重叠，所以就用了旧版 Safari。。那我还是改成 Google 图标吧。

在我的设计中，右上角以后可以显示许多类似快捷小功能的图标，参考 Raycast 的 [quicklinks](https://manual.raycast.com/quicklinks)，这些功能支持用户自定义 URL 和 icon，当然也包括关闭开启等。这个具体还需要构思一下。

关于这个，稍后我先会简单提供一个开关设置。

**Comment by Alphabet1226** [comment]
原来如此，感谢你解释这些开发背后的思考和故事，很有意思！

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已支持关闭快捷功能图标。
