### ISSUE TITLE
反馈问题：多显示器，窗口有时候会跳到第一个显示器而不是当前聚焦的显示器

### ISSUE THREAD

**Issue by takeeasyman** [tisfeng/Easydict#30]
## 描述问题
电脑有外接显示器的时候，窗口有时候会显示在排序第一的显示器上

## 运行环境

- Device: MacBook Pro
- macOS: 13.2.1 (22D68)
- Easydict Version: 1.2.3

**Comment by tisfeng** [comment]
感谢反馈！还真没发现这个问题，稍后我去查一下资料看看。

但，我没有外接显示器，没办法复现问题，也无法进行测试，这可咋办 😧

**Comment by tisfeng** [comment]
你好，请问你的窗口位置是屏幕右侧吗，你试一下上次位置，看有没有问题。

<img width="611" alt="image" src="https://user-images.githubusercontent.com/25194972/224530114-588c4ed6-49ef-443f-95f4-da89d0542627.png">

**Comment by takeeasyman** [comment]
感谢回复。
我是选了”上次位置“，而且发现输入过程也会跳。但是如果我点击左上角按钮固定，输入过程就不会跳。

**Comment by tisfeng** [comment]
你好，请问 “鼠标位置” 会有问题吗？ 另外，我不太明白这个跳具体是什么表现，可以麻烦录个视频看看吗

**Comment by takeeasyman** [comment]
Hi，

我试了“鼠标位置”，看上去这种设置下窗口不会乱跳了。

选择”上次位置“时窗口跳动，请看录屏，录屏中我把窗口拖到另外一个显示器，输入单词回车之后窗口就跳回第一个显示器了。

上边提到的”输入过程也会乱跳“，在录屏的时候又不会出现了 🤣 

https://user-images.githubusercontent.com/3069003/225219524-30fbd77c-32f2-4b4d-b1bd-982b8d87e005.mp4

**Comment by tisfeng** [comment]
好的，感谢反馈，稍后我查一下代码。

**Comment by JK-Wang** [comment]
我遇到了类似的bug。使用外接扩展屏，选择“鼠标位置”的时候，在主屏幕显示正常，在外界屏会有一定弹窗位置会有一定程度的偏移。如图，横向坐标正确，纵向无论在什么位置选词，窗口都会出现在扩展屏的下边缘处（屏幕位置关系是主屏幕在扩展屏下方）。
<img width="801" alt="image" src="https://user-images.githubusercontent.com/32212764/232405359-0f607242-8db9-40dd-a966-48b91adb46b5.png">

**Comment by tisfeng** [comment]
收到，这应该是计算位置只考虑了主屏幕，，扩展屏这个，我想一下。

**Comment by JK-Wang** [comment]
初步定位了一下，https://github.com/tisfeng/Easydict/blob/15eac09113e7a6cda3c31f24bd73d8d9409eb113/Easydict/Feature/ViewController/Window/WindowManager/EZWindowManager.m#L309
看起来像是这个函数返回光标值没有用到第一行 screen 的结果。
<img width="752" alt="image" src="https://user-images.githubusercontent.com/32212764/233827522-bb83de8a-9e25-4b52-9def-91d236086c60.png">

我没写过 OC，你如果有空改的话可以参考下 GPT 的样例～
<img width="843" alt="image" src="https://user-images.githubusercontent.com/32212764/233827535-5b1dca9d-b806-4c78-81df-0ccc2a1576eb.png">

**Comment by JK-Wang** [comment]
BTW，如果有易懂的项目搭建调试文档，我也很乐意来提交 PR～

**Comment by tisfeng** [comment]
感谢反馈～

我发现 iPad 可以当作外接显示屏，正在调试优化中，下个版本会修复。

我刚更新了文档， 增加了[开发者构建](https://github.com/tisfeng/Easydict/blob/dev/README.md#%E5%BC%80%E5%8F%91%E8%80%85%E6%9E%84%E5%BB%BA) 描述，另外最新的 [dev](https://github.com/tisfeng/Easydict/tree/dev) 分支初步修复了这个问题，可能稍后还需要优化一下，你可以先试试 🙂
