### ISSUE TITLE
🚀 功能建议：增加输入翻译重新打开窗口时自动全选功能

### ISSUE THREAD

**Issue by kongzue** [tisfeng/Easydict#300]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

使用输入翻译翻译了一些内容之后，下次启动输入翻译时建议可以自动全选输入框中的内容，或者添加相应的设置开关。
既避免了读取剪贴板的困扰，也避免了因为直接从剪贴板粘贴导致上次的翻译结果丢失的困扰。
自动选中可以交由用户自行选择是否使用 Command+V 粘贴还是查看上次的翻译结果。

### 使用场景（可选）

我习惯使用 Option+A 启动输入翻译，在翻译后偶尔也会有重新启动小窗口临时查看翻译结果的需求。
但有时候则需要翻译新的内容，此时必须通过 Command+A 全选输入框的内容亦或者通过鼠标选择全部内容删除再输入新的内容，有些繁琐，如果能提供默认全选的操作会方便很多。

### 实现方案（可选）

在使用输入翻译翻译了一些内容之后，下次启动输入翻译时建议可以自动全选输入框中的内容，或者添加相应的设置开关。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by Jerry23011** [comment]
> 此时必须通过 Command+A 全选输入框的内容亦或者通过鼠标选择全部内容删除再输入新的内容

这里可以在 ⌥A 打开窗口后使用快捷键 ⌘⇧K 清除所有内容

**Comment by kongzue** [comment]
@Jerry23011 会很麻烦，如果能默认全选输入框的内容会方便很多

**Comment by Jerry23011** [comment]
我来演示一下，其实和默认全选输入框的内容的按键盘次数是一样的，都是两次

https://github.com/tisfeng/Easydict/assets/89069957/25004925-895d-4e6e-8703-462c7b0f5696

**Comment by kongzue** [comment]
不不不我的意思是当重新打开界面时自动默认选中输入框的内容，不是需要通过键盘来选中
________________________________
发件人: Jerry Zhang ***@***.***>
发送时间: Thursday, January 4, 2024 2:53:18 PM
收件人: tisfeng/Easydict ***@***.***>
抄送: Kongzue ***@***.***>; Author ***@***.***>
主题: Re: [tisfeng/Easydict] 🚀 功能建议：增加输入翻译重新打开窗口时自动全选功能 (Issue #300)


我来演示一下，其实和默认全选输入框的内容的按键盘次数是一样的，都是两次

https://github.com/tisfeng/Easydict/assets/89069957/25004925-895d-4e6e-8703-462c7b0f5696

**Comment by kongzue** [comment]
我感觉你没有仔细看我提问的意思，我的意思是如果可以默认全选输入框的内容，那么用户如果要翻译新的内容直接按粘贴键即可，如果不需要而是仅需要查看之前翻译的内容直接看即可，这样省一步操作而已
________________________________
发件人: Jerry Zhang ***@***.***>
发送时间: Thursday, January 4, 2024 2:57:11 PM
收件人: tisfeng/Easydict ***@***.***>
抄送: Kongzue ***@***.***>; Author ***@***.***>
主题: Re: [tisfeng/Easydict] 🚀 功能建议：增加输入翻译重新打开窗口时自动全选功能 (Issue #300)


请问默认全选的下一步操作是清除内容吗？还是直接开始输入新的内容呢？

**Comment by tisfeng** [comment]
看明白了，但是我对这个功能使用场景存疑，可能不是那么必要。设置页目前选项已经很多了，一些不必要的设置项暂时不会添加了。

**Comment by tisfeng** [comment]
你好，在这个 PR https://github.com/tisfeng/Easydict/pull/375#discussion_r1472243738 中添加了一个自动选中查询文本选项，将会在下个版本上线，感谢你的建议。

**Comment by kongzue** [comment]
好的非常感谢，辛苦了
________________________________
发件人: Tisfeng ***@***.***>
发送时间: Sunday, February 4, 2024 11:57:02 AM
收件人: tisfeng/Easydict ***@***.***>
抄送: Kongzue ***@***.***>; Author ***@***.***>
主题: Re: [tisfeng/Easydict] 🚀 功能建议：增加输入翻译重新打开窗口时自动全选功能 (Issue #300)


你好，在这个 PR #375 (comment)<https://github.com/tisfeng/Easydict/pull/375#discussion_r1472243738> 中添加了一个自动选中查询文本选项，将会在下个版本上线，感谢你的建议。

**Comment by tisfeng** [comment]
[2.6.0](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 新版本已提供设置项。
