### ISSUE TITLE
🚀 功能建议：

### ISSUE THREAD

**Issue by virologist** [tisfeng/Easydict#301]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

建议在翻译选中文字前增加一个段落内容自动整理的步骤；
<img width="579" alt="image" src="https://github.com/tisfeng/Easydict/assets/54756814/fba824d4-cf91-4945-961e-d71e5d61f183">

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
是这个意思吗 https://github.com/tisfeng/Easydict/issues/86

**Comment by virologist** [comment]
是的

**Comment by tisfeng** [comment]
等重写完设置页后，再做这个。
