### ISSUE TITLE
🐞 Bug Report: mini query window not fully display placeholder text

### ISSUE THREAD

**Issue by phlpsong** [tisfeng/Easydict#302]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)

### Problem description

placeholder text is not fully displayed in the mini window

mini: 
<img width="298" alt="Screenshot 2024-01-04 at 12 49 43" src="https://github.com/tisfeng/Easydict/assets/103433299/d54287e7-1b58-4807-bfea-6c6246a76610">

### Reproduction steps

Status bar menu icon, select `Show Mini Window` in pop menu

### Screenshot

<img width="300" alt="Screenshot 2024-01-04 at 12 49 52" src="https://github.com/tisfeng/Easydict/assets/103433299/3895dc45-70f5-42b9-85e5-a5a49d6495f6">

### Expected result

Show fully placeholder text

### Proposed solution (optional)

increase the window width or text view lines.

### Device type and OS version

MacOS 14.2.1, Easydict 2.4.1

### Are you willing to submit a PR to fix this issue?

- [X] I'm willing to submit a PR

**Comment by tisfeng** [comment]
行，那还是增加 mini 输入框高度，显示2行吧。
