### ISSUE TITLE
🚀 功能建议：有没有可能支持Android系统或做成浏览器插件？

### ISSUE THREAD

**Issue by funnybones2015** [tisfeng/Easydict#304]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

Easydict功能强大而丰富，要是能支持安卓系统就好了。

### 使用场景

在Android系统中使用

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
不会安卓，JS 也不太会，目前只会专注 macOS。

**Comment by funnybones2015** [comment]
> 不会安卓，JS 也不太会，目前只会专注 macOS。

ok，没关系，谢谢回复。
