### ISSUE TITLE
🐞 Bug Report: App language does not change after update language orders in system settings

### ISSUE THREAD

**Issue by phlpsong** [tisfeng/Easydict#305]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

App language does not change after updating language orders in system settings.

You can check the screenshot attached below. 
After changing preferred languages to (1. 简体中文 2. English) in System Settings, the result from `[[NSUserDefaults standardUserDefaults] objectForKey:@"AppleLanguages"]`  in app is 
```
[
  "en-CN",
  "zh-Hans-CN"
]
```
but in the terminal the result is 
```
(
    "zh-Hans-CN",
    "en-CN"
)
```

### Reproduction steps

1. Go to System Settings -> General -> Languages and regions -> Preferred Languages 
2. Update language order, like swap English and 简体中文
3. Rebot(Optional) and relaunch app
4. Check app language

### Screenshot

<img width="1155" alt="截屏2024-01-05 11 24 52" src="https://github.com/tisfeng/Easydict/assets/103433299/60ddd9a7-aaed-44cd-bf07-e9aec3b404db">

### Expected result

App language follows system settings

### Device type and OS version

MacOS 14.2.1, Easydict 2.5.0

### Are you willing to submit a PR to fix this issue?

- [X] I'm willing to submit a PR

**Comment by phlpsong** [comment]
I found `AppleLanguages` values are not updated after the system languages change.

I found a similar issue in https://stackoverflow.com/questions/24841113/override-applelanguages-in-nsuserdefaults , 

```
if I insert a new object at index 0 and later on change the system language, iOS will not put the new language on the top of the list anymore. 
```

which is pretty like what we do in `AppDelegate`. 

@tisfeng appreciate it if you could confirm it.

**Comment by tisfeng** [comment]
使用 [[NSUserDefaults standardUserDefaults] objectForKey:@"AppleLanguages"] 方式获取系统语言并不好，遇到特殊语言，如 Canadian English 会导致语言解析有问题。后面我改成了 [NSLocale preferredLanguages]

>  !!!: For Canadian English, AppleLanguages returns "en_CA", while [NSLocale preferredLanguages] returns "en-CA"


另外，一般我们也没必要修改 AppleLanguages，之前我修改这个值是为了测试，后面忘记移除了。

具体你可以看 localization  分支的这个提交 e8923f0ab00421efc9d1f4d680578a2f581b81ed

**Comment by phlpsong** [comment]
Yes, I think the `AppleLanguages` result combines the language and region, such as `en_CN`, and currently we using `en_CN` and `zh-CN` to update its values in `AppDelegate` is not accurate if users are in other regions.


> 另外，一般我们也没必要修改 AppleLanguages，之前我修改这个值是为了测试，后面忘记移除了。

Yeah, we should not update this. After removing `setupAppLanguage` the behavior is fine.

Do you have a plan to merge the commit into dev or apply a new commit to fix this?

**Comment by tisfeng** [comment]
你测一下看这个提交 https://github.com/tisfeng/Easydict/commit/e8923f0ab00421efc9d1f4d680578a2f581b81ed 会有你说的问题吗？  如果没问题，稍后我就把它 pick 过来。

**Comment by phlpsong** [comment]
I tested but it's not working as expected. 

I think the reason is the app has changed the `AppleLanguages` values which will prevent it refresh after system changes.

A workaround is to reset this value when `EZLanguageManager` setup.

**Comment by tisfeng** [comment]
行，那麻烦你修复一下这个问题，可以把 https://github.com/tisfeng/Easydict/commit/e8923f0ab00421efc9d1f4d680578a2f581b81ed pick 过去，弄个新 PR。

**Comment by phlpsong** [comment]
Sure, will create one later.

**Comment by tisfeng** [comment]
[2.6.0](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 新版本已修复该问题。
