### ISSUE TITLE
功能建议：界面上的文字支持自由复制

### ISSUE THREAD

**Issue by takeeasyman** [tisfeng/Easydict#31]
## 功能描述
界面上的文字支持自由复制

## 使用场景（可选）
有时候查完词，想把内容复制下来保存到笔记本，所以希望可以复制音标、释义，或者直接全选复制

BTW, 非常棒的 app 👍🏻

**Comment by tisfeng** [comment]
感谢反馈，之前本来设计是都可以复制的，但后面遇到一个问题，不确定是不是系统 bug，就暂停了，稍后我再去研究一下。

**Comment by tisfeng** [comment]
你好，新版本已支持选中复制 https://github.com/tisfeng/Easydict/releases/tag/1.3.1

**Comment by takeeasyman** [comment]
赞👍，感谢
