### ISSUE TITLE
【UI/UX】改进翻译服务图标设计

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#310]
目前翻译服务逐渐增多，但是图标设计不是很协调，可以规范翻译图标的设计标准（圆角/解析度，等等）

这样有助于减小 app 的包体积，并给用户一个协调的体验

**Comment by tisfeng** [comment]
确实，项目中的图片是可以整理一下，目前很多图片是从网上找的，有些图片没用到也没有及时删除。

这个 issue 需要一个人来负责推进，我不会切图，对设计也不懂 🥲

**Comment by Jerry23011** [comment]
我会一些基础的，这个我可以来

**Comment by tisfeng** [comment]
目前项目中不少地方都使用了系统图片，之前为了支持 SF 图片，就将最低 target 设置为 macOS 11.0+，以为 SF 图片就一种，所以有些地方的代码会有问题，例如这里 https://github.com/tisfeng/Easydict/pull/212#discussion_r1437951644 ，这个我刚才修复了 70466d8a ，后面大家也注意一下。

>  SF 图片分为
>
> SF 1.0 (macOS 10.15+)
> SF 2.0 (macOS 11+)
> SF 3.0 (macOS 12+)

![image](https://github.com/tisfeng/Easydict/assets/25194972/b36d1937-5ad2-4996-8136-60e0f466b2a4)
