### ISSUE TITLE
🚀 功能建议：添加代理配置

### ISSUE THREAD

**Issue by KamToHung** [tisfeng/Easydict#313]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

添加代理配置，使用google可以走指定代理端口

### 使用场景

google翻译代理

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
参考 https://github.com/tisfeng/Easydict/issues/18#issuecomment-1445039337 ，这种网络代理问题，我更倾向使用专门的软件来处理。

**Comment by KamToHung** [comment]
> 参考 [#18 (comment)](https://github.com/tisfeng/Easydict/issues/18#issuecomment-1445039337) ，这种网络代理问题，我更倾向使用专门的软件来处理。

遇到一种情况是连接其他vpn（比如公司等）后代理软件没法全局代理。不过也可以使用别的翻译，感谢作者和committer的付出
