### ISSUE TITLE
🚀 功能建议：建议增加隐藏原文功能？

### ISSUE THREAD

**Issue by jiangaq** [tisfeng/Easydict#317]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

就是只显示译文，隐藏原文

### 使用场景

。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
这个可以，目前正在重构代码，后面会考虑加。

**Comment by tisfeng** [comment]
这里代码耦合太多，可能不太好改，稍后我看一下。

如果你不需要显示翻译原文，可以先用迷你窗口，这个窗口高度是一个较小的固定值。

**Comment by jiangaq** [comment]
最好像bob那样，可以折叠原文就好了

**Comment by tisfeng** [comment]
ok，这个功能会有的。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。
