### ISSUE TITLE
🚀 功能建议：增加“bob”的替换原文功能

### ISSUE THREAD

**Issue by mining-id** [tisfeng/Easydict#319]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

<img width="465" alt="image" src="https://github.com/tisfeng/Easydict/assets/94845005/60142393-9b13-47f8-b5c5-a79ee251c00e">

### 使用场景

1. 写邮件的时候，一般先写中文，然后翻译成英文，有了这个功能，可以一键替换
2. 引用英文的笔记时，需要备注下对应的翻译，有了这个功能，可以一键添加

### 实现方案（可选）

对于上述场景，有两种模式：
1. 替换模式，直接替换选中的内容
2. 追加模式，在选中内容的后面追加翻译的内容

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
使用译文替换功能已经有了

<img width="823" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/95358691-9068-44ae-9c36-e2891d3bc583">

**Comment by tisfeng** [comment]
追加模式，这个需求不是那么普遍，暂时不会加。

**Comment by mining-id** [comment]
@tisfeng 抱歉，我发帖前有升级到最新版，且仔细查看了设置，没有看到这个选项。所以才提issue
即使在你截图之后，我也没找到开启项。请问要如何开启呢？
![image](https://github.com/tisfeng/Easydict/assets/94845005/ccff1164-1137-4a8c-b86d-4309af8f2a74)
![image](https://github.com/tisfeng/Easydict/assets/94845005/df4035dd-56c0-4d1d-930a-139cbb136074)

**Comment by tisfeng** [comment]
这个不用手动开启，当选中的文本是可编辑状态时，触发划词翻译后会自动显示这个替换按钮。

**Comment by mining-id** [comment]
@tisfeng 试过，还是不行哦，是不是我的系统问题呢？
<img width="703" alt="image" src="https://github.com/tisfeng/Easydict/assets/94845005/e20ca7f7-b538-411d-b852-772907c5263c">

<img width="206" alt="image" src="https://github.com/tisfeng/Easydict/assets/94845005/d89e3b56-4d67-4a95-8443-161936812b10">

**Comment by mining-id** [comment]
@tisfeng  我知道问题了
我是通过popclip触发的翻译，这个时候没有
我试了划词翻译就显示了。

希望可以增加对popclip的支持，感谢！

**Comment by tisfeng** [comment]
最新版本已经支持 PopClip 使用译文替换了。

如果不行，请尝试使用最新的 PopClip 脚本 https://github.com/tisfeng/Easydict?tab=readme-ov-file#%E9%85%8D%E5%90%88-popclip-%E4%BD%BF%E7%94%A8


https://github.com/tisfeng/Easydict/assets/25194972/59ec7eb5-de43-4793-8e6b-44a74795d1fc

**Comment by mining-id** [comment]
@tisfeng  可以了！感谢大佬！Very easy to use

**Comment by Tespera** [comment]
是最新版本 v2.5.0，划词中文或输入中文后都不进行中译英，请问这个要怎么设置呀？
<img width="1093" alt="image" src="https://github.com/tisfeng/Easydict/assets/27461964/fa35a4bc-cb04-4b5e-b8fe-6052c4131a27">

**Comment by tisfeng** [comment]
新版本没有改动相关代码，我刚也测试过，这个功能没有问题。

请检查你自己的设备环境问题。

**Comment by tisfeng** [comment]
> 是最新版本 v2.5.0，划词中文或输入中文后都不进行中译英，请问这个要怎么设置呀？

你好，之前没注意到你的反馈，请问这个问题还存在吗？是否可以复现？

**Comment by tisfeng** [comment]
了解了，这个确实是升级导致的问题 https://github.com/tisfeng/Easydict/releases ，之前的辅助功能失效，所以【替换】按钮没有显示。

重新授权后应该就没问题，后续应用更新不再会导致权限失效了。
