### ISSUE TITLE
🐞 Bug Report: 菜单栏打开设置时，程序自动退出

### ISSUE THREAD

**Issue by coder-xiaohuangyu** [tisfeng/Easydict#320]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

菜单栏右键点击easydict图标后，点击设置，程序自动退出
crash 目录有报错日志
1. 尝试过
brew uninstall easydict 
brew install --cask easydict
卸载重装之后仍然报错
2. 重启后卸载重装依然报错，以下是crash 日志

========uncaughtException异常错误报告========
name:NSInvalidArgumentException
reason:
*** -[NSBundle initWithURL:]: nil URL argument
callStackSymbols:
0   CoreFoundation                      0x00000001aac6f154 __exceptionPreprocess + 176
1   libobjc.A.dylib                     0x00000001aa78e4d4 objc_exception_throw + 60
2   Foundation                          0x00000001abb93a54 -[NSVariableExpression isEqual:] + 0
3   Easydict                            0x00000001002bd2e4 Easydict + 217828
4   Easydict                            0x00000001002ba1f0 Easydict + 205296
5   AppKit                              0x00000001adf51908 -[NSTableView(NSTableViewViewBased) _delegate_viewForTableColumn:row:] + 92
6   AppKit                              0x00000001adeaac44 -[NSTableView(NSTableViewViewBased) makeViewForTableColumn:row:] + 88
7   AppKit                              0x00000001adeaa3f0 -[NSTableRowData _addViewToRowView:atColumn:row:] + 228
8   AppKit                              0x00000001adea7600 -[NSTableRowData _preparedRowViewForRow:storageHandler:] + 788
9   AppKit                              0x00000001adea7240 -[NSTableRowData _addRowViewForVisibleRow:withPriorView:] + 272
10  AppKit                              0x00000001adea705c -[NSTableRowData _addRowViewForVisibleRow:] + 304
11  AppKit                              0x00000001adea6800 -[NSTableRowData _updateVisibleRowEntries] + 664
12  AppKit                              0x00000001adea6334 -[NSTableRowData updateVisibleRowViews] + 572
13  AppKit                              0x00000001adea5aa0 -[NSTableView layout] + 148
14  AppKit                              0x00000001ae5e8014 ___NSViewLayout_block_invoke + 592
15  AppKit                              0x00000001ade5f230 NSPerformVisuallyAtomicChange + 108
16  AppKit                              0x00000001ade643c8 _NSViewLayout + 96
17  AppKit                              0x00000001ae5de8fc __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 364
18  AppKit                              0x00000001ade5f230 NSPerformVisuallyAtomicChange + 108
19  AppKit                              0x00000001ade6435c -[NSView _layoutSubtreeWithOldSize:] + 100
20  AppKit                              0x00000001ae5dea40 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
21  AppKit                              0x00000001ade5f230 NSPerformVisuallyAtomicChange + 108
22  AppKit                              0x00000001ade6435c -[NSView _layoutSubtreeWithOldSize:] + 100
23  AppKit                              0x00000001ae5dea40 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
24  AppKit                              0x00000001ade5f230 NSPerformVisuallyAtomicChange + 108
25  AppKit                              0x00000001ade6435c -[NSView _layoutSubtreeWithOldSize:] + 100
26  AppKit                              0x00000001ae5dea40 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
27  AppKit                              0x00000001ade5f230 NSPerformVisuallyAtomicChange + 108
28  AppKit                              0x00000001ade6435c -[NSView _layoutSubtreeWithOldSize:] + 100
29  AppKit                              0x00000001ae5df400 __56-[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:]_block_invoke + 800
30  AppKit                              0x00000001ade5f230 NSPerformVisuallyAtomicChange + 108
31  AppKit                              0x00000001ade63eac -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 100
32  AppKit                              0x00000001ade5f230 NSPerformVisuallyAtomicChange + 108
33  AppKit                              0x00000001ade63e3c -[NSView layoutSubtreeIfNeeded] + 96
34  AppKit                              0x00000001adead934 -[NSView _setDefaultKeyViewLoop] + 216
35  AppKit                              0x00000001adf1c180 -[NSWindow recalculateKeyViewLoop] + 64
36  MASPreferences                      0x0000000100fa13a4 -[MASPreferencesWindowController setSelectedViewController:] + 1684
37  MASPreferences                      0x0000000100fa02e0 -[MASPreferencesWindowController windowDidLoad] + 532
38  AppKit                              0x00000001adf88d18 -[NSWindowController _windowDidLoad] + 620
39  AppKit                              0x00000001adf8510c -[NSWindowController window] + 84
40  Easydict                            0x0000000100332534 Easydict + 697652
41  Easydict                            0x000000010030e954 Easydict + 551252
42  AppKit                              0x00000001adfc34cc -[NSApplication(NSResponder) sendAction:to:from:] + 440
43  AppKit                              0x00000001ae08f498 -[NSMenuItem _corePerformAction] + 336
44  AppKit                              0x00000001ae08f214 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 104
45  AppKit                              0x00000001ae0caba0 -[NSMenu performActionForItemAtIndex:] + 200
46  AppKit                              0x00000001ae0caac0 -[NSMenu _internalPerformActionForItemAtIndex:] + 76
47  AppKit                              0x00000001ae0ca914 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 108
48  AppKit                              0x00000001ae077828 NSSLMMenuEventHandler + 640
49  HIToolbox                           0x00000001b441f3a4 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1092
50  HIToolbox                           0x00000001b441e828 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 356
51  HIToolbox                           0x00000001b4434a40 SendEventToEventTarget + 40
52  HIToolbox                           0x00000001b44928e4 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 416
53  HIToolbox                           0x00000001b44b6564 SendMenuCommandWithContextAndModifiers + 56
54  HIToolbox                           0x00000001b44b64f4 SendMenuItemSelectedEvent + 352
55  HIToolbox                           0x00000001b44b6320 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 100
56  HIToolbox                           0x00000001b45e7e20 _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1760
57  HIToolbox                           0x00000001b45e7328 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 612
58  HIToolbox                           0x00000001b4499e6c _HandlePopUpMenuSelectionWithDictionary + 380
59  AppKit                              0x00000001ae206fec SLMPerformPopUpCarbonMenu + 1552
60  AppKit                              0x00000001ae202038 _NSSLMPopUpCarbonMenu4 + 908
61  AppKit                              0x00000001ae201c84 -[NSCarbonMenuImpl popUpMenu:atLocation:width:view:selectedItemIndexProvider:font:flags:options:] + 312
62  AppKit                              0x00000001ae0c55f8 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 96
63  AppKit                              0x00000001ae4b2f90 +[NSStatusBarButtonCell popupStatusBarMenu:ofItem:ofBar:inRect:ofView:withEvent:] + 320
64  AppKit                              0x00000001ae4b2444 -[NSStatusBarButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 168
65  AppKit                              0x00000001adfbf408 -[NSControl mouseDown:] + 448
66  AppKit                              0x00000001adfbdef0 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 3476
67  AppKit                              0x00000001adf48b2c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 364
68  AppKit                              0x00000001adf487ec -[NSWindow(NSEventRouting) sendEvent:] + 284
69  AppKit                              0x00000001ae4b455c -[NSStatusBarWindow sendEvent:] + 656
70  AppKit                              0x00000001adf47b30 -[NSApplication(NSEvent) sendEvent:] + 1556
71  AppKit                              0x00000001ae197c48 -[NSApplication _handleEvent:] + 60
72  AppKit                              0x00000001ade0efa0 -[NSApplication run] + 500
73  AppKit                              0x00000001adde63cc NSApplicationMain + 880
74  Easydict                            0x0000000100345f2c Easydict + 778028
75  dyld                                0x00000001aa7bff28 start + 2236

### Reproduction steps

![image](https://github.com/tisfeng/Easydict/assets/21954802/9361fd0f-f578-494a-96fb-fd6465700dbe)

### Screenshot

![image](https://github.com/tisfeng/Easydict/assets/21954802/68090aa7-e5cc-40d4-bcb2-a20dd4b61f28)

### Expected result

期望弹出设置选项进行配置

### Device type and OS version

Apple M1 Pro, macos 13.5

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by tisfeng** [comment]
我看一下。

**Comment by coder-xiaohuangyu** [comment]
> 好像是第三方库 MASPreferences 里面有问题，不确定，我这边无法复现，看不出具体问题 😓
> 
> 你是第一次安装使用吗？尝试过之前的版本吗

之前用的时候没啥问题，刚完全卸载之后换到2.0.4 没问题了，应该是2.0.4之后出现的问题

**Comment by tisfeng** [comment]
2.1.0 有问题吗？ 2.0.4 到 2.1.0 之间只加了一个小牛翻译，没有改其它代码，应该不会有什么问题的。

另外，如果方便的话，你用 Xcode 在本地编译运行看一下，到底哪个地方报错，方便我定位修复问题。

**Comment by coder-xiaohuangyu** [comment]
> 2.1.0 有问题吗？ 2.0.4 到 2.1.0 之间只加了一个小牛翻译，没有改其它代码，应该不会有什么问题的。
> 
> 另外，如果方便的话，你用 Xcode 在本地编译运行看一下，到底哪个地方报错，方便我定位修复问题。

我使用appclearner 卸载了easydict之后，把2.1.0 以及之后的版本全都试了一遍，发现每一个版本都正常工作了，没法复现了，我先关issue了，后续遇到了再说 😂
