### ISSUE TITLE
🚀 功能建议：为驼峰/下划线命名法变量自动分词

### ISSUE THREAD

**Issue by CanglongCl** [tisfeng/Easydict#321]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

之前用Bob有的功能，对驼峰/下划线命名变量自动分词。

例如
`convertToString`翻译时会变为`convert to string`

### 使用场景

之前Bob社区版有这一功能

### 实现方案（可选）

在设置内设置一个相关开关（默认关闭），打开后，如果仅输入单个词，则按大小写/下划线拆分再翻译。

BTW我Swift比较熟，也愿意贡献。但我完全看不懂objc

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
有的 https://github.com/tisfeng/Easydict/issues/135#issuecomment-1753165936 ，开启 Beta 后会自动分词。

暂时没有单独开放这个设置项，等重构完设置页后，会添加这个选项。

<img width="450" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/f155c038-8d0e-4326-9a53-4550526a4d7c">

**Comment by CanglongCl** [comment]
> 如果你会 SwiftUI，可以帮忙写一下设置页 #287 ，顺便可以把这个设置项加上去 😃

其实我之前看了一下设置页，但是因为完全看不懂objc所以放弃了，只要是看不懂怎么取出存起来的选项...

**Comment by tisfeng** [comment]
> 主要是看不懂怎么取出存起来的选项...

你是说，读取之前的设置选项吗？

如果是这个，那比较简单，直接用 `@AppStorage` 就可以，你可以参考项目中已使用 SwiftUI 重写的隐私界面 PrivacyTab.swift

```swift
@AppStorage("EZConfiguration_kAllowCrashLogKey")
    private var allowCollectCrashLog = true
```

https://github.com/tisfeng/Easydict/blob/261b625f3d770365ff1fa0ddabe6a030b0592d08/Easydict/NewApp/View/SettingView/Tabs/PrivacyTab.swift#L25

**Comment by tisfeng** [comment]
其他 objc 代码可以不用去看，只要把 EZConfiguration 中的选项定义看一下就可以

https://github.com/tisfeng/Easydict/blob/261b625f3d770365ff1fa0ddabe6a030b0592d08/Easydict/Feature/Configuration/EZConfiguration.m#L31

**Comment by CanglongCl** [comment]
> 其他 objc 代码可以不用去看，只要把 EZConfiguration 中的选项定义看一下就可以
> 
> https://github.com/tisfeng/Easydict/blob/261b625f3d770365ff1fa0ddabe6a030b0592d08/Easydict/Feature/Configuration/EZConfiguration.m#L31

好的，那我晚些看看，有没有群之类的IM工具？加一下好问问题

**Comment by tisfeng** [comment]
目前还真没有，感觉是可以弄一个开发组群，有时候交流会方便些。

这样吧，你们加我 Telegram: tisfeng，等会我建一个 Group。

**Comment by CanglongCl** [comment]
> 目前还真没有，感觉是可以弄一个开发组群，有时候交流会方便些。
> 
> 这样吧，你们加我 Telegram: tisfeng，等会我建一个 Group，记得备注一下 GitHub 用户名。

我的Telegram账号不知道为何被限制了...你加一下我吧，Lava_C

另外感觉用Discord会更好

**Comment by tisfeng** [comment]
Discord 也行，只是这个我用的少，不太熟，你们加一下我：isfeng

**Comment by tisfeng** [comment]
@CanglongCl  你现在可以在设置中加一下这个选项。

**Comment by tisfeng** [comment]
麻烦有空加一下这个选项。

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。
