### ISSUE TITLE
🚀 功能建议：想沉浸式学习英文阅读,可以是把复杂句编程简单句吗?

### ISSUE THREAD

**Issue by Rice888** [tisfeng/Easydict#325]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

参考:https://read.readwise.io/
invoke ghostreader > simplify  
对于学习英文应该很有帮助?
感谢大佬.
<img width="659" alt="To this end I have included classic picture books and classic" src="https://github.com/tisfeng/Easydict/assets/59442434/c2a6b19b-0845-49e3-9a11-76dc37e386a1">

### 使用场景

沉浸式学习英文.

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
没太懂，你是想要自定义 OpenAI prompt 吗？这个要等 API key 可视化配置完成再说 https://github.com/tisfeng/Easydict/issues/324

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现自定义 Prompt。
