### ISSUE TITLE
🐞 反馈问题：在开启【划词后自动显示查询图标】选项后，后台开着QQ音乐，双击很多地方都会突然导致音乐卡顿

### ISSUE THREAD

**Issue by Kahen** [tisfeng/Easydict#330]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

在开启【划词后自动显示查询图标】选项后，后台开着QQ音乐，双击很多地方都会突然导致音乐卡顿

### 重现步骤

后台播放着QQ音乐，开启Chrome后打开网页，对着网页头双击，有很大几率复现

### 截图

<img width="269" alt="image" src="https://github.com/tisfeng/Easydict/assets/48155854/d81c1878-d752-468e-b049-cdbccfea5c01">
<img width="581" alt="image" src="https://github.com/tisfeng/Easydict/assets/48155854/181f9ae9-86dd-4729-aa4f-dd528183047b">

### 期望结果

解决这类卡顿

### 设备型号 && 系统版本

Apple M2 Pro MacOS 14.2

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
某些应用，或者某些网页不支持鼠标自动取词，可能会导致问题，请问你具体那个网页有问题？

浏览器取词如果有问题，请开启 JaveScript/AppleScript 权限。

**Comment by Maxing1997** [comment]
+1，mac切换屏幕和很多点击都很卡。退出easydict就好了

**Comment by tisfeng** [comment]
参考 https://github.com/tisfeng/Easydict/issues/250#issuecomment-1880041630 ，如果遇到卡顿问题，请尝试在设置中关闭【划词后自动显示查询图标】选项。

**Comment by tisfeng** [comment]
清理 issue，没有后续反馈的就先关闭了，如果再遇到问题，请另外提 issue。
