### ISSUE TITLE
【文档】添加常见问题 FAQ

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#334]
鉴于 https://github.com/tisfeng/Easydict/issues/330 ，https://github.com/tisfeng/Easydict/issues/315 ， https://github.com/tisfeng/Easydict/issues/84 这类问题实在太多了，而目前技术上暂时没办法解决，因此需要一个 FAQ 告知用户，减少这类型的 issue。

FAQ 包括但不限于：

- 某些应用无法使用鼠标划词。
- 某些应用取词为空（空白处拖动等）时会出现提示音。
- 取词为空时可能打断当前播放的音乐。
- 取词需要开启系统权限问题。
- 浏览器取词问题，是否开启 JaveScript/AppleScript 权限。
- 特殊网站的奇葩问题。

**Comment by tisfeng** [comment]
@Jerry23011 帮忙添加完善这个文档，目前已经接收到很多类似的 issue，可以收集整理一下，后面这个 FAQ 我们看是弄个置顶 issue 还是放 README。

**Comment by tisfeng** [comment]
写在 README 吧，方便中英文用户都可以看到，后续我再更新一下 issue 模版，确保用户提 issue 之前阅读 FAQ。

**Comment by tisfeng** [comment]
目前感觉 README 有点太长了，等服务配 API key 界面完成后，可以把相关的命令介绍都去掉，精简一下。

**Comment by Jerry23011** [comment]
> 写在 README 吧，方便中英文用户都可以看到，后续我再更新一下 issue 模版，确保用户提 issue 之前阅读 FAQ。

OK

> 目前感觉 README 有点太长了

我觉得也有点，回头会精简的

**Comment by AkaShark** [comment]
或者其实可以开一个这个仓库的wiki专门放这些东西，然后readme链接过去

**Comment by Jerry23011** [comment]
> 或者其实可以开一个这个仓库的wiki专门放这些东西，然后readme链接过去

这个确实，CC @tisfeng

**Comment by tisfeng** [comment]
也行，只是 wiki 我没怎么用过，你们来弄一下吧。

**Comment by Jerry23011** [comment]
我也没用过，想请教一下@akashark

**Comment by AkaShark** [comment]
好搞，不过我这没权限，@Tisfeng 在setting里面
![CleanShot 2024-01-17 at 11 20 12@2x](https://github.com/tisfeng/Easydict/assets/26460192/5723acd1-69ea-4cad-84fa-865cf736a56b)
打开这个feature就OK了
![CleanShot 2024-01-17 at 11 20 18@2x](https://github.com/tisfeng/Easydict/assets/26460192/9965e44a-6fed-4a24-be37-b294bc142a79)
然后
![CleanShot 2024-01-17 at 11 21 20@2x](https://github.com/tisfeng/Easydict/assets/26460192/eefece9b-1db3-4a30-a43d-0bfbe070933e)
就和我们平时用的云文档大差不差

**Comment by tisfeng** [comment]
开了

<img width="1708" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0728fe97-70d7-4d4b-9845-4c3723591d29">

**Comment by Jerry23011** [comment]
OK 看到了，让我去学习一下其他项目的 wiki 都是怎么写的

**Comment by Jerry23011** [comment]
IINA 这个 wiki 就不错，还支持中/英，放在这里备忘一下
https://github.com/iina/iina/wiki

**Comment by tisfeng** [comment]
@Jerry23011  FAQ 这个麻烦优先加一下，这类问题太多了 https://github.com/tisfeng/Easydict/issues/83#issuecomment-1914022196 ，我们不能在这些 issue 上花时间。

**Comment by Jerry23011** [comment]
好的在 2024年1月29日，05:04，Tisfeng ***@***.***> 写道：﻿
@Jerry23011  FAQ 这个麻烦优先加一下，这类问题太多了 #83 (comment) ，我们不能在这些 issue 上花时间。

**Comment by Jerry23011** [comment]
好的

**Comment by Jerry23011** [comment]
这周事太多，我先写了上面列出的几个，回头再完善其他的

**Comment by tisfeng** [comment]
ok，先把最主要的几个问题加上。

**Comment by tisfeng** [comment]
@Jerry23011 有空可以把 FAQ 添加到 [easydict-docs](https://github.com/tisfeng/easydict-docs) ，等这个文档补全后，我们就把 issue 模版这些链接都切换过去。

**Comment by Jerry23011** [comment]
> @Jerry23011 有空可以把 FAQ 添加到 [easydict-docs](https://github.com/tisfeng/easydict-docs) ，等这个文档补全后，我们就把 issue 模版这些链接都切换过去。

OK
