### ISSUE TITLE
🐞 反馈问题：朗文高级词典界面左侧显示不全

### ISSUE THREAD

**Issue by LuuuuuuHaaaaaaao** [tisfeng/Easydict#339]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

如图, 这个应该是和这个词典本身的排版有关, 有些单词的解释就是会有某行左侧凸出来的情况, 自带词典中显示无误, 但Easydict就显示不全, 不知道是CSS的问题还是Easydict的问题.

### 重现步骤

每次查词均出现

### 截图

![image](https://github.com/tisfeng/Easydict/assets/142016253/16e77021-403c-434d-b3c7-26ab5eee2536)

### 期望结果

修复显示界面

### 设备型号 && 系统版本

Apple m2 air, macOS 14.2.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
这个我知道，这就是朗文词典的 CSS 不规范，它这个播放图标就是贴着最左边。

苹果系统词典显示没问题，那是因为它界面大，布局留了很大的 margin，而 Easydict 本身显示窗口就小，我设置的 margin 是 0 😑

建议自己手动调整一下朗文词典的 CSS。

<img width="456" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/aeb156dc-a894-46fd-a31d-2eb0d553cc0b">

**Comment by tisfeng** [comment]
这个 CSS 我改过好几次，你试一下看行不行，稍后我更新一下词典资源吧。

[DefaultStyle.css.zip](https://github.com/tisfeng/Easydict/files/13976590/DefaultStyle.css.zip)

**Comment by LuuuuuuHaaaaaaao** [comment]
> 这个 CSS 我改过好几次，你试一下看行不行，稍后我更新一下词典资源吧。
> 
> [DefaultStyle.css.zip](https://github.com/tisfeng/Easydict/files/13976590/DefaultStyle.css.zip)

感谢感谢!

**Comment by tisfeng** [comment]
已更新朗文词典资源。
