### ISSUE TITLE
【Swift 重构】补充设置-服务页各项 API key 配置

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#342]
目前新的设置服务页，只有 OpenAI 一个配置演示界面，需要补充各项服务的 API key 配置，实现完整可用。

<img width="836" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/8badc96f-ae39-40c5-8755-2b47b1adb2dd">

**Comment by tisfeng** [comment]
@phlpsong 你能补充一下这个配置吗

**Comment by phlpsong** [comment]
Sure, will take a look
