### ISSUE TITLE
🐞 反馈问题：休眠后，疑似后台退出？

### ISSUE THREAD

**Issue by levihuayuzhang** [tisfeng/Easydict#343]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

合上笔记本后，再打开，会出现快捷键不起作用。只能重新点击图标。疑似后台退出？

### 重现步骤

如上。

### 截图

null

### 期望结果

在休眠后依旧保持程序打开，可以直接使用快捷键。

### 设备型号 && 系统版本

m1 max

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
已知问题：关闭菜单图标，小概率会导致应用后台自动退出 https://github.com/tisfeng/Easydict/issues/110

**Comment by tisfeng** [comment]
每次电脑休眠，都会出现这个问题吗？

试过万能的重启大法吗？重启、重装应用，重启电脑

另外，你可以导出日志，我看一下。

**Comment by levihuayuzhang** [comment]
似乎和 #110 类似。除了休眠重新打开电脑的情况以外，普通用一段时间也会自动关闭。
sorry，重复问题了，close咯。
