### ISSUE TITLE
dev: Adding a disabled App by dragging it causes a very noticeable lag

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#346]
From  https://github.com/tisfeng/Easydict/pull/340#discussion_r1458604586

https://github.com/tisfeng/Easydict/assets/25194972/09958504-2f96-4939-9ff2-c8d0100ab92d

**Comment by tisfeng** [comment]
The problem may be related to get select word by mouse, I didn't find the exact reason, here is my previous fix code 0b8f9e9

**Comment by phlpsong** [comment]
ok, I will check it

**Comment by phlpsong** [comment]
I tested it and could not reproduce it on my 2 Mac devices(M2 chip model & Intel chip 2018 model).

[screen-capture.webm](https://github.com/tisfeng/Easydict/assets/103433299/296b9d79-0f9e-43f8-8823-60b3f9083897)

I wonder if any others have this issue and do you have some special settings in your side?

**Comment by tisfeng** [comment]
I tested this code, it doesn't fix on my mac.

Maybe I forgot to say,  option  `auto select text` should be turned on.

<img width="617" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/cc11542f-4ae5-40af-9aa2-a861f50399b3">
