### ISSUE TITLE
🚀 功能建议：添加应用内切换语言选项

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#348]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

在设置页添加一个语言选项，方便应用内快速切换界面显示语言，而不需要退出重启应用。

### 使用场景

也方便我们开发测试多语言环境。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by choykarl** [comment]
可以。就中英切换吗？

**Comment by tisfeng** [comment]
是的，目前就中英文就行。

**Comment by tisfeng** [comment]
我看有些用户需要这个语言切换，如果完成了，下个版本我们就加上去。

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。
