### ISSUE TITLE
🐞 反馈问题：查询图标不能跨屏显示

### ISSUE THREAD

**Issue by mkeco** [tisfeng/Easydict#35]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

查询图标只能在主屏幕显示。

### 重现步骤

外接第二个显示器，划词后在主屏幕显示查询图标

### 期望结果

跟着鼠标显示

### 设备信息 && 操作系统版本（可选）

Apple m1

**Comment by tisfeng** [comment]
感谢反馈，稍后我查一下。

主要是我没有外接显示器，问题不太好弄 😰

**Comment by tisfeng** [comment]
参考 https://github.com/tisfeng/Easydict/issues/30#issuecomment-1521606688

**Comment by tisfeng** [comment]
你好，新版本已修复该问题  https://github.com/tisfeng/Easydict/releases/tag/1.3.0
