### ISSUE TITLE
🐞 反馈问题：修改菜单栏图标

### ISSUE THREAD

**Issue by krtttt** [tisfeng/Easydict#351]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

现菜单栏图标视图不够清晰，文字过小，图标很小气

### 重现步骤

左：预想
右：现 Easydict 2.5.0

### 截图

![CleanShot 2024-01-22 at 08 46 27@2x](https://github.com/tisfeng/Easydict/assets/84033501/b0120913-66a9-4fe4-a6fb-838d2c737360)

### 期望结果

应该更改菜单栏图标，或提供自定义

### 设备型号 && 系统版本

Apple M1 Pro, macOS 14.0

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
我觉得这图标看起来还行。

如果只是单单来评价这个图标，那没必要，如果你有其他想法，可以 PR 提供你认为好的图标，我们来看看效果。

<img width="301" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/29d87410-63ec-490b-9215-fe52a67753e1">

**Comment by tisfeng** [comment]
其实我觉得目前 Easydict 这两个图标都不错，只是为了方便开发调试，区分版本，所以一个用作 release 环境，另一个用作 debug 环境。

后面想了一下，考虑到不同用户偏好不同，可能有人更喜欢 debug 版本的图标，因此感觉可以开放出来，让用户自己去做选择。

<img width="123" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/1120b295-f793-42d3-9172-6f8a4917d8e7">

**Comment by tisfeng** [comment]
@choykarl 你可以加一下这个功能吗？就在新的设置页用 Picker 添加一个图标设置项，目前暂定上面那两个选项，默认还是之前 release 版本的图标。

**Comment by choykarl** [comment]
可以，不过我这个月刚换了工作，现在一边熟悉项目一边做需求，忙到飞起🤣。
不急的话我抽节假日看看。

**Comment by tisfeng** [comment]
可以

**Comment by tisfeng** [comment]
[2.6.0](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 新版本已提供菜单栏图标选项。
