### ISSUE TITLE
dev: Add missing in-app shortcuts in new settings

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#352]
It seems that when using the new `EasydictApp.swift` to launch, the shortcuts in the previous `Main.storyboard` are not loaded, and shortcuts like `Cmd+P` for pinning the window do not work. 

In addition, we can also move these in-app shortcuts to the new shortcut tab and allow users to modify them.

<img width="611" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/5863e3fc-62c4-46e8-bf3d-289cc0a0df14">

**Comment by tisfeng** [comment]
How is this going, can we add it in the next few days?

I hope to release a new version before Chinese New Year.

**Comment by AkaShark** [comment]
yeah, I will PR soon, I'll try to make it later today or tomorrow

**Comment by AkaShark** [comment]
> It seems that when using the new EasydictApp.swift to launch, the shortcuts in the previous Main.storyboard are not loaded, and shortcuts like Cmd+P for pinning the window do not work.
SwiftUI seem  not support storyboar,  I will add shortcut commands in this term. For other parts, should we add a new issues to track.

**Comment by tisfeng** [comment]
> For other parts, should we add a new issues to track.

What exactly does this mean? Is there any problem?

**Comment by tisfeng** [comment]
If you feel like this issue is a little big, we could do it in two steps. This time we just add all the in-app shortcuts, that is the most important thing. 

We can support custom shortcuts in another issue later.

**Comment by tisfeng** [comment]
Even this shortcuts menu UI is not necessary, we can put it off and do it later.

**Comment by AkaShark** [comment]
yeah, I mean using  SwiftUI in `EasydictApp.swift ` to launch is not support  setting UI by storyboard(Main.storyboard). You can see this in new app is different with `Main.storyboard`
![CleanShot 2024-02-04 at 23 17 52@2x](https://github.com/tisfeng/Easydict/assets/26460192/5d208610-5e4f-4acf-9965-1882a13334cd)
![CleanShot 2024-02-04 at 23 19 05@2x](https://github.com/tisfeng/Easydict/assets/26460192/c1ca9302-b6ad-41cc-a952-ecb5eee91547)
So, I think in this issues we need finished shortcut and open other issues to track other menu like file, format,etc

**Comment by AkaShark** [comment]
> Even this shortcuts menu UI is not necessary, we can put it off and do it later.

It's okay, I'm almost done the shortcut part

**Comment by tisfeng** [comment]
The new settings will not invoke Main.storyboard, we don't need to care about it. 

If we need to add new menu items in the future, we can use Swift/SwiftUI code.

**Comment by AkaShark** [comment]
> The new settings will not invoke Main.storyboard, we don't need to care about it.
> 
> If we need to add new menu items in the future, we can use Swift/SwiftUI code.

yeah, if we need to track other menu items, I suggest opening another issue instead of finishing this one.

**Comment by AkaShark** [comment]
> The new settings will not invoke Main.storyboard, we don't need to care about it.
> 
> If we need to add new menu items in the future, we can use Swift/SwiftUI code.

yeah, if we need to track other menu items, I suggest opening another issue instead of finishing this one.

**Comment by tisfeng** [comment]
ok
