### ISSUE TITLE
🚀 功能建议：“快捷功能”区添加快捷设置

### ISSUE THREAD

**Issue by CanglongCl** [tisfeng/Easydict#354]
# 背景：

1. EasyDict的许多特色功能，包括开启各种翻译、自定义选项均在设置中。
2. 多数用户会隐藏菜单栏，但是隐藏菜单栏图标后，需要使用快捷键`cmd+,`才能进入设置，对于一般用户入口较深也较难理解。隐藏菜单栏时虽然会提供提示，但提示力度相对较弱，很可能被手快的用户忽略。
3. 目前翻译窗口右上角的快捷功能区域有一定冗余，空间允许添加入口。

# 功能描述：

在翻译窗口右上角，快捷功能区域添加一个设置入口导航。

与其他快捷功能类似，该入口自定义配置，但默认开启。

可参考Bob。
![image](https://github.com/tisfeng/Easydict/assets/34743145/c59b3090-d200-4380-859c-9156853b3a80)

# 待讨论的问题：

1. 是否添加该按钮？该按钮是否会导致UI复杂？
2. 按钮的图标。目前快捷区域按钮均为彩色按钮，设置入口应当采用彩色按钮还是使用常规accentColor按钮？（我倾向于用accentColor+SFSymbol，指示该功能是应用内部链接，与外部链接区分，但可能会导致UI一致性问题）

**Comment by tisfeng** [comment]
可以的，我之前也有过这个想法 https://github.com/tisfeng/Easydict/issues/3#issuecomment-1401903900 ，这样相当于可在右上角实现一个便捷入口的设置功能项，也可以实现一些对输入文本内容的处理功能，例如 https://github.com/tisfeng/Easydict/issues/86 翻译原文处理，OCR 文本拼接的处理，打开其他应用 https://github.com/tisfeng/Easydict/issues/190 。

这一块的相关设置，看是放在高级里面，还是专门弄个 tab 来设置。

**Comment by tisfeng** [comment]
> 按钮的图标。目前快捷区域按钮均为彩色按钮，设置入口应当采用彩色按钮还是使用常规accentColor按钮？（我倾向于用accentColor+SFSymbol，指示该功能是应用内部链接，与外部链接区分，但可能会导致UI一致性问题）

没问题，就常规 accentColor 就可以，尽量用系统的 SF 图片。

外部链接图标，我们就用第三方应用的图标，这样容易理解。

**Comment by tisfeng** [comment]
@CanglongCl 你可以负责这个功能吗？

**Comment by CanglongCl** [comment]
> @CanglongCl 你可以负责这个功能吗？

安排我没问题，不过最近比较忙，可能要过一段时间才能动工。BTW我其实不太熟悉窗口管理这一块的内容，回头得学习一下。

**Comment by tisfeng** [comment]
ok，这个不急，你可以先熟悉一下。

**Comment by tisfeng** [comment]
还真有不少用户关闭菜单栏图标后，不知道如何打开设置页 https://github.com/tisfeng/Easydict/issues/413 ，或重新显示菜单栏图标，感觉确实可以在查询界面的右上角加个快捷设置功能图标。

@CanglongCl  目前这里可以实现简单一点，先就添加一个功能图标，允许隐藏，然后菜单项里面放【自动去除代码注释符号】https://github.com/tisfeng/Easydict/issues/135 和【单词自动分词】https://github.com/tisfeng/Easydict/issues/321 和一个打开设置的菜单项就行，其他的我们后面在慢慢加。

**Comment by CanglongCl** [comment]
@tisfeng 我之前看了一下代码，窗口那块目前是objc那边在管理，我感觉这个需求我可能做不来，感觉还是换个人做？

**Comment by tisfeng** [comment]
ok，@NeverAgain11 你能做一下这个吗

**Comment by NeverAgain11** [comment]
@tisfeng 需求不太明白，能详细说明吗

**Comment by tisfeng** [comment]
右上角加一个快捷设置功能图标，像这样

<img width="742" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/26b21a23-87b6-4fa2-9326-194c7f0571cb">

**Comment by tisfeng** [comment]
相关代码在这里，去除注释符号和分词之前没有单独开关，你加一下。

有专门的开关后，这里的 beta 就不需要了。

https://github.com/tisfeng/Easydict/blob/033e391917820787a3108b1a01cdf291be0c197f/Easydict/Feature/ViewController/Model/EZQueryModel.m#L180

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。
