### ISSUE TITLE
🚀 功能建议：自动删除换行符

### ISSUE THREAD

**Issue by CanglongCl** [tisfeng/Easydict#357]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

取词或OCR取词时，自动删除换行符。

该功能可自定义，默认关闭。

### 使用场景

PDF取词时或ORC取词时经常出现错误换行情况。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by CanglongCl** [comment]
好像duplicated了（）

**Comment by tisfeng** [comment]
是的，这个也属于对翻译原文处理，稍后我们可以放到这里 https://github.com/tisfeng/Easydict/issues/354 ，添加几个快捷处理动作。
