### ISSUE TITLE
🐞 反馈问题：输入翻译无法使用

### ISSUE THREAD

**Issue by ShelbyTang** [tisfeng/Easydict#358]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

划词翻译正常
<img width="482" alt="image" src="https://github.com/tisfeng/Easydict/assets/54990505/2e9f7639-a877-4b7f-84a3-d491316c78ad">

输入翻译无法延伸出翻译，按enter有时无用，有时会播放读音
<img width="403" alt="image" src="https://github.com/tisfeng/Easydict/assets/54990505/0d4e634d-6d8f-4cb1-9b63-f221541e5be4">

### 重现步骤

...

### 截图

...

### 期望结果

正常翻译

### 设备型号 && 系统版本

MacBook Pro 2019, macOS Sonoma 14.1.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by Jerry23011** [comment]
从第二张截图来看，是有时候连翻译图标都不会出现吗？

**Comment by phlpsong** [comment]
Have you ever pressed the `<` button to make the result collapse? If so, you could try to expand the cell manually and see if it works well.

**Comment by ShelbyTang** [comment]
> 从第二张截图来看，是有时候连翻译图标都不会出现吗？

不太清楚你说的翻译图标是指哪里，在我这边看到的，输入翻译时，不会出现任何的翻译结果（苹果字典、有道），划词翻译会正常出现

**Comment by ShelbyTang** [comment]
> Have you ever pressed the `<` button to make the result collapse? If so, you could try to expand the cell manually and see if it works well.

在输入翻译中，并出现没有`<`按钮

**Comment by Jerry23011** [comment]
@ShelbyTang 你有在设置 -> 服务 中把迷你窗口、主窗口、侧悬浮的服务都开启吗

**Comment by ShelbyTang** [comment]
> @ShelbyTang 你有在设置 -> 服务 中把迷你窗口、主窗口、侧悬浮的服务都开启吗

破案了，就是这个原因👍。但是我下载下来，应该没有主动关闭过这个地方的配置，侧悬浮是默认关闭所有的服务的吗？

**Comment by Jerry23011** [comment]
> 侧悬浮是默认关闭所有的服务的吗？

说实话我也不太熟悉这里的代码😂

破案了就先 close 啦，使用愉快

**Comment by ShelbyTang** [comment]
感谢各位！🙏
