### ISSUE TITLE
dev: `Configuration.shared.updater` return nil on setting and getting `automaticallyChecksForUpdates`

### ISSUE THREAD

**Issue by CanglongCl** [tisfeng/Easydict#363]
![image](https://github.com/tisfeng/Easydict/assets/34743145/b4921ad8-ed70-4bc2-9d60-ba214297cd0f)

@NeverAgain11 Can you have a look?

**Comment by NeverAgain11** [comment]
![image](https://github.com/tisfeng/Easydict/assets/10336013/75ddca18-59e2-4ff6-97ad-4726fcb37b6f)
it's not nil in my side.

**Comment by NeverAgain11** [comment]
Have you checked that the appDelegate is nil?

**Comment by CanglongCl** [comment]
> Have you checked that the appDelegate is nil?

Yes, `appDelegate` is nil as well.

**Comment by NeverAgain11** [comment]
> > Have you checked that the appDelegate is nil?
> 
> Yes, `appDelegate` is nil as well.

can you replace `appDelegate` to 
```
var appDelegate: AppDelegate? {
        NSApp.delegate as? AppDelegate
    }
```
and see if it can solve?

**Comment by CanglongCl** [comment]
> > > Have you checked that the appDelegate is nil?
> > 
> > 
> > Yes, `appDelegate` is nil as well.
> 
> can you replace `appDelegate` to
> 
> ```
> var appDelegate: AppDelegate? {
>         NSApp.delegate as? AppDelegate
>     }
> ```
> 
> and see if it can solve?

It is still `nil`

**Comment by NeverAgain11** [comment]
<img width="939" alt="image" src="https://github.com/tisfeng/Easydict/assets/10336013/dd17074e-b79f-4d69-8e95-7df2e477a405">

perhaps casued by this.
`NSApplicationMain` not get called.

**Comment by CanglongCl** [comment]
@tisfeng Please have a look at this issue. I'm really not familiar with NSApp's life circle.

**Comment by tisfeng** [comment]
> <img alt="image" width="939" src="https://private-user-images.githubusercontent.com/10336013/299537596-dd17074e-b79f-4d69-8e95-7df2e477a405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzMwMjksIm5iZiI6MTcwNjE3MjcyOSwicGF0aCI6Ii8xMDMzNjAxMy8yOTk1Mzc1OTYtZGQxNzA3NGUtYjc5Zi00ZDY5LThlOTUtN2RmMmU0NzdhNDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4NTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YjNlZGQ0ZTZhYjU5ZjgwNGQ5YTdmZDZmYmRiMWZlN2ZiYjBhOWRjNjA4ZTRkMzcxZjYwYzYxYjc4NmFhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxGuR6hPaC6AdJFx53hLJPmUgWRv5Rxckk_6_zoUaQ8">
> perhaps casued by this. `NSApplicationMain` not get called.

Yes, I've found this too, when started with SwiftUI, it doesn't initialize `Main.storyboard` as it did before, and `updaterController`, which is an IBOutlet that depends on it, isn't initialized, resulting in `updater` being nil as well.

```objc
@interface AppDelegate : NSObject <NSApplicationDelegate>

@property (weak) IBOutlet SPUStandardUpdaterController *updaterController;

@end
```

```swift
var updater: SPUUpdater? {
        appDelegate?.updaterController.updater
    }
```

**Comment by tisfeng** [comment]
Maybe we can refer to the Sparkle document and initialize `updaterController` with code instead.

https://sparkle-project.org/documentation/programmatic-setup/

**Comment by tisfeng** [comment]
I found that there's already another `updaterController` created in EasydictApp.swift, we may need to reorganize the code in this part.

https://github.com/tisfeng/Easydict/blob/dev/Easydict/NewApp/EasydictApp.swift#L64
