### ISSUE TITLE
您好，我想咨询一个关于EasyDict中关于划词/取词功能的问题

### ISSUE THREAD

**Issue by donfishman** [tisfeng/Easydict#369]
EasyDict中关于划词/取词的功能好像是有几个解决方案，一个是用的Accessibility，然后还有就是模拟键盘Command+C，还有就是用执行applescript脚本来实现，然后这几个方案好像都有缺陷，导致app的沙盒不能使用，然后我观察到有道，欧陆等词典里也有划词/取词功能，但是他们的软件好像是可以在app store上上架的，不知道他们用的那种解决方案，我是一名swift新手，但是公司业务中遇到这样一个需求，实在不会了，希望有大佬能帮我指点迷津，谢谢🙏

**Comment by tisfeng** [comment]
> 这几个方案好像都有缺陷

是的，目前没有一个完美的方案。

> 导致app的沙盒不能使用

这个我不明白，上面提到的这几种方式，都是合法的，应该没有问题。
