### ISSUE TITLE
🐞 反馈问题：设置页面深色模式适配问题

### ISSUE THREAD

**Issue by Aboceder** [tisfeng/Easydict#37]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

偏好设置页面，即使是白天，也是黑暗的主题色，而且又不是纯深色，显示有问题（系统本身是浅色深色自动切换的）
<img width="564" alt="CleanShot 2023-03-27 at 08 53 44@2x" src="https://user-images.githubusercontent.com/53726224/227816511-86c208dc-f505-4fa1-8129-0a678d394875.png">

### 重现步骤

偏好设置页面

### 期望结果

能够跟随系统变换，或者一直保持浅色or深色

### 设备信息 && 操作系统版本（可选）

Apple M1 mbp macOS 12.2.1 (21D62)

**Comment by Jerry23011** [comment]
@Aboceder 这个问题可以关注一下 #134
