### ISSUE TITLE
🚀 功能建议：can we hold on the previous result if selected text is empty?

### ISSUE THREAD

**Issue by yam-liu** [tisfeng/Easydict#371]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

if no text is selected, and trigger the selectTextTranslate, can we just show the window and the previous result?
![CleanShot 2024-01-29 at 14 27 32@2x](https://github.com/tisfeng/Easydict/assets/1056803/ce1f7795-7c4c-4a82-a511-111409ec4192)

### 使用场景

To get myself remember less shortcuts, I only give 'Select Text Translate' a shortcut, let's say, option+d. Sometimes, focus may get dismissed accidentally, if I press option+d again, the prev result got cleared, I must select context again or type it again.

### 实现方案（可选）

The expected behavior is when option+d pressed, check if any selected text exists, if not, just showing the previous result and making the previous selectedText selected. If I want to search other words, I can just start typing. It's a win-win, suitable for two different scenarios.

![CleanShot 2024-01-29 at 14 27 32@2x](https://github.com/tisfeng/Easydict/assets/1056803/ce1f7795-7c4c-4a82-a511-111409ec4192)
Is replacing
```        
self.selectedText = [text trim] ?: @"";
```
with 
```        
self.selectedText = [text trim] ?: self.selectedText;
```
almost all the work? anythings else to consider?

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
Your suggestion is good, maybe we can add an option in the settings to allow the user to choose whether to display the previous content or clear it when the selected text is empty.

<img width="686" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/4dd6e0f5-903d-4fca-857f-e17b58c447ca">

**Comment by yangg** [comment]
同样不想清空，因为只使用一个快捷键，没有给 Input Translate 单独一个快捷键。

**Comment by yam-liu** [comment]
> 同样不想清空，因为只使用一个快捷键，没有给 Input Translate 单独一个快捷键。

Just wait for #375 to be merged.

**Comment by tisfeng** [comment]
[2.6.0](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 新版本已提供设置项。
