### ISSUE TITLE
🐞 反馈问题：默认未开启翻译服务

### ISSUE THREAD

**Issue by ccc469** [tisfeng/Easydict#372]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

嗨，非常感谢有这么棒项目  我在这个设备上出现无法使用截图翻译
![image](https://github.com/tisfeng/Easydict/assets/27529250/b98ab8c4-f8aa-4bcb-a73f-93d1ced7eef4)

软件操作如下：
![image](https://github.com/tisfeng/Easydict/assets/27529250/a935dc1b-ff98-4927-9943-28ca5c2076f9)

### 重现步骤

截图翻译

### 截图

![image](https://github.com/tisfeng/Easydict/assets/27529250/1cc0b5dc-bf82-49b0-b9b2-6fad439ad3be)

### 期望结果

期望显示输入翻译的小窗口

### 设备型号 && 系统版本

Apple m1 pro macos 12.3

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
看这里 https://github.com/tisfeng/Easydict/issues/358#issuecomment-1907476987 ，下个版本会修改这个问题。
