### ISSUE TITLE
🐞 反馈问题：At first, the App displays light. Suddenly become dark

### ISSUE THREAD

**Issue by AkaShark** [tisfeng/Easydict#376]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

When I clone the dev and run I found that  the App displays light at first, but suddenly became dark. 
My laptop in dark mode.
https://github.com/tisfeng/Easydict/assets/26460192/187a1967-f39f-481c-9b8a-672577bb4bbb

### 重现步骤

above

### 截图

above

### 期望结果

Not appear  the switch animations

### 设备型号 && 系统版本

Apple M2 pro, Mac OS 14.0 

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
I have tested it, if enable main window, the problem does exist. 

@NeverAgain11  Can you have a look?
