### ISSUE TITLE
🚀 功能建议：希望能支持第三方应用内可使用

### ISSUE THREAD

**Issue by LongLiveForFreedom** [tisfeng/Easydict#378]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

目前发现在web app（safari新增的对某个网站可以以应用的形式开启的功能）以及像pdf expert软件中无法使用划词翻译的功能（之前使用apple books的原生软件是可以正常使用的，但现在换成了pdf expert就无法使用了）

### 使用场景

在其他软件或web app中使用，方便阅读pdf文件等

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by Jerry23011** [comment]
请看 [Wiki 常见问题](https://github.com/tisfeng/Easydict/wiki/常见问题)

**Comment by LongLiveForFreedom** [comment]
> 请看 [Wiki 常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

已解决，谢谢！
