### ISSUE TITLE
🐞 Bug Report: query window dismissed before showing the result in Stage Manager mode

### ISSUE THREAD

**Issue by phlpsong** [tisfeng/Easydict#381]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

query window dismissed before showing the result in Stage Manager mode

### Reproduction steps

1. Enable Stage Manager mode in system settings and unchecked `Hide main window at startup`
2. Select text to query

### Screenshot

https://github.com/tisfeng/Easydict/assets/103433299/c3078ab7-a5d8-4612-85e2-f484545d2605

### Expected result

The query window stays visible

### Device type and OS version

macOS 14.2.1

### Are you willing to submit a PR to fix this issue?

- [X] I'm willing to submit a PR

**Comment by phlpsong** [comment]
I noticed that we check `[EZMainQueryWindow isAlive]` twice in the `showFloatingWindow` function of EZWindowManager and then perform `orderOut` and `orderBack` on the `mainWindow`. 

Is it necessary to have the subsequent `orderBack`?

**Comment by tisfeng** [comment]
Currently the window management in the code is confusing, it needs to be improved https://github.com/tisfeng/Easydict/issues/362 , but I'm not too familiar with this.

Previously I found that if the main window is turned on, when displaying the mini query window, the main window needs to be hidden first for a better user experience, if don't call `orderBack`, we can't see main window any more. But now I tested it and it seems to work without `orderBack`, which is strange.

I haven't tested this in `Stage Manager mode` before, you can try to fix this as you see fit.

**Comment by tisfeng** [comment]
[2.6.0](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 新版本已修复该问题。
