### ISSUE TITLE
dev: Background list item got selected when toggling switches

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#386]
In Settings -> Service, when a switch is toggled, the backgruond colour appears to be selected as well

Screenshot (SwiftUI)

https://github.com/tisfeng/Easydict/assets/89069957/6d2c5b79-4da5-4454-85e4-ad730dd810db

Expected behaviour (Easydict 2.5.0)

https://github.com/tisfeng/Easydict/assets/89069957/1e706f8b-bc0a-4fbd-897e-d136db948a9f

**Comment by tisfeng** [comment]
@NeverAgain11 Can you have a look this?

**Comment by phlpsong** [comment]
@tisfeng  I believe this is a side effect caused by the list selection bg color workaround. Do you accept the default List behavior like the `Disable Apps` tab?

**Comment by tisfeng** [comment]
OK, let's use default selection effect.
