### ISSUE TITLE
🚀 功能建议：添加一个支持通用 OpenAI 接口格式的翻译服务

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#387]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)

### 功能描述

该服务和 OpenAI 翻译类似，只是它支持自定义模型，可以和 OpenAI 翻译共存 https://github.com/tisfeng/Easydict/pull/379#discussion_r1476926766

### 使用场景

使用 [one-api](https://github.com/songquanpeng/one-api) 将第三方 LLM 接口转为标准的 OpenAI 接口，方便在 Easydict 中使用。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by phlpsong** [comment]
Should I wait to start until this this pr https://github.com/tisfeng/Easydict/pull/312 is completed?

**Comment by tisfeng** [comment]
No, You can work on this feature first, the refactored OpenAI service later will be consistent with the previous one, and I can ensure there will be no destructive changes.

Since #312 depends on upstream library [OpenAI](https://github.com/MacPaw/OpenAI) which lacks custom `end point` feature, I need to wait for feedback or fork and implement this myself.

**Comment by phlpsong** [comment]
OK, got it.

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。

**Comment by Mrycp** [comment]
尝试使用了该功能，在配置界面验证提示是验证成功的，且在其它软件中确认过接口和 key 都是正确的。但是在 dict 中无法显示输出结果。当输入是句子时无结果输出，当输入是单词时只会重复输出该单词，并不会进行翻译或单词解析输出。
![CleanShot 2024-05-07 at 00 39 32@2x](https://github.com/tisfeng/Easydict/assets/35561057/55ed5a8e-913f-4b40-9a56-87659ccc045c)
![CleanShot 2024-05-07 at 00 43 18@2x](https://github.com/tisfeng/Easydict/assets/35561057/17a5c99e-5b45-4538-a452-adaeb10705d6)
