### ISSUE TITLE
Others 更新时直接覆盖安装还是卸载旧版再安装新版？

### ISSUE THREAD

**Issue by suibianzai** [tisfeng/Easydict#39]
RT，刚刚发现这个词典，非常感谢开发者！

**Comment by tisfeng** [comment]
点击检查更新，它会自动下载最新版本更新的。你也可以在【设置-关于】里打开自动检查更新 🤗

**Comment by suibianzai** [comment]
> 点击检查更新，它会自动下载最新版本更新的。你也可以在【设置-关于】里打开自动检查更新 🤗

好嘞 谢谢！
