### ISSUE TITLE
dev: stream service(like OpenAI) displays multiple alert when validating  

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#392]
https://github.com/tisfeng/Easydict/assets/25194972/c014b20e-b290-471e-81cb-782427e2800c

**Comment by tisfeng** [comment]
This warning came again when validating OpenAI service https://github.com/tisfeng/Easydict/pull/379#issuecomment-1925821896

<img width="1088" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/52fc2005-9050-41ce-a1ea-526dd52c6d44">

**Comment by phlpsong** [comment]
<img width="739" alt="Screenshot 2024-02-07 at 14 01 31" src="https://github.com/tisfeng/Easydict/assets/103433299/d87e708f-e287-454b-a67f-b4655db40eb6">

Not sure if the above change could fix this. I need get an API Key to test it.
