### ISSUE TITLE
🐞 反馈问题：2.6版本赋予权限后还是无法进行翻译

### ISSUE THREAD

**Issue by dqzboy** [tisfeng/Easydict#397]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

2.6版本安装后，划词翻译没有任何反应，截图翻译提示权限问题，赋予了权限再次使用截图翻译又是提示权限问题，但是权限是给的了；回滚2.5版本一切正常

### 该问题是否可以稳定重现？

可重现

### 重现步骤

安装最新2.6版本，使用划词和截图翻译

### 截图

- 权限已开启
<img width="484" alt="image" src="https://github.com/tisfeng/Easydict/assets/42825450/e9a395d0-d53e-4d7a-a894-76c12259896a">

- 使用截图翻译还是提示需要给权限
<img width="577" alt="image" src="https://github.com/tisfeng/Easydict/assets/42825450/c7f430fb-9171-4bda-973b-08c4aca500b7">

- 划词翻译没有任何反应，也不会弹出翻译的图标
<img width="904" alt="image" src="https://github.com/tisfeng/Easydict/assets/42825450/461e532a-8526-4f5b-b187-aaaf15a73604">

### 期望结果

可以正常使用划词翻译和截图翻译

### 设备型号 && 系统版本

m3 pro mac-os 14.3.1 

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by oneluxyou** [comment]
same question

**Comment by phlpsong** [comment]
Please try to remove `Easydict` from the permission list and grant the accessibility permission again.

**Comment by dqzboy** [comment]
> Please try to remove `Easydict` from the permission list and grant the accessibility permission again.

尝试过了 没有任何效果，还是同样的问题，回退2.5版本一切正常

**Comment by KaiWenRui** [comment]
同样，截图翻译也无法正常使用，可以输入翻译，同样是权限问题，2.5版本正常

**Comment by tisfeng** [comment]
由于 2.6 版本使用了新的账号签名 https://github.com/tisfeng/Easydict/issues/2#issuecomment-1935524993 ，因此需要重新授权，请移除之前 Easydict 的权限，然后重新添加。

如果上面方法无效，可尝试在终端使用命令重置 Easydict 的权限

```shell
tccutil reset Accessibility com.izual.Easydict
```

之后重启电脑，重新授权。

**Comment by iTvX** [comment]
> 由于 2.6 版本使用了新的账号签名 [#2 (comment)](https://github.com/tisfeng/Easydict/issues/2#issuecomment-1935524993) ，因此需要重新授权，请移除之前 Easydict 的权限，然后重新添加。
> 
> 如果上面方法无效，可尝试在终端使用命令重置 Easydict 的权限
> 
> ```shell
> tccutil reset Accessibility com.izual.Easydict
> ```
> 
> 之后重启电脑，重新授权。
方法无效，并且使用的是新电脑，还是有这个问题
![CleanShot 2024-02-09 at 22 25 05@2x](https://github.com/tisfeng/Easydict/assets/46791134/d28b309c-1c2f-4f55-a86c-6517c3ae03c2)

**Comment by iTvX** [comment]
> 由于 2.6 版本使用了新的账号签名 [#2 (comment)](https://github.com/tisfeng/Easydict/issues/2#issuecomment-1935524993) ，因此需要重新授权，请移除之前 Easydict 的权限，然后重新添加。
> 
> 如果上面方法无效，可尝试在终端使用命令重置 Easydict 的权限
> 
> ```shell
> tccutil reset Accessibility com.izual.Easydict
> ```
> 
> 之后重启电脑，重新授权。

方法 无效：



![CleanShot 2024-02-09 at 22 25 05@2x](https://github.com/tisfeng/Easydict/assets/46791134/61985119-b74a-45f8-8a83-d14b7ee2ba96)

**Comment by tisfeng** [comment]
@iTvX 查看一下你电脑上 Easydict 的 bundle id，release 版本应该是 com.izual.Easydict

**Comment by tisfeng** [comment]
如果还是不行，请参考 FAQ 重置所有 App 的辅助功能权限：

https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90%E5%90%8E-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90

**Comment by Chin-Me** [comment]
> 由于 2.6 版本使用了新的账号签名 [#2 (comment)](https://github.com/tisfeng/Easydict/issues/2#issuecomment-1935524993) ，因此需要重新授权，请移除之前 Easydict 的权限，然后重新添加。
> 
> 如果上面方法无效，可尝试在终端使用命令重置 Easydict 的权限
> 
> ```shell
> tccutil reset Accessibility com.izual.Easydict
> ```
> 
> 之后重启电脑，重新授权。

设置权限界面删除Easydict再重新添加后截图翻译功能恢复，感谢大佬。

**Comment by dqzboy** [comment]
> 如果还是不行，请参考 FAQ 重置所有 App 的辅助功能权限：
> 
> https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90%E5%90%8E-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90

按照方法操作后已经解决，谢谢

**Comment by WookieGao** [comment]
> Please try to remove `Easydict` from the permission list and grant the accessibility permission again.

It works

**Comment by bigpong2527** [comment]
到 设置 -> 隐私与安全性 -> 辅助功能 -> 点 - 将 Easydict 从列表中移除再重新添加。
成功了，谢谢

**Comment by RichardKimber** [comment]
会不会和beta系统有关，我使用的是 版本14.4 Beta版(23E5196e)，发现微信自带的截图，在使用的时候，会反复提示权限获取的需求。

**Comment by flyisland** [comment]
> 由于 2.6 版本使用了新的账号签名 [#2 (comment)](https://github.com/tisfeng/Easydict/issues/2#issuecomment-1935524993) ，因此需要重新授权，请移除之前 Easydict 的权限，然后重新添加。
> 
> 如果上面方法无效，可尝试在终端使用命令重置 Easydict 的权限
> 
> ```shell
> tccutil reset Accessibility com.izual.Easydict
> ```
> 
> 之后重启电脑，重新授权。

用了这个方法解决问题，谢谢！（版本：2.6.1）

**Comment by zhonghua723** [comment]
同样的问题！！请开发者及时解决！

**Comment by suibianzai** [comment]
> 同样的问题！！请开发者及时解决！

我也碰到同样的问题 参考上面的回复 把easydict原有的权限从列表中先删除 然后重新打开app 继续按照提示重新添加 这样就可以正常授权了

**Comment by zhonghua723** [comment]
> > 同样的问题！！请开发者及时解决！
> 
> 我也碰到同样的问题 参考上面的回复 把easydict原有的权限从列表中先删除 然后重新打开app 继续按照提示重新添加 这样就可以正常授权了

我最后是恢复了2.5.0版本才解决了
