### ISSUE TITLE
🐞 Bug Report: Shortcuts bugs in SwiftUI

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#399]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

I cleared the shortcut in the settings, but I still see it in the menu items, it seems to have been reset to the default shortcut.

For in-app shortcuts, it's weird that it still works after clearing it.

Also, if I clear the shortcut and restart the app, it gets reset to the default shortcut again, like this https://github.com/tisfeng/Easydict/pull/395#issuecomment-1935862963

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

This issue can be reproduced in both debug and release environments.

### Screenshot

https://github.com/tisfeng/Easydict/assets/25194972/77278da3-be87-4b31-9375-bfc3c6bb7a33

### Expected result

*

### Device type and OS version

*

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by AkaShark** [comment]
In this PR https://github.com/tisfeng/Easydict/pull/398, this issue will be closed

**Comment by tisfeng** [comment]
ok

**Comment by phlpsong** [comment]
Maybe it should be assigned to @CanglongCl or @AkaShark ?

**Comment by CanglongCl** [comment]
Already fixed with #398. Sorry I forgot to close this issue.

**Comment by tisfeng** [comment]
Please note that for issues that affect the production environment, even if we have fixed them in dev, we should use `fixed in next release` tag instead of closing them directly. 

I will close these types of issues later when we release a new version. 

Since we usually will not release patched versions once code is merged, closing the issue will lead some users  to mistakenly think the issue has been fixed(but in fact it has currently not), so they may open a bug issue again 😑

**Comment by tisfeng** [comment]
[2.6.1](https://github.com/tisfeng/Easydict/releases/tag/2.6.1) 版本已修复该问题。
