### ISSUE TITLE
关于翻译窗口位置的优化建议

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#4]
## 功能描述
现在截图翻译和快捷键翻译，弹出的窗口会默认在最右边，并且无法设置。
这会导致两个问题，一个是当我翻译屏幕左边的内容时（尤其是显示器过宽时），弹出的小窗出现在屏幕最右边会很不人性化；第二个是右上角是通知中心的地方，如果遇到日历通知在右上方（尤其是持久通知那种），就会出现UI上的重叠。

想到的两个优化办法：
1.自动记住上次调整的位置。
2.像沙拉查词一样，在原文（或图片）旁边的位置显示。

**Comment by tisfeng** [comment]
可以，很好的建议，宽显示屏这个我没考虑到。稍后我会提供设置选项，让用户可选择浮窗出现的位置。

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已支持了可选择浮窗出现的位置。
