### ISSUE TITLE
🚀 功能建议：通过 ⌘W 关闭偏好设置窗口

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#40]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

Easydict 的翻译窗口是可以用 ⌘W 关闭的，但是偏好设置窗口貌似不行，个人认为如果偏好设置窗口也能通过 ⌘W 关闭的话会在体验上更加统一

### 使用场景（可选）

偏好设置窗口

### 实现方案（可选）

类似在 SwiftUI 里的这种：
```
 Button("Close Window") {
                NSApp.keyWindow?.windowController?.close()
            }
            .keyboardShortcut("w", modifiers: [.command])
```

**Comment by tisfeng** [comment]
可以，稍后我加一下。

**Comment by Jerry23011** [comment]
感谢在 2023年4月1日，13:03，Tisfeng ***@***.***> 写道：﻿
可以，稍后我加一下。

**Comment by tisfeng** [comment]
你好，新版本已添加快捷键  https://github.com/tisfeng/Easydict/releases/tag/1.3.0
