### ISSUE TITLE
🐞 反馈问题：{{option + D, select translate功能提示权限不够}}

### ISSUE THREAD

**Issue by iTvX** [tisfeng/Easydict#400]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

option + d提示权限不够，但是已经在设置给了权限，目前无解。旧版本没有这个问题。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

option + D

### 截图

![CleanShot 2024-02-09 at 22 21 21@2x](https://github.com/tisfeng/Easydict/assets/46791134/6a070e3c-8ae7-4b3a-aea1-d3658b8c5490)

### 期望结果

解决权限问题

### 设备型号 && 系统版本

最新macOS

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by Jerry23011** [comment]
Hi @iTvX，
感谢反馈，你可以尝试将设置中的Easydict选中后按 `-` 移除后重新添加

**Comment by iTvX** [comment]
> Hi @iTvX， 感谢反馈，你可以尝试将设置中的Easydict选中后按 `-` 移除后重新添加

您好，我是在虚拟机尝试过，虚拟机第一次安装easydict，依然有这个问题。尝试你的方法之后，还是无法解决问题。

**Comment by Jerry23011** [comment]
> 虚拟机第一次安装easydict，依然有这个问题

这里是说第一次安装后给予 Easydict 权限并能在列表中看到权限已启用还是会有弹窗吗？

**Comment by tisfeng** [comment]
和 https://github.com/tisfeng/Easydict/issues/397 一样的问题，现在解决了吗？

**Comment by Jerry23011** [comment]
已经在 FAQ 中补充

**Comment by Svec-Tomas** [comment]
I have the same problem like iTvX user. After updating to newest version 2.6.0 It constantly asks me to grant Accessibility Permissions, but they were granted already. Tu turn off and then turn on again does not help and everytime I use option + D the popup window asking to grant permission appears.

**Comment by Svec-Tomas** [comment]
@AkaShark yes, removing EasyDict (-) from the list and adding back (+) EasyDict really helps and solves this problem. Thank you!
