### ISSUE TITLE
🐞 反馈问题：{{更新後不能截圖翻譯}}

### ISSUE THREAD

**Issue by dakuo6299** [tisfeng/Easydict#401]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [x] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

雖然我已經允許了它，但是就是不能截圖翻譯

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1.點擊截圖翻譯
2.打開系統設置
3.允許它
4.輸入密碼
5.重啟

### 截图

<img width="1004" alt="截圖 2024-02-10 下午5 43 16" src="https://github.com/tisfeng/Easydict/assets/159615832/dbed9145-5e3c-41b5-b7cb-e15b01275c76">

### 期望结果

可以修復這個問題

### 解决方案（可选）

沒有想到

### 设备型号 && 系统版本

Apple M1 Air, macOS 14.2.1

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR

**Comment by gxd523** [comment]
我也有同样的问题

**Comment by AkaShark** [comment]
I hope this [document](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90%E5%90%8E-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90) can help you

**Comment by dakuo6299** [comment]
我很感謝你，但這三種方式並未起到作用

**Comment by tisfeng** [comment]
> 我很感謝你，但這三種方式並未起到作用

使用终端命令重置完权限后，是否有重启电脑？

**Comment by tisfeng** [comment]
> 我很感謝你，但這三種方式並未起到作用

都不行吗，终端命令有报错信息吗

**Comment by RogerDeng** [comment]
我也發生同樣的問題，解決的方式是將在將原本在系統設定 ->  隱私權與安全性 -> 螢幕與系統錄音 和  輔助使用  中的 Easydict 先刪除掉，然後當你再次按下快捷鍵後，系統會跳出請開啟授權此應用，你再次開啟並重開程式就沒可以使用了。  
我是這樣子解決這個問題的。

**Comment by atinst** [comment]
谢谢你的回复，问题已成功解决！





------------------ 原始邮件 ------------------
发件人: RogerDeng ***@***.***&gt;
发送时间: 2024年2月12日 00:58
收件人: tisfeng/Easydict ***@***.***&gt;
抄送: atinst ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [tisfeng/Easydict] �� 反馈问题：{{更新後不能截圖翻譯}} (Issue #401)





 
我也發生同樣的問題，解決的方式是將在將原本在系統設定 -&gt;  隱私權與安全性 -&gt; 螢幕與系統錄音 和  輔助使用  中的 Easydict 先刪除掉，然後當你再次按下快捷鍵後，系統會跳出請開啟授權此應用，你再次開啟並重開程式就沒可以使用了。
 我是這樣子解決這個問題的。

**Comment by dakuo6299** [comment]
我確認我有重新開機但沒用，後來我自己用好了我用的方式和RogerDeng一樣

**Comment by tisfeng** [comment]
这不是程序 bug，这是一个预期的小问题，但没想到会有这么多用户感觉困惑，因此我再次说明一下，解决办法在  [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90%E5%90%8E-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90) 中也有写，请参照执行便可解决。

（注意：有时升级 macOS 系统也可能会遇到这种权限失效问题，这是苹果的 bug 😓）

> [!NOTE]
> 由于 2.6.0 版本 Easydict 使用了新的苹果开发者账号签名公证 https://github.com/tisfeng/Easydict/issues/2#issuecomment-1935524993 ，因此在使用划词翻译和 OCR 功能时会提示重新请求辅助功能权限，详情请看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90%E5%90%8E-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90)。

<img width="833" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/9ef56faf-5231-41f4-9405-2b5e7e667e87">
