### ISSUE TITLE
🐞 Bug Report: brew SHA256 mismatch, 2.5.6

### ISSUE THREAD

**Issue by ysmintor** [tisfeng/Easydict#402]
I do the usual upgrade, however got error when the 2.6.0 version.
 Downloading https://github.com/tisfeng/Easydict/releases/download/2.6.0/Easydict.dmg
Already downloaded: /Users/york/Library/Caches/Homebrew/downloads/84fd59d81d654910ffad51c2ba9786c321108129cc875f4ccb89b729abe0bf64--Easydict.dmg
Error: SHA256 mismatch
Expected: 0fe4c1e76c21fa3017a1a72176a858ebe64bfe86d9a894dd6a04fc2bcb01f8af
  Actual: b7883fcceebbc5d09d58c52382213390953bf97e765b3757c7b7da20c03fa49e
    File: /Users/york/Library/Caches/Homebrew/downloads/84fd59d81d654910ffad51c2ba9786c321108129cc875f4ccb89b729abe0bf64--Easydict.dmg
To retry an incomplete download, remove the file above.

I found https://[formulae.brew.sh/api/cask/easydict.json](https://formulae.brew.sh/api/cask/easydict.json)
```
"sha256": "0fe4c1e76c21fa3017a1a72176a858ebe64bfe86d9a894dd6a04fc2bcb01f8af",
```
It seems that the sha256 on formulase is different with relase version img.

**Comment by tisfeng** [comment]
@Jerry23011 Please check this https://github.com/Homebrew/homebrew-cask/pull/166357/files

<img width="830" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/d4b91527-749d-4ddf-b74e-875a95d02011">

**Comment by Jerry23011** [comment]
已更新，应该是当时 Sparkle 签名后 hash 改变了

**Comment by Jerry23011** [comment]
@ysmintor Please try again and tell me if it works

**Comment by ysmintor** [comment]
> @ysmintor Please try again and tell me if it works

Thanks. The fix has solved sha256 mismatch error.
