### ISSUE TITLE
🐞 反馈问题：开启自启动后，每次开机都会弹出「后台任务添加」

### ISSUE THREAD

**Issue by Lxnii** [tisfeng/Easydict#403]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

开启开机启动后每次开机都会弹出「后台任务添加」提醒，2.5 版本并不会。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

开启开机启动，每次重启

### 截图

<img width="341" alt="Screenshot 2024-02-11 at 12 18 36" src="https://github.com/tisfeng/Easydict/assets/27051542/9f42e3b0-a52b-4f08-a253-e496bb020a78">

### 期望结果

不会重复提醒

### 设备型号 && 系统版本

M2 Pro, 14.3.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
> 开启开机启动后每次开机都会弹出「后台任务添加」提醒，2.5 版本并不会。

@NeverAgain11 请确认一下这个问题，可能是使用 Swift 重写导致。

**Comment by NeverAgain11** [comment]
> > 开启开机启动后每次开机都会弹出「后台任务添加」提醒，2.5 版本并不会。
> 
> @NeverAgain11 请确认一下这个问题，可能是使用 Swift 重写导致。

好，我看看

**Comment by NeverAgain11** [comment]
@tisfeng 
We use Defaults to observe the change in the LaunchAtStart value, the oldValue will always return false when initialised, even if the value in UserDefault is true.

One solution is that we can remove the initial option, then it will be called when the value changes. 
Currently it is called both on app startup and on value change.
I don't think it needs to be called on startup.

**Comment by tisfeng** [comment]
确实，启动时不需要调用这个方法，你修改试试。

**Comment by tisfeng** [comment]
[2.6.1](https://github.com/tisfeng/Easydict/releases/tag/2.6.1) 版本已修复该问题。
