### ISSUE TITLE
🚀 功能建议：Add tips for FQA

### ISSUE THREAD

**Issue by AkaShark** [tisfeng/Easydict#404]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

Add tips for common FQA, like this
![CleanShot 2024-02-13 at 11 27 23@2x](https://github.com/tisfeng/Easydict/assets/26460192/fef53601-13f7-4cef-9631-d52b0a8b799a)
And add a button text is "更多"

### 使用场景

Help the user find a way to resolve common problems, and improve user experience. 

### 实现方案（可选）

This tips view will show when a window appears but the selected text is empty. The tips content is random from [FQA](https://github.com/tisfeng/Easydict/wiki/FAQ) 
![CleanShot 2024-02-13 at 11 45 10@2x](https://github.com/tisfeng/Easydict/assets/26460192/e2c7239c-8e1e-40fe-8599-57186b56d541)
When the user clicks the "如何解决" link FQA corresponding category, clicks the "更多" link FQA.

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
This function is fine, but needs to consider some special cases. 

For example, sometimes it's expected that the selected text is empty, users may just want to display the query window as a replacement for input translation or show previous query results https://github.com/tisfeng/Easydict/issues/371

**Comment by AkaShark** [comment]
> This feature is fine, but needs to consider some special cases.
> 
> For example, sometimes it's expected that the selected text is empty, users may just want to display the query window as a replacement for input translation or show previous query results #371

In this case, I think the tips view will hidden

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本已实现。
