### ISSUE TITLE
🚀 Feature Request: SwiftUI settings support in macOS 12

### ISSUE THREAD

**Issue by ysmintor** [tisfeng/Easydict#405]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Feature description

I do not want to upgrade macOS but still want to enable SwiftUI settings.

### Use case

I want to know if there is any chance to introduce SwiftUI settings into lower macOS version.

### Are you willing to submit a PR to implement this feature

- [ ] I'm willing to submit PR

**Comment by tisfeng** [comment]
I'm afraid it's not possible, the new Settings uses a lot of SwiftUI codes which all require macOS 13+.

I highly recommend everyone to upgrade to the latest macOS to enjoy a much better user experience, if your computer's hardware supports it.

Although Easydict currently supports a minimum macOS 11+, many new features in the future will be written in SwiftUI, which all may require macOS 13+ 

In addition, for developers, it is a tired thing to support low versions of the system. In the future, Easydict will change the minimum supported version to macOS 13+ https://github.com/tisfeng/Easydict/pull/329#issuecomment-1897703547

**Comment by ysmintor** [comment]
Ok, I will choose to upgrade current macOS.
