### ISSUE TITLE
🐞 反馈问题：2.6 swift ui 快捷键全局快捷键无法清空

### ISSUE THREAD

**Issue by yangg** [tisfeng/Easydict#407]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

只需要部分全局快捷键，但是输入框清空后，菜单里面还有，重启后输入框也有值了。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

设置里清空部分快捷键

### 截图

<img width="768" alt="image" src="https://github.com/tisfeng/Easydict/assets/409225/dd0d7099-af4c-4c54-a99a-bdeab20fa70a">

<img width="238" alt="image" src="https://github.com/tisfeng/Easydict/assets/409225/8b2317a4-1fe5-44d0-ac2b-e8f1fce9cdce">

### 期望结果

快捷键可以移除

### 设备型号 && 系统版本

Apple M2, 14.3

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
了解，这是已知问题 https://github.com/tisfeng/Easydict/issues/399 ，将会再下个版本修复。

**Comment by yangg** [comment]
sorry, 竟然没看到。
