### ISSUE TITLE
🐞 反馈问题：隐藏菜单栏图标后无法恢复

### ISSUE THREAD

**Issue by easy4u** [tisfeng/Easydict#408]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

- 在设置中选择了 "Hide Menu Bar Icon" 后，图标从状态栏消失
- 在取消这个选项后，图标无法回到状态栏
- 彻底杀掉后台进程，重新启动也没有出现图标

### 该问题是否可以稳定重现？

可重现

### 重现步骤

重现步骤同上

补充：
- 在我电脑上测试了几个版本，都有同样问题
- 重启启动应用后，可以通过快捷键来启动窗口，也可以通过 Command+, 进入设置页面
- 使用 App Cleaner & Uninstall App 删除应用，再重新安装，启动后直接不出现图标，无法解决问题
- 重启电脑也无法解决问题

### 截图

<img width="826" alt="image" src="https://github.com/tisfeng/Easydict/assets/6970526/c8a65582-03ce-4a1b-8b40-02b995a7a42c">

### 期望结果

取消 "Hide Menu Bar Icon" 选项后，图标可以正常显示在菜单栏

### 设备型号 && 系统版本

Apple M2 Max, macOS 14.3.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by easy4u** [comment]
补充个信息：在我电脑上也安装了 Translatium 应用和Karabiner-Elements应用，这两个应用也有类似的删除菜单栏图标功能，是可以正常反复操作的。

**Comment by tisfeng** [comment]
什么情况，这个问题解决了吗？这个功能我们测试没有问题，看是否被刘海遮挡住了。

**Comment by SysuJayce** [comment]
+1，怎么解决啊？Macos 14.3.1，easydict 2.6.1，点了隐藏状态栏之后就再也找不到了，关键是我快捷键也不生效，调不出界面

**Comment by EricWong1994** [comment]
<img width="1129" alt="image" src="https://github.com/tisfeng/Easydict/assets/48429995/7b1561d1-6024-49a7-92c3-dc9a5946cc2c">
我今天更新软件后遇到了类似的问题，但我没有主动隐藏图标，我是更新后，再重启菜单栏就看不见图标了....，但按Option + D，还能判断出来软件还在运行中，
还有按强制退出，应用列表里并没有这个软件
<img width="379" alt="image" src="https://github.com/tisfeng/Easydict/assets/48429995/30610e3e-c9c4-421c-b75a-522cb0c3367a">
还有另外一个问题就是更新后 我OCR功能，提示我没权限，但我已经把权限给这个软件了，不知道咋回事

**Comment by EricWong1994** [comment]
我去，杀死应用进程后，菜单栏图标又出现了，但是 截图翻译功能还是不行
<img width="728" alt="image" src="https://github.com/tisfeng/Easydict/assets/48429995/8741e435-f858-4309-b9b9-ee809a0febcd">

**Comment by EricWong1994** [comment]
<img width="510" alt="image" src="https://github.com/tisfeng/Easydict/assets/48429995/510771f2-8f1f-4673-84f0-b0622e8cae8f">
我已经卸载了，降级到 2.6.1版本了，老版本没有这个问题

**Comment by tisfeng** [comment]
https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90

**Comment by EricWong1994** [comment]
> https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90

终于好了，谢谢大佬👍🏻
