### ISSUE TITLE
🐞 反馈问题：拖动窗口出现提示音

### ISSUE THREAD

**Issue by cirexjohnson** [tisfeng/Easydict#41]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

开启软件后在拖动其他应用窗口时会出现系统提示音，“编辑”菜单会被选中。

### 重现步骤

例如：打开Safari，按住窗口拖动位置后松开，即可听到系统提示音，并且可以看到菜单栏的“编辑”选项被调用。

### 期望结果

正常拖动应用应该不存在这种情况

### 设备信息 && 操作系统版本（可选）

macOS 13.3

**Comment by tisfeng** [comment]
感谢反馈，这个问题是因为某些应用不支持常规的 Accessibility 取词，比如 Safari，所以此时只能采取模拟 Cmd+C 这种比较笨的取词方式，而空复制操作会触发系统提示音 😔

其实我一直在研究 PopClip 的取词实现方式，但没有进展，所以目前还没有一个好的解决办法。

关于这个问题，下个版本我会提供一个【禁止空复制提示音】选项，临时过渡一下。

<img width="614" alt="image" src="https://user-images.githubusercontent.com/25194972/229722295-04eb0ab4-d660-46af-ba11-579ffe2a5c2f.png">

**Comment by tisfeng** [comment]
你好，新版本已修复该问题  https://github.com/tisfeng/Easydict/releases/tag/1.3.0

**Comment by cirexjohnson** [comment]
> 你好，新版本已修复该问题 https://github.com/tisfeng/Easydict/releases/tag/1.3.0

开发者你好，我已经安装了新版。很感激的是大部分应用已经没有这个问题了。但是我发现Safari在非输入状态和未选词状态时还是会出现提示音。希望作者可以看看这个问题。

**Comment by tisfeng** [comment]
你好，请问是如何触发问题的？ 开启了【禁止空复制提示音】选项吗

**Comment by cirexjohnson** [comment]
> 你好，请问是如何触发问题的？ 开启了【禁止空复制提示音】选项吗

开启了。Safari随便打开个网页都能触发，只要没有选词，不在输入状态。

**Comment by tisfeng** [comment]
你是说，未选词状态， Safari 拖动窗口会出现提示音吗？我这边测试不会啊

**Comment by cirexjohnson** [comment]
> 你是说，未选词状态， Safari 拖动窗口会出现提示音吗？我这边测试不会啊

我这里会😂可能是我的原因吧，搞不懂了

**Comment by tisfeng** [comment]
难搞，只有 Safari 会这样吗？

你退出 Easydict 再试一下，看是否是其他应用导致？先确定是不是 Easydict 导致的问题，后面我再查查吧。

**Comment by cirexjohnson** [comment]
> 

我找到问题了。我今天刚发现每次拖动都会静音再恢复，才知道实现的原理。我用的系统提示音是Funky，长度大概1秒。但是Easydict静音再恢复的间隔太短了。所以我这里响的提示音不完整，只有后半段，开头被卡掉了。所以作者大大只需要把静音到恢复的时常换到1秒以上就好了。（我试了下时长最短的提示音Boop也会有小尾巴露出来）

**Comment by tisfeng** [comment]
感谢反馈，快十年的苹果用户了我居然不知道这个提示音可以设置修改 😂

系统默认的这个提示音真有点难听，，查了一下，这些个提示音时长确实不固定，短的才 0.1，长的有 1 秒多。

我测试的是默认的 Boop，静音 0.1 s 足够了，为了减少对用户的入侵干扰，所以这个值应该尽量小的，不知道为什么在你电脑上却不行？难道不同系统版本，这些提示音的长度也不同？这种系统环境兼容问题太累人了 😭

<img width="890" alt="image" src="https://user-images.githubusercontent.com/25194972/235360090-3982836a-07cd-465e-824c-018e4f53fc0a.png">

**Comment by tisfeng** [comment]
信不太过 ChatGPT，亲自打印看了一下，显示 Funk.aiff 时长竟然有 2 秒

<img width="766" alt="image" src="https://user-images.githubusercontent.com/25194972/235363638-4afac1b6-640f-4988-9180-174ff146b862.png">


<img width="296" alt="image" src="https://user-images.githubusercontent.com/25194972/235363800-a57a02f4-7a75-4cd3-bbfa-ff6181905230.png">

**Comment by cirexjohnson** [comment]
> 信不太过 ChatGPT，亲自打印看了一下，显示 Funk.aiff 时长竟然有 2 秒
> 
> <img alt="image" width="766" src="https://user-images.githubusercontent.com/25194972/235363638-4afac1b6-640f-4988-9180-174ff146b862.png">
> 
> <img alt="image" width="296" src="https://user-images.githubusercontent.com/25194972/235363800-a57a02f4-7a75-4cd3-bbfa-ff6181905230.png">

看来得找到更好的办法😂辛苦大大了。

**Comment by tisfeng** [comment]
音频虽然显示时长 2s，但实际测试有效播放时长并没有那么长， 我尝试把静音时长调到 0.8s 能满足当前所有的提示音。

暂时没找到方法可以从本质上解决这个问题，先这样吧。

**Comment by tisfeng** [comment]
你好，新版本已修复该问题 https://github.com/tisfeng/Easydict/releases/tag/1.3.1
