### ISSUE TITLE
“划词内容为空”该项设置，在浏览地图网页时，会造成电脑暂时静音

### ISSUE THREAD

**Issue by yaoppp** [tisfeng/Easydict#412]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

设置-通用-声音-“划词内容为空时”，开启这个选项后，在浏览地图网页时，鼠标左键拖动地图的话，系统会暂时静音。如果此时在聊天或者听音乐就会很受影响。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

设置-通用-声音-“划词内容为空时”，开启这个选项

### 截图

<img width="780" alt="image" src="https://github.com/tisfeng/Easydict/assets/16505311/e8e62932-9eb4-4c87-aeef-f3acfbb33980">

### 期望结果

解决划词为空时的程序响应

### 设备型号 && 系统版本

Apple M1 Pro, 14.3.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
你好，这是一个已知的问题，暂时没有很好的解决办法，我刚更新了 [FAQ ](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

<img width="980" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/735fd882-49d0-4548-a729-2984bdc44d27">
