### ISSUE TITLE
任务栏隐藏，无法进入设置界面

### ISSUE THREAD

**Issue by hotmob** [tisfeng/Easydict#413]
### 问题描述

我把任务栏隐藏了，设置各种快捷键呼出的都是迷你面板，求问如何打开设置界面

### 该问题是否可以稳定重现？

可重现

### 重现步骤

设置任务栏隐藏

### 期望结果

可以在迷你界面进入设置

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR

**Comment by hotmob** [comment]
有人知道快捷键（如果有）也请不吝赐教

**Comment by AkaShark** [comment]
You can try `cmd + ,` to open the settings page when mini query window display
