### ISSUE TITLE
🚀 功能建议：设置界面固定宽度

### ISSUE THREAD

**Issue by LaicZhang** [tisfeng/Easydict#414]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

避免选择不同选项卡时设置宽度同时变动

### 使用场景

以General选项卡的宽度为固定宽度，个人认为是更优雅的。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
请尝试使用新的 SwiftUI 设置页 https://github.com/tisfeng/Easydict/releases

后续旧的设置页将会进入维护状态，不会有大的功能变动。
