### ISSUE TITLE
🐞 最新版本, 划词翻译一直索要权限, 不可使用

### ISSUE THREAD

**Issue by YuXI-Chn** [tisfeng/Easydict#415]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

在Mac OS 14.2.1上, 更新到最新的版本, 划词翻译的时候 总是会提示要控制权限. 即使控制权限已开也会一直提示, 该功能不能正常使用.

### 该问题是否可以稳定重现？

可重现

### 重现步骤

我的两台mac 在更新后, 都出现了这个问题

### 截图

<img width="459" alt="Screenshot 2024-02-21 at 10 52 51" src="https://github.com/tisfeng/Easydict/assets/87346573/f8c669bc-8ef4-49a5-86dc-e9d078dfdfda">
<img width="481" alt="Screenshot 2024-02-21 at 10 53 10" src="https://github.com/tisfeng/Easydict/assets/87346573/1e10bf03-682a-454d-bcef-e4f2b9abfe75">
<img width="469" alt="Screenshot 2024-02-21 at 10 53 18" src="https://github.com/tisfeng/Easydict/assets/87346573/9210358f-9ada-492e-88d4-91652d57a2cf">

### 期望结果

划词翻译正常使用

### 设备型号 && 系统版本

Mac OS 14.2.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by AkaShark** [comment]
duplicate issues https://github.com/tisfeng/Easydict/issues/401

**Comment by WenBin-Zhang** [comment]
Me too！！重启，重装，都尝试过了

**Comment by YuXI-Chn** [comment]
> duplicate issues #401
Thanks for your reply!  It could be better to add some notes about this issue in README, as the solution is not straightforward and the issue may confuse a lot of users. Anyway, thank you so much for your reply to help me solve the problem!

**Comment by AkaShark** [comment]
In our [WIKI](https://github.com/tisfeng/Easydict/wiki ) FQA can see common issues. You can see 
https://github.com/tisfeng/Easydict/pull/411 In our next release you can click `feedback` to find the FQA. And https://github.com/tisfeng/Easydict/pull/418 will show common issues as tips.
