### ISSUE TITLE
🐞 反馈问题：Clear input when translating 在 Select Text Translate mode 不會清空了

### ISSUE THREAD

**Issue by jchuder** [tisfeng/Easydict#419]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

使用完 Select Text Translate mode 後,
若未選擇任何文字時再次按一次 Select Text Translate mode 的快捷鍵,
input 不會被清空

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1. 隨意選取文字並按下 Select Text Translate mode 快捷鍵
2. 會看到彈窗正常翻譯
3. 按下 Esc 或點取別處, Select Text Translate mode 視窗應該會消失
4. 此時不選取任何文字, 再次按下 Select Text Translate mode 快捷鍵
5. 會看到視窗沒有清空

### 截图

https://github.com/tisfeng/Easydict/assets/61487174/56f076c1-1f0e-49a4-90ea-ba8cec292b77

### 期望结果

未選取任何文字時 Select Text Translate mode 應該是清空的

### 设备型号 && 系统版本

Apple M1 (Sonoma 14.3.1)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
你好，默认未选中划词时会保留之前的查询结果，如果你希望清空，可以关闭这个选项。

<img width="816" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/428c38ae-6c12-490e-b63d-07993d144c0f">

**Comment by tisfeng** [comment]
[2.6.1](https://github.com/tisfeng/Easydict/releases/tag/2.6.1) 版本优化了相关代码。

注意，输入翻译和划词翻译虽然都能实现触发显示 Easydict 查询窗口，但它们是两个不同的动作，因此对于是否清除上次查询内容的设置选项都是独立的。

<img width="234" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0dd7162a-18bc-489e-b150-f025a35d0d33">

**Comment by jchuder** [comment]
在 2.6.1 版本中依照欄位關閉選項後該功能已可以照預期運作, 謝謝 🙏🏻

> 你好，默认未选中划词时会保留之前的查询结果，如果你希望清空，可以关闭这个选项。
> 
> <img alt="image" width="816" src="https://private-user-images.githubusercontent.com/25194972/307488179-428c38ae-6c12-490e-b63d-07993d144c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTg5NjYsIm5iZiI6MTcwODkxODY2NiwicGF0aCI6Ii8yNTE5NDk3Mi8zMDc0ODgxNzktNDI4YzM4YWUtNmMxMi00OTBlLWI2M2QtMDc5OTNkMTQ0YzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzMzc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YmJkMGY2ZTAxNTRlYjZlNWM2MDE4MzgxOTU4ZDMxODA0ZTU2NTgwNDc0NThkY2ZhYzc4NGU2NmMxYzY3MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k9sXPQyi31XS_tduwoU2PnK9fW-v-z9VVkrUCVs7_oI">
