### ISSUE TITLE
🚀 功能建議：增加快速切換語言(Swap languages)的快捷鍵

### ISSUE THREAD

**Issue by chaniatwang** [tisfeng/Easydict#42]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

Thanks for your project! 有時候為了確認翻譯品質，會切換語言(Swap languages)，希望可以增加一個快捷鍵來達成這件事。

<img width="326" alt="SCR-20230407-ulyu" src="https://user-images.githubusercontent.com/56515641/230638830-12203687-1dd6-4cd8-9927-cd5e9949314e.png">

**Comment by tisfeng** [comment]
可以，下次会添加几个快捷键，这个也一并添加上。

**Comment by tisfeng** [comment]
你好，新版本已添加了快捷键  https://github.com/tisfeng/Easydict/releases/tag/1.3.0
