### ISSUE TITLE
🐞 反馈问题：Release版本无法中翻译英

### ISSUE THREAD

**Issue by Rick630** [tisfeng/Easydict#420]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

翻译时，输入英文，可以翻译成中文，但是输入中文无法翻译成中文，但是使用代码编译的debug版本是正常的

### 该问题是否可以稳定重现？

可重现

### 重现步骤

输入中文

## Release版本
<img width="504" alt="image" src="https://github.com/tisfeng/Easydict/assets/11673596/1995c8c4-1e67-4d9b-972a-551178527eb6">

## 自编的Debug版本
<img width="504" alt="image" src="https://github.com/tisfeng/Easydict/assets/11673596/d64113d0-791c-4f48-a172-c706938f6fe6">

### 期望结果

能正常翻译

### 设备型号 && 系统版本

M1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by Rick630** [comment]
解决了，看了下代码发现有两个window，在Input Translate窗口有一个设置toLanguage的地方，在这里设置成auto就可以了
![image](https://github.com/tisfeng/Easydict/assets/11673596/a8a8248b-cd47-4c37-be6f-aea6dd8987ff)

PS：
这里的设计比较奇怪，readme里并没有说⌥ + A 和 ⌥ + F的区别，不仔细看可能真不知道⌥ + A 里的设置会影响 miniwindow的配置，建议把这个设置放入setting里面，或者在mini window也显示这个设置cell

再次感谢作者开发这么优秀的工具

**Comment by tisfeng** [comment]
明白了，感谢反馈，这里后面会改进的。
