### ISSUE TITLE
切换到 SwiftUI App 模式，服务中各种翻译模型的选中状态不稳定

### ISSUE THREAD

**Issue by KrabsWong** [tisfeng/Easydict#423]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

勾选不同的翻译服务之后，设置窗口失去焦点，再重新获得焦点之后，翻译服务的选中状态异常。
EasyDict 是 2.6.0 版本

### 该问题是否可以稳定重现？

不可稳定重现

### 重现步骤

暂时还没能找到稳定重现的路径，但是又没找到什么规律。

1. 以 SwiftUI App 模式起动之后，切换到“服务”。
2. 勾选有道，OpenAI翻译，Gemini翻译（因为 Gemini 翻译是在最下边，需要稍微滚动下。）
3. 选中 OpenAI，准备设置相关的 key 等信息
4. 点击设置窗口之外，让设置窗口失去焦点
5. 重新点击设置页面（比如点击整个设置页面的标题部分）
6. 这时候一定几率会发现，选中的 OpenAI 翻译那一行的开关是灰色的（失去焦点效果，但是依然保持选中状态），底部 gemini 变成了未选中状态

第6步的表现，没办法稳定重现，有时候是完全正常，有时候是 6 的表现，有时候又会是 gemini 选中+失去焦点的状态。

### 截图

<img width="892" alt="image" src="https://github.com/tisfeng/Easydict/assets/12368943/b7cc4f5c-153c-47ac-9c7b-04b81d69080c">

### 期望结果

选中状态保持正常，设置窗口失去焦点/获得焦点之后，相关的配置项展示正确

### 设备型号 && 系统版本

Apple M1 Pro, macOS 14.2.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
@phlpsong 看一下这个问题

**Comment by phlpsong** [comment]
Yes, the easiest way to reproduce this is to toggle the service state and move focus to another app, then switch focus back, and the enable state revert.

**Comment by tisfeng** [comment]
[2.6.1](https://github.com/tisfeng/Easydict/releases/tag/2.6.1) 版本已修复该问题。
