### ISSUE TITLE
🐞 反馈问题：系統設置語言變成英文，怎麼改回中文？

### ISSUE THREAD

**Issue by aura9595** [tisfeng/Easydict#430]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

我已經搜尋過，但沒有找到對應解決問題，還請協助幫助
因為我更新最新版本之後，我的介面都變成是英文了，想請問怎麼改回中文？
![image](https://github.com/tisfeng/Easydict/assets/161396695/05aeee1a-f9e9-4ce1-baff-af45968ee948)
![image](https://github.com/tisfeng/Easydict/assets/161396695/c5cd7762-7be9-499b-bacb-59d4062e64ec)

### 该问题是否可以稳定重现？

可重现

### 重现步骤

重啟過也重新下載了
還是一樣變成英文版面

### 截图

![image](https://github.com/tisfeng/Easydict/assets/161396695/5b4a7ec1-1878-4947-b73d-db46f81f408f)

### 期望结果

希望變回中文版就好

### 设备型号 && 系统版本

Apple M1 , macOS 14.0

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
参考 https://github.com/tisfeng/Easydict/issues/84#issuecomment-1964251707

**Comment by tisfeng** [comment]
后面将会支持应用内修改显示语言 https://github.com/tisfeng/Easydict/issues/348

**Comment by aura9595** [comment]
謝謝
