### ISSUE TITLE
🐞 反馈问题：重大 BUG，软件频繁闪退

### ISSUE THREAD

**Issue by Sligcm** [tisfeng/Easydict#432]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

OS：14.3.1 (23D60)
CPU：Apple M2 Max。
Easydict 版本：2.6.1。
从升级到这个版本之后，刚开始的时候发现原来设置好的快捷键没了，重新设置后，用快捷键调用出了软件窗口，但是发现不能再次用快捷键调用出窗口了。之后重复了几次，现在打开软件，顶部菜单栏能看到软件图标，但是只要使用快捷键调用窗口或者手工点击图标出现的菜单里的各种功能，软件立马就闪退了。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

OS：14.3.1 (23D60)
CPU：Apple M2 Max。
Easydict 版本：2.6.1。
从升级到这个版本之后，刚开始的时候发现原来设置好的快捷键没了，重新设置后，用快捷键调用出了软件窗口，但是发现不能再次用快捷键调用出窗口了。之后重复了几次，现在打开软件，顶部菜单栏能看到软件图标，但是只要使用快捷键调用窗口或者手工点击图标出现的菜单里的各种功能，软件立马就闪退了。

### 截图

https://github.com/tisfeng/Easydict/assets/2296912/92b812b3-9db2-44b5-8d8f-f7bd282a83ea

### 期望结果

正常使用。

### 设备型号 && 系统版本

Apple M2 Max，14.3.1 (23D60)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
如果是应用崩溃问题，请务必提供崩溃日志，菜单图标 -> 帮助 -> 导出日志。（日志目录：~/Library/Caches/com.izual.Easydict/MMLogs）

**Comment by Sligcm** [comment]
> 如果是应用崩溃问题，请务必提供崩溃日志，菜单图标 -> 帮助 -> 导出日志。（日志目录：~/Library/Caches/com.izual.Easydict/MMLogs）

[Easydict log 2024-02-28 10-10-54-783.zip](https://github.com/tisfeng/Easydict/files/14427778/Easydict.log.2024-02-28.10-10-54-783.zip)

你好，已上传。

**Comment by tisfeng** [comment]
看了一下崩溃日志，但没看到具体原因 😓

请问你是否开启新的 SwiftUI 设置页？尝试过重装之前的版本吗

**Comment by tisfeng** [comment]
> 从升级到这个版本之后，刚开始的时候发现原来设置好的快捷键没了

@AkaShark 麻烦你看下，这个问题是否和快捷键有关。

**Comment by Sligcm** [comment]
> 看了一下崩溃日志，但没看到具体原因 😓
> 
> 请问你是否开启新的 SwiftUI 设置页？尝试过重装之前的版本吗

SwiftUI 设置页是开启的。

我从最新版按版本号倒序进行重新安装，直到 2.4.1 这个版本才可以正常使用。
我有点奇怪的是，每次最新版我都会及时安装，基本上工作日每天都会使用。
我记得很清楚，就是升级到 2.6.1 之后快捷键变了，我重新设置了一下快捷键之后没多久就出现了闪退的情况。

而且回退重新安装测试的过程中，我发现 2.6+ 版本的快捷键是一套配置，2.6- 版本的快捷键又是一套配置。应该存在新老两套配置，不知道是不是和这个有关系。

为了使用最新版，我最终用卸载工具完全卸载了 easydict，然后安装最新版 2.6.1 后重新设置了快捷键，目前一切正常，所以我怀疑是新老版本的配置冲突之类的问题导致的崩溃闪退，敬请参考。

**Comment by AkaShark** [comment]
> > 看了一下崩溃日志，但没看到具体原因 😓
> > 请问你是否开启新的 SwiftUI 设置页？尝试过重装之前的版本吗
> 
> SwiftUI 设置页是开启的。
> 
> 我从最新版按版本号倒序挨个版本进行重新安装，直到回退到 2.4.1 这个版本才可以正常使用。 我有点奇怪的是，每次最新版我都会及时安装，基本上工作日每天都会使用。 我记得很清楚，就是升级到 2.6.1 之后快捷键变了，我重新设置了一下快捷键之后没多久就出现了闪退的情况。
> 
> 而且回退重新安装测试的过程中，我发现 2.6+ 版本的快捷键是一套配置，2.6- 版本的快捷键又是一套配置。应该存在新老两套配置，不知道是不是和这个有关系。
> 
> 为了使用最新版 easydict，我最终用卸载工具完全卸载了 easydict，然后安装了最新版 2.6.1 之后重新设置了快捷键，目前一切正常，所以我怀疑是新老版本的配置冲突之类的问题导致的崩溃闪退，敬请参考。

是这样的SwiftUI与旧版本的快捷键是两套配置，所以刚更新的到默认开启SwiftUI版本的Easydict会发现快捷键都是空的，我等下检查下是不是两个快捷键版本冲突导致的问题。

**Comment by Sligcm** [comment]
> > > 看了一下崩溃日志，但没看到具体原因 😓
> > > 请问你是否开启新的 SwiftUI 设置页？尝试过重装之前的版本吗
> > 
> > 
> > SwiftUI 设置页是开启的。
> > 我从最新版按版本号倒序挨个版本进行重新安装，直到回退到 2.4.1 这个版本才可以正常使用。 我有点奇怪的是，每次最新版我都会及时安装，基本上工作日每天都会使用。 我记得很清楚，就是升级到 2.6.1 之后快捷键变了，我重新设置了一下快捷键之后没多久就出现了闪退的情况。
> > 而且回退重新安装测试的过程中，我发现 2.6+ 版本的快捷键是一套配置，2.6- 版本的快捷键又是一套配置。应该存在新老两套配置，不知道是不是和这个有关系。
> > 为了使用最新版 easydict，我最终用卸载工具完全卸载了 easydict，然后安装了最新版 2.6.1 之后重新设置了快捷键，目前一切正常，所以我怀疑是新老版本的配置冲突之类的问题导致的崩溃闪退，敬请参考。
> 
> 是这样的SwiftUI与旧版本的快捷键是两套配置，所以刚更新的到默认开启SwiftUI版本的Easydict会发现快捷键都是空的，我等下检查下是不是两个快捷键版本冲突导致的问题。

好的，辛苦了。

**Comment by xiaoshengwpp** [comment]
> 如果是应用崩溃问题，请务必提供崩溃日志，菜单图标 -> 帮助 -> 导出日志。（日志目录：~/Library/Caches/com.izual.Easydict/MMLogs）

M2 Pro 芯片上 升级2.6.1 版本后 进程在  但是无任何反馈 也没顶栏的图标。软件打不开的状态

**Comment by AkaShark** [comment]
> > 如果是应用崩溃问题，请务必提供崩溃日志，菜单图标 -> 帮助 -> 导出日志。（日志目录：~/Library/Caches/com.izual.Easydict/MMLogs）
> 
> M2 Pro 芯片上 升级2.6.1 版本后 进程在 但是无任何反馈 也没顶栏的图标。软件打不开的状态

可以提供下崩溃日志，菜单图标 -> 帮助 -> 导出日志。（日志目录：~/Library/Caches/com.izual.Easydict/MMLogs）

**Comment by AkaShark** [comment]
> > 看了一下崩溃日志，但没看到具体原因 😓
> > 请问你是否开启新的 SwiftUI 设置页？尝试过重装之前的版本吗
> 
> SwiftUI 设置页是开启的。
> 
> 我从最新版按版本号倒序挨个版本进行重新安装，直到回退到 2.4.1 这个版本才可以正常使用。 我有点奇怪的是，每次最新版我都会及时安装，基本上工作日每天都会使用。 我记得很清楚，就是升级到 2.6.1 之后快捷键变了，我重新设置了一下快捷键之后没多久就出现了闪退的情况。
> 
> 而且回退重新安装测试的过程中，我发现 2.6+ 版本的快捷键是一套配置，2.6- 版本的快捷键又是一套配置。应该存在新老两套配置，不知道是不是和这个有关系。
> 
> 为了使用最新版 easydict，我最终用卸载工具完全卸载了 easydict，然后安装了最新版 2.6.1 之后重新设置了快捷键，目前一切正常，所以我怀疑是新老版本的配置冲突之类的问题导致的崩溃闪退，敬请参考。

我看了下所有的Crash都是
![CleanShot 2024-03-09 at 23 52 37@2x](https://github.com/tisfeng/Easydict/assets/26460192/f135682e-65c1-4730-9089-993f28b166ef)
感觉是在打开主窗口的时候走到tableView代理方法的时候崩了的，我并没复现，还可以多提供一些复现的条件么？
快捷键设置的话我看着新旧两套是分离的key值都是不一样的应该也不会影响到。

**Comment by Sligcm** [comment]
> 抱歉，我最终用卸载工具完全卸载了 easydict，所以没法复现了。

**Comment by tisfeng** [comment]
> > 看了一下崩溃日志，但没看到具体原因 😓
> > 请问你是否开启新的 SwiftUI 设置页？尝试过重装之前的版本吗
> 
> SwiftUI 设置页是开启的。
> 
> 我从最新版按版本号倒序挨个版本进行重新安装，直到回退到 2.4.1 这个版本才可以正常使用。 我有点奇怪的是，每次最新版我都会及时安装，基本上工作日每天都会使用。 我记得很清楚，就是升级到 2.6.1 之后快捷键变了，我重新设置了一下快捷键之后没多久就出现了闪退的情况。
> 
> 而且回退重新安装测试的过程中，我发现 2.6+ 版本的快捷键是一套配置，2.6- 版本的快捷键又是一套配置。应该存在新老两套配置，不知道是不是和这个有关系。
> 
> 为了使用最新版 easydict，我最终用卸载工具完全卸载了 easydict，然后安装了最新版 2.6.1 之后重新设置了快捷键，目前一切正常，所以我怀疑是新老版本的配置冲突之类的问题导致的崩溃闪退，敬请参考。

@AkaShark 你按这个步骤尝试一下，看能否复现问题。

如果不能复现，就当小概率问题，暂时忽略。后面如果还有用户报这个问题，我们再来看。

**Comment by AkaShark** [comment]
是的我那天就是按照这个复现步骤搞得，但是没复现的了

**Comment by tisfeng** [comment]
清理 issue，没有后续反馈的就先关闭了，如果再遇到问题，请另外提 issue。

**Comment by Mickychen00** [comment]
我现在最新版本的easydict也是经常闪退，需要重新打开

**Comment by tisfeng** [comment]
> 我现在最新版本的easydict也是经常闪退，需要重新打开

请单独开 issue 反馈，如果能提供详细准确的信息，能够帮助开发者定位或复现问题，相信我们会很快修改它的。
