### ISSUE TITLE
🚀 功能建议：添加自定义prompt以及折叠未选中服务

### ISSUE THREAD

**Issue by tianzhuwei** [tisfeng/Easydict#434]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

感谢大佬提供这款产品开源使用
此次开issue希望添加两个功能
1. 添加自定义prompt，看之前issue也有提到过类似功能建议的，我希望可以添加多个prompt，从而实现不同的功能。如一个基础的翻译prompt，另一个prompt是用于优化改写自己写的英文语句，即可以翻译又可以改写均是通过OpenAI提供的api实现，这个功能目前是我的刚需；
2. 另一个功能属于锦上添花，即把未选中的翻译服务折叠，将选中的服务自动置顶，未选中服务在选中之后，这样排序起来也会更为简单；

### 使用场景

多个prompt的使用场景刚刚也提到，即既可以提供翻译服务，又可以提供改写服务，即一个OpenAI的服务创建多个实例。

### 实现方案（可选）

这个功能可以直接再复制一下现有OpenAI的服务，命令其他即可（这是我想当然的想法哈）
后续应该可以做成添加任意多的prompt，即多个功能窗口

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
了解，等重新完这部分功能后，会支持自定义 prompt 的，创建多个 OpenAI 服务实例这个也会考虑。

**Comment by tisfeng** [comment]
我来尝试一下支持自定义 prompt 🙂

**Comment by y4code** [comment]
已关注这个 FR，如果有动静了请踢我一脚

**Comment by tisfeng** [comment]
这个已经实现了，周末看情况发个新版本。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。
