### ISSUE TITLE
The query icon with "Force get selected text when auto get selected text failed (Experimental)" no longer appearing

### ISSUE THREAD

**Issue by gofa67** [tisfeng/Easydict#435]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

The query icon with the feature "Force get selected text when auto get selected text failed (Experimental)" is no longer appearing after V2.5.0.  

### 该问题是否可以稳定重现？

可重现

### 重现步骤

disable/enable the features of 
Auto show query icon after selecting text 
Force get selected text when auto get selected text failed (Experimental)

### 截图

![Pasted_Image_2_29_24__2_03 PM-2](https://github.com/tisfeng/Easydict/assets/40278852/a51af859-6d4a-4bc8-9941-580f9ebac43e)

### 期望结果

The feature is very useful.  Please fix it.  Thanks.

### 设备型号 && 系统版本

Macbook Air M1, macOS 14.3.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
Maybe Accessibility Service is corrupted, try remove Accessibility Service permission of Easydict in your System Setting, and then re-authorize again.

Refer: https://github.com/tisfeng/Easydict/wiki/FAQ#why-does-macos-still-pop-up-asking-for-permissions-even-though-i-have-given-easydict-the-accessibilityscreen-recording-permissions

**Comment by gofa67** [comment]
case closed
