### ISSUE TITLE
🚀 功能建议：建议增加鼠标查询开关的全局快捷键

### ISSUE THREAD

**Issue by LittleFishLove** [tisfeng/Easydict#436]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

建议增加鼠标查询的全局开关快捷键，在不需要进行查询的时候，鼠标划线文本不会自动显示easydict的图标。因为在使用中该图标会影响到cmd+c复制的有效性，可能导致按一次快捷键无法复制到内容的问题。

### 使用场景

在Windows下欧路词典有类似功能，因此不影响使用。在MacOS下使用easydict常常因为鼠标查询导致复制内容失败，且无一个全局快捷键去开关划词翻译功能，带来了体验降低。

### 实现方案（可选）

增加鼠标查询开关的快捷键

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
没太理解，目前不是有是否启用鼠标划词的选项吗？

> 因为在使用中该图标会影响到cmd+c复制的有效性，可能导致按一次快捷键无法复制到内容的问题。

只有少部分不支持 [系统 Accessibility 取词](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E6%9F%90%E4%BA%9B%E5%BA%94%E7%94%A8%E4%B8%AD%E5%8F%96%E8%AF%8D%E6%96%87%E6%9C%AC%E4%B8%BA%E7%A9%BA) 的应用才会使用 `Cmd + C` 取词，如果觉得有影响，可以在设置中禁止这些应用。

**Comment by LittleFishLove** [comment]
抱歉没有表达清楚。首先是鼠标划词选项确实有，但是我希望有一个全局快捷键来开关鼠标划词，目前只能打开设置点击进行开关。其次，我说的”影响CMD+C复制有效性“指的是：当我用鼠标划线选中一段文字时，由于此时Easydict的鼠标划词功能开启，会显示一个翻译图标，此时按“CMD+C"进行复制，会复制不到文字。需要再按一次或者等一小会儿。此外，还存在很多场景不想开启Easydict的鼠标划词翻译；但是切换应用后又想立马使用。因此，我希望增加鼠标划词翻译的全局快捷键，这样可以方便的一键开启或者关闭这项功能，即我希望下图选项有一个全局快捷开关：
<img width="754" alt="image" src="https://github.com/tisfeng/Easydict/assets/35796964/2ad4b724-6d6f-42d2-89fe-8fea6c007368">

**Comment by tisfeng** [comment]
ok，了解了，这个我们先考虑一下。

**Comment by tisfeng** [comment]
这个可以加，先打开放这里吧。

**Comment by tisfeng** [comment]
想了想，这个功能太小众了，我们先聚焦其他高优先级功能，这个先关了。
