### ISSUE TITLE
🚀 功能建议：希望加入Groq模型的API

### ISSUE THREAD

**Issue by slipbox** [tisfeng/Easydict#439]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

feature
强烈希望作者能够将 Groq 模型引入

描述 Motivation
因为Groq的翻译速度太快了，而且准确度也很高，API也很好申请。如果能够引用这个模型，简直就是一场飞跃，希望作者能够将其带入，谢谢！（每天都在使用这个产品，非常棒👍）

### 使用场景

文本翻译

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
试了一下 [Groq](https://console.groq.com/docs/quickstart)，响应速度快到离谱，这家公司有点东西 🤯

但似乎目前只支持 mixtral-8x7b-32768 和 llama2-70b-4096 模型，而这两个模型对中文翻译都不太友好 😓

https://wow.groq.com/

<img width="1431" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/df120153-4786-452e-ab42-be2e38e4e688">

**Comment by tisfeng** [comment]
[Groq](https://console.groq.com/docs/openai) 也兼容 OpenAI 接口，如果你想尝试 Groq，可以直接修改目前 OpenAI 翻译的配置来使用。

这个 one api 还没完成，当前请用 [命令行](https://github.com/tisfeng/Easydict?tab=readme-ov-file#openai-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0) 方式修改模型参数。

稍后会支持用户任意添加新的自定义 OpenAI 翻译服务，并修改配置项。

<img width="816" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0499f0a2-dd31-47fa-9468-a755817727bd">

**Comment by quanru** [comment]
> [Groq](https://console.groq.com/docs/openai) 也兼容 OpenAI 接口，如果你想尝试 Groq，可以直接修改目前 OpenAI 翻译的配置来使用。
> 
> 这个 one api 还没完成，当前请用 [命令行](https://github.com/tisfeng/Easydict?tab=readme-ov-file#openai-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0) 方式修改模型参数。
> 
> 稍后会支持用户任意添加新的自定义 OpenAI 翻译服务，并修改配置项。
> 
> <img alt="image" width="816" src="https://private-user-images.githubusercontent.com/25194972/309987192-0499f0a2-dd31-47fa-9468-a755817727bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDM3MDgsIm5iZiI6MTcwOTcwMzQwOCwicGF0aCI6Ii8yNTE5NDk3Mi8zMDk5ODcxOTItMDQ5OWYwYTItZGQzMS00N2ZhLTk0NjgtYTc1NTgxNzcyN2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzA5MDA5MzUxZjFiMTczNTcyYzc1Y2FiMmFlNjQyYTBkNWY5M2ZlMjlkYTA3MmVmYTYwZmU5MGRhYWRmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SDq2ZC1R6eH0s4kK7E1gC1ZDUtLBEpYc9hM2k0TkNQQ">

命令提示不存在：
![image](https://github.com/tisfeng/Easydict/assets/11739753/ce1710d0-1d7e-4a1d-be55-be5746e10663)

**Comment by phlpsong** [comment]
> > [Groq](https://console.groq.com/docs/openai) 也兼容 OpenAI 接口，如果你想尝试 Groq，可以直接修改目前 OpenAI 翻译的配置来使用。
> > 这个 one api 还没完成，当前请用 [命令行](https://github.com/tisfeng/Easydict?tab=readme-ov-file#openai-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0) 方式修改模型参数。
> > 稍后会支持用户任意添加新的自定义 OpenAI 翻译服务，并修改配置项。
> > <img alt="image" width="816" src="https://private-user-images.githubusercontent.com/25194972/309987192-0499f0a2-dd31-47fa-9468-a755817727bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDM3MDgsIm5iZiI6MTcwOTcwMzQwOCwicGF0aCI6Ii8yNTE5NDk3Mi8zMDk5ODcxOTItMDQ5OWYwYTItZGQzMS00N2ZhLTk0NjgtYTc1NTgxNzcyN2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzA5MDA5MzUxZjFiMTczNTcyYzc1Y2FiMmFlNjQyYTBkNWY5M2ZlMjlkYTA3MmVmYTYwZmU5MGRhYWRmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SDq2ZC1R6eH0s4kK7E1gC1ZDUtLBEpYc9hM2k0TkNQQ">
> 
> 命令提示不存在： ![image](https://private-user-images.githubusercontent.com/11739753/310374613-ce1710d0-1d7e-4a1d-be55-be5746e10663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ0OTMsIm5iZiI6MTcwOTcyNDE5MywicGF0aCI6Ii8xMTczOTc1My8zMTAzNzQ2MTMtY2UxNzEwZDAtMWQ3ZS00YTFkLWJlNTUtYmU1NzQ2ZTEwNjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZTE2YjRhMTAxZDg5MWZmYTcxODY0MGVkYWVjMTQyNmJkNWE5NGFjYWUyZTRhYzkwZGEzNjk0ODg1MTFlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lDo7-YAJfelLI8SQaY67sMqCkrf3Z1ugucYwUifIsOg)

Input this command line in query window like below:

<img width="330" alt="image" src="https://github.com/tisfeng/Easydict/assets/103433299/a9dad564-b46a-4abb-b7cf-82b59eeff6c7">

**Comment by quanru** [comment]
still not working:

![image](https://github.com/tisfeng/Easydict/assets/11739753/8a28eeec-8f8a-4a71-b574-680b70465d38)

![image](https://github.com/tisfeng/Easydict/assets/11739753/e0e41299-5c83-4b94-8d99-af1dae2672d0)

**Comment by tisfeng** [comment]
其实已经修改成功了，只是设置服务页这里不会显示，你可以用 easydict://readValueOfKey? EZOpenAIModelKey 查看当前设置的模型。

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已添加了一个自定义 OpenAI 服务，可通过配置直接使用 Groq。
