### ISSUE TITLE
UI建议：给NSMenuItem添加图标，如图所示

### ISSUE THREAD

**Issue by code4you2021** [tisfeng/Easydict#44]
![CleanShot 2023-04-16 at 19 32 42@2x](https://user-images.githubusercontent.com/83153991/232307069-e5cd1bdb-eb39-4fb2-9ecc-50a28a3a6c6a.png)

希望给NSMenuItem添加图标，这样看着会更好看一点

```swift
func makeMenuItem(title: String, action: Selector?, imageName: String?, keyEquivalent: String)
  -> NSMenuItem
{
  let menuItem = NSMenuItem(title: title, action: action, keyEquivalent: keyEquivalent)

  if let imageName = imageName {
    menuItem.image = NSImage(named: imageName)
    menuItem.image?.isTemplate = true
  }

  return menuItem
}
```

图片尺寸：
1x图片：
图片大小：24 * 24
内置图标大小：16 * 16

2x图片尺寸：
图片大小：48 * 48
内置图标大小：32 * 32

PS:
这个尺寸是从CleanShot X的资源文件解包找到的，不能100%确定。

图标预览

![menubarAllInOne24x24](https://user-images.githubusercontent.com/83153991/232307901-cecc7085-744c-4a57-a009-c237bc9e94ed.png)

图标下载

[icon.zip](https://github.com/tisfeng/Easydict/files/11242160/icon.zip)

**Comment by tisfeng** [comment]
可以，感谢反馈。

**Comment by tisfeng** [comment]
你好，新版本已添加 https://github.com/tisfeng/Easydict/releases/tag/1.3.1

<img width="236" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/50d7aba1-aef8-4374-9401-8df98dae1a3c">
