### ISSUE TITLE
dev: rewrite About new

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#449]
We want to rewrite the About view in Settings to look modern and in a horizontal layout

Some apps with good about views we could take as reference
- Xcode (Apple)
- Pages (Apple)
- [Cork](https://github.com/buresdv/Cork)
- [CodeEdit](https://github.com/CodeEditApp/CodeEdit)
- [Proxyman](https://proxyman.io)

**Comment by tisfeng** [comment]
Xcode's About  looks very concise and the layout is good, we can replace the two buttons below with GitHub links and contributors.

<img width="566" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/eef7b705-aa3f-4462-9f19-5b8ff08f54ef">

**Comment by tisfeng** [comment]
Also, we need to unify these two about pages.

<img width="1384" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/2c0e8f1e-3dc0-48b4-8438-5795c381c3cf">

**Comment by Jerry23011** [comment]
The one from the main window seems to be autogenerated, I’m wondering how&where I can add it 🤔在 2024年3月9日，21:30，Tisfeng ***@***.***> 写道：﻿
Also, we need to unify these two about pages.
image.png (view on web)
