### ISSUE TITLE
🐞 反馈问题: Unable to get translation in Gemini sometimes

### ISSUE THREAD

**Issue by pxy0592** [tisfeng/Easydict#451]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

Sometimes Gemini can't translate. The access to the internet is in China.

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1. Add Gemini API key
2. Enable Gemini translate
3. Input an English sentence that want to translate
4. Try more times to translate any English sentence
5. 

### 截图

Here's the snapshot while EasyDict translated an English sentence.

![image](https://github.com/tisfeng/Easydict/assets/7930555/72ae23c9-af67-4240-bf82-2ce03cea2955)

### 期望结果

Able to translate any English sentence using Gemini Translate service.

### 设备型号 && 系统版本

Apple M1 Pro, macOS 14.3.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
Gemini appears to be not supported in China. 

Please use [supported countries and regions](https://support.google.com/gemini/answer/13575153?sjid=2321712859127962296-NA)' IP proxy to access Gemini.

**Comment by tisfeng** [comment]
Another solution is to use a proxy URL to request Gemini, e.g. refer to [StakeVladDracula](https://github.com/Herm-Studio/StakeVladDracula) .
