### ISSUE TITLE
🐞 反馈问题：快捷键划词翻译，窗口高度计算有误，出现大片空白

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#452]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

目测是这个 #418  PR 导致，几乎每次都会出现。

https://github.com/tisfeng/Easydict/assets/25194972/2c5ed4e9-034c-4b8c-9a5a-730bacbee1d4

### 该问题是否可以稳定重现？

可重现

### 重现步骤

*

### 截图

<img width="456" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/6324fe2b-1e3d-4ca2-bb1f-ca3332a19463">

### 期望结果

*

### 设备型号 && 系统版本

*

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
这个建议 https://github.com/tisfeng/Easydict/issues/404 是可以的，但感觉实现方式不是很好，之前测试偶尔会出现 tips view 一闪而过的情况。

这段代码很丑陋，嵌套逻辑太多，容易出问题。

```objc
else if ([self isTipsCellRow:row]) {
        if (!self.tipsCell) {
            height = 100;
        } else {
            height = [self.tipsCell cellHeight];
        }
    }
```

**Comment by tisfeng** [comment]
每次快捷键划词查询时，会先重置 queryText，可能会导致这里误判。

```objc
- (BOOL)isShowTipsView {
    if (Configuration.shared.disableTipsView) {
        return NO;
    }
    if (EZ_isEmptyString(self.queryModel.queryText) && 
        !self.hasShowTips &&
        self.queryModel.actionType != EZActionTypeInputQuery) {
        return YES;
    }
    return NO;
}
```

**Comment by AkaShark** [comment]
okay 我晚点看看这个问题

**Comment by tisfeng** [comment]
有时候 OCR 截图翻译也会莫名出现 tips view，就很怪。

<img width="975" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/e4a0c5be-0c3c-4973-884b-53884d58b887">

**Comment by tisfeng** [comment]
如果暂时不能解决，我们可以考虑先 revert 掉这个 feature。

**Comment by AkaShark** [comment]
okay 这俩天感冒了，一直没来得及看下，稍后我会看看，如果解决起来比较复杂的话，我先把这个feature revert掉

**Comment by tisfeng** [comment]
ok，先保重身体。

**Comment by AkaShark** [comment]
sorry 最近有点忙... 这个issue 会周末解决下~

**Comment by tisfeng** [comment]
待修复好这个问题后，你可以用 tips view 优化一下 OCR 错误显示  https://github.com/tisfeng/Easydict/issues/478 。

**Comment by tisfeng** [comment]
另外，这个错误提示内容可以修改一下，不要使用随机，改成参数指定错误类型，这样方便其他地方使用。

**Comment by AkaShark** [comment]
okay
