### ISSUE TITLE
🚀 Feature Request: Support eudic2 shortcut

### ISSUE THREAD

**Issue by Roiocam** [tisfeng/Easydict#454]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Feature description

<img width="430" alt="截屏2024-03-13 13 42 52" src="https://github.com/tisfeng/Easydict/assets/26020358/852134b6-7794-40fc-afae-66728a1c006d">

### Use case

We already have eudic shortcut, it will be great that support eudic2 too.

<img width="784" alt="截屏2024-03-13 13 44 15" src="https://github.com/tisfeng/Easydict/assets/26020358/73a65e60-1ec4-448d-92b6-4279d1c47b24">

### Are you willing to submit a PR to implement this feature

- [x] I'm willing to submit PR

**Comment by Roiocam** [comment]
I will be trying to resolve this issue later.

**Comment by Roiocam** [comment]
Solved in #455

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。
