### ISSUE TITLE
🚀 功能建议：希望能设置文本识别窗口的折叠，优化阅读效率

### ISSUE THREAD

**Issue by githublue123** [tisfeng/Easydict#46]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

希望能折叠文本识别结果的窗口，在长文字翻译时，减少原始文本的视觉占比，更快锁定翻译区域；（当前的识别结果窗口高度上限还是太高）

### 使用场景（可选）

目前ocr和文字识别的准确率很高了，基本不太需要矫正识别结果，已经习惯直奔翻译区域而去，而且往往需要矫正的时候不如重新截图或复制文本；

在长文字或者多段落文本的情况下，识别结果窗口占比很大，所以希望可以优化视窗的阅读效率

### 实现方案（可选）

可以考虑沿用翻译区域的折叠逻辑，折叠状态仅显示（缩略文本）o（r功能标题），展开状态是当前版本的窗口效果；

**Comment by tisfeng** [comment]
收到，感谢反馈，稍后我优化一下。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。

现在可以隐藏输入文本显示框。
