### ISSUE TITLE
🚀 Feature Request: A stickier pin? 

### ISSUE THREAD

**Issue by thesla13** [tisfeng/Easydict#460]
Hey there!

When using Easydict, sometimes I would like to tinker with the translations provided further and go to the respective service's webpage. Say, Google's or Bing's. Your app, blissfully, does have a convenient link button for this.

But then at other times I would like to look at both. But when I click the link button of any one service, ED's floating window would close, and I would have to run OCR or select the needed text again. Even when ED's window is pinned, it would still close after clicking the link button.

Could you please consider making the pin button stickier? Harder? Stronger? Source some Vanadium steel for it? Tungsten? Unobtainium? Would be cool!

Thank you so much!

**Comment by tisfeng** [comment]
> I would have to run OCR or select the needed text again.

You can use `Input Translate` or `Show Mini Window` to see previous query results.

<img width="287" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/4c7c8a16-84ed-4d2d-b830-ae490d5f3e73">

**Comment by tisfeng** [comment]
> Even when ED's window is pinned, it would still close after clicking the link button.

Thank you for your reminder, I thought about it, if the window is pinned, it shouldn't be closed.

Later, I will modify this logic.

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。
