### ISSUE TITLE
DeepL 自定义 API 支持 JSON 格式的参数

### ISSUE THREAD

**Issue by NieXi** [tisfeng/Easydict#464]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

自定义 API 使用的是 JSON 格式的参数，看起来当前还不支持

### 使用场景

使用第三方的接口，只支持 JSON 格式的参数

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
没看懂，你能详细描述一下你的想法吗？

**Comment by NieXi** [comment]
不好意思，描述的不清楚。

是这样的，我在 Easydict 中使用第三方 DeepL 接口报错了。因为第三方 DeepL API 只支持 JSON 格式的参数，curl 请求如下：
```
curl -X POST http://localhost:1188/translate \
-H "Content-Type: application/json" \
-H "Authorization: Bearer your_access_token" \
-d '{
    "text": "Hello, world!",
    "source_lang": "EN",
    "target_lang": "DE"
}'
```
然后我看 Easydict 调用 DeepL 接口是用 form 传参的，希望能支持 JSON 格式的传参

**Comment by tisfeng** [comment]
ok，我查一下。

**Comment by tisfeng** [comment]
看了一下代码，目前 Easydict 目前是支持官方 [DeepL URL-encoded](https://www.deepl.com/docs-api) 数据格式，这个没问题。

你上面接口是 [DeepLX](https://github.com/OwO-Network/DeepLX) 生成的吧，我本地安装跑了一下，发现它这个好像支持 JSON 格式，并且返回的数据格式也和 DeepL 官方 API 不一样 🥲

我这边可以改成 JSON 格式，但意义不大，这边只是客户端，我觉得这里应该向服务端 [DeepLX](https://github.com/OwO-Network/DeepLX)  提请求，让它支持 form 格式，并且最好返回的数据格式能兼容官方 API，这样能更方便接口在各种第三方平台使用。

**Comment by NieXi** [comment]
好的，谢谢。那我自己先中间套一层好了😂

**Comment by tisfeng** [comment]
可能不需要了，DeepLX 那边将会支持 DeepL 官方 API https://github.com/OwO-Network/DeepLX/issues/99#issuecomment-2009928287

**Comment by missuo** [comment]
It is already supported in the latest version [v0.9.1](https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.1).

**Comment by NieXi** [comment]
好的，谢谢^_^
