### ISSUE TITLE
🐞 Bug Report: macOS Big Sur 11.7.10 系统下无法填写  OpenAI  key

### ISSUE THREAD

**Issue by wangbiye** [tisfeng/Easydict#465]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

<img width="586" alt="Snipaste_2024-03-19_22-06-44" src="https://github.com/tisfeng/Easydict/assets/9958811/2f8cd164-127c-41c5-bcfd-a2aad716c835">
<img width="350" alt="Snipaste_2024-03-19_22-06-59" src="https://github.com/tisfeng/Easydict/assets/9958811/593f7826-a78e-423d-8e78-61b20b1dd7fa">

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

打开设置 - 选中服务的 OpenAI, 没有额外的输入窗口

### Screenshot

-

### Expected result

-

### Device type and OS version

Intel macOS Big Sur

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by tisfeng** [comment]
[OpenAI（ChatGPT）翻译](https://github.com/tisfeng/Easydict?tab=readme-ov-file#openaichatgpt%E7%BF%BB%E8%AF%91)

> [2.6.0](https://github.com/tisfeng/Easydict/releases) 版本实现了新的 SwiftUI 设置页（支持 macOS 13+），支持 GUI 方式配置服务 API key，其他版本则需要在 Easydict 的输入框中使用命令方式配置。
