### ISSUE TITLE
🐞 反馈问题：服务设置里，切换窗口设置会频繁访问fanyi.baidu.com

### ISSUE THREAD

**Issue by re1oaded** [tisfeng/Easydict#466]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

直接上图吧

![2024-03-20](https://github.com/tisfeng/Easydict/assets/48444178/280854c9-bc8f-490f-ad54-1dad75e4ae32)

点击红框的三个选项切换，会频繁的向fanyi.baidu.com请求，主要我没有开启百度翻译，这是什么原因导致的呢？

还有个小问题反馈一下，菜单栏图标点击后选择动画很卡顿，鼠标不流畅，这个可能是个例，系统版本13.4.1。

<img width="192" alt="image" src="https://github.com/tisfeng/Easydict/assets/48444178/b31582a3-c7f6-42b7-848e-0f1f1aede2bd">

### 该问题是否可以稳定重现？

可重现

### 重现步骤

点击红框的三个选项切换，会频繁的向fanyi.baidu.com请求。

### 截图

![2024-03-20](https://github.com/tisfeng/Easydict/assets/48444178/280854c9-bc8f-490f-ad54-1dad75e4ae32)

### 期望结果

出现这种情况的原因

### 设备型号 && 系统版本

iMac 2020, macOS 13.4.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
稍后我看一下。

**Comment by tisfeng** [comment]
下个版本将会修复。

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已修复。

**Comment by tisfeng** [comment]
ok，感谢反馈，稍后我查一下。

**Comment by tisfeng** [comment]
下个版本会修复无故访问 youdao 问题。
