### ISSUE TITLE
🚀 功能建议：隐藏菜单栏图标后,再次打开设置较为繁琐的优化建议

### ISSUE THREAD

**Issue by WindWash** [tisfeng/Easydict#469]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

目前,隐藏菜单栏图标后,需要多个步骤才能重新打开设置菜单,并且快捷键还需额外记忆.

### 使用场景

是否可以借鉴PopClip的交互方式?

当软件**没有处于活动状态**时-点击图标-运行程序.

当软件**处于活动状态**时-点击图标-显示菜单栏图标或者打开设置.

当**失去焦点**后,菜单栏图标又会自动重新隐藏.

既可以将**快捷键额外记忆**这个问题解决,又可以将原本需要按2次快捷键简化为点击图标一个步骤.

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
不了，这里不准备弄得很复杂，`Cmd + ,` 打开设置页，这在 macOS 上是一个非常通用的快捷键，几乎所有应用都遵守。

另外，下个版本会在右上角添加一个快捷设置按钮，可以方便打开设置页。

<img width="434" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/28866fe6-eb50-4bc1-b487-4ea7952d5080">
