### ISSUE TITLE
🚀 功能建议：希望可以调整翻译服务展示顺序

### ISSUE THREAD

**Issue by githublue123** [tisfeng/Easydict#47]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

设置里面可以调整翻译服务的展示顺序

### 使用场景（可选）

长期使用会对某些翻译服务产生信赖，有优先查看的倾向

**Comment by tisfeng** [comment]
可以的，设置页服务，拖动可以修改顺序。

<img width="336" alt="image" src="https://user-images.githubusercontent.com/25194972/232359186-8298fc35-bf6a-4af6-8c7f-3b9af399b0d9.png">
