### ISSUE TITLE
🐞 反馈问题：内置苹果词典查询错误，出现“查询失败，A 未查询到结果”

### ISSUE THREAD

**Issue by foxllhl** [tisfeng/Easydict#470]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

苹果词典查询错误

### 该问题是否可以稳定重现？

可重现

### 重现步骤

突然出现的问题，尝试重装未能解决

### 截图

![截屏2024-03-23 16 24 15](https://github.com/tisfeng/Easydict/assets/66822197/809da57d-e668-4e7a-843b-97cedfe8a70f)
![截屏2024-03-23 16 24 15](https://github.com/tisfeng/Easydict/assets/66822197/6a97391b-6a07-47a6-893c-68f1dffeb497)

### 期望结果

解决问题

### 设备型号 && 系统版本

Apple M1 Ultra 

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
你看一下是不是语种识别有问题，你这个查询结果明显不对，messages 有道翻译结果怎么可能是 `页面`，语种识别按钮也是灰色 😓

**Comment by foxllhl** [comment]
问题解决了，谢谢，就是语言识别的问题
