### ISSUE TITLE
🐞 Bug Report: Main window can not again after press escape while input query word

### ISSUE THREAD

**Issue by phlpsong** [tisfeng/Easydict#471]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

Can not open Main query window again after press escape key while input query word

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

1. Open app with Main window shown
2. Focus on the input view on top of query window
3. Main window hide and cannot open again

### Screenshot

N/A

### Expected result

the Main window should be shown again 

### Device type and OS version

macOS 14.2.1

### Are you willing to submit a PR to fix this issue?

- [X] I'm willing to submit a PR

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已修复。
