### ISSUE TITLE
系统兼容问题

### ISSUE THREAD

**Issue by ct1987** [tisfeng/Easydict#476]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

我的 mac 版本是11.7.10，使用命令行安装 easydict（2.6.1） 成功后，发现无法配置各个服务，原因是右侧的配置页面无法展示出来。请看图片

### 该问题是否可以稳定重现？

可重现

### 重现步骤

安装成功，配置服务的时候必现

### 截图

![1711766296864](https://github.com/tisfeng/Easydict/assets/34504101/21df617e-5fb5-4a30-845e-cdd393b758a4)

### 期望结果

请修复一下该 bug

### 设备型号 && 系统版本

macbook 11.7.10

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
https://github.com/tisfeng/Easydict?tab=readme-ov-file#openaichatgpt%E7%BF%BB%E8%AF%91

<img width="868" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/22aa1de1-2ee6-438d-bd0f-af17c8ade0bf">
