### ISSUE TITLE
🚀 功能建议：允许添加多个自定义 OpenAI 服务

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#479]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

目前最新 dev 已添加了一个自定义 OpenAI 服务，但用户可能想要添加多个自定义服务 https://github.com/tisfeng/Easydict/issues/439#issuecomment-1977974655 ，https://github.com/tisfeng/Easydict/issues/434

因此，我们可以在已有的自定义 OpenAI 服务功能上进行改进，例如在设置服务页添加一个【复制】按钮，点击后创建一个新的自定义 OpenAI 服务。

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/8a66c013-8331-45bd-ab37-0be3ac634ecc">

### 使用场景

*

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
@phlpsong 这个功能开始做了么，如果还没有的话，可以构思一下如何配合 https://github.com/tisfeng/Easydict/issues/551 一起做。

目前加载服务代码都是固定好的，一个类对应一个服务，对于添加多个自定义 OpenAI 这种服务来说不方便，而使用 SwiftUI 重写查询窗口时，这部分代码逻辑可能会大改，因此最好配合起来实现。

**Comment by phlpsong** [comment]
Sorry about that, I've been quite busy with work lately, so I might have to wait until mid of next month to take a look.

**Comment by tisfeng** [comment]
ok，你先忙，我们先等 https://github.com/tisfeng/Easydict/issues/551 搭个架子，可能也没那么快。

--- 

我在想，如果服务配置 UI 这部分代码实现得比较好的话，稍后是否可以像  [Raycast](https://developers.raycast.com/api-reference/preferences) 一样使用配置文件实现服务界面配置，最后实现 js 自定义扩展服务 https://github.com/tisfeng/Easydict/issues/136 。 这个还有点遥远，先一步步来吧。

**Comment by valens7** [comment]
奇怪，在最新的版本里找不到自定义OPEN AI服务呢
<img width="696" alt="image" src="https://github.com/tisfeng/Easydict/assets/35646496/eeb0a991-dc75-42cf-8038-aafbd7ebaf7a">

**Comment by tisfeng** [comment]
@valens7 之前的回复你没看到吗  https://github.com/tisfeng/Easydict/issues/536#issuecomment-2132194072

**Comment by tisfeng** [comment]
@phlpsong 最近有空看一下这个吗

**Comment by phlpsong** [comment]
OK. I looked into this issue some days before, but didn't make any progress. I'll take another look later.

**Comment by tisfeng** [comment]
[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。
