### ISSUE TITLE
🐞 反馈问题：百度翻译接口出现异常

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#481]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

抓包一看，百度好像修改了网页版接口，为了推 AI 翻译，甚至都改成了 text/event-stream 类型 😓

得了，那我们也不要折腾这个接口了，直接改用百度官方 API，个人免费额度 100 万字符也够用。

<img width="1673" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/e104b103-c3ee-4201-88f7-a665670a2f62">

<img width="834" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/6a683fdc-6ce5-4867-8ae6-a9f3e636bd20">

### 该问题是否可以稳定重现？

可重现

### 重现步骤

*

### 截图

<img width="419" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/757f13b5-ee55-48bc-bdf8-ade8663e08e7">

### 期望结果

支持百度官方 API

### 设备型号 && 系统版本

*

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
这个我们直接用 Swift 重写吧，既然旧的接口已废弃，也没有维护的必要了。

@choykarl 你可以做一下这个吗

**Comment by choykarl** [comment]
可以，不过还是时间的问题，我只能抽空弄，时间不稳定……🥲🥲

**Comment by tisfeng** [comment]
ok，目前网页接口似乎还能用一会，这个 https://github.com/tisfeng/Easydict/issues/484 你可以有空时写。

**Comment by choykarl** [comment]
ok，我抽出时间就弄弄

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已修复。
