### ISSUE TITLE
🐞 反馈问题：配戴 AirPods 時，禁用空复制提示音後仍然會出現聲音

### ISSUE THREAD

**Issue by pilisir** [tisfeng/Easydict#485]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

配戴 AirPods 時，禁用空复制提示音後仍然會出現聲音，不佩戴耳機時可以靜音

### 该问题是否可以稳定重现？

可重现

### 重现步骤

配戴 AirPods，拖曳網頁空白處，不要選取到任何文字再放開

### 截图

<img width="782" alt="image" src="https://github.com/tisfeng/Easydict/assets/16663837/5b12b4fe-3e51-413a-a6cc-cc76c2b6fdf9">

### 期望结果

應該與不配戴 AirPods 時的行為一致

### 设备型号 && 系统版本

Apple M2 Pro, macOS 14.4.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
ok，有点奇怪，稍后我们看一下。

**Comment by Jerry23011** [comment]
可以在Safari复现，很神奇

**Comment by tisfeng** [comment]
看了一下代码，似乎是修改声音的方法有问题，目前只能修改设备的系统音量，无法修改耳机外设音量 😥

而禁用空复制提示音的实现比较 tricky，本质上是通过短暂禁止系统声音来实现的，所以使用 AirPods 不会生效。

稍后我尝试修复下。

**Comment by pilisir** [comment]
希望能成功，無論如何都非常感謝你的付出 👍

**Comment by tisfeng** [comment]
开发环境已修复该问题，明天后天会发布新版本。

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已修复。
