### ISSUE TITLE
🐞 反馈问题：应用闪退

### ISSUE THREAD

**Issue by huangheLee** [tisfeng/Easydict#486]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

macos 14.4 (23E214)
应用版本 2.6.1
闪退触发路径
     悬浮窗连续按command + “+” 放大字体，  多次放大后闪退
     闪退后重新打开应用， 点击输入翻译等功能 都会再次闪退
目前避免使用快捷键 放大字体

### 该问题是否可以稳定重现？

可重现

### 重现步骤

     悬浮窗连续按command + “+” 放大字体，  多次放大后闪退
     闪退后重新打开应用， 点击输入翻译等功能 都会再次闪退

### 截图

闪退后没有截图，也没有报错弹窗

### 期望结果

解决闪退问题

### 解决方案（可选）

1、临时解决，不使用快捷键放大字体
2、猜测是快捷键放大字体超出了最大字体导致了数组下标越界

### 设备型号 && 系统版本

MacBookPro 14.4 (23E214)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
下个版本更新将会修复 https://github.com/tisfeng/Easydict/issues/437
