### ISSUE TITLE
🐞 反馈问题：设置界面显示不全，无法设置翻译服务的API

### ISSUE THREAD

**Issue by suibianzai** [tisfeng/Easydict#488]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

请问要在哪里填写Gemini、百度、腾讯等翻译服务的API密钥？我在使用说明里找了半天没找到，后来在其他issue里看到进设置-服务 窗口有边有设置的界面，但是我这边怎么没有？是我理解有误还是我本地APP的问题？

### 该问题是否可以稳定重现？

可重现

### 重现步骤

进设置界面找不到翻译源API设置，迷你窗口、侧悬浮窗口、主窗口 这3个选项卡都是一样的，点进服务的名称也没有反应

### 截图

<img width="409" alt="image" src="https://github.com/tisfeng/Easydict/assets/42022663/1c3cf66f-6182-4b5c-87dd-f41d0babf53f">

### 期望结果

填写API

### 设备型号 && 系统版本

M1 , 12.6.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
https://github.com/tisfeng/Easydict/issues/476
