### ISSUE TITLE
🐞 反馈问题：README中添加系统版本要求

### ISSUE THREAD

**Issue by houzixiashanxiedaima** [tisfeng/Easydict#49]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

在 V2EX 看到有人推荐这个软件，下载之后发现不支持  macOS 10.15.7，希望可以在 README 中补充一下系统版本要求。 

### 重现步骤

无

### 期望结果

无

**Comment by tisfeng** [comment]
感谢反馈，目前系统最低支持 macOS 11.0

其实最开始是支持 macOS 10.15 的，但因为不会设计图标，就用了系统的 `Symbol Image` ，被迫升到 11.0 了 😓

**Comment by tisfeng** [comment]
已添加。
