### ISSUE TITLE
代码重构：设置页 OpenAI 和自定义 OpenAI 服务有太多重复代码

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#497]
参见 https://github.com/tisfeng/Easydict/pull/493#issuecomment-2041520213

稍后将会有更多类似的 OpenAI 服务，如 [Ollama 翻译服务](https://github.com/tisfeng/Easydict/issues/492) 和 [内置 AI 翻译服务](https://github.com/tisfeng/Easydict/issues/474)，因此需要重构优化这部分代码，方便后续功能开发。

**Comment by tisfeng** [comment]
@phlpsong 你可以来做这个吗

**Comment by phlpsong** [comment]
OK

**Comment by tisfeng** [comment]
我把 https://github.com/tisfeng/Easydict/issues/492 也给你吧，都是相互关联的，重构完后你可以用它来验证一下。

**Comment by phlpsong** [comment]
Sure, I will check.

**Comment by tianzhuwei** [comment]
想了解一下，下个版本的预计什么时间发布呢？

**Comment by tianzhuwei** [comment]
> 快了，这个周末吧 🙂

大佬 是不是该改版了

**Comment by tisfeng** [comment]
可能要鸽了，得延后几天，目前还有几个小问题需要处理，待我整理一下代码。

**Comment by tisfeng** [comment]
关于这个优化 issue，我有一些想法，我先来尝试一下。
