### ISSUE TITLE
🐞 反馈问题：右上角快捷功能按钮的 toolTip 有误

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#498]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

目前代码中这个 toolTip 是写死的，没有动态获取。

<img width="821" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/81965ffb-97a9-4e01-bfa5-8e2a5707ffea">

### 该问题是否可以稳定重现？

可重现

### 重现步骤

*

### 截图

*

### 期望结果

*

### 设备型号 && 系统版本

*

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
@AkaShark 你看一下这个。

**Comment by AkaShark** [comment]
okay

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已修复。
