### ISSUE TITLE
新功能请求：像 DeepL 一样使用 Cmd+C+C 启动划词翻译

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#5]
## 功能描述
这样就不需要申请辅助功能权限了，直接从剪贴板取词。

**Comment by tisfeng** [comment]
看到了 DeepL 的这个功能了，欧路词典也有这个功能，它的实现原理我大概能想到，优点是不需要申请权限，但缺点也很明显，容易和电脑上的其他类似功能软件冲突。。

由于 Easydict 的一个核心功能就是自动划词查询，而这个功能必须申请辅助功能权限，所以，我还是希望用户能够开启这个权限的。另外，快捷键划词功能目前的部分实现也是 Cmd+C，只不过是通过代码实现而不是用户手动按下 😂

如果你是希望能够通过快捷键更方便地触发，像这个 issue [关于快捷键的问题](https://github.com/tisfeng/Raycast-Easydict/issues/25#issuecomment-1289919639)，其实目前 Easydict 已经可以支持双击 Cmd 键触发了，只是暂时还在内部测试，没有发布。

**Comment by Alphabet1226** [comment]
感谢耐心详细解答，确实你说的有道理。

**Comment by PPPPigggg** [comment]
> 双击 Cmd 键

现在可以使用了吗

**Comment by tisfeng** [comment]
没，因为我测试发现，双击 Cmd 很容易误触发 😓  这种非常规快捷键感觉不适合广泛使用，而且我也担心会和其他软件冲突，专门弄个开关又太累了。
