### ISSUE TITLE
🐞 反馈问题：快捷键弹出窗口位置不同

### ISSUE THREAD

**Issue by 1xiaocainiao** [tisfeng/Easydict#50]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

未选中文案option+D位置偏上，选中文案option+D位置偏下，能否统一一下呢；而且option+A调出窗口的时候，每次都会显示上一次输入的内容，是否能做个开关选择是否清除呢

### 重现步骤

无

### 期望结果

无

### 解决方案（可选）

无

**Comment by tisfeng** [comment]
下个版本会修复 https://github.com/tisfeng/Easydict/issues/19#issuecomment-1445314173

**Comment by kilvn** [comment]
还有再次按快捷键，正常应该是隐藏窗口，但是现在窗口无法消失了，只有个置顶按钮，不知道怎么再次隐藏窗口，
预期是按Ctrl+F显示，再按一次窗口隐藏

<img width="337" alt="image" src="https://user-images.githubusercontent.com/16423601/232453258-e4913643-b2a0-4b48-bde7-c6bd5e61a271.png">

**Comment by tisfeng** [comment]
点击查询窗口外，没有自动隐藏吗

**Comment by 1xiaocainiao** [comment]
> #19 (comment)

谢谢大佬回复

**Comment by kilvn** [comment]
> 点击查询窗口外，没有自动隐藏吗

有，之前用百度翻译是那样的感觉才是正常的设计

**Comment by tisfeng** [comment]
额，我没能理解你说的，，我以为你是遇到 bug 了，无法隐藏窗口 😢

> 现在窗口无法消失了

除了主窗口，其他查询窗口都是只要点击窗口外就会自动隐藏，这符合轻量使用设计，也比较容易理解吧。

**Comment by kilvn** [comment]
> 额，我没能理解你说的，，我以为你是遇到 bug 了，无法隐藏窗口 😢
> 
> > 现在窗口无法消失了
> 
> 除了主窗口，其他查询窗口都是只要点击窗口外就会自动隐藏，这符合轻量使用设计，也比较容易理解吧。

刚开始不知道是这样设计的，没毛病，不过我还是老习惯了  快捷键显示和隐藏

**Comment by tisfeng** [comment]
有的，也可以使用 Escape 或 `Cmd+W` 快捷关闭窗口。如果要把同一个快捷键赋予 on 和 off 两种功能，通常得做额外逻辑处理，略微麻烦，而这里也不是很有必要。

**Comment by tisfeng** [comment]
你好，新版本已修复该问题  https://github.com/tisfeng/Easydict/releases/tag/1.3.0

**Comment by tisfeng** [comment]
后面想了想，你说的有道理，这种方式也符合操作直觉，[1.3.1](https://github.com/tisfeng/Easydict/releases/tag/1.3.1) 版本对【输入翻译】和【显示迷你窗口】添加了这个支持。

> 预期是按Ctrl+F显示，再按一次窗口隐藏
