### ISSUE TITLE
🐞 反馈问题：开启 easydict 需要按两次 command+c 才能复制

### ISSUE THREAD

**Issue by mkeco** [tisfeng/Easydict#503]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

开启 easydict 后需要两次 command +c 才能复制内容

### 该问题是否可以稳定重现？

可重现

### 重现步骤

两次 command +c 

### 截图

两次 command +c 

### 期望结果

两次 command +c 

### 解决方案（可选）

按一次

### 设备型号 && 系统版本

m1 macbook

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
请提供更详细的问题描述，不可能你什么都没做，只是因为开启了 Easydict 就导致这个问题。

> 需要两次 command +c 才能复制内容

这个问题似乎已经存在 macOS 很多年了，当然也可能是一些类似 PopClip 划词应用所导致。

随手Google一搜能找到很多类似问题 [macos 需要两次 command +c 才能复制内容](https://www.google.com/search?q=%E9%9C%80%E8%A6%81%E4%B8%A4%E6%AC%A1%20command%20%2Bc%20%E6%89%8D%E8%83%BD%E5%A4%8D%E5%88%B6%E5%86%85%E5%AE%B9#ip=1)

**Comment by tisfeng** [comment]
突然想起来，Easydict 本身也是一个划词应用 😓

你可以尝试在设置中关闭这两个选项，某些应用不支持系统取词时，会占用剪贴板，可能会导致一些奇怪的问题。

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/744b5d8b-63ef-4e5d-9593-b2eb991fe991">

**Comment by mkeco** [comment]
下午尝试过把这两个选项关闭暂时没有这个问题了，之前搜过这个问题，一直以为是macOS问题，今天偶然把软件退出这个问题消失了。

**Comment by tisfeng** [comment]
> 你可以尝试在设置中关闭这两个选项，某些应用不支持系统取词时，会占用剪贴板，可能会导致一些奇怪的问题。

强制划词功能，在某些情况下确实会导致一些奇怪问题，所以标注了【实验功能】。虽然知道可能会导致问题，但目前也没有很好的解决办法。

你试一下看只开启【划词后自动显示查询图标】会不会有问题。

**Comment by mkeco** [comment]
好的，谢谢

**Comment by tianzhuwei** [comment]
我之前在使用欧陆词典的时候也出现过这种现象，当时也没有找到是什么原因

**Comment by starsea** [comment]
用 mac 很多年了，欧陆也出现过这个问题 把划词关掉就行了。
但是 easydict 之前的版本是没有这个问题的， 只有最新版本才有这个问题。我个人觉得最近的几个版本用了某些奇怪的特性导致的 @tisfeng

**Comment by tisfeng** [comment]
[2.6.0 版本](https://github.com/tisfeng/Easydict/releases/tag/2.6.0) 开始，我们使用 Swift/SwiftUI 重写了设置页相关功能，这可能会导致一些问题，但应该问题不大，我们内部测试了很久，大部分都已修复。

> 开启 easydict 后需要两次 command +c 才能复制内容

关于划词功能部分，暂时还未改动，应该不会影响到吧 🫠

**Comment by tisfeng** [comment]
@starsea  如果你那边确认有这个问题，请提供更多、更详细的问题描述，这样才能方便我们能复现，或者定位到问题，然后去解决。

**Comment by tisfeng** [comment]
清理 issue，没有后续反馈的就先关闭了，如果再遇到问题，请另外提 issue。

**Comment by LittleFishLove** [comment]
能否增加一个开关“划词后自动显示查询图标”的全局快捷键？
![image](https://github.com/tisfeng/Easydict/assets/35796964/a7631281-4b53-4f09-aa84-19fb87afc150)

**Comment by LittleFishLove** [comment]
如果有这样在一个快捷键，那么对于一些不太有复制需求的网页，可以快速划词查看词义；而对于需要复制的网页，可以方便地关闭此功能？

**Comment by tisfeng** [comment]
你好，后面会添加网页白名单/黑名单 https://github.com/tisfeng/Easydict/issues/502 ，方便处理这种情况。
