### ISSUE TITLE
dev: 调试模式下，每次应用启动，迷你窗口的位置都被重置了

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#504]
很奇怪，调试模式下，每次应用启动会调用 windowDidResize，导致迷你窗口的位置都被重置了，坐标都会是一个奇怪的值，例如 {55, 28}

<img width="1671" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/138436b0-adea-4489-ade0-080cbfb95b9e">

**Comment by tisfeng** [comment]
调试发现，好像是这个 PR 导致 #500 ，切到前一个提交 06929ffe 就没有这个问题 😑

**Comment by tisfeng** [comment]
@AkaShark 有空看一下

**Comment by AkaShark** [comment]
emm.. Let me check #500 code, but seems I don't change the window location😭

**Comment by AkaShark** [comment]
> @AkaShark 有空看一下

okay

**Comment by tisfeng** [comment]
明天可能要发新版本，这个你看能不能先解决。

**Comment by AkaShark** [comment]
> 明天可能要发新版本，这个你看能不能先解决。

okay 今天上午看下了，是由于https://github.com/tisfeng/Easydict/blob/7d7c8d4e026267ada2bf03749027a9951626413b/Easydict/Swift/Feature/Configuration/Configuration.swift#L406 这个地方会在初始化的时候掉一次，所以在启动的时候会调用下`windowDidResize`

**Comment by tisfeng** [comment]
你修改一下 `updateButtonsToolTip` 方法，不要调用 updateConstraints，改成销毁这些动作按钮，然后重新创建，`updateConstraints` 方法也需要作出相应的修改。

**Comment by tisfeng** [comment]
想了想，好像也没必要，我们直接更新一下按钮的 toolTip 应该就可以 🥲

你试一下。

**Comment by AkaShark** [comment]
okay 稍等我试下的

**Comment by AkaShark** [comment]
https://github.com/tisfeng/Easydict/pull/506 看了下`closeFloatingWindowIfNotPinnedOrMain`这个回调在在启动并且监听到后也会去初始化window，然后`windowDidResize `就会收到通知。

**Comment by tisfeng** [comment]
Fixed.
