### ISSUE TITLE
怎么把英语翻译成俄语了，怎么改？

### ISSUE THREAD

**Issue by 1994WangHui** [tisfeng/Easydict#508]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

翻译成俄语了

### 该问题是否可以稳定重现？

可重现

### 重现步骤

翻译成俄语了

### 截图

<img width="504" alt="image" src="https://github.com/tisfeng/Easydict/assets/166966147/4e45513c-224e-4505-8bce-09af3f840da7">

### 期望结果

改回中文

### 设备型号 && 系统版本

M1 air 

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
打开输入翻译窗口，看目标语言是不是选中了俄语。

目标语言通常使用自动选择就行。

<img width="413" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/1bd8043d-7eed-4ad4-9c1c-c4dad8190047">

**Comment by tisfeng** [comment]
清理 issue，没有后续反馈的就先关闭了，如果再遇到问题，请另外提 issue。
