### ISSUE TITLE
🚀 功能建议：希望能release的时候同时维护brew

### ISSUE THREAD

**Issue by kilvn** [tisfeng/Easydict#51]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

相比手动去release下载安装包，Mac brew同步更新还是非常方便的

**Comment by tisfeng** [comment]
你好，我对 brew 不太了解，不知道它能不能配合 Spark 使用？

因为目前 Easydict 是支持 Spark 方式自动更新的，如果用户是通过 brew 下载，然后开启自动更新，这样能工作吗？

**Comment by kilvn** [comment]
> 你好，我对 brew 不太了解，不知道它能不能配合 Spark 使用？
> 
> 因为目前 Easydict 是支持 Spark 方式自动更新的，如果用户是通过 brew 下载，然后开启自动更新，这样能工作吗？

非常感谢你的回复，在我创建了这个issue后搜了下你已经提交了，只不过没有改readme，已经通过brew cask安装了

我没用Sparkle做自动更新，写了个脚本每天习惯性的update下

![image](https://user-images.githubusercontent.com/16423601/232435028-504666ee-f1b3-4507-ac21-41190a65ddd8.png)

你每次发release后向brew的库提update包hash的pr通过以后，用户就可以更新软件了，这样很方便

**Comment by tisfeng** [comment]
感谢，是提 PR 修改这里的 sha256 吗

https://github.com/Homebrew/homebrew-cask/pull/141992/files

**Comment by kilvn** [comment]
> 感谢，是提 PR 修改这里的 sha256 吗
> 
> https://github.com/Homebrew/homebrew-cask/pull/141992/files

只需要改 version 和 hash 就好了

hash在这里获取

![image](https://user-images.githubusercontent.com/16423601/232452092-1be3bec7-c681-40b4-8ea2-26bbd41db99b.png)
