### ISSUE TITLE
🚀 功能建议：建议增加翻译前，去除换行符之类的空白符的功能

### ISSUE THREAD

**Issue by luckmoon** [tisfeng/Easydict#513]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

从一些pdf，特别是双栏的学术论文中，复制一段文本后去翻译时，由于有些pdf会带着换行符，比如：
CategoryAlignment. Intheindustrialscenario,thecategories
of items will be diverse (e.g., food, hotels, movies, etc.) and the
number of items in each category is seriously uneven. With the
imbalanced category data, the two-tower model performs differ-
ently for the different categories, and it performs much worse on
the categories with relatively smaller amount of items.
这导致翻译时，翻译接口会把这段文字错误拆句，非常影响效果：
<img width="481" alt="image" src="https://github.com/tisfeng/Easydict/assets/12612749/d5871fe4-f71b-438d-a866-4bf9ea78ccf6">

### 使用场景

pdf复制时

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
目前已经实现了，下个版本就上。

这个周末应该会发新版本。

<img width="1110" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/561d11d6-d94b-4fca-ab00-db9a6172660f">

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。

**Comment by K-JW** [comment]
这个问题好像还没有解决，无法正确处理双栏PDF中的换行符号。
