### ISSUE TITLE
🚀 功能建议：建议增加单独OCR功能

### ISSUE THREAD

**Issue by MrCharlesWu** [tisfeng/Easydict#52]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

建议增加单独OCR的快捷键，有时候只需要OCR，不需要翻译

**Comment by MoienBowen** [comment]
系统自带的捷径有相关功能，然后通过服务设置快捷键。

**Comment by MrCharlesWu** [comment]
> 目前设置页，有截图 OCR 后是否查询选项，你想要的是这个吗？
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/25194972/232498292-ae55f9ba-7db7-441c-a04d-e9098b7d089f.png">

我是想用快捷键单独使用OCR功能

**Comment by MrCharlesWu** [comment]
> 系统自带的捷径有相关功能，然后通过服务设置快捷键。

具体是怎么操作呢，试了下没发现如何设置OCR的快捷键

**Comment by MoienBowen** [comment]
> > 系统自带的捷径有相关功能，然后通过服务设置快捷键。
> 
> 具体是怎么操作呢，试了下没发现如何设置OCR的快捷键

大概如下。

首先创建捷径，包含以下动作：
- Take `Interactive` screenshot
- Extract text from `Screenshot`
- 这里可以创建 if 检查 `Text from Image` 是否包含内容
- Copy `Text from Image` to clipboard

编辑页面右侧 （i）中，勾选 Use as Quick Action 和 Services Menu 这里可以设置快捷键。不行的话，按照下面的方式。

然后设置快捷键：
- System Settings
- Keyboard
- Keyboard Shortcuts...
- Services
- Shortcuts
- 找到你刚刚创建的捷径，设置快捷键

**Comment by tisfeng** [comment]
就是说，想要一个单纯的 OCR 功能（配快捷键），识别完后将结果写到剪贴板，不显示查询窗口是吗？

> 我是想用快捷键单独使用OCR功能

**Comment by MrCharlesWu** [comment]
> 就是说，想要一个单纯的 OCR 功能（配快捷键），识别完后将结果写到剪贴板，不显示查询窗口是吗？
> 
> > 我是想用快捷键单独使用OCR功能

是的，就是这个意思。抱歉很久没登录github了，才看到

**Comment by tisfeng** [comment]
加了，明天看能不能发个新版本。

<img width="236" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/50d7aba1-aef8-4374-9401-8df98dae1a3c">

**Comment by MrCharlesWu** [comment]
> 加了，明天看能不能发个新版本。
> 
> <img alt="image" width="236" src="https://user-images.githubusercontent.com/25194972/239691535-50d7aba1-aef8-4374-9401-8df98dae1a3c.png">

非常感谢，坐等更新，确实可以替代bob了

**Comment by tisfeng** [comment]
你好，新版本已添加 https://github.com/tisfeng/Easydict/releases/tag/1.3.1
