### ISSUE TITLE
在m1电脑上面，使用AppleScript,模拟cmd+c划词，但是权限NSAppleEventsUsageDescription一直添加不上去，在x86上面是正常的，arm不正常，这种需要怎么解决？？

### ISSUE THREAD

**Issue by Jakn** [tisfeng/Easydict#520]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

划词时使用- (void)getSelectedTextBySimulatedKey:(void (^)(NSString *_Nullable))completion 使用这个方法时，授权问题一直解决不了

### 该问题是否可以稳定重现？

可重现

### 重现步骤

划词时使用- (void)getSelectedTextBySimulatedKey:(void (^)(NSString *_Nullable))completion 使用这个方法时，授权问题一直解决不了

### 截图

<img width="1173" alt="WeChat2cf5f9d42b3ebb83331f4effac3f1e19" src="https://github.com/tisfeng/Easydict/assets/5644262/700e67d0-37d0-40ca-806c-303b7ae94763">
<img width="710" alt="WeChat202154cf786d8795c93bc31572a768c0" src="https://github.com/tisfeng/Easydict/assets/5644262/4414aa22-ea5d-44f7-be21-c08ca56e2418">

### 期望结果

使用能解决m1 权限问题

### 设备型号 && 系统版本

Apple m1

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
这个方法 `getSelectedTextBySimulatedKey` 和授权没关系，真正负责授权的是 `[self isAccessibilityEnabled]`。
