### ISSUE TITLE
🚀 功能建议：能做个win版本吗？

### ISSUE THREAD

**Issue by githubcatheaven** [tisfeng/Easydict#527]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

太好用了。
pot实在是太差了。没有做到开箱即用，也不能划词搜索，很麻烦。

### 使用场景

需要开箱即用，直接划词查询，不需要单独设置快捷键。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by Jerry23011** [comment]
Hi，@githubcatheaven
感谢建议，请看#57
