### ISSUE TITLE
🐞 Bug Report: 2.70版本，无法使用划词翻译，弹出需要授予辅助功能权限

### ISSUE THREAD

**Issue by linchangyi** [tisfeng/Easydict#529]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

更新到2.70版本，无法使用划词翻译，弹出需要授予辅助功能权限，但是系统实际上已经授予了权限。回退到2.6.1版本功能正常。  

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

1.升级到2.70版本
2.打开程序
3.使用快捷键划词翻译

### Screenshot

![Uploading image.png…]()

### Expected result

弹出划词翻译窗口

### Device type and OS version

Apple M1 pro, 14.4.1

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by Diane-Best** [comment]
Same questions！

**Comment by tisfeng** [comment]
Please read FAQ:

-  [Why does macOS still pop up asking for permissions even though I have given Easydict the Accessibility/Screen Recording permissions?](https://github.com/tisfeng/Easydict/wiki/FAQ#why-does-macos-still-pop-up-asking-for-permissions-even-though-i-have-given-easydict-the-accessibilityscreen-recording-permissions)

<img width="938" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0f08f9ac-66fe-47c2-b2b3-f3a3b0a13038">

**Comment by Diane-Best** [comment]
> * Why does macOS still pop up asking for permissions even though I have given Easydict the Accessibility/Screen Recording permissions?

the second method referred worked successfully!

**Comment by JackeyLov5** [comment]
> 请阅读常见问题解答：
> 
> * [为什么即使我已授予 Easydict 辅助功能/屏幕录制权限，macOS 仍会弹出请求权限？](https://github.com/tisfeng/Easydict/wiki/FAQ#why-does-macos-still-pop-up-asking-for-permissions-even-though-i-have-given-easydict-the-accessibilityscreen-recording-permissions)
> 
> <img alt="图像" width="938" src="https://private-user-images.githubusercontent.com/25194972/327298518-0f08f9ac-66fe-47c2-b2b3-f3a3b0a13038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDA0MzAsIm5iZiI6MTcxNDY0MDEzMCwicGF0aCI6Ii8yNTE5NDk3Mi8zMjcyOTg1MTgtMGYwOGY5YWMtNjZmZS00N2MyLWIyYjMtZjNhM2IwYTEzMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA4NTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4M2I2MWM3ZjVmZWIwYjBlOTE3Mzk2NDhlMDhjYjE1YmFiOTFiM2U3YjQzOTQyMzliMmQwNDZlYWMzMWE3ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xk9rTpQgeGwyzFLKobZkknv9AabuiE6QE2D0lnBLQdA">

我觉得应该尝试修复一下这个问题 orz

**Comment by tisfeng** [comment]
这不是问题，和上次不一样，这次版本更新，我们没有修改权限相关的代码功能，这很可能是系统 bug，macOS 系统更新时有时会莫名导致权限被重置。

如果你认为这是问题，或者你有解决办法或思路，欢迎提出来。

**Comment by tisfeng** [comment]
好像是 Easydict 发布的应用证书出了问题 https://github.com/tisfeng/Easydict/issues/531 ，稍后我们查一下 😰

**Comment by tisfeng** [comment]
[2.7.1](https://github.com/tisfeng/Easydict/releases/tag/2.7.1)  新版本已发布， 修复了 2.7.0 版本应用签名异常问题。

> [!NOTE]
> 如果之前 Easydict 升级到了 2.7.0，那此更新后需要对应用 [权限重新授权](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90) 。
>
> 通常应用权限授权一次就可以，这次是配置签名错误导致的意外 😓

**Comment by Diane-Best** [comment]
2.7.1 更新后还是不能划词翻译

**Comment by tisfeng** [comment]
请尝试对 Easydict  [权限重新授权](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90) 。

**Comment by SuperSter** [comment]
> 2.7.1 更新后还是不能划词翻译

剛好也有遇到這個狀況，我的處理方式是
整個app刪除重新安裝 v2.7.2 後,將權限全數刪除重新添加就修復了。

**Comment by aaron0713** [comment]
> > 2.7.1 更新后还是不能划词翻译
> 
> 剛好也有遇到這個狀況，我的處理方式是 整個app刪除重新安裝 v2.7.2 後,將權限全數刪除重新添加就修復了。

新安装的2.7.2也有这个问题，同样需要删除授权，重新添加
