### ISSUE TITLE
🐞 反馈问题：开发者证书出现异常

### ISSUE THREAD

**Issue by AmnaSN** [tisfeng/Easydict#531]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

I just noticed that the code signature has chnaged from 'Canglong Dai (45Z6V4YD5U)' to 'Apple Development: Canglong Dai (PUBB6MZ2EF)' in the latest version. Can you please confirm if it is a legitimate change?

### 该问题是否可以稳定重现？

可重现

### 重现步骤

-

### 截图

-

### 期望结果

NA

### 设备型号 && 系统版本

Apple M2 Air

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
Thanks for the feedback, we'll take a closer look at this.

**Comment by tisfeng** [comment]
Hi, the application signing issue has been fixed, and we have just released a new version [2.7.1](https://github.com/tisfeng/Easydict/releases/tag/2.7.1)

<img width="400" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/ac143519-2ea1-4b20-ba28-241851ff7533">
