### ISSUE TITLE
dev:  将 Easydict 最低系统支持版本修改为 macOS 13.0

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#534]
目前设置页已使用 SwiftUI 重写，而许多 SwiftUI API 都要求 macOS 13.0，未来我们还将使用 SwiftUI 重写查询窗口页面，因此决定将最低系统支持版本从 macOS 11.0 修改为 macOS 13.0。

该 issue 除了将 Minimum Deployments 修改为 macOS 13.0，还包括以下内容修改：

- 移除旧的设置页相关代码。
- 移除之前设置页使用的第三方库，如 MASPreferences，MASShortcut 等。
- 移除有关系统版本判断的代码，如 @available(macOS 13, *) 等。

**Comment by tisfeng** [comment]
@AkaShark 你能做一下这个吗

**Comment by AkaShark** [comment]
okay 我明天先梳理下代码，有问题我们在这个issue中沟通

**Comment by AkaShark** [comment]
@tisfeng "移除旧的设置页相关代码" 移除就的设置页相关的代码，我们是不是直接把之前的Launch In SwiftUI App mode给取掉了，直接走SwiftUI

**Comment by tisfeng** [comment]
是的，Launch In SwiftUI App mode 这个也可以删除了。
