### ISSUE TITLE
🐞 反馈问题：内置 AI 翻译服务的开启存在 bug

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#536]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

正式环境下，上次版本新添加的两个服务，如内置 AI 翻译和自定义 OpenAI 翻译的开启似乎有问题，具体请看视频内容。 

我是看到用户反馈 https://github.com/tisfeng/Easydict/issues/502#issuecomment-2094405836  ，然后用 Easydict 正式版测试的，发现确实存在问题。

但多次测试后，后面又无法复现了，不知道什么原因，可能需要检查代码。

### 该问题是否可以稳定重现？

不可重现

### 重现步骤

*

### 截图

https://github.com/tisfeng/Easydict/assets/25194972/40becf27-3655-4128-889d-c64ab438b65d

### 期望结果

服务正常开启、关闭。

### 设备型号 && 系统版本

*

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
@phlpsong 帮忙看一下这个问题 🥲

**Comment by phlpsong** [comment]
Sure, it can be reproduced in dev branch.

**Comment by phlpsong** [comment]
Could u confirm whether enabled the `Translation`/`Sentence`/`Dictionary` option in configuration?

**Comment by tisfeng** [comment]
Both only enabled `Translation`.

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/9e60b8ad-d24b-4bb4-bd4e-e98c1654ca88">

**Comment by phlpsong** [comment]
ok, thx

**Comment by atinst** [comment]
> @phlpsong帮忙看看这个问题🥲

我也遇到了这个问题，该问题是由Swift UI App 模式引起的，当我关闭Swift UI模式时（切换成传统菜单模式），问题得到解决。

**Comment by tisfeng** [comment]
@atinst 可能是服务配置问题 https://github.com/tisfeng/Easydict/issues/502#issuecomment-2094798997 ，你把翻译，句子和单词选项都开启试试。

**Comment by tisfeng** [comment]
我们尝试修复了这个问题，刚打了个新包，请测试一下，直接覆盖安装就行，这样不会丢失之前的配置数据  @atinst  @JackeyLov5

[Easydict.zip](https://github.com/tisfeng/Easydict/files/15221487/Easydict.zip)

**Comment by tisfeng** [comment]
@Ineffable919  具体什么问题？请详细描述一下问题，实在不行，你可以关闭内置 AI 试试。

如果是闪退问题，请另外开个 issue 反馈一下，务必提供崩溃日志，稍后我们会定位修复它，然后发布新版本。

**Comment by tisfeng** [comment]
[2.7.2](https://github.com/tisfeng/Easydict/releases/tag/2.7.2) 版本已修复该问题。

**Comment by valens7** [comment]
<img width="628" alt="image" src="https://github.com/tisfeng/Easydict/assets/35646496/045078ce-29c4-44df-a2b2-80bdaceaeb56">
奇怪了，怎么没有自定义OEN AI翻译选择了？

**Comment by tisfeng** [comment]
注意看图标，你都都把它改成了 Kimi 😑
