### ISSUE TITLE
🚀 功能建议：Cmd+V之后不需要按回车键也能立即展开翻译结果

### ISSUE THREAD

**Issue by oxoxoxox** [tisfeng/Easydict#54]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

Cmd+V之后，立即开始翻译，而不是要等用户按回车键才开始翻译。
可以做成设置项中的一个开关菜单。

**Comment by JK-Wang** [comment]
说不定可以更简单一点？比如打开 Input translate 或者 mini window 的时候直接从剪贴板获取文本进行翻译

**Comment by tisfeng** [comment]
这个感觉也不错，只是这样一来设置项就越来越多了，而且如果还要考虑适应窗口类型的话，会有点复杂。我考虑一下。

> 直接从剪贴板获取文本进行翻译

**Comment by tisfeng** [comment]
你好，新版本已添加该选项 https://github.com/tisfeng/Easydict/releases/tag/1.3.1
