### ISSUE TITLE
🐞 反馈问题：mac双屏情况下副屏快捷键调用 Select Text Translate 会闪退

### ISSUE THREAD

**Issue by lemoolu** [tisfeng/Easydict#542]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

mac笔记本双屏下，扩展屏幕内翻译时直接闪退，笔记本屏幕没有异常
软件版本：v2.7.1

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1. 打开软件
2. 在扩展屏幕选中需要翻译的文本
3. 按快捷键进行翻译，然后就闪退了

### 截图

[Easydict log 2024-05-09 09-18-38-127.zip](https://github.com/tisfeng/Easydict/files/15256420/Easydict.log.2024-05-09.09-18-38-127.zip)

### 期望结果

正常弹窗翻译选中的文本

### 设备型号 && 系统版本

Apple M1 Pro Version 13.6.5 

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by JohnWickzzz** [comment]
我好像也遇到闪退了，同是外接显示器

**Comment by lleiwang** [comment]
同样闪退，但是不知道是不是连接外接显示器的原因。

刚才重试了下，果然在笔记本显示器内没闪退，在外接屏快捷键翻译立刻闪退了。
crash log :  [Crash(Signal) 2024-05-09 10:15:53.log](https://github.com/tisfeng/Easydict/files/15256762/Crash.Signal.2024-05-09.10.15.53.log)

**Comment by phlpsong** [comment]
Thanks for your feedbacks.

I tried a few times and I couldn't reproduce it (macOS 14.4.1 and app version 2.7.1). I was wondering if you could share more info like system version and check whether version 2.6 works properly?

**Comment by lemoolu** [comment]
There is no problem with version 2.6
my system version is Apple M1 Pro Version 13.6.5 (22G621)
The video is my extended screen

https://github.com/tisfeng/Easydict/assets/4410030/c6ef4c49-ed08-4508-a55e-1d7fae69d93a

**Comment by lemoolu** [comment]
After upgrading my system to Version 14.4.1, there is no problem

**Comment by tisfeng** [comment]
这些奇怪的闪退问题，我们开发者都无法复现，我系统 macOS 14.4.1 确认不会出现这个问题。

可能和系统版本有关，似乎出问题的用户都是 macOS 12 和 13，如果有用户遇到这种问题，建议先升级系统试试。

**Comment by tisfeng** [comment]
如果没有后续反馈，稍后我会关闭这个 issue。

**Comment by tisfeng** [comment]
请尝试更新到 macOS 14 系统 https://github.com/tisfeng/Easydict/issues/547#issuecomment-2106498291
