### ISSUE TITLE
🚀 功能建议：无法截图翻译

### ISSUE THREAD

**Issue by zzzStefan** [tisfeng/Easydict#549]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

在2.7.1版本中无法使用截图翻译

### 使用场景

在隐私设置里重新设置也没用

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
首先，issue 类型错误，这不是功能建议，这是 bug 反馈。

其次，如果选择 bug 反馈 issue，里面有个 FAQ，请仔细阅读  [权限重新授权](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%B7%B2%E7%BB%8F%E7%BB%99-easydict-%E8%BE%85%E5%8A%A9%E5%8A%9F%E8%83%BD%E5%BD%95%E5%B1%8F%E6%9D%83%E9%99%90-macos-%E4%BB%8D%E7%84%B6%E5%BC%B9%E7%AA%97%E8%A6%81%E6%B1%82%E7%BB%99%E4%BA%88%E6%9D%83%E9%99%90) 。
