### ISSUE TITLE
🚀 功能建议：是否考虑增加AI翻译？

### ISSUE THREAD

**Issue by geekbb** [tisfeng/Easydict#55]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

Sage, GPT3&4, , Claude, ChatGPT, Dragonfly，Bing

**Comment by tisfeng** [comment]
OpenAI 的在做了，快了 https://github.com/tisfeng/Easydict/issues/28

其他的听过，但好像还没开放 API ？

如果后续开放接口了，可以考虑。

**Comment by tisfeng** [comment]
请看 https://github.com/tisfeng/Easydict/issues/28#issuecomment-1527827829

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已开放 OpenAI 翻译。

其他 AI 服务我暂时没有接口资格，只能等待其他小伙伴 PR。

> 开放 [OpenAI (ChatGPT)](https://github.com/tisfeng/Easydict#openaichatgpt%E7%BF%BB%E8%AF%91) 翻译，支持 Azure OpenAI 接口。 https://github.com/tisfeng/Easydict/issues/28

**Comment by tisfeng** [comment]
是的，目前关闭窗口不会停止正在进行的请求。

> 关闭窗口后不会自动结束 openai api 的请求吗？

**Comment by tisfeng** [comment]
OpenAI 翻译我这边已经测试半年多了，没有出现过这种情况，其他参加内测的用户也没有反馈过卡顿问题，这可能和你的个人电脑系统环境有关，建议你单独开一个 issue，详细描述一下上下文环境，最好录个视频。

目前 OpenAI 的流式渲染实现方式不是很理想，但应该也还好，不会造成很大的问题。后面会改进这部份功能的。

你确定是 OpenAI 导致的卡顿吗，关闭它是否就正常？你可以用【活动监视器】看一下 Easydict 的 CPU 和内存占用，确认一下。

**Comment by chachako** [comment]
> 你确定是 OpenAI 导致的卡顿吗，关闭它是否就正常？

是的，关闭后就正常了。开启用了一段时间后就会非常卡，唤醒划词窗口响应会很久

> 这可能和你的个人电脑系统环境有关，建议你单独开一个 issue，详细描述一下上下文环境，最好录个视频。

好，之后我再尝试 OpenAI 的时候会录制一个的
