### ISSUE TITLE
🐞 反馈问题：自定义服务添加千问模型无法翻译

### ISSUE THREAD

**Issue by AnaheimEX** [tisfeng/Easydict#550]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

自定义模型那边已经设置好了，验证也通过。
设置如下：

但是在翻译时，窗口内是空白的
![CleanShot 2024-05-12 at 12 17 11@2x](https://github.com/tisfeng/Easydict/assets/10279911/35de9c33-34ac-44bd-aefd-41e0f4929f56)

### 该问题是否可以稳定重现？

可重现

### 重现步骤

翻译时窗口内是空白

### 截图

![CleanShot 2024-05-12 at 12 17 11@2x](https://github.com/tisfeng/Easydict/assets/10279911/f1b5940a-de99-4f8d-8568-e8a7cd09d718)
![CleanShot 2024-05-12 at 12 18 35@2x](https://github.com/tisfeng/Easydict/assets/10279911/19fb4744-d6cf-4df5-9c25-60493ce33d14)

### 期望结果

期待解决

### 设备型号 && 系统版本

Apple M2 Pro macOS14.4.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by Jerry23011** [comment]
感谢反馈，这个现象看起来有点像 https://github.com/tisfeng/Easydict/issues/538#issuecomment-2096483786
@anaheim 如果可以的话你可以 build dev 分支然后看看这个问题是否还存在吗？

**Comment by tisfeng** [comment]
不不，你这个用法不对，目前 Easydict 只支持符合标准  [OpenAI 接口](https://platform.openai.com/docs/api-reference/chat) 格式的服务，而阿里的 [dashscope](https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-7b-14b-72b-api-detailes?spm=a2c4g.11186623.0.0.4d3d7a82lUUI9E#48063821f9diz) 接口并不兼容 OpenAI，你仔细看看。

一般来说，如果某个服务支持标准的 OpenAI 接口，它一般会在显著的地方表明这一点，因为这是一个很大优势，能够兼容众多 OpenAI 第三方服务，例如 [DeepSeek](https://platform.deepseek.com/docs)、 [零一万物](https://platform.lingyiwanwu.com/docs) 等。如果它没有写，一般就是不兼容。

**Comment by tisfeng** [comment]
标准的 OpenAI 请求格式如下，其中 URL 和 API_KEY 替换为响应的值。

```bash
curl $URL \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $API_KEY" \
  -d '{
    "model": "No models available",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'
```

**Comment by tisfeng** [comment]
对于一些不兼容 OpenAI 接口的服务，可通过 [one-api](https://github.com/songquanpeng/one-api) 等第三方开源项目，将其转换为标准的 OpenAI 接口格式，这样就能在 Easydict 中使用了。

**Comment by tisfeng** [comment]
看了一下文档，阿里前两天也做了 [OpenAI 接口兼容](https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope/)，这是好事。（不兼容 OpenAI 格式的 LLM 服务都是异端 🙄）

但感觉他们很仓促，明显没有经过足够测试，没有严格遵守 [标准 OpenAI 接口](https://platform.openai.com/docs/api-reference/chat/object) 。

stream 接口的 finish_reason 字段返回数据格式不对，要么应该是 stop 或 length 等枚举，要么是 null，不应该是字符串 "null"，这可能会导致解析错误。

> data:{"choices":[{"delta":{"content":"我是","role":"assistant"},"finish_reason":"null","index":0,"logprobs":null}],"object":"chat.completion.chunk","created":1715562574,"system_fingerprint":"","model":"qwen-turbo","id":"chatcmpl-a1e2281f5d759fecb1557c266a62b843"}

<img width="1238" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/1fc223fe-763e-422d-8f2f-2c9b7a5be366">

**Comment by tisfeng** [comment]
目前阿里的接口直接在 Easydict 中使用，会出现格式解析错误，建议向阿里那边多多反馈，给他们上一点压力。

建议大家部署 [one-api](https://github.com/songquanpeng/one-api) ，一劳永逸。

如果  [one-api](https://github.com/songquanpeng/one-api) 出现问题，对于开源项目，可以去提 issue 反馈，有能力还可以自己去修复顺便 PR，对于这种大厂黑盒服务，先不说他们会不会接受反馈，即使接受，修复可能也不会那么及时，一套流程走下来等个几个月也是常规操作 🫠

<img width="819" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/82896370-e66a-4b70-9453-c18c0bbdfd78">

**Comment by AnaheimEX** [comment]
> 目前阿里的接口直接在 Easydict 中使用，会出现格式解析错误，建议向阿里那边多多反馈，给他们上点压力。
> 
> 建议大家部署 [one-api](https://github.com/songquanpeng/one-api) ，一劳永逸。
> 
> 如果 [one-api](https://github.com/songquanpeng/one-api) 出现问题，对于开源项目，可以去提 issue 反馈，有能力还可以自己去修复顺便 PR，对于这种大厂黑盒服务，先不说他们会不会接受反馈，即使接受，修复可能也不会那么及时，一套流程走下来等几个月也是常规操作 🫠
> 
> <img alt="image" width="819" src="https://private-user-images.githubusercontent.com/25194972/329901608-82896370-e66a-4b70-9453-c18c0bbdfd78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjcwMzAsIm5iZiI6MTcxNTU2NjczMCwicGF0aCI6Ii8yNTE5NDk3Mi8zMjk5MDE2MDgtODI4OTYzNzAtZTY2YS00YjcwLTk0NTMtYzE4YzBiYmRmZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAyMTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZGJiODQ1Y2NmMTZiNjViYjAwMjkwN2FlYWZiZDIyYjE0YzUyOGFhNzQ4NzlkNGQ1ZDk5ZjVhOGYxYjk4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2HNenFFSjivD66eWdgFZmGAh7yFBU6pg4gpGKzMEs8g">

感谢测试，我昨天找了一家第三方卖API的用他们的API地址然后填写我在阿里申请的key，正常用上了23333 不过为了用OpenAI Claude3之类的我也要买第三方的API。。。

**Comment by tisfeng** [comment]
其实大部份这种第三方 LLM 服务都是用 [one-api](https://github.com/songquanpeng/one-api) 搭建的，我自己也搭了一个， Easydict 内置 AI 翻译支持各种模型，就是这样实现的。
