### ISSUE TITLE
dev: prompt 表达问题

### ISSUE THREAD

**Issue by cyugao** [tisfeng/Easydict#552]
看了下prompt，感觉很多Chinglish的表达，建议喂给chatgpt重新改写一下。比如
https://github.com/tisfeng/Easydict/blob/d6a2817a9091c6e06fc4b2ca2dc719b16b5b61e7/Easydict/Swift/Service/OpenAI/Prompt.swift#L319

> "3. According to the results of literal translation, find out ~~the~~ existing problems, including [but] not limited to: not in line with \(targetLanguage) expression habits, [the] sentence is not smooth, obscure, difficult to understand, and then ~~re-free~~ translation, on the basis of ensuring the original meaning of the content, make it easier to understand, more in line with the \(targetLanguage) expression habits, while keeping the original format unchanged. If this sentence contains proverbs, metaphors, historical allusions, or comes from famous works, please break the line after the translation and attach its detailed introduction. Desired display format: \"\(freeTranslation):\n{free_translation} \", \n\n" 

expression habits?
re-free => rephrase?
"attach its detailed introduction"?

用Gemini重写了一下
> Review the literal translation, identifying any issues such as unnatural phrasing, awkwardness, ambiguity, or difficulty understanding it in (targetLanguage). Then, retranslate it into a smoother, clearer version that aligns better with (targetLanguage) norms, while retaining the original meaning and format. If the sentence contains idioms, metaphors, historical references, or quotes from famous works, include a line break after the translation followed by a detailed explanation. The desired output format is: "(freeTranslation):\n{free_translation}",\n\n"

**Comment by tisfeng** [comment]
ok，稍后我优化一下。

**Comment by tisfeng** [comment]
Prompt 已优化。
