### ISSUE TITLE
🐞 反馈问题：会与snipaste 的双击复制冲突，导致无法截图后双击复制图片

### ISSUE THREAD

**Issue by githubcatheaven** [tisfeng/Easydict#555]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

如果开启了 easydict 的划词后显示查词图标，即使没有划词，只是双击，都会在chrome菜单里进行编辑操作（编辑按钮会闪动一下，不知道做了什么操作）。
这会导致，在使用snipaste截图后，通过双击直接复制图片的功能，失效。
希望解决这个冲突，两个软件都是必须的。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

参上

### 截图

<img width="429" alt="image" src="https://github.com/tisfeng/Easydict/assets/1519099/d4250ef3-0d30-4e9b-8b81-9be0ba34ad56">

### 期望结果

解决开启【划词后显示查词图标】前提下，双击复制snipaste截图，可直接复制到剪贴板，不与查词重复

### 设备型号 && 系统版本

13.2 MBA M2

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
请仔细阅读 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by tisfeng** [comment]
> 即使没有划词，只是双击，都会在chrome菜单里进行编辑操作（编辑按钮会闪动一下，不知道做了什么操作）

通常来说，如果你开启了辅助功能划词权限，Chrome 应该不会这种问题。

如果某些特殊情况浏览器辅助功能取词失败，请开启 `允许 Apple 事件中的 JavaScript` 选项。
