### ISSUE TITLE
🐞 反馈问题：macOS 全屏应用快捷键划词，弹窗不会展示在此应用上方

### ISSUE THREAD

**Issue by charisna** [tisfeng/Easydict#556]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

macOS 系统，在应用全屏状态下使用快捷键划词翻译，弹窗不会出现在当前全屏应用上，会出现在空白桌面页，应用非全屏状态下无此问题

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1、存在一个全屏应用，如 Chrome
2、划词，并使用快捷键翻译

### 截图

![iShot_2024-05-15_13 01 29](https://github.com/tisfeng/Easydict/assets/4499480/06e9683b-6d7a-43b5-9f5c-a48052ce840b)
![iShot_2024-05-15_13 01 52](https://github.com/tisfeng/Easydict/assets/4499480/5a68015f-08a4-41fa-923e-92c418878465)
![iShot_2024-05-15_13 02 57](https://github.com/tisfeng/Easydict/assets/4499480/2b7652b2-5165-4a71-bf69-849609e6d956)

### 期望结果

弹窗可正常展示在全屏应用上方

### 设备型号 && 系统版本

macOS 14.4.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
没明白你的问题，，你设置中是不是开启了 main 窗口？

在全屏状态下，如果开启了 main 窗口，会导致划词查询窗口显示的位置不对。

**Comment by charisna** [comment]
> 没明白你的问题，，你设置中是不是开启了 main 窗口？
> 
> 在全屏状态下，如果开启了 main 窗口，会导致划词查询窗口显示的位置不对。

可以了，重启电脑后好了😓，可能是 macOS 的问题

**Comment by tisfeng** [comment]
ok，issue 先关闭了，后面有问题再提。
