### ISSUE TITLE
🚀 功能建议：优化 Google Gemini 服务，支持最新的 gemini-1.5-flash-latest 模型

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#559]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

Google 已推出更强大的新模型 [gemini-1.5-flash](https://ai.google.dev/gemini-api/docs/models/gemini?hl=zh-cn#gemini-1.5-flash) 和 gemini-1.5-pro ，而 Easydict 目前的 Gemini 只能使用 gemini-1.0-pro，我们需要改进它，让它和 OpenAI 服务保持一致，支持用户手动输入模型，允许开启查询单词，句子和翻译类型等设置。

<img width="1061" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/eaf90298-c8ae-402b-8def-0bd8ae7f5c8f">

### 使用场景

*

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
可以更新一下 [generative-ai-swift](https://github.com/google-gemini/generative-ai-swift) 这个库，我们使用的还是 0.4.7，最新版本已经到 [0.5.3](https://github.com/google-gemini/generative-ai-swift/releases/tag/0.5.3) 了。

**Comment by tisfeng** [comment]
@Jerry23011 你可以做这个吗？

我已经优化了 `GeminiService` 服务 https://github.com/tisfeng/Easydict/pull/561 ，你只要参考现有的 OpenAI 服务和内置 AI 服务代码，应该就能完成对 Gemini 的改造。

**Comment by Jerry23011** [comment]
最近没看issues，这个我来试试

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本已实现。
