### ISSUE TITLE
🚀 功能建议：【点击】查询图标才触发翻译

### ISSUE THREAD

**Issue by hedongshu** [tisfeng/Easydict#56]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

鼠标滑词翻译功能现在是 hover到那个翻译图标就会触发，我希望能提供一个开关让他能改成 click 触发。

**Comment by tisfeng** [comment]
感谢反馈。

其实我考虑过这个，但实现的时候遇到了问题：点击触发时，除了会显示当前查询窗口，还是会自动显示 Easydict 的其他窗口（比如设置页，或主窗口等）😓 ，这不是我想要的效果。

这是个技术问题，由于对 macOS 开发还不熟，我暂时没找到解决方法，有懂的小伙伴可以告知一下。

**Comment by zhjh0521** [comment]
> 感谢反馈。
> 
> 其实我考虑过这个，但实现的时候遇到了问题：点击触发时，除了会显示当前查询窗口，还是会自动显示 Easydict 的其他窗口（比如设置页，或主窗口等）😓 ，这不是我想要的效果。
> 
> 这是个技术问题，由于对 macOS 开发还不熟，我暂时没找到解决方法，有懂的小伙伴可以告知一下。

也希望支持这个功能，现在鼠标 hover到那个翻译图标就会触发，经常是不想要触发翻译的

**Comment by tisfeng** [comment]
行，那我暂时糊一个 🤔

**Comment by ahbjcb** [comment]
同样希望加点击,
经常 误触发 和 想触发时,因为鼠标移动而消失 能增加图标消失的时间选项 1-10秒吗

**Comment by tisfeng** [comment]
Easydict 的取词图标功能主要参考了 PopClip，鼠标滑出一定范围，鼠标点击，或输入有效按键，或滑到滚轮都会触发隐藏图标，但并没有设置自动隐藏时间。

请问你这个具体是什么场景，希望如何改进？

**Comment by tisfeng** [comment]
你好，新版本已提供【点击查询】选项  https://github.com/tisfeng/Easydict/releases/tag/1.3.0

**Comment by tisfeng** [comment]
另外，也参考 PopClip 优化了隐藏图标的使用体验。
