### ISSUE TITLE
🐞 反馈问题：将“换行符”转换为“空格”功能在adobe acobat中失效

### ISSUE THREAD

**Issue by Piggy-Boy** [tisfeng/Easydict#563]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

在使用adobe acrobat打开的pdf进行划词翻译时，无法通过“将换行符转换为空格”功能将空格替换。
issues #513 最新的评论也报告了此问题

附：此功能在用“预览”app打开pdf时有效，仅在adobe acrobat中失效

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1. adobe acrobat打开pdf
2. 使用鼠标划词或者快捷键翻译对多行文本进行翻译
3. 点击、选中文本点击“将换行符转换为空格”均无效

### 截图

<img width="975" alt="issue" src="https://github.com/tisfeng/Easydict/assets/24268580/a3c5a69c-c542-4762-b523-846dfd449cf1">

### 期望结果

“将换行符转换为空格”功能能支持adobe acrobat，自动或者手动替换换行均可

### 解决方案（可选）

个人猜测：可能是adobe acobat中的换行符"\r"、"\n"、"\r\n"与代码中检测不一致。

### 设备型号 && 系统版本

Apple M1 Pro, MacOS 13.5.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
我没用过 adobe acobat，有人能帮忙测一下这个问题吗

**Comment by tisfeng** [comment]
感谢反馈，调试发现 adobe acobat 中使用的换行符是 `\r` 而不是常用的 `\n`，稍后我处理一下。

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本已修复该问题。
