### ISSUE TITLE
🚀 功能建议：迷你窗口，侧悬浮窗口，主窗口有些多余

### ISSUE THREAD

**Issue by louischanz** [tisfeng/Easydict#565]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

不知道大家的需求如何，在我看来分出三个窗口不同的翻译途径有些多余，一般情况下不会开启过多的翻译服务去做比较，可能主流的就三五个

### 使用场景

日常场景

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
最初设计时，这些窗口应该有不同的使用场景和功能，但由于某些原因暂未实现 https://github.com/tisfeng/Easydict/issues/103#issuecomment-1557265180 。

因此，如果你只想使用一个窗口，可在设置中修改鼠标划词和快捷键划词使用的窗口类型。

至于主窗口，默认是关闭的，如果你没有这方面的需要，忽略就是了。

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/0e6f7d19-27a7-43ae-94e6-3d38d6da20b8">

**Comment by tisfeng** [comment]
为了让 Easydict 更容易使用，减少新用户的困惑，我决定将 fixed 窗口设置为默认窗口，鼠标选择和快捷键都默认使用 fixed 窗口 https://github.com/tisfeng/Easydict/pull/610

**Comment by jaychoubaby** [comment]
从哪里才能调出主窗口呢？
