### ISSUE TITLE
🐞 反馈问题：使用Kimi翻译，输入API后提示错误，可能是和endpoint有关

### ISSUE THREAD

**Issue by valens7** [tisfeng/Easydict#568]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

如图
<img width="543" alt="image" src="https://github.com/tisfeng/Easydict/assets/35646496/bd62fa6e-3a1d-4515-b5dd-740b32a55755">

### 该问题是否可以稳定重现？

可重现

### 重现步骤

不确定是否是我一个人

### 截图

<img width="543" alt="image" src="https://github.com/tisfeng/Easydict/assets/35646496/cf865cb0-1104-4800-89f5-105c6d998de5">

### 期望结果

使用KIMI

### 设备型号 && 系统版本

M2, 15 inch MBA

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
你的 endpoint 错了，注意格式，它必须是完整的请求地址，例如 https://api.moonshot.cn/v1/chat/completions
