### ISSUE TITLE
Translating to Brazilian Portuguese

### ISSUE THREAD

**Issue by rmoncks** [tisfeng/Easydict#569]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Feature description

Hi! Thanks for this awesome tool, I love it. The only thing it would be great for me is that, when selecting the language, I could opt to translate the text to Brazilian Portuguese (which is supported in DeepL and Google Translate, for example). As for now, I can only select Pt-Pt (Portuguese from Portugal), not Pt-Br, which are very different, meaning that I use the tool only as a shortcut to the DeepL page, for example. I don't need EasyDict to be localized to Pt-Br, I would only like to select it as a target language for my translations. Is that possible? 

Sorry if this is not the best place to ask this question - I haven't found this request elsewhere.

Thanks!

### Use case

When translating texts from English to Brazilian Portuguese, for example. The Pt-Pt option is not adequate for Pt-Br.

### Are you willing to submit a PR to implement this feature

- [ ] I'm willing to submit PR

**Comment by tisfeng** [comment]
@NeverAgain11 hi, do you have time to do this?

**Comment by NeverAgain11** [comment]
@tisfeng OK, I'll do it.

**Comment by tisfeng** [comment]
The [2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) version has support for Brazilian Portuguese.
