### ISSUE TITLE
🚀 功能建议：希望能开发 Windows 版本

### ISSUE THREAD

**Issue by Mlearn** [tisfeng/Easydict#57]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

是否有后续开发 Windows 版本的计划呢？很期待。

### 使用场景（可选）

Windows 上目前尝试使用的划词翻译软件中， QTranslate 是最好的了，但还是有很多的问题，比如响应迟缓、界面风格古老、使用习惯不适应等。

我想不少用户工作生活中都存在跨平台的现象。非常希望在 Windows 能见到 Easydict 的出现。

**Comment by tisfeng** [comment]
额，我只会一点 macOS 开发，不懂 Windows 😥 

建议可以找个热爱开源、对词典翻译类应用感兴趣的 Windows 大佬来做，其实有了参考原型后，技术上的开发都不难～

**Comment by tisfeng** [comment]
其实之前关注过这个词典翻译项目  https://github.com/KrisLee1/panda-dict ，但可惜后面没有继续更新了。

Windows 的话，可以看看这个  https://github.com/pot-app/pot-desktop ，一个跨平台的划词翻译软件。

**Comment by tisfeng** [comment]
所以，短时间内 Easydict 不会有 Windows 或 Linux 版本，长时间也不一定会有，除非某一天醒来开发者 JS 功力大增，又或者突然对跨平台版本 Easydict 起了强烈兴趣。

目前有这方面需求的朋友，可以看看这个项目  https://github.com/pot-app/pot-desktop ，一个跨平台的划词翻译软件，macOS，Windows 和 Linux 都支持， 项目初期还在快速发展中，开源项目，大家有什么功能建议都可以去提 issue 反馈的。

<table>
    <td> <img src="https://cdn.staticaly.com/gh/pot-app/pot-desktop/master/asset/dark.png">
    <td> <img src="https://cdn.staticaly.com/gh/pot-app/pot-desktop/master/asset/example.png">
    <td> <img src="https://cdn.staticaly.com/gh/pot-app/pot-desktop/master/asset/light.png">
</table>

**Comment by ruinmi** [comment]
我刚想把我下载的那款给卸载了，突然发现没有Windows

**Comment by xiaocang** [comment]
https://github.com/xiaocang/easydict_win32
我移植了 win 版本，现在还处于比较早的阶段，不过大多功能都已经实现了
cc @tisfeng
