### ISSUE TITLE
🚀文本串拼接

### ISSUE THREAD

**Issue by kplngyi** [tisfeng/Easydict#579]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

在复制长短英文的时候，尤其是扫描类pdf文件，在字符之间会出现空格（换行之类的），希望能够实现拼接功能，这样的话能省下很多时间。

### 使用场景

在复制长短英文的时候，尤其是扫描类pdf文件，在字符之间会出现空格，希望能够实现拼接功能
<img width="348" alt="Screenshot 2024-06-04 at 3 58 23 PM" src="https://github.com/tisfeng/Easydict/assets/54162311/6ec272a7-ba7b-4bd1-bae7-44b23d990822">
<img width="353" alt="Screenshot 2024-06-04 at 3 58 09 PM" src="https://github.com/tisfeng/Easydict/assets/54162311/a180f2da-6f5d-41ac-a216-fb3e340149d6">

### 实现方案（可选）

需要再处理一遍粘贴板上的字符串

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
将「换行符」替换为「空格」

<img width="1023" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/9f21dce1-883d-47b5-8062-39379c1c9366">

**Comment by kplngyi** [comment]
收到 谢谢 尝试了一下感觉不错 请问这个功能如何默认开启（软件很棒 UI也很喜欢

**Comment by tisfeng** [comment]
不，这个没有默认开启选项。

和【去除代码注释符号】这些功能不一样，大部份场景下用户应该不需要替换换行符，否则会丢失段落格式，请仅在需要时手动点击使用。
