### ISSUE TITLE
🐞 反馈问题：在隐藏菜单栏后无法进入偏好设置页面

### ISSUE THREAD

**Issue by evnydd0sf** [tisfeng/Easydict#58]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

在将 Easydict 偏好设置中的在菜单栏显示选项关闭后，没有可以在打开偏好设置的路径。

已尝试：
1. 强制退出后在打开
2. 卸载后再安装

### 重现步骤

无

### 期望结果

希望可以点击 launchpad app 图标时，临时显示进入偏好设置的路径，

### 解决方案（可选）

希望可以类似 Remote for Mac 那样，在 launchpad 中点击图片，会提示
<img width="372" alt="image" src="https://user-images.githubusercontent.com/16290402/232650488-ed56e2fe-eb4b-40d5-ada7-f5361d5a7e4d.png">
用户可以选择是否要进入偏好设置。

### 设备信息 && 操作系统版本（可选）

MacBook Pro 16 2021 M1Pro 13.4 Beta版(22F5037d)

**Comment by tisfeng** [comment]
看一下 https://github.com/tisfeng/Easydict/issues/20
