### ISSUE TITLE
🚀 功能建议：Easydict 支持本地 HTTP 接口请求

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#580]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

让 Easydict 支持本地 HTTP 接口请求，方便外部程序调用，实现翻译查询，划词，OCR，以及将 Easydict 查询结果以接口形式返回等功能。

### 使用场景

例如， Alfred Workflow 使用 HTTP 接口调用 Easydict  https://github.com/tisfeng/Easydict/issues/78#issuecomment-2147715310

### 实现方案（可选）

Swift HTTP 服务器使用 [vapor](https://github.com/vapor/vapor) ？

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by marsjane** [comment]
支持 也非常需要这个功能 另外想问一下现在有什么通过执行一个命令的方式去调出这个划词翻译/输入翻译/截图翻译窗口的吗？类似的bob里面提供Apple script的方式, pot里面提供curl 一个本地端口的方式

**Comment by tisfeng** [comment]
> 支持 也非常需要这个功能 另外想问一下现在有什么通过执行一个命令的方式去调出这个划词翻译/输入翻译/截图翻译窗口的吗？类似的bob里面提供Apple script的方式, pot里面提供curl 一个本地端口的方式

Easydict 支持 [URL Scheme](https://github.com/tisfeng/Easydict?tab=readme-ov-file#url-scheme) 调用。

**Comment by marsjane** [comment]
oh可不可以是一个命令直接达到按下快捷键的功能？比如我执行一个shell命令 它直接跟快捷键一样直接获取我选中的文字进行翻译？ 以及另一个命令启动截图翻译等等..

**Comment by tisfeng** [comment]
目前  URL Scheme 只支持调用 Easydict 查询文本：easydict://query?text=good 。

如果你想 shell 调用，你先为 Easydict 设置好快捷键，比如划词翻译 Opt + D，然后脚本使用模拟这个快捷键就行。

**Comment by WillSuo-Github** [comment]
HI, 之前我说可以帮忙搞这个的, 但是我最近有好多事情, 造成最近应该就没有时间搞这个事情了, 非常抱歉哦.

**Comment by tisfeng** [comment]
Sad 😔 那暂时先放这儿。

如果有小伙伴对这个有兴趣，可以留言接手一下。

**Comment by tisfeng** [comment]
我来用 [vapor](https://github.com/vapor/vapor) 尝试一下。

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本目前已支持 translate 和 ocr 两个接口。

**Comment by tisfeng** [comment]
还没写文档，，服务类型在这里 https://github.com/tisfeng/Easydict/blob/2d0cf752df5fd3e7f31e5752409c801744d83f2a/Easydict/objc/Service/Model/EZEnumTypes.m#L13

```
NSString *const EZServiceTypeGoogle = @"Google";
NSString *const EZServiceTypeBaidu = @"Baidu";
NSString *const EZServiceTypeYoudao = @"Youdao";
NSString *const EZServiceTypeApple = @"Apple";
NSString *const EZServiceTypeDeepL = @"DeepL";
NSString *const EZServiceTypeVolcano = @"Volcano";
NSString *const EZServiceTypeOpenAI = @"OpenAI";
NSString *const EZServiceTypeCustomOpenAI = @"CustomOpenAI";
NSString *const EZServiceTypeBuiltInAI = @"BuiltInAI";
NSString *const EZServiceTypeBing = @"Bing";
NSString *const EZServiceTypeNiuTrans = @"NiuTrans";
NSString *const EZServiceTypeCaiyun = @"Caiyun";
NSString *const EZServiceTypeTencent = @"Tencent";
NSString *const EZServiceTypeAlibaba = @"Alibaba";
NSString *const EZServiceTypeGemini = @"Gemini";
NSString *const EZServiceTypeOllama = @"Ollama";
NSString *const EZServiceTypePolishing = @"Polishing";
NSString *const EZServiceTypeSummary = @"Summary";

NSString *const EZServiceTypeAppleDictionary = @"AppleDictionary";
```

**Comment by tisfeng** [comment]
[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。

**Comment by firzen** [comment]
BuiltInAI 提示需要 StremTranslate 接口，这个http支持吗？

![image](https://github.com/user-attachments/assets/cb82bf31-31b7-4a00-ae45-fdb6369225c6)

**Comment by tisfeng** [comment]
理论上也可以支持，但 stream 和常规接口有些不一样，我担心出问题，因此目前只能在 debug 模式使用。

稍后我把 streamTranslate 接口也开放出来吧。

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/83c76487-7e00-4c77-b936-cca6d2945cec" />

**Comment by tisfeng** [comment]
[2.10.2](https://github.com/tisfeng/Easydict/releases/tag/2.10.2) 版本已开放 streamTranslate 接口。

**Comment by cxwx** [comment]
有cli吗？还是自己写curl？
