### ISSUE TITLE
🚀 Feature Request: Disable TTS entirely

### ISSUE THREAD

**Issue by Nokinori** [tisfeng/Easydict#581]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Feature description

Hello! 
I see that there are options for different TTS services.
But I want to just disable it. According to the doc, there is no such possibility.

### Use case

I'm sitting late, reading some comments, and then I decided to translate one word...
All my family hears what it is. 

### Are you willing to submit a PR to implement this feature

- [ ] I'm willing to submit PR

**Comment by tisfeng** [comment]
I don't quite understand your request. 

Do you need to turn off the automatic pronunciation of English words?

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/2586d571-c948-4dfd-9e60-6ec3e3772e4f">

**Comment by tisfeng** [comment]
The default setting for automatic pronunciation of English words may confuse some users, I will change it to default off shortly.
