### ISSUE TITLE
🚀 功能建议：Easydict 支持「润色/语法检查+总结」

### ISSUE THREAD

**Issue by yaoyhu** [tisfeng/Easydict#588]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

类似于 openai-translator，多加两个按钮用于 polishing 和 summary。
<img width="459" alt="image" src="https://github.com/tisfeng/Easydict/assets/86143910/2e9115da-9552-4aed-adc1-e099c463f544">

### 使用场景

Easydict 使用快捷键直接唤出可应用于一切文本：
- 替代 Grammarly 逐个词报错，更好优化需要开会员，且需要单独下软件，不能应用于全局
- 替代 LanguageTool 这种插件和桌面软件都要下的软件，且 Safari 支持不太好，软件适配不够多（读取文本是否安全？）
- 不需要老是打开 AI 客户端复制粘贴去润色/总结句子

### 实现方案（可选）

由于本人不会 swift 无法贡献代码，但可以给出一些拙见：
1. 关于 prompt: 看了#260，可以征集好的 prompt 写进代码里，不用实现自定义 prompt 对开发者友好
2. 关于选择模型：可以直接使用已经配置好的模型？或者重新填写亦可

或者可以参考 openai-translator 的关于这方面的实现 [PR](https://github.com/openai-translator/openai-translator/pull/719)

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
感谢建议，我们先构思一下，主要是这个功能在 Easydict 上的产品设计。

**Comment by tisfeng** [comment]
想了一下，感觉可以先添加两个单独的服务 polishing 和 summary，类似现在的翻译服务，但它们的功能是润色和总结。

目前这部分代码经重构后，已经可以很容易地添加类似这样的 AI 服务了，只需要调一下 prompt 就行。

等后面完成自定义 prompt https://github.com/tisfeng/Easydict/issues/434 和添加多个自定义 OpenAI 服务 https://github.com/tisfeng/Easydict/issues/479 ，用户可以随意创建自己想要的 AI 服务。

**Comment by yaoyhu** [comment]
> 想了一下，感觉可以先添加两个单独的服务 polishing 和 summary，类似现在的翻译服务，但它们的功能是润色和总结。
> 
> 目前这部分代码经重构后，已经可以很容易地添加类似这样的 AI 服务了，只需要调一下 prompt 就行。
> 
> 等后面完成自定义 prompt #434 和添加多个自定义 OpenAI 服务 #479 ，用户可以随意创建自己想要的 AI 服务。

LGTM!

**Comment by tisfeng** [comment]
稍后我们可以参考 PopClip 优化一下服务入口，划词后不再简单显示一个查询图标，而是一个动作列表的 action bar，允许用户将一些服务添加到这里，点击后直接进行该服务查询，而不是查询所有的翻译服务。

<img width="932" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/7e0506dd-9f80-494f-8ce7-fe30b80c9f82">

**Comment by tisfeng** [comment]
@Jerry23011 你可以做一下这个吗，添加 polishing 和 summary 两个服务就行，就基于内置 AI 服务使用模型 llama3-70b-8192，然后重写一下 prompt。

**Comment by Jerry23011** [comment]
OK

**Comment by Jerry23011** [comment]
> 就基于内置 AI 服务使用模型 llama3-70b-8192

这里允许用户自定义模型吗？还是只支持这一个呢

**Comment by tisfeng** [comment]
先别太复杂，暂时就使用这一个模型，它速度快，效果也不错。

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本已添加两个新的 AI 工具类服务：润色（Polishing)）和总结（Summary）。
