### ISSUE TITLE
如何将语言切换为中文。

### ISSUE THREAD

**Issue by skdfslkdfskl** [tisfeng/Easydict#590]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

我在设置中将：First Language 选择为简体中文，Second Language 选择为繁体中文，重启后界面任然是英文。卸载重新安装，更换版本，依旧如此。
请问是我哪里设置错误了吗？我看介绍页面，本软件是支持中文的吧。
求解，谢谢！

### 该问题是否可以稳定重现？

可重现

### 重现步骤

First Language 选择为简体中文，Second Language 选择为繁体中文，重启后界面任然是英文。卸载重新安装，更换版本，依旧如此。

### 截图

![Xnip2024-06-15_22-32-46](https://github.com/tisfeng/Easydict/assets/145334558/2e3b7727-b498-4253-a4aa-29214a9244a0)

### 期望结果

告知我是否支持简体中文，或告知我哪里设置错误。

### 设备型号 && 系统版本

macmini m1，12.7.5 Monterey

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by skdfslkdfskl** [comment]
补充，我的软件版本为： Easydict 2.7.2

**Comment by tisfeng** [comment]
这里的 First Language 是指翻译便好语言第一语言，不是应用界面语言。

Easydict 只有 macOS 13.0+ 才支持应用内切换界面语言，否则需要手动去设置-通用-语言与地区修改。

<img width="715" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/360fff38-3cbf-4aee-ad4f-a3d39120348b">

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/1d33b139-ce95-4597-a851-edd0aa7d599a">

**Comment by skdfslkdfskl** [comment]
明白了，谢谢！
