### ISSUE TITLE
关于语言设置

### ISSUE THREAD

**Issue by dwgzT** [tisfeng/Easydict#597]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

挺有趣的一个现象，完全不影响使用，但是可以复现。
如果是英文系统，在系统设置中，制定将Easydict设置为中文，那么此操作只能有效1次，当Easydict运行并退出之后，在系统设置中查看，原来操作将变为英文。
在Easydict app中的语言设置并不能改变这个状况，但能够保证app界面一只保持为中文。
当系统设置中的语言被自动改回英文时，如果Easydict app中的语言设置为中文，那么app将展现中文用户界面，但菜单是英文的。尽管菜单没什么用。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

先修改系统设置，再正常运行app，退出。再查看系统设置。

### 截图

<img width="468" alt="Screenshot 2024-06-29 at 6 22 16 PM" src="https://github.com/tisfeng/Easydict/assets/162351332/96a1514c-25b6-46e8-aad6-69b030a3fec3">

### 期望结果

让系统设置中的语言设定结果不被改变

### 设备型号 && 系统版本

M1/intel, macOS 14.5

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
@choykarl 有空看一下这个问题 😶

**Comment by choykarl** [comment]
抱歉，我没有看太明白是什么意思。。。

**Comment by tisfeng** [comment]
@dwgzT 我也没看懂，你能详细描述一下问题吗？

**Comment by dwgzT** [comment]
感谢关注此问题。
我试试用一张图来描述问题。如图，Easydict app 中语言设置为中文，但是它的菜单却是英文的，理论上即便是在英文的macOS下这个界面也不应该存在。

事实上，如果macOS为英文，Easydict设成中文后，菜单的确是中文的。但只要关闭Easydict，再次打开的时候，菜单就变英文的了。

参见截图中macOS的系统设置，Easydict的语言被设置成英文------这个并不是我设置的。我原本设置为中文的，但每次运行Easydict后，它就自动改回来。

我描述一下我的使用环境：这个软件我用来使用DeepL API来翻译长文本，所以除了DeepL外，其他服务全部都是关闭的。


<img width="1106" alt="Screenshot 2024-07-16 at 9 53 28 PM" src="https://github.com/user-attachments/assets/6a69adea-8dd7-4b5e-a1a2-cd1d298ba9c5">

**Comment by choykarl** [comment]
是有些奇怪，目前没找到是什么原因导致的，你如果需要修改语言，请先用app内置的语言偏好设置。

**Comment by tisfeng** [comment]
@dwgzT  是的，请使用 Easydict 的应用设置切换显示语言，不然可能会有冲突，我们没有处理这种异常情况。
