### ISSUE TITLE
功能建议：自定义隐藏菜单栏图标

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#6]
## 功能描述

既然都可以用快捷键操作，那还是希望能提供一个自定义选项来隐藏这个菜单栏图标。

**Comment by tisfeng** [comment]
这个可以有。

非常感谢你的反馈和建议，对我很有帮助，希望能收到更多来自你的建议，无论是功能或是使用体验上的问题，我都会仔细考虑。

**Comment by Alphabet1226** [comment]
我也非常开心能为这么喜爱的产品提出建议，这么好的产品肯定会越来越好的！太感谢你开发这么棒的作品了，该感谢的是我才对。

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已支持隐藏状态栏图标。
