### ISSUE TITLE
🐞 反馈问题：划词翻译和 edge 浏览器冲突

### ISSUE THREAD

**Issue by pipashu** [tisfeng/Easydict#605]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

edge 浏览器截图时会弹出功能菜单（复制，保存，视觉搜索），但是在Easydict开启的状态下，edge 浏览器的该菜单会闪现并消失，显示已复制提示，然后截图功能自动退出。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

打开Easydict，edge，在 edge 使用截图功能。

### 截图

![QQ20240711-094924](https://github.com/tisfeng/Easydict/assets/27265628/343c4e18-18f2-4cbe-81f0-c080e3a2ea2f)
![QQ20240711-095026](https://github.com/tisfeng/Easydict/assets/27265628/076f31de-924a-44f2-a88f-26a32455ff15)

### 期望结果

edge 划词功能可以正常使用。

### 设备型号 && 系统版本

Apple M1，macOS15

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
请开启 Edge【允许 Apple 事件中的 JavaScript】选项。

<img width="935" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/90380618-dfe7-4b7f-aa8c-fbae5047eb93">

**Comment by pipashu** [comment]
谢谢🙏
