### ISSUE TITLE
🐞 Bug Report: control + c ,老是复制出问题

### ISSUE THREAD

**Issue by xiaoboJoin** [tisfeng/Easydict#608]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

打开这个软件的时候，control + c ,老是复制出问题，有时候复制不了，剪切板还是上次复制的内容，有时候要control+c好几次，才能复制到内容，啥原因？

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

打开这个软件的时候，control + c ,老是复制出问题，有时候复制不了，剪切板还是上次复制的内容，有时候要control+c好几次，才能复制到内容，啥原因？

### Screenshot

打开这个软件的时候，control + c ,老是复制出问题，有时候复制不了，剪切板还是上次复制的内容，有时候要control+c好几次，才能复制到内容，啥原因？

### Expected result

打开这个软件的时候，control + c ,老是复制出问题，有时候复制不了，剪切板还是上次复制的内容，有时候要control+c好几次，才能复制到内容，啥原因？

### Device type and OS version

M2 PRO

### Are you willing to submit a PR to fix this issue?

- [X] I'm willing to submit a PR

**Comment by tisfeng** [comment]
和这个 https://github.com/tisfeng/Easydict/issues/503 类似，可能是 Easydict 强制划词导致的问题，目前没有很好的解决方法，请尝试在设置中关闭这个选项。

电脑上其他类似划词应用也可能导致这个问题，例如 PopClip，有道词典，欧路词典等。

**Comment by JackeyLov5** [comment]
> 和这个#503类似，可能是Easydict 强制划词导致的问题，目前没有很好的解决方法，请尝试在设置中关闭这个选项。
> 
> 电脑上其他类似的划词也值得关注，例如PopClip，有道词典，欧路词典等。

大哥。我又来了。我最近也发现了这个问题。但是我发现我并没有开启强制划词
<img width="820" alt="image" src="https://github.com/user-attachments/assets/ce6f80ed-d9b2-4db7-afcb-339aa6216e92">

**Comment by tisfeng** [comment]
自动复制也可能会导致这种问题，可以闭关试试。

如果不是以上两种情况，那可能和 Easydict 无关。

<img width="820" alt="92348" src="https://github.com/user-attachments/assets/6a825717-ae0f-4b21-82bf-beb03adc01b9">

**Comment by JackeyLov5** [comment]
> 自动复制也可能会导致这种问题，可以闭关试试。
> 
> 如果不是以上两种情况，那可能和 Easydict 无关。
> 
> <img alt="92348" width="820" src="https://private-user-images.githubusercontent.com/25194972/349530115-6a825717-ae0f-4b21-82bf-beb03adc01b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzcyMzQsIm5iZiI6MTcyMTIzNjkzNCwicGF0aCI6Ii8yNTE5NDk3Mi8zNDk1MzAxMTUtNmE4MjU3MTctYWUwZi00YjIxLTgyYmYtYmViMDNhZGMwMWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE3MjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMjllZTJjY2QwOWI1NjU3N2I4ODFjNWQ4NjQ3MTAwNDM2N2IzNmEyMTk3ZDhiYTcwYTMwNjg2YjRmMTFmMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sXvEzZkeQ1scRTtpDrEv3_InF8bGl5Eh4NQ9tN63VHs">

我没开这个自动复制  但是当我退出Easydict后 并没有出现类似情况orz

**Comment by tisfeng** [comment]
这就比较奇怪了，，Easydict 某些地方确实使用了剪贴板，不确定你有没有触发到。由于一些奇怪的原因，这可能会导致污染剪贴板 😓

但这种问题比较难测试，也不好解决。

**Comment by xiaoboJoin** [comment]
<img width="820" alt="image" src="https://github.com/user-attachments/assets/fa4c6398-a1de-4e60-92e0-f2914413d903">
目前关闭自动复制，不会出错

**Comment by JackeyLov5** [comment]
> <img alt="image" width="820" src="https://private-user-images.githubusercontent.com/6210610/352342943-fa4c6398-a1de-4e60-92e0-f2914413d903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjQ1MDgsIm5iZiI6MTcyMTk2NDIwOCwicGF0aCI6Ii82MjEwNjEwLzM1MjM0Mjk0My1mYTRjNjM5OC1hMWRlLTRlNjAtOTJlMC1mMjkxNDQxM2Q5MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMDMyMzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjBjNjViNmQwNWMwMmZmMmRmZWQ3YmNkOGZmOWM2ZDlhYjU2Mzg1MTAwMTk1ZTZlYTZmMmJiZWY2OTE5MzFiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vFwNTuZi8cQ1TP659JJAlycQa947DuOfshToe6SN5T4"> 目前关闭自动复制，不会出错

我一直关闭 也总是复制不了呢

**Comment by tisfeng** [comment]
确定是 Easydict 导致的这个问题吗？关闭后就没有出现了？

如果确定是 Easydict 的问题，还请提供更详细的上下文信息。

**Comment by JackeyLov5** [comment]
> 确定是 Easydict 导致的这个问题吗？关闭后就没有出现了？
> 
> 如果确定是 Easydict 的问题，还请提供更详细的上下文信息。

确定了 就是easydict的问题。。
当我设置是下图时：
<img width="572" alt="image" src="https://github.com/user-attachments/assets/4f6cbe00-812c-46a1-bef4-45215527999b">

我在一个协同表格里滑动选中两个格里的数据 会提示复制成功 其实我并没有任何其他操作，但并没有复制成功，因为当我粘贴时还是上一次的数据 

当我设置是下图时：

<img width="572" alt="image" src="https://github.com/user-attachments/assets/4d864145-527b-45c6-b866-1ce3832b2f42">
就不会出现复制问题

**Comment by tisfeng** [comment]
对比看了一下，似乎只有【划词后自动显示查询图标】选项可能导致问题，但如果不开启强制划词（Cmd + C 取词），默认只会使用 Accessibility 取词，这个是系统的常规 API，按理说它应该是安全的，不太可能导致剪贴板问题。。

很难分析，这个我暂时也看不出哪里有问题 😓

**Comment by JackeyLov5** [comment]
> 对比看了一下，似乎只有【划词后自动显示查询图标】选项可能导致问题，但如果不开启强制划词（Cmd + C 取词），默认只会使用 Accessibility 取词，这个是系统的常规 API，按理说它应该是安全的，不太可能导致剪贴板问题。。
> 
> 很难分析，这个我暂时也看不出哪里有问题 😓

烦请您多关注该bug 挺折磨的😩

**Comment by tisfeng** [comment]
检查代码发现，目前即使未开启【强制划词】选项，Easydict 某些地方也会调用 Cmd + C，我尝试对此进行了修复 https://github.com/tisfeng/Easydict/pull/632 ，不确定是否能解决这个问题 🤔

**Comment by JackeyLov5** [comment]
> 检查代码发现，目前即使未开启【强制划词】选项，Easydict 某些地方也会调用 Cmd + C，我尝试对此进行了修复 #632 ，不确定是否能解决这个问题 🤔

thx！

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本已修复该问题。

如果后续还有问题，再来观察。

**Comment by JackeyLov5** [comment]
建议重启该问题。经过几天使用 我发现还是有50概率会复制失败 orz

**Comment by tisfeng** [comment]
这问题太麻烦了，可能是还没找到根本原因 😥

ok，那就先打开，再观察看看，希望能提供更多有用的信息。

**Comment by oxoxoxox** [comment]
我也遇到了相同的问题，在macOS Sonoma 14.6.1 / Safari 17.6上，访问stackoverflow这个网站，没有开强制取词，但系统粘贴板里面会出现待翻译的文本：
<img width="891" alt="image" src="https://github.com/user-attachments/assets/ee63f099-4c52-4acf-8a58-f760bd451422">
<img width="878" alt="image" src="https://github.com/user-attachments/assets/9e36b6f1-7e3d-4a64-ba5f-eaeac0f4f810">

Alfred粘贴板上能看到被取词的文本（"English is a West Germanic language in the Indo-European language family"）排在我主动CMD+C的文本（"tccutil reset AppleEvents com.izual.Easydict"）的下面：
<img width="366" alt="image" src="https://github.com/user-attachments/assets/7e121cfe-f25e-4c07-accb-897931dfa89c">

这是当前的日志：
[com.izual.Easydict 2024-09-02--10-23-21-531.log](https://github.com/user-attachments/files/16836377/com.izual.Easydict.2024-09-02--10-23-21-531.log)

在测试之前，我已经执行 tccutil reset AppleEvents com.izual.Easydict，重新运行EasyDict，并在弹出窗口中添加了AppleEvent权限：
<img width="475" alt="image" src="https://github.com/user-attachments/assets/c7affd4f-2a72-4368-a166-f7c4a45fe33b">

**Comment by oxoxoxox** [comment]
> 我也遇到了相同的问题，在macOS Sonoma 14.6.1 / Safari 17.6上，访问stackoverflow这个网站，没有开强制取词，但系统粘贴板里面会出现待翻译的文本： 

而且，我这里在Safari里面开启了 允许 Apple 事件中的 JavaScript 选项，并重启了Safari，但log里面还是能看到报错"Not authorized to send Apple events to Safari"

**Comment by oxoxoxox** [comment]
我按照 https://github.com/Whisky-App/Whisky/issues/378 这里说的，在iterm里面手动运行 /Applications/Easydict.app/Contents/MacOS/Easydict，结果在取词的时候，可以弹出Safari的权限申请，同意之后，可以正常取词了，而且没有报错"Not authorized to send Apple events to Safari"。

```
[2024-09-02 19:05:44.587 ● EZEventMonitor ● 395 ● ℹ️] -[EZEventMonitor autoGetSelectedText:] ● auto get selected text
[2024-09-02 19:05:44.589 ● EZEventMonitor ● 519 ● ℹ️] -[EZEventMonitor getSelectedTextByAccessibility:] ● Unsupported Accessibility error: -25212 (kAXErrorNoValue)
[2024-09-02 19:05:44.596 ● EZScriptExecutor ● 124 ● ℹ️] -[EZScriptExecutor runAppleScript:completionHandler:]_block_invoke ● run AppleScript cost: 7.3 ms
[2024-09-02 19:05:44.596 ● EZAppleScriptManager ● 94 ● ℹ️] -[EZAppleScriptManager getSafariSelectedText:]_block_invoke ● Safari selected text: I had the same issue, but if you run the app through terminal (/Applications/Whisky.app/Contents/MacOS/Whisky), then you can run the winetricks
[2024-09-02 19:05:44.979 ● EZWindowManager ● 707 ● ℹ️] -[EZWindowManager selectTextTranslate] ● selectTextTranslate
[2024-09-02 19:05:44.980 ● EZEventMonitor ● 585 ● ℹ️] -[EZEventMonitor isAccessibilityEnabled] ● accessibilityEnabled: 1
[2024-09-02 19:05:44.981 ● EZWindowManager ● 720 ● ℹ️] -[EZWindowManager selectTextTranslate] ● selectTextTranslate windowType: 2
[2024-09-02 19:05:44.983 ● EZEventMonitor ● 519 ● ℹ️] -[EZEventMonitor getSelectedTextByAccessibility:] ● Unsupported Accessibility error: -25212 (kAXErrorNoValue)
[2024-09-02 19:05:44.996 ● EZScriptExecutor ● 124 ● ℹ️] -[EZScriptExecutor runAppleScript:completionHandler:]_block_invoke ● run AppleScript cost: 12.6 ms
[2024-09-02 19:05:44.996 ● EZAppleScriptManager ● 94 ● ℹ️] -[EZAppleScriptManager getSafariSelectedText:]_block_invoke ● Safari selected text: I had the same issue, but if you run the app through terminal (/Applications/Whisky.app/Contents/MacOS/Whisky), then you can run the winetricks
[2024-09-02 19:05:44.996 ● EZWindowManager ● 310 ● ℹ️] -[EZWindowManager showFloatingWindowType:queryText:autoQuery:actionType:atPoint:completionHandler:] ● show floating windowType: 2, queryText: I had the same issue, but if you run the app through terminal (/Applications/Whisky.app/Contents/MacOS/Whisky), then you can run the winetricks, autoQuery: 1, actionType: shortcut_query, atPoint: NSPoint: {1032, 944}
```

我尝试 tccutil reset All com.izual.Easydict，然后重新运行Easydict，并授权所有的权限申请，但还是报错"Not authorized to send Apple events to Safari"。

[com.izual.Easydict 2024-09-02--10-23-21-531（2）.log](https://github.com/user-attachments/files/16836694/com.izual.Easydict.2024-09-02--10-23-21-531.2.log)

**Comment by oxoxoxox** [comment]
翻了一下stackoverflow上别人的提问， 可能是需要在plist里面添加 NSAppleEventsUsageDescription 这个key，明天我在本地用xcode编译出来试试看 。

**Comment by oxoxoxox** [comment]
> 翻了一下stackoverflow上别人的提问， 可能是需要在plist里面添加 NSAppleEventsUsageDescription 这个key，明天我在本地用xcode编译出来试试看 。

本地xcode编译验证，确认添加 NSAppleEventsUsageDescription 后，没有出现"Not authorized to send Apple events to Safari"了。

**Comment by tisfeng** [comment]
是这个吗 https://stackoverflow.com/a/55295234/8378840 ，我之前看过，但没人 check 这一点，也就忽略了。

AppleScript 脚本的执行权限很奇怪， 最开始在我电脑上测试时，使用 `NSAppleScript` 执行取词脚本会失败，直接报没有权限，也不会自动弹窗申请权限，后面我就改用更底层的 `NSTask` 了，这个初次使用会自动申请权限，大部分用户也都运行正常，我以为就解决了。

这个问题我电脑上无法复现，但既然你测试 NSAppleEventsUsageDescription 有效，那我们就先添加试试看。

**Comment by oxoxoxox** [comment]
> 是这个吗 https://stackoverflow.com/a/55295234/8378840 ，我之前看过，但没人 check 这一点，也就忽略了。
> 
> AppleScript 脚本的执行权限很奇怪， 最开始在我电脑上测试时，使用 `NSAppleScript` 执行取词脚本会失败，直接报没有权限，也不会自动弹窗申请权限，后面我就改用更底层的 `NSTask` 了，这个初次使用会自动申请权限，大部分用户也都运行正常，我以为就解决了。
> 
> 这个问题我电脑上无法复现，但既然你测试 NSAppleEventsUsageDescription 有效，那我们就先添加试试看。

我这边测试，添加NSAppleEventsUsageDescription之后，第一次运行时会弹窗申请权限，我reset所有的权限，然后去掉NSAppleEventsUsageDescription重新编译，第一次运行的时候就不弹窗了，只弹出了shortcuts的申请（这个一直都能正常弹出）。
所以看起来是有效果的，至少在我的MacBook环境下有效。😅

**Comment by tisfeng** [comment]
检查了一下代码，其中苹果翻译 shortcuts 脚本是使用 `NSTask` 执行的，但取词部分浏览器脚本是用 `NSAppleScript` （这个比 NSTask 速度快一些），这两种类型是不一样的。

测试发现，如果是使用 `NSTask` 执行脚本，不要 NSAppleEventsUsageDescription 也行，但 `NSAppleScript` 必须添加 NSAppleEventsUsageDescription，不然会直接报错，并且不会弹窗申请权限。


下个版本将会修改这个问题。 你可以用 https://github.com/tisfeng/Easydict/pull/669 测试一下。

**Comment by oxoxoxox** [comment]
> 检查了一下代码，其中苹果翻译 shortcuts 脚本是使用 `NSTask` 执行的，但取词部分浏览器脚本是用 `NSAppleScript` （这个比 NSTask 速度快一些），这两种类型是不一样的。
> 
> 测试发现，如果是使用 `NSTask` 执行脚本，不要 NSAppleEventsUsageDescription 也行，但 `NSAppleScript` 必须添加 NSAppleEventsUsageDescription，不然会直接报错，并且不会弹窗申请权限。
> 
> 下个版本将会修改这个问题。
> 
> 你可以用 #669 测试一下。

我本地编译打包release版本安装到/Applications下面，现在Safari下取词正常了，查看log没有权限报错，粘贴板也不会出现被取词的文本了。

**Comment by oxoxoxox** [comment]
@tisfeng 对了，和这个问题关联，有一个bug，在Safari中取词的时候，如果Accessibility取词失败，AppleScript取词也失败的时候（比如没有权限，或者是其他限制），即使设置项中关闭了“允许强制取词”，还是会模拟快捷键 ⌘ + C 强制取词。
代码实际运行没有遵守设置项中的设定。

**Comment by tisfeng** [comment]
感谢反馈，查了一下，这里代码确实有问题，已提交 PR 修复 https://github.com/tisfeng/Easydict/pull/670 。

**Comment by tisfeng** [comment]
你好，[2.9.0](https://github.com/tisfeng/Easydict/releases/tag/2.9.0) 版本已修复该问题。

我仔细检查了代码，目前如果关闭了【允许强制取词】，不再会调用 Cmd + C，应该不会干扰剪贴板了 🫠
