### ISSUE TITLE
🚀 功能建议：PDF划词和截图换行格式问题

### ISSUE THREAD

**Issue by WAYSC** [tisfeng/Easydict#61]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

在PDF中复制内容也是按照原来的格式分行，但是仍然希望翻译软件能把中间的分行去掉~
不然就要手动清除每行后面Enter，否则它翻译的就是一行一行的内容，而不是完整的段落内容，可以get嘛

### 使用场景（可选）

PDF中的划词/截图翻译

### 实现方案（可选）

emmmm感觉可以清除格式之后再丢到翻译软件中是不是会好一点~~

**Comment by tisfeng** [comment]
OCR 后自动处理换行，你说的是这个吗  https://github.com/tisfeng/Easydict/issues/16

**Comment by tisfeng** [comment]
这个我不太理解，PDF 取词和正常的取词一样，都是遵守原文本段落格式的，目前只有 OCR 取词后格式有点问题，下个版本会修复。

> 在PDF中复制内容也是按照原来的格式分行

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/25194972/232737390-4c4b1df7-f865-4947-85fa-105d9afbad20.png">

**Comment by WAYSC** [comment]
> OCR 后自动处理换行，你说的是这个吗 #16

对滴，不知是怎么设置才能清除换行符呢？

**Comment by WAYSC** [comment]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/50772845/232738560-d023cb69-2720-47f5-a44b-3a66ba912b16.png">
我现在PDF划词翻译为啥还是分行的呢

**Comment by tisfeng** [comment]
> > OCR 后自动处理换行，你说的是这个吗 #16
> 
> 对滴，不知是怎么设置才能清除换行符呢？

额，这个目前不行，是 Feature 😅 过两天，下个版本会实现智能清除多余换行符。

**Comment by WAYSC** [comment]
好的呢~~支持支持~~要是把这个功能调好了简直是PDF阅读懒癌患者的福音🌹

**Comment by tisfeng** [comment]
> <img alt="image" width="743" src="https://user-images.githubusercontent.com/50772845/232738560-d023cb69-2720-47f5-a44b-3a66ba912b16.png">
> 
> 我现在PDF划词翻译为啥还是分行的呢

#### 好像某些翻译服务，会自作多情地对翻译结果进行换行，比如我这里取词了两段文本，有道和谷歌就搞了很多行。你再看一下其他的翻译结果，或者用快捷键 `Opt + D` 取词，完整看看取词文本内容。

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/25194972/232741846-cfdd7f49-9524-4f8a-ad03-6974330a31d2.png">

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/25194972/232742811-ca59115a-312c-45a2-afe1-b9ed7559e6a6.png">

**Comment by WAYSC** [comment]
好的捏~

**Comment by tisfeng** [comment]
你好，新版本已修复该问题  https://github.com/tisfeng/Easydict/releases/tag/1.3.0

**Comment by tisfeng** [comment]
有问题随时反馈～
