### ISSUE TITLE
提个需求， AI 提示语自定义吗

### ISSUE THREAD

**Issue by eachann1024** [tisfeng/Easydict#611]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

目前是固定三个选项， 希望能够自定义提示词。 
 

![Image 2024-07-13 at 03 14 53@2x](https://github.com/user-attachments/assets/4f4d63cf-0c2e-4927-ad6c-20ab2bae5b03)

### 使用场景

比如开发会有一个需求就是把单词转换成变量名，驼峰、下划线的之类的。
让他同时给我返回各种形式的变量名

### 是否愿意提交 PR 实现该功能

- [x] 我愿意提交 PR

**Comment by tisfeng** [comment]
已经有个自定义 prompt 的 issue https://github.com/tisfeng/Easydict/issues/434 ，但没开始做，如果你愿意来 PR，可以先给你。

<img width="268" alt="image" src="https://github.com/user-attachments/assets/90c18250-7a61-4970-92d2-268e3e2330e8">

**Comment by eachann1024** [comment]
> 已经有个自定义 prompt 的 issue #434 ，但没开始做，如果你愿意来 PR，可以先给你。
> 
> <img alt="image" width="268" src="https://private-user-images.githubusercontent.com/25194972/348449321-90c18250-7a61-4970-92d2-268e3e2330e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTQ5MDYsIm5iZiI6MTcyMDg1NDYwNiwicGF0aCI6Ii8yNTE5NDk3Mi8zNDg0NDkzMjEtOTBjMTgyNTAtN2E2MS00OTcwLTkyZDItMjY4ZTNlMjMzMGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA3MTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYzI1YzhkYWViNWYwN2U0NTY5NGNkZmM4YjQ3NTU5MDdkZjVmZTA4OGE5NmIyNjJjNWM5ZWE5NTFiMDUyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fDB_J_oc9N6MVoy7k9S_NDtbVv16P1ybms8-tO8wjOw">

愿意帮忙，但语法不太懂😂

**Comment by tisfeng** [comment]
我看你勾选了提交 PR 选项，就问一下，误选的人有点多 😓

先放这里吧。

**Comment by eachann1024** [comment]
> 我看你勾选了提交 PR 选项，就问一下，误选的人有点多 😓
> 
> 先放这里吧。

哈哈，确实是可以试试，还有不懂就问 ai 问题应该不大，现在也有空。主要是不知道怎么接 pr 去做，之前没做过

**Comment by tisfeng** [comment]
ok，那我先把这个 issue 给你，你尝试一下。

只要熟悉一下 GitHub/Git 操作和 Swift/SwiftUI 语法应该就差不多，有问题可以问 @Jerry23011

**Comment by eachann1024** [comment]
@Jerry23011 请问我该怎么走流程拉取代码呢，我直接拉取代码 -> 创建新的分支进行吗？  实现之后直接提交推送吗？

**Comment by Jerry23011** [comment]
> @Jerry23011 请问我该怎么走流程拉取代码呢，我直接拉取代码 -> 创建新的分支进行吗？ 实现之后直接提交推送吗？

你需要将这个 repo 先 fork 到你自己的账户下，然后基于 dev 分支新建一个分支进行开发，最后再在 tisfeng/Easydict 这个主仓库下提交一个 Pull Request

**Comment by eachann1024** [comment]
> > @Jerry23011 请问我该怎么走流程拉取代码呢，我直接拉取代码 -> 创建新的分支进行吗？ 实现之后直接提交推送吗？
> 
> 你需要将这个 repo 先 fork 到你自己的账户下，然后基于 dev 分支新建一个分支进行开发，最后再在 tisfeng/Easydict 这个主仓库下提交一个 Pull Request

对不起 努力了，但还是失败了 @tisfeng  🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by tisfeng** [comment]
...你可能需先要系统地学习一下 Git 已经 GitHub 相关使用 🫠
