### ISSUE TITLE
Please add privacy statement

### ISSUE THREAD

**Issue by qupig** [tisfeng/Easydict#62]
Thank you so much for developing and open sourcing this project.

I didn't find a privacy statement for this app, I am very concerned about privacy, I would like to know what data it sends, or what analysis data it collects, could you add a description?

I see that it seems to include [Google Analytics](https://github.com/tisfeng/Easydict/blob/8e63a0f58973c60a0f9c10b4e01710155cd2dd03/Podfile#L20) Service, if it is enabled by default, can we turn it off through some setting? I didn't find related settings or instructions in App and Repo.

**Comment by tisfeng** [comment]
Of course, thanks for the reminder, and sorry that this is my first time developing a Mac app and I forgot this important point.

The project uses AppCenter and Firebase, which are mainly used to record user crash logs for bug fixing, and some general analytics, which, rest assured, collects absolutely no user-level privacy, so you can check the code.

Later I will provide instructions to let users know about the crash logs and analytics collected by Easydict, and also provide the option to turn them off.

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/25194972/232947565-dd693b08-e1ac-41b7-a202-e67a4dc2891b.png">

**Comment by tisfeng** [comment]
Hello, the new version has added privacy management options  https://github.com/tisfeng/Easydict/releases/tag/1.3.0
