### ISSUE TITLE
配置自定义deepl接口，请求方式是form表单

### ISSUE THREAD

**Issue by gufeng0** [tisfeng/Easydict#620]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

![image](https://github.com/user-attachments/assets/f29c8303-9535-4064-9ebf-28e6794590cb)

### 该问题是否可以稳定重现？

可重现

### 重现步骤

设置自定义url后
easydict://writeKeyValue?EZDeepLTranslateEndPointKey=http://in.tcyun:1188/translate

### 截图

![image](https://github.com/user-attachments/assets/40296ea2-5a61-4eac-97a4-34b0544b5f4b)

### 期望结果

json请求

### 设备型号 && 系统版本

Intel macOS 14.21

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
[DeepL API](https://developers.deepl.com/docs/v/zh/api-reference/translate/openapi-spec-for-text-translation) 是同时支持 JSON 和 Form 格式，Easydict 代码实现选择使用默认的表单格式，这个也没问题吧 😑

@gufeng0 你是遇到了什么问题吗？

<img width="1395" alt="92170" src="https://github.com/user-attachments/assets/ca055da3-b713-4c8b-90e6-902dd4414f80">

**Comment by tisfeng** [comment]
既然是你自己写的，那你服务器支持表单格式请求不就行了吗？你的接口按照 DeepL 官方文档来，自然可以在 Easydict 中使用。

DeepL API 文档修改过，之前我记得默认是表单格式，所以 Easydict 也是支持的表单。后面不知道什么时候改成了默认 JSON 格式，表单同时也是支持的，我担心如果 Easydict 从表单修改为 JSON 格式可能会一些用户有影响，所以就没改。

**Comment by gufeng0** [comment]
> 既然是你自己写的，那你服务器支持表单格式请求不就行了吗？你的接口按照 DeepL 官方文档来，自然可以在 Easydict 中使用。
> 
> DeepL API 文档修改过，之前我记得默认是表单格式，所以 Easydict 也是支持的表单。后面不知道什么时候改成了默认 JSON 格式，表单同时也是支持的，我担心如果 Easydict 从表单修改为 JSON 格式可能会一些用户有影响，所以就没改。

但我看readme里面有写支持deeplx接口啊
![image](https://github.com/user-attachments/assets/8386a21c-2498-46db-b7e4-49aa7767f141)

**Comment by tisfeng** [comment]
没看懂你的意思，Easydict 支持 DeepLX，DeepLX 也支持表单格式，有什么问题？

**Comment by gufeng0** [comment]
> 没看懂你的意思，Easydict 支持 DeepLX，DeepLX 也支持表单格式，有什么问题？
> 
> 我自己的这个 DeepL 自定义接口用的就是 [DeepLX](https://github.com/OwO-Network/DeepLX) 。

我知道了，原来是需要调/v2/translate 才行
