### ISSUE TITLE
Arc Browser: Insert doesn't work from "Select Translate"

### ISSUE THREAD

**Issue by simonbcn** [tisfeng/Easydict#622]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

Arc Browser. 
When I select text within an input field and press the icon or key combination for "Select Translate", the mini-window with the translation opens and there is a button that allows me to replace the selected text with the translation but it does nothing.

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

Arc Browser. 
When I select text within an input field and press the icon or key combination for "Select Translate", the mini-window with the translation opens and there is a button that allows me to replace the selected text with the translation but it does nothing.

### Screenshot

![Captura de pantalla 2024-07-28 a las 9 19 35](https://github.com/user-attachments/assets/e08651d6-3034-41d7-ac8c-ddec725196ec)

### Expected result

It should replace the selected text with the translation.

### Device type and OS version

macOS 14.5

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by tisfeng** [comment]
I'm not using Arc Browser, @Jerry23011 can you help look at this?

**Comment by Jerry23011** [comment]
I can reproduce the issue.
e.g. On google.com, input “test” in the search field, then select text, and replace with translated text. Works on Safari but not Arc

**Comment by simonbcn** [comment]
Arc Browser is based on Chromium, like most current browsers.

**Comment by tisfeng** [comment]
I tested and found that using the Accessibility method to replace translations on Arc Browser returns successful results, but the actual replacement operation fails, which is strange. It behaves differently from Chrome in some ways.

I added an option to ensure that replacement is successful on Arc Browser https://github.com/tisfeng/Easydict/pull/624 .

**Comment by tisfeng** [comment]
Version [2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) has fixed this issue.

**Comment by simonbcn** [comment]
It still fails.

**Comment by Jerry23011** [comment]
Turn on Replace translation with compatibility mode in advanced settings @simonbcn

**Comment by simonbcn** [comment]
It doesn't work either. Paste the content into the _easydict_ application window:

![Captura de pantalla 2024-08-17 a las 9 18 45](https://github.com/user-attachments/assets/aef6bcf6-c034-4206-a263-27b237ebc0d4)

**Comment by Jerry23011** [comment]
Could you give me the website that didn’t work for you?

**Comment by simonbcn** [comment]
This: github.

**Comment by Jerry23011** [comment]
It works for me. Could you upload a screen recording to reproduce the issue? Thanks

https://github.com/user-attachments/assets/514024b3-0b53-4ec4-9499-1d644cb9bb1c

**Comment by simonbcn** [comment]
https://github.com/user-attachments/assets/a4cb6017-67aa-4d35-9a73-e963a16b8001

**Comment by Jerry23011** [comment]
CC @tisfeng Not sure what's going on here. I can't reproduce the issue with the exact same operations.

@simonbcn Meanwhile, I suggest uninstalling Easydict completely (including the cache and config files) and reinstall it to see if the issue persists. This is to see if the issue happens due to an environment variable on your local macOS.

**Comment by tisfeng** [comment]
@simonbcn First, make sure you have the "Use Replace with Translation in compatibility mode" option turned on.

Also, could you please provide the Easydict log zip file(menu icon -> Help -> Export log) and we'll check it out.

<img width="900" alt="99367" src="https://github.com/user-attachments/assets/5e98531d-b84f-4349-91b8-eb613a9a7522">

**Comment by simonbcn** [comment]
I have uninstalled the application with CleanMyMac. I have done a search on the disk for "easydict" and I have deleted the folders/files that had that name. I have restarted the system and reinstalled the application, now it works correctly.

**Comment by Jerry23011** [comment]
Great to hear that! This could be caused by a data race error where user data is corrupted. We might want to migrate the project to Swift 6 in the future to prevent that.

**Comment by MilchstraB** [comment]
I found that I had to turn on the forced word option to successfully open the translation button in Arc browser.

**Comment by tisfeng** [comment]
No, testing on my computer, Arc supports Accessibility to obtain selected text, which means that it can work without enabling forced word retrieval.

I rarely use Arc and am not familiar with it, so I'm not sure if there is a problem with Arc, because I found that some of its behaviors are different from Chrome, for example, https://github.com/tisfeng/Easydict/issues/622#issuecomment-2256359689.

**Comment by MilchstraB** [comment]
Thanks for your reply! My question is shown in the video. The machine I used was the M2 Macbook Air with MacOS 14.6.1, Arc Browser 1.56.0 and Easydict 2.8.1.

https://github.com/user-attachments/assets/6f128c5f-d349-4648-95b1-93f5c962e261

**Comment by Jerry23011** [comment]
Very interesting. It works on my end as well without enabling force get text.

@MilchstraB How about try resetting your Easydict Accessibility permissions
https://github.com/user-attachments/assets/858b2e06-cb46-4b31-8800-166de65d18cd

**Comment by MilchstraB** [comment]
It's very interesting. I tried to reinstall the APP and reset the permissions for word translation, and only the button that turns on the forced text selection seemed to work for me. If this option is not turned on, text cannot be correctly selected in the sidebar even if the shortcut option + D is used. However, it has little effect on use.

**Comment by tisfeng** [comment]
@MilchstraB You can upload the Easydict zip runtime log. It might be helpful.
