### ISSUE TITLE
无法开机自启

### ISSUE THREAD

**Issue by lisanshengovo** [tisfeng/Easydict#625]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

macos Big Sur 版本 11.7.10
无法开机自启，每次需要手动启动

### 该问题是否可以稳定重现？

可重现

### 重现步骤

已重装

### 截图

![1482245269](https://github.com/user-attachments/assets/fe61f529-45ce-4a34-a238-d536877629bb)

### 期望结果

希望能开机自启

### 设备型号 && 系统版本

M1 macmini macos Big Sur 版本 11.7.10

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
你好，请确认开启了【开机自启动】，并且系统设置-隐私与安全性-自动化下面授权给 Easydict 权限 System Events。

如果开启成功，你应该能在设置-通用-登录项中看到 Easydict。

<img width="820" alt="19296" src="https://github.com/user-attachments/assets/a3e370c0-ed78-430e-a57e-b91612861c84">

<img width="715" alt="86352" src="https://github.com/user-attachments/assets/e0efa35e-09cd-4ada-898d-199addb7f9dc">

**Comment by tisfeng** [comment]
开机启动问题先前已修复 https://github.com/tisfeng/Easydict/issues/64 ，有用户遇到类似问题 https://github.com/tisfeng/Easydict/issues/183#issuecomment-1768582828 ，但也已经解决，请尝试关闭自动化里面的项目后重新启用。

**Comment by tisfeng** [comment]
长时间没有反馈，就先关闭了。
