### ISSUE TITLE
Please add some build instructions

### ISSUE THREAD

**Issue by qupig** [tisfeng/Easydict#63]
As an open source project, we hope that its construction can be reproduced locally. Any developer or user should be able to build and debug the project locally by themselves. Of course, subject to compliance with the license. This is also the basis for possible contributions to the project. Could you add some simple build instructions for this? I don't currently find them in the Repo.

Thanks for developing this open source project!

**Comment by tisfeng** [comment]
Of course, thanks for the heads up.

**Comment by tisfeng** [comment]
It's very easy, in fact, you just need to download this Repo, then open Easydict.xcworkspace with Xcode, compile and run it.

There may be a few minor warnings, but that's okay, I'll update the code and README later, or you can use the code from the dev branch, which is the latest code.

**Comment by oxoxoxox** [comment]
The project is so easy to build. 
Just download the source code, open this project in XCode, select your developer account in the profiles (or else you will get several errors), then click building and enjoy the debugging.
I am not event an Apple developer~
