### ISSUE TITLE
deepl翻译报错不支持阿拉伯语

### ISSUE THREAD

**Issue by gufeng0** [tisfeng/Easydict#630]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

是历史原因吗，我看readme 里面标记 deepl不支持阿拉伯语，但是官网是支持的
![image](https://github.com/user-attachments/assets/8e50c3ef-73b1-43f4-beda-08478b9d00ad)
<img width="1661" alt="image" src="https://github.com/user-attachments/assets/ecf6a6b0-2df3-4166-bd4f-0c8ceed7d472">
接口用的是deeplx ，但是抓包发现没有调接口

### 该问题是否可以稳定重现？

可重现

### 重现步骤

لطفا شرتکات رو به اپ ای او اس اضافه کنید ممنونم

### 截图

<img width="754" alt="image" src="https://github.com/user-attachments/assets/40899a1b-cb93-4475-b571-bbc20d18ffd1">

### 期望结果

正常翻译

### 设备型号 && 系统版本

Intel macOS 14.21

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
查了一下，[DeepL 2024 年 1 月 25](https://www.deepl.com/zh/press-release ) 日开始支持阿拉伯语 ，我们确实也可以跟进。

这个应该比较简单，只要添加一下语言支持和更新文档就行，你可以做这个吗  @choykarl 

<img width="1410" alt="51988" src="https://github.com/user-attachments/assets/90f09e69-4cfb-4179-a3cb-2c9ad54253bc">

**Comment by choykarl** [comment]
好的，我晚点看下哈

**Comment by tisfeng** [comment]
[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本 DeepL 已支持阿拉伯语。
