### ISSUE TITLE
🚀 功能建议：选中或者查询词语，自动识别语种

### ISSUE THREAD

**Issue by DiamondThree** [tisfeng/Easydict#634]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

选中或者查询词语，自动识别语种，如果是英语自动转换成中文，如果是中文，翻译成英文

### 使用场景

阅读，和写东西

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR

**Comment by tisfeng** [comment]
> 选中或者查询词语，自动识别语种，如果是英语自动转换成中文，如果是中文，翻译成英文

没看懂，你能详细描述一下这个功能吗？另外，你可以提交 PR ？

<img width="266" alt="31114" src="https://github.com/user-attachments/assets/da79fae1-da66-4c86-84fc-72e6e50a8212">
