### ISSUE TITLE
🚀 Feature Request: Slovak Localization

### ISSUE THREAD

**Issue by Svec-Tomas** [tisfeng/Easydict#637]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Feature description

I would like to contribute and make available Easydict available in my native language - Slovak

### Use case

It would make it much easier to customize and set up Easydict for those who do not speak good English (or Chinese, the only two languages Easydict is currently available in).

### Proposed solution (optional)

After providing the files or a method for translating the necessary strings, I will translate all strings from English to Slovak and send them for implementation in the next Easydict release.

### Are you willing to submit a PR to implement this feature

- [X] I'm willing to submit PR

**Comment by Jerry23011** [comment]
Thank you for considering contributing! Please see #229

**Comment by tisfeng** [comment]
@Svec-Tomas  Thank you for your contribution. We will support Slovak localization in the next version.

**Comment by tisfeng** [comment]
The feature has been added in version [2.9.0](https://github.com/tisfeng/Easydict/releases/tag/2.9.0).

**Comment by Svec-Tomas** [comment]
Thank you for implementing Slovak translation! ❤️

I will work on fine-tuning my translation to make it perfect and share the updated file with you in the coming days.

On the screen below, the highlighted text is somehow not in Slovak but Slovene.

![EasyDict 00](https://github.com/user-attachments/assets/616115b0-f635-44fc-8c51-628411d38269)

**Comment by Jerry23011** [comment]
> On the screen below, the highlighted text is somehow not in Slovak but Slovene.

Thank you for the feedback. Could you send the correct Slovak translation here , and we will update it.

**Comment by Svec-Tomas** [comment]
Of course, but what is the original text in English, please? So I can translate it.

**Comment by Jerry23011** [comment]
It's `Easydict requires permission to execute AppleScript.`

**Comment by Svec-Tomas** [comment]
Easydict vyžaduje povolenie na vykonanie AppleScriptu.

**Comment by Jerry23011** [comment]
Thank you!
