### ISSUE TITLE
🐞 反馈问题：最新版本2.8.0 TAG没有dmg下载包

### ISSUE THREAD

**Issue by ychy00001** [tisfeng/Easydict#638]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

最新版本[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 没有mac安装包。只有源码，怎么下载最新的应用

### 该问题是否可以稳定重现？

可重现

### 重现步骤

见描述

### 截图

见描述

### 期望结果

可以下载dmg安装包

### 设备型号 && 系统版本

macOS 14.6 Air M3

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR

**Comment by tisfeng** [comment]
本来昨晚准备好了发布新版本，但打包后发现一个应用崩溃问题 f647167d ，等我今晚在来试试。

**Comment by tisfeng** [comment]
ok，[2.8.0](https://github.com/tisfeng/Easydict/releases/tag/2.8.0) 版本已发布。
