### ISSUE TITLE
🚀 功能建议：建议将换行符替换为空格功能在设置里常驻

### ISSUE THREAD

**Issue by Lhli001** [tisfeng/Easydict#639]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

[首先感谢开发者的软件，在使用软件翻译pdf格式的文献时，经常出现一下问题（换行符每次都需要手动在中替换为空格)，虽然OCR功能已足够好用，但在某些场景下还是使用划词更方便，谢谢！!
<img width="702" alt="截屏2024-08-13 10 13 51" src="https://github.com/user-attachments/assets/1e99a1e7-adc4-49c6-9028-b026e80cbfad">
<img width="351" alt="截屏2024-08-13 10 14 11" src="https://github.com/user-attachments/assets/cf3e93f4-8f6a-4022-b639-5a1c0c215502">
<img width="206" alt="截屏2024-08-13 10 14 19" src="https://github.com/user-attachments/assets/9f1e6ff9-b83e-41d2-8417-db604c9e0e92">

### 使用场景

翻译pdf格式的文献时

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
> 建议将换行符替换为空格功能在设置里常驻

不是很理解，目前不是已经在窗口右上角的快捷菜单里面了吗？

**Comment by Lhli001** [comment]
在阅读pdf文档时，每次都是这样子的，都不是连贯的一句话。能不能设置一个自动识别或者默认将换行符直接替换成空格或者删除的，不然每次都得在右上角的快捷菜单里点真的非常麻烦，
<img width="339" alt="截屏2024-08-13 22 09 55" src="https://github.com/user-attachments/assets/08c22489-3c43-49af-bb42-c432e305995f">

**Comment by tisfeng** [comment]
你是说类似这样，在设置中添加一个默认选项【将换行符替换为空格】？

<img width="900" alt="42641" src="https://github.com/user-attachments/assets/acf87726-85c3-4ac0-b07e-108d7bff7044">

**Comment by tisfeng** [comment]
ok，明白了， 稍后我们会添加一个这样的选项。

**Comment by tisfeng** [comment]
@choykarl 有空可以加一下这个。

**Comment by choykarl** [comment]
好的，我晚点加一下

**Comment by xuestrange** [comment]
强烈建议加入这个选项，隔壁的[Pot](https://github.com/pot-app/pot-desktop)甚至都会自动做这个事情，感谢开发者！

**Comment by tisfeng** [comment]
加了加了，这几天就准备发新版本。

<img width="900" alt="image" src="https://github.com/user-attachments/assets/2c8e1950-a500-4380-897d-8f3a1ba48a7b">

**Comment by qq420100523** [comment]
> 加了加了，这几天就准备发新版本。
> 

果然有人提这个需求，作者准备发布新版本啊

**Comment by xuestrange** [comment]
> > 加了加了，这几天就准备发新版本。
> 
> 果然有人提这个需求，作者准备什么时间发布新版本啊

+1

**Comment by tisfeng** [comment]
本来准备发布了，但发现一个问题 https://github.com/tisfeng/Easydict/pull/693#issuecomment-2408920916 ，等这个解决了就可以发布新版本了。

**Comment by tisfeng** [comment]
今天，或明天，一定发。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。
