### ISSUE TITLE
🐞 反馈问题：开机自启动无效

### ISSUE THREAD

**Issue by isahwn** [tisfeng/Easydict#64]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

macOS 13.3.1
Easydict 1.2.3
已勾选 Launch at login，但是开机仍然无法自启动。
<img width="801" alt="SCR-20230419-mboj" src="https://user-images.githubusercontent.com/19422918/232977200-651dd38b-cf53-4c7a-aa1b-7b329bdf940d.png">
<img width="592" alt="SCR-20230419-mezt" src="https://user-images.githubusercontent.com/19422918/232977213-3bc94174-b293-4199-bcbe-d444d9a65d61.png">

### 重现步骤

尝试前往系统偏好设置 - 通用 - 登录项，手动添加 Easydict，但是添加后并未出现在列表中，也就无法开机自启动。

### 期望结果

修复。

### 设备信息 && 操作系统版本（可选）

macOS 13.3.1, Intel

**Comment by tisfeng** [comment]
在 GitHub Coplit 的帮助下找到了一个 trick 实现，测试能达到效果，虽然不知道会不会有坑，先用起来再说，后面有坑再填 🙃

**Comment by tisfeng** [comment]
你好，新版本已修复该问题  https://github.com/tisfeng/Easydict/releases/tag/1.3.0
