### ISSUE TITLE
更新2.8版本后，无法划词翻译

### ISSUE THREAD

**Issue by OwnerCM** [tisfeng/Easydict#640]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

更新2.8版本后，Teams聊天内容无法划词翻译

### 该问题是否可以稳定重现？

可重现

### 重现步骤

快捷键划词无反应

### 截图

快捷键划词无反应

### 运行日志

快捷键划词无反应

### 期望结果

快捷键划词无反应

### 设备型号 && 系统版本

macOS 14

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by OwnerCM** [comment]
退回2.7.2后功能正常

[2024-08-13 11:00:50.141 ● EZEventMonitor ● 397 ● ℹ️] -[EZEventMonitor autoGetSelectedText:] ● auto get selected text
[2024-08-13 11:00:50.174 ● EZEventMonitor ● 523 ● ❌] -[EZEventMonitor getSelectedTextByAccessibility:] ● Accessibility error: -25205
[2024-08-13 11:07:12.371 ● EZWindowManager ● 720 ● ℹ️] -[EZWindowManager selectTextTranslate] ● selectTextTranslate windowType: 2
[2024-08-13 11:07:12.422 ● EZEventMonitor ● 521 ● ❌] -[EZEventMonitor getSelectedTextByAccessibility:] ● Accessibility error: -25205

**Comment by ItsRyanWu** [comment]
所有内容都无法划词翻译...

**Comment by Nat30** [comment]
划词翻译会导致easydict退出

**Comment by Medivh-z** [comment]
发布新版本不自测的吗😂，怎么感觉每次新版本都有坑。

**Comment by daypu** [comment]
浏览器里的文本没法划词翻译了，但是设置里开启强制取词可用

**Comment by OwnerCM** [comment]
> 发布新版本不自测的吗😂，怎么感觉每次新版本都有坑。

每个人的设备环境不一样，不能以偏概全。而且tisfeng纯粹的用爱发电，我们要理解他、爱护他。
个人感觉Easydict是开源中最好用的。

**Comment by Medivh-z** [comment]
> > 发布新版本不自测的吗😂，怎么感觉每次新版本都有坑。
> 
> 每个人的设备环境不一样，不能以偏概全。而且tisfeng纯粹的用爱发电，我们要理解他、爱护他。 个人感觉Easydict是开源中最好用的。

确实，我的问题，删了

**Comment by wudb** [comment]
确实不能划词翻译了，感谢作者的付出

**Comment by tisfeng** [comment]
> 快捷键划词无反应

之前版本为了确保取词成功，会在常规取词失败时使用 Cmd + C 取词，但有用户反馈这样可能会导致剪贴板问题 https://github.com/tisfeng/Easydict/issues/608#issuecomment-2273432100  ，因此，新版本修改了取词逻辑，默认只使用 Accessibility 取词。

部分应用（例如 Teams）可能不支持 Accessibility 取词，此时 Easydict 无法取词是正常的。

如果你希望能够在所有应用中取词成功，请开启【强制取词】。

<img width="900" alt="67249" src="https://github.com/user-attachments/assets/be5492d8-b47b-4221-a1ab-3b1425dcf527">

**Comment by tisfeng** [comment]
> 浏览器里的文本没法划词翻译了，但是设置里开启强制取词可用

浏览器也是类似情况， 例如苹果的 Safari 就不支持 Accessibility。

对于浏览器，建议开启【允许 Apple 事件中的 JavaScript 选项】，详情请看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E6%9F%90%E4%BA%9B%E5%BA%94%E7%94%A8%E4%B8%AD%E5%8F%96%E8%AF%8D%E6%96%87%E6%9C%AC%E4%B8%BA%E7%A9%BA)

**Comment by tisfeng** [comment]
> 划词翻译会导致easydict退出
> 
> MacOS: 15.0 Beta版(24A5320a)MacOS：15.0 测试版(24A5320a)

我没有在 Beta 系统测试过，不清楚新系统苹果是否修改了什么 API。

建议你另外开一个 issue，稍后我们跟进看看，记得附上崩溃日志。

**Comment by Roiocam** [comment]
> > 快捷键划词无反应
> 
> 之前版本为了确保取词成功，快捷键取词会在常规取词失败时使用 Cmd + C 取词，但有用户反馈这样可能会导致剪贴板问题 [#608 (comment)](https://github.com/tisfeng/Easydict/issues/608#issuecomment-2273432100) ，因此，新版本修改了取词逻辑，默认只使用 Accessibility 取词。

Cool, thanks.

**Comment by gang83211** [comment]
不開啟強制取詞，也不開啟「划詞翻譯未選中文本時，保留上次結果」，就會退出

**Comment by tisfeng** [comment]
> 不開啟強制取詞，也不開啟「划詞翻譯未選中文本時，保留上次結果」，就會退出不开启强制取词，也不开启「划词翻译未选中文本时，保留上次结果」，就会退出

当前 issue 应该已经解决，关于你这个应用崩溃问题，请另外单独开一个 issue，记得附上崩溃日志。

**Comment by OwnerCM** [comment]
> > 快捷键划词无反应
> 
> 之前版本为了确保取词成功，快捷键取词会在常规取词失败时使用 Cmd + C 取词，但有用户反馈这样可能会导致剪贴板问题 [#608 (comment)](https://github.com/tisfeng/Easydict/issues/608#issuecomment-2273432100) ，因此，新版本修改了取词逻辑，默认只使用 Accessibility 取词。
> 
> 部分应用（例如 Teams）可能不支持 Accessibility 取词，此时 Easydict 无法取词是正常的。
> 
> 如果你希望能够在所有应用中取词成功，请开启【强制取词】。
> 
> <img alt="67249" width="900" src="https://private-user-images.githubusercontent.com/25194972/357436241-be5492d8-b47b-4221-a1ab-3b1425dcf527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDA3NzQsIm5iZiI6MTcyNzE0MDQ3NCwicGF0aCI6Ii8yNTE5NDk3Mi8zNTc0MzYyNDEtYmU1NDkyZDgtYjQ3Yi00MjIxLWExYWItM2IxNDI1ZGNmNTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAxMTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNDk4ZGMxNTVmMTM4OWJhMDVlMTVmYTA3NjYyOGQyMTg3YWEyYzcwY2Y3NzQzNGRmMjNhZjI4ODkwNmRjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wLXIACgJFTBmGWgBRZ3jCLLzrwhdBMUG1NwOL0W_eOM">

“开启强制划词”后，更新2.9版本又出现了无法快捷划词翻译的问题

**Comment by tisfeng** [comment]
请看这里 https://github.com/tisfeng/Easydict/issues/684#issuecomment-2367972417

如果还有问题，请另外开 issue，记得附上运行日志。
