### ISSUE TITLE
🐞 失败: 令牌 Easydict 内置 AI 翻译（#1）额度已用尽

### ISSUE THREAD

**Issue by valens7** [tisfeng/Easydict#642]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

<img width="575" alt="image" src="https://github.com/user-attachments/assets/9c773445-c2f0-4539-9f66-f654afdb104f">
请参见截图, 失败: 令牌 Easydict 内置 AI 翻译（#1）额度已用尽

### 该问题是否可以稳定重现？

可重现

### 重现步骤

开启翻译就会看到

### 截图

<img width="583" alt="image" src="https://github.com/user-attachments/assets/9216ad60-5b0b-4cbf-b2c0-08b372acb1f4">

### 运行日志

暂时没有

### 期望结果

fixed

### 设备型号 && 系统版本

M2, 15 inch MBA

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
ok，已经充钱了 😶

**Comment by JackeyLov5** [comment]
出现了这个问题 
<img width="405" alt="image" src="https://github.com/user-attachments/assets/d079ffd6-6e27-458d-a241-e0324ff9ad3a">
还有就是有时候比如要点击箭头才会弹出翻译

**Comment by tisfeng** [comment]
我弄了几个 [Groq](https://console.groq.com/) 账号用作内置 AI 翻译服务，之前运行好好的，不知道是不是最近 Easydict 太过高频使用导致被盯上了，这可能不符合他们的服务协议，于是账号被封了 😥

我们提供的这个内置 AI 服务只是为了方便部分用户使用，但不保证可用性。 

建议还是添加一些自己的服务，例如 Groq，免费额度完全够用。

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/cfe8584a-fc45-4025-8a62-f4b023d11491">
