### ISSUE TITLE
🐞 Bug Report: 更新 2.8.0 后，OpenAI 服务中无法验证通过了。

### ISSUE THREAD

**Issue by Sligcm** [tisfeng/Easydict#643]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

OpenAI 服务验证失败。
💥 失败: Incorrect Content-Type: application/json, acceptable type is text/event-stream. This may be caused by a wrong endpoint: https://api.gptsapi.net

看返回的内容应该是 Header 中可以接受的 type 是 text/event-stream，但是 EasyDict 传入了 application/json。

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

原来正常可以验证成功的 OpenAI 服务现在不能验证成功了。

### Screenshot

<img width="900" alt="Snipaste_2024-08-14_11-59-33" src="https://github.com/user-attachments/assets/669780d4-0ee6-4964-a8c1-251ca58aaa05">

### Runtime log

[Easydict log 2024-08-14 12-00-16-393.zip](https://github.com/user-attachments/files/16607441/Easydict.log.2024-08-14.12-00-16-393.zip)

### Expected result

验证成功。

### Device type and OS version

Apple M2 Max Pro, macOS 14.6.1 (23G93)

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR to fix this issue

**Comment by tisfeng** [comment]
请看 https://github.com/tisfeng/Easydict/issues/623

**Comment by Sligcm** [comment]
> 请看 #623

是这个问题，已解决，谢谢。
