### ISSUE TITLE
在excel中选中单元格，使用快捷键查询（cmd + D，弹出的软件界面输入框中没有正确填入选中单元格的词

### ISSUE THREAD

**Issue by meooxx** [tisfeng/Easydict#648]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

在excel中选中单元格，使用快捷键查询（cmd + D），弹出的软件界面的输入框中没有正确填入选中单元格的词

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1 打开excel,选中单元格（单元格中有词）
2 使用快捷键查询
3 此时excel失去焦点，弹出的词典界面出现，但输入框没有填入选中单元格的词
4 上个版本可以正确的查询 （2.7.2）

### 截图

# 选中单元格
1 <img width="522" alt="Screenshot 2024-08-18 at 14 53 00" src="https://github.com/user-attachments/assets/08c3f728-b84d-4825-8b54-58086902f08e">
```
# 使用快捷键后, 输入框内无选中单元格中的词
```
2 
<img width="1565" alt="Screenshot 2024-08-18 at 14 53 46" src="https://github.com/user-attachments/assets/d12e0505-825b-4328-a58c-0b7575fc58ad">

### 运行日志

[com.izual.Easydict 2024-08-17--21-57-40-311.log](https://github.com/user-attachments/files/16647480/com.izual.Easydict.2024-08-17--21-57-40-311.log)

### 期望结果

修复到上个版本的行为，即在excel中选中单元格，使用快捷键查询，可以正确的查询单元格内单词

### 设备型号 && 系统版本

Apple m1 && mac os 14.3

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by Jerry23011** [comment]
请尝试在设置中打开

**Comment by meooxx** [comment]
> 请尝试在设置中打开“允许强制取词” <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/89069957/358890049-90e7d096-9244-4815-b5b2-1617261fdc70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjU1NjMsIm5iZiI6MTcyMzk2NTI2MywicGF0aCI6Ii84OTA2OTk1Ny8zNTg4OTAwNDktOTBlN2QwOTYtOTI0NC00ODE1LWI1YjItMTYxNzI2MWZkYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3MTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlM2NiMmI3Yjg4MWI4ZmUwMDNkNDAzNWQwYjk3MDFlMWYzY2Y2ZmJkZDM5NzIzZWY4ODhkNjA3ZTk3MTJjMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8-BinP7iL3ZsFkzJ2MJZrWw0CoLoji7xCcae_Y0HSQ">

it works but 我在重新查找了相关日志发现这条```改进了一些可能导致剪贴板复制问题的代码。 https://github.com/tisfeng/Easydict/issues/608```，这个选项难道在上个版本是默认开启，然后在最新版本里面改成默认关闭？ 然后上述所提到的issue的修复手段是改成默认关闭吗？ 🤔

**Comment by Jerry23011** [comment]
> 这个选项难道在上个版本是默认开启，然后在最新版本里面改成默认关闭？ 然后上述所提到的issue的修复手段是改成默认关闭吗？ 🤔

相关的改动在这个 PR 中 ，应该只是减少了 ⌘C 的使用，我看代码中一直都是默认关闭的 https://github.com/tisfeng/Easydict/pull/632 https://github.com/tisfeng/Easydict/blob/f18eb571e324dacb6b96ff095248c5e3071ff105/Easydict/objc/EventMonitor/EZEventMonitor.m#L592




objc我看不太懂，更具体的就需要请教 @tisfeng 了

**Comment by tisfeng** [comment]
【强制取词】默认是关闭的，之前版本为确保取词成功，即使未开启【强制取词】，快捷键取词失败时也会使用 Cmd + C 强制取词 https://github.com/tisfeng/Easydict/issues/640#issuecomment-2286322490 。
