### ISSUE TITLE
🚀 功能建议：能否支持阿里翻译 

### ISSUE THREAD

**Issue by echosoar** [tisfeng/Easydict#65]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

能否支持阿里翻译，之前使用 bob，只有阿里翻译的 ak，bob的界面如下：
![image](https://user-images.githubusercontent.com/14832743/233249047-bf1cedee-2df9-4b37-be11-31ca04f47b28.png)

**Comment by tisfeng** [comment]
额，我没用过阿里翻译，请问它和目前已有的翻译服务相比，有什么优点吗？方便的话，可以列举一些翻译示例，对比展示一下。

**Comment by rainzm** [comment]
@tisfeng 抱歉 我最近太忙了 而且我对objc和switft也知之甚少 我最近无法参与这个项目了 十分抱歉

**Comment by tisfeng** [comment]
@choykarl 你有空可以做一下这个吗？正好每人都用 Swift 写一个服务，方便后面大家都来用 Swift 编写和维护。

**Comment by choykarl** [comment]
> @choykarl 你有空可以做一下这个吗？正好每人都用 Swift 写一个服务，方便后面大家都来用 Swift 编写和维护。

@tisfeng 好，我稍后可以看看，紧急吗

**Comment by tisfeng** [comment]
不急，这周末先发你之前完成的 Bing 词典，下周看情况发腾讯翻译  #240 ，阿里翻译这个可以排后面。

**Comment by tisfeng** [comment]
这个怎么样了？如果做完了，下个版本就可以发这个。

**Comment by choykarl** [comment]
> 这个怎么样了？如果做完了，下个版本就可以发这个。

还没呢，这周准备开始弄。

**Comment by tisfeng** [comment]
[2.5.0](https://github.com/tisfeng/Easydict/releases/tag/2.5.0) 版本已支持阿里翻译。
