### ISSUE TITLE
🐞 反馈问题：「划词翻译未选中文本时，保留上次结果」关闭时，仍会保留上次结果

### ISSUE THREAD

**Issue by daypu** [tisfeng/Easydict#657]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

使用option+d进行划词翻译，但是当「划词翻译未选中文本时，保留上次结果」关闭时，仍会保留上次结果
 在浏览器（我用的是Arc），macos自带预览和文本编辑中，该问题均可以重现

### 该问题是否可以稳定重现？

可重现

### 重现步骤

使用option+d进行划词翻译

### 截图

https://github.com/user-attachments/assets/47e5d473-4750-4c1c-80e4-2fe4e9f944d0

### 运行日志（zip 文件）

[MMLogs.zip](https://github.com/user-attachments/files/16738777/MMLogs.zip)

### 期望结果

「划词翻译未选中文本时，保留上次结果」关闭时，不会保留上次结果，输入框应该是空的

### 设备型号 && 系统版本

Apple M1 Pro, macOS 14.3.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
ok，下个版本将会修复。

**Comment by tisfeng** [comment]
看了一下日志，你的 Arc 浏览器似乎不支持 Accessibility 取词，和这里 https://github.com/tisfeng/Easydict/issues/622#issuecomment-2297872203 一样，但在我和 @Jerry23011 电脑上测试是支持 Accessibility 的 🤯 

可能 Arc 确实有点怪。

```
[2024-08-25 10:28:51.993 ● EZEventMonitor ● 624 ● ℹ️] -[EZEventMonitor shouldUseSimulatedKey:error:] ● Unsupported Accessibility App: Arc (company.thebrowser.Browser)
```

**Comment by Jerry23011** [comment]
我之前也有测试调整 Arc 的一些设置，但是试了一圈没找到不支持 Accessibility 的情况

**Comment by tisfeng** [comment]
你好，[2.9.0](https://github.com/tisfeng/Easydict/releases/tag/2.9.0) 版本已修复该问题。
