### ISSUE TITLE
哇哦 这和chrome里的那个划词翻译插件好像哦,不过多了一个可以添加朗文词典的功能很好,可以做到chrome扩展程序里吗,这样就不用每台电脑都装了

### ISSUE THREAD

**Issue by imbigyellow** [tisfeng/Easydict#660]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

哇哦 这和chrome里的那个划词翻译插件好像哦,不过多了一个可以添加朗文词典的功能很好,可以做到chrome扩展程序里吗,这样就不用每台电脑都装了

### 使用场景

方便最大化

### 实现方案（可选）

有打算做到浏览器插件里吗

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
我对 Chrome 扩展不太了解，目前没有开发扩展的计划。

如果想要浏览器扩展，可以看看 [ext-saladict](https://github.com/crimx/ext-saladict)

> 多了一个可以添加朗文词典的功能很好

这个功能依赖于苹果的系统词典功能，macOS 上的浏览器扩展应该也能实现。
