### ISSUE TITLE
🚀 功能建议：希望新增「窗口最小化」功能

### ISSUE THREAD

**Issue by amazinglin0** [tisfeng/Easydict#661]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

当鼠标离开了此程序时它便消失在桌面中,这导致我无法同时查看翻译和其他应用程序.
<img width="1432" alt="截屏2024-08-30 下午2 24 20" src="https://github.com/user-attachments/assets/48f6920f-cae7-4da8-880e-5f73621ccc34">

### 使用场景

我希望在使用其他应用程序的时候,可以同步浏览、更改翻译内容

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by imbigyellow** [comment]
左上角的图钉📌按钮没看见吗?先研究一下再提问题

**Comment by amazinglin0** [comment]
搞定

发件人: imbigyellow ***@***.***>
日期: 星期五, 2024年8月30日 下午2:50
收件人: tisfeng/Easydict ***@***.***>
抄送: Cendre Lin ***@***.***>, Author ***@***.***>
主题: Re: [tisfeng/Easydict] 🚀 功能建议：希望新增「窗口最小化」功能 (Issue #661)


左上角的图钉📌按钮没看见吗?先研究一下再提问题
