### ISSUE TITLE
option+d 某些场景画词翻译提取不到

### ISSUE THREAD

**Issue by liuzhe101** [tisfeng/Easydict#663]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

<img width="772" alt="image" src="https://github.com/user-attachments/assets/f161fc15-8c87-4318-a8d8-f3281fa5823f">
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/5cd06893-d583-4701-aff5-f3afa929cfe0">

### 该问题是否可以稳定重现？

可重现

### 重现步骤

画词，然后option+d

### 截图

问题描述

### 运行日志（zip 文件）

[com.izual.Easydict 2024-08-30--13-18-45-704.log](https://github.com/user-attachments/files/16824550/com.izual.Easydict.2024-08-30--13-18-45-704.log)

### 期望结果

软件内能提取到，比如IDEA里面就可以提取到

### 设备型号 && 系统版本

Macos 15.1 beta 3

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
看了一下日志，取词好像是有问题，但没看出具体问题在哪 😓 

你这是是哪个应用中取词失败的？

某些应用取词存在问题 https://github.com/tisfeng/Easydict/issues/84 ，需要特殊处理， VSCode 和 IDEA 已加入白名单，目前只要开启【允许强制划词】，应该就能取词成功。

**Comment by liuzhe101** [comment]
> 看日志，取词看起来是有问题，但没看出具体问题在哪 😓
> 
> 你这是哪个应用中取词失败的？
> 
> 某些应用取词存在问题#84，需要特殊处理， VSCode 和 IDEA 已加入白名单，目前只要开启【允许强制划词】，应该就能取词成功。

好多应用程序都不行，比如QQ，微信，苹果邮箱等其他，可以取到的有：google chrome，IDEA ，safari，苹果信息等等，不确定什么因素导致。

**Comment by tisfeng** [comment]
某些特殊应用，在不同用户电脑上测试取词的结果可能不同，有可能遇到奇怪的失败问题，这点之前我们碰到过，但暂时不知道如何处理。

不过 Chrome 浏览器的兼容性很好，除了支持 Accessibility 取词，还支持 AppleScript 取词，请尝试使用下面命令重置辅助功能 权限，并且开启浏览器中的 允许 Apple 事件中的 JavaScript 选项，详情请看  [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 。

```
tccutil reset Accessibility com.izual.Easydict
```

**Comment by liuzhe101** [comment]
> 某些特殊应用，在不同用户电脑上测试取词的结果可能不同，有可能遇到奇怪的失败问题，这点之前我们碰到过，但暂时不知道如何处理。
> 
> 不过 Chrome 浏览器的兼容性很好，除了支持 Accessibility 取词，还支持 AppleScript 取词，请尝试使用下面命令重置辅助功能 权限，并且开启浏览器中的 允许 Apple 事件中的 JavaScript 选项，详情请看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 。
> 
> ```
> tccutil reset Accessibility com.izual.Easydict
> ```

重制了没有什么效果，和之前一样的，还是取不到

**Comment by tisfeng** [comment]
确认开了【允许强制划词】吗

**Comment by liuzhe101** [comment]
> 开启【允许强制划词】

开启。【允许强制划词】 都能取到了，之前都是软件默认选项

**Comment by mo2g** [comment]
> 确认开了【允许强制划词】吗

2.7.2 不开启 [自动划词失败时，强制划词(实验功能)] 也是可以正常使用
2.8.1 开启 【允许强制划词】才能正常在微信 vscode 之类的软件中使用

**Comment by tisfeng** [comment]
有空记得看一下更新日志 https://github.com/tisfeng/Easydict/releases/tag/2.8.0

另外，某些特殊类应用（例如微信）必须开启【允许强制划词】才能取词，这是某些应用自己的问题。

<img width="1280" alt="27906" src="https://github.com/user-attachments/assets/837c8885-6559-4208-a8ec-da3253cd6be6">

**Comment by tisfeng** [comment]
> > 开启【允许强制划词】
> 
> 开启。【允许强制划词】 都能取到了，之前都是软件默认选项

ok，既然没问题，那就先关闭这个 issue 了。

**Comment by tisfeng** [comment]
我在考虑，是否需要将【允许强制划词】选项修改为默认开启 😔

之前为了避免某些潜在的问题 https://github.com/tisfeng/Easydict/issues/640#issuecomment-2286322490 ，于是我们默认关闭了这个选项，因为更希望将这个选项交给用户自己去判断是否要开启，但现在看来，一些用户不怎么看更新日志，也没有主动探索 Easydict 设置更新的习惯，很容易忽略这些功能变动。。。

**Comment by tisfeng** [comment]
浏览器取词失败问题可能和 https://github.com/tisfeng/Easydict/issues/608#issuecomment-2331955312 有关，下个版本将会修复。
