### ISSUE TITLE
🚀 功能建议：菜单栏的图标大小

### ISSUE THREAD

**Issue by jq6136** [tisfeng/Easydict#665]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

感谢作者大大，软件很棒，但是我发现在使用的过程有个小小的问题，就是菜单栏显示的图标会比其他的标志大了一圈，不知道能不能解决一下呢，感谢！

### 使用场景

菜单栏显示的图标会比其他的标志大了一圈

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
我们成员目前没有专职 UI 设计师，这些图标都是我们自己业余制作，或网上搜寻，因此图标可能不是那么完美，但基本上够用。

改进 UI 设计不是我们的强项，如果你有这方面的建议，请提交 PR，并附上合理的说明。
