### ISSUE TITLE
🐞 反馈问题：MacOS 13.4系统下 升级easydict到2.8.1版本，无法开启截图

### ISSUE THREAD

**Issue by Danny-wp** [tisfeng/Easydict#666]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

MacOS 13.4系统下 升级easydict到2.8.1版本，无法开启截图

### 该问题是否可以稳定重现？

可重现

### 重现步骤

MacOS 13.4系统下 升级easydict到2.8.1版本，无法开启截图

### 截图

<img width="733" alt="image" src="https://github.com/user-attachments/assets/ab7cf55d-be0b-4aee-9c5a-6663158eaff9">

### 运行日志（zip 文件）

[Easydict log 2024-09-04 12-28-13-344.zip](https://github.com/user-attachments/files/16860784/Easydict.log.2024-09-04.12-28-13-344.zip)

### 期望结果

可以正常打开截图翻译

### 设备型号 && 系统版本

Apple M1 pro, MacOS 13.4

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
请尝试使用下面命令重置截图权限，然后重新添加权限。

```
tccutil reset ScreenCapture com.izual.Easydict
```

**Comment by Danny-wp** [comment]
It's working, thank you master 🐮

**Comment by Danny-wp** [comment]
fixed
