### ISSUE TITLE
Translate without confirming (Enter)

### ISSUE THREAD

**Issue by kostazzz** [tisfeng/Easydict#671]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Feature description

Translation of inserted or entered text without confirming the Enter key.

### Use case

While entering or inserting text, you must constantly confirm the translation by pressing Enter.

### Proposed solution (optional)

Тranslate immediately as the text is inserted or entered.

### Are you willing to submit a PR to implement this feature

- [ ] I'm willing to submit PR to implement this feature

**Comment by tisfeng** [comment]
I understand that you mean to automatically translate the input text like Google Translate on the web. 

This method may not be suitable for Easydict, so we will not adopt it for the time being.
