### ISSUE TITLE
🐞 反馈问题：无法开机自启动，且设置-隐私-自动化里没有easydict这一项

### ISSUE THREAD

**Issue by wjfu99** [tisfeng/Easydict#673]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [x] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

打开easydict的开机自启动开关后，无法实现自启动，且重复开关或卸载重装后均无法修复

### 该问题是否可以稳定重现？

可重现

### 重现步骤

安装easydict，打开自启动开关

### 截图

<img width="482" alt="image" src="https://github.com/user-attachments/assets/dd4a19aa-6772-442a-bba2-5e4feae53b73">

### 运行日志（zip 文件）

[MMLogs.zip](https://github.com/user-attachments/files/16987369/MMLogs.zip)

### 期望结果

可以实现开机自启动功能

### 设备型号 && 系统版本

Air M1，MacOS Sequoia

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
看一下是不是这个问题 https://github.com/tisfeng/Easydict/issues/646#issuecomment-2293726287

下个版本将会优化开机启动的实现。

**Comment by tisfeng** [comment]
你好，[2.9.0](https://github.com/tisfeng/Easydict/releases/tag/2.9.0) 版本已修复该问题。
