### ISSUE TITLE
🐞 Bug Report: Apple Dict doesn't work in some languages

### ISSUE THREAD

**Issue by windrunner414** [tisfeng/Easydict#677]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

Apple Dict in Easydict returns no result when the query text contains hiragana/katakana (Japanese) or some Swedish letters (å, ä, ö). I only tested Japanese and Swedish, it's possible that all characters other than Chinese and Latin don't work.
For example, はなし:
超級クラウン中日辞典 / クラウン日中辞典 (the built-in one in apple dictionary):
<img width="578" alt="Screenshot 2024-09-16 at 3 45 49 AM" src="https://github.com/user-attachments/assets/b638e07b-0fd4-4518-a489-7c3b43a7fe1d">
Easydict:
<img width="472" alt="Screenshot 2024-09-16 at 3 46 21 AM" src="https://github.com/user-attachments/assets/6cbb33e2-89df-4b9b-9b59-e94be145d11d">

However, 話 will return the correct results
<img width="469" alt="Screenshot 2024-09-16 at 3 48 15 AM" src="https://github.com/user-attachments/assets/023b41f7-1495-48f0-b782-641c91c30af7">

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

1. Enabling 超級クラウン中日辞典 / クラウン日中辞典 in Apple Dictionary
2. Quering any word contains hiragana, e.g. はなし. Apple Dictionary will show the correct result but Easydict will say no result

### Screenshot

<img width="472" alt="Screenshot 2024-09-16 at 3 46 21 AM" src="https://github.com/user-attachments/assets/6cbb33e2-89df-4b9b-9b59-e94be145d11d">

### Runtime log(zip file)

Sorry there are too many menu icons on my laptop and the easydict one is not showing up, I'll try to get the log later

### Expected result

Easydict shows the correct result as Apple Dictionary does

### Device type and OS version

Apple M1 Pro, MacOS 14.6.1

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR to fix this issue

**Comment by windrunner414** [comment]
Just had a look into code. Maybe it doesn't even query the dictionary because word count > 1
https://github.com/tisfeng/Easydict/blob/main/Easydict/objc/Service/Apple/AppleDictionary/EZAppleDictionary.m#L126
https://github.com/tisfeng/Easydict/blob/2d0cf752df5fd3e7f31e5752409c801744d83f2a/Easydict/objc/Utility/EZCategory/NSString/NSString%2BEZUtils.m#L174

It appears Chinese bypasses the word count check in `shouldQueryDictionaryWithLanguage` so it works for Chinese. Not sure why Swedish "välkommen" also returns no result, maybe the word count is not accurate for Swedish?

I don't have a dev environment to debug it now, I probably can take a closer look some time later though.

**Comment by tisfeng** [comment]
ok, I'll take a look at it later.

**Comment by tisfeng** [comment]
This is a bug. 

The Apple dictionary query should not call the `queryTypeWithLanguage` method here because this method is incomplete. Initially, I only considered Chinese and English, and it is not suitable for other languages, such as Japanese.

I have removed this check https://github.com/tisfeng/Easydict/pull/681, and the next version will fix it.

**Comment by tisfeng** [comment]
Hello, the new version [2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0) has fixed this issue.
