### ISSUE TITLE
Select translate doesn't work after Sequoia update

### ISSUE THREAD

**Issue by hyperphysin** [tisfeng/Easydict#678]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

Select translate only works in text editor, etc. It doesn't work with web browsers or pdf viewers.

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

just try to use it.

### Screenshot

![Screenshot 2024-09-17 at 10 19 43 PM](https://github.com/user-attachments/assets/56807057-e2bc-40dd-9c70-73099ddfa80e)
not working with a web browser

![Screenshot 2024-09-17 at 10 20 10 PM](https://github.com/user-attachments/assets/41c82492-21ad-4fd5-b684-b88535690fe7)
working with text editor

### Runtime log(zip file)

.

### Expected result

.

### Device type and OS version

macOS 15

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR to fix this issue

**Comment by tisfeng** [comment]
Please make sure you have enabled the `Allow forced text selection` option.

<img width="900" alt="image" src="https://github.com/user-attachments/assets/f96aef94-55c8-4e07-9ba8-0aa3b5017384">

**Comment by tisfeng** [comment]
Why don't you upload Runtime log?

**Comment by hyperphysin** [comment]
> Please make sure you have enabled the `Allow forced text selection` option.
> 
> <img alt="image" width="900" src="https://private-user-images.githubusercontent.com/25194972/368196949-f96aef94-55c8-4e07-9ba8-0aa3b5017384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODU3MTQsIm5iZiI6MTcyNjU4NTQxNCwicGF0aCI6Ii8yNTE5NDk3Mi8zNjgxOTY5NDktZjk2YWVmOTQtNTVjOC00ZTA3LTliYTgtMGFhM2I1MDE3Mzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE1MDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YzQ0OWRiYTllN2IzNzlhNzcwNmNmY2NkYmQxMTJlYTc1M2Q3YzhkNjA0OWFhNGVjMzA2MWE5ZmQyMTg4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ppB6fMVr7WC0NY9hyEJEjGJ7zazg5dJQsdT7jm65urc">

This works. Thank you :)

**Comment by hyperphysin** [comment]
> Why don't you upload Runtime log?

just out of curiosity, how do I uplead runtime log?

**Comment by tisfeng** [comment]
> Please provide the runtime log for the developer to troubleshoot: menu icon -> Help -> Export log. (Log directory: ~/Library/Caches/com.izual.Easydict/MMLogs)

**Comment by Pikman** [comment]
> Please make sure you have enabled the `Allow forced text selection`option.
> 
> <img alt="image" width="900" src="https://private-user-images.githubusercontent.com/25194972/368196949-f96aef94-55c8-4e07-9ba8-0aa3b5017384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzA1MzgsIm5iZiI6MTczMDczMDIzOCwicGF0aCI6Ii8yNTE5NDk3Mi8zNjgxOTY5NDktZjk2YWVmOTQtNTVjOC00ZTA3LTliYTgtMGFhM2I1MDE3Mzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE0MjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMmU2ZTU2YzMwMWNhOTVlODk5MGQzOWJhYjZmNmUyNDE5YjZiNDNiNjk4MDlhMzdlNjE5MTZmYTk4ZjcyOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rB308Bo2NHwb2INNZQEaPRpUMLPfk5jcjdjhrDy6zj4">

Text is not being selected for me after Sequoia update. I also don't have this option in menu. How it can be solved?

**Comment by Pikman** [comment]
> > Please make sure you have enabled the `Allow forced text selection`option.
> > <img alt="image" width="900" src="https://private-user-images.githubusercontent.com/25194972/368196949-f96aef94-55c8-4e07-9ba8-0aa3b5017384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzA1MzgsIm5iZiI6MTczMDczMDIzOCwicGF0aCI6Ii8yNTE5NDk3Mi8zNjgxOTY5NDktZjk2YWVmOTQtNTVjOC00ZTA3LTliYTgtMGFhM2I1MDE3Mzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE0MjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMmU2ZTU2YzMwMWNhOTVlODk5MGQzOWJhYjZmNmUyNDE5YjZiNDNiNjk4MDlhMzdlNjE5MTZmYTk4ZjcyOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rB308Bo2NHwb2INNZQEaPRpUMLPfk5jcjdjhrDy6zj4">
> 
> Text is not being selected for me after Sequoia update. I also don't have this option in menu. How it can be solved?

Found this option in _Advanced_ tab, thanks
