### ISSUE TITLE
🚀 功能建议：设置固定输入/输出语言

### ISSUE THREAD

**Issue by toooonyy** [tisfeng/Easydict#68]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

能够设置所有模式下默认的输入及输出语言。目前仅有快捷键翻译的时候可以手动设置目标语言。

---
快捷键翻译，
![4](https://user-images.githubusercontent.com/3480434/233351891-63b372d1-e628-4e04-803e-15ee62589041.jpg)
![2](https://user-images.githubusercontent.com/3480434/233351897-8ba01387-d3a3-42d6-bb63-8c9b67009205.jpg)

---
划词长句，识别出是德语，翻译成英文。
![1](https://user-images.githubusercontent.com/3480434/233352068-a170c2fd-d1db-4ad7-b355-168ff21940f6.jpg)

划词检测为英文，翻译成中文。
![3](https://user-images.githubusercontent.com/3480434/233352210-05542477-7c78-40d4-b2d9-0273690f5977.jpg)

### 使用场景（可选）

目前主要用到翻译的地方是德语比较多，deepl德翻中偶尔不太精确，个人会默认让它输出英文翻译。

**Comment by tisfeng** [comment]
了解，后面会将不同模式的设置项分隔开，尽量让用户能够自定义设置。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。

现在可以可以为每种窗口都设置显示或隐藏语言选择栏。
