### ISSUE TITLE
🐞 反馈问题：更新macOS 15以后，Safari浏览器滑词无法显示查询图标

### ISSUE THREAD

**Issue by DojaCat8** [tisfeng/Easydict#680]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

没更新macOS15之前，浏览器滑词能正常弹出查询图标
更新之后失效，重新开启「辅助功能」也失效

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1.更新系统为macOS15

### 截图

<img width="1137" alt="Snipaste_2024-09-18_00-49-01" src="https://github.com/user-attachments/assets/ed753dc4-1810-44d6-85cd-7b3f1f9d8cb4">

### 运行日志（zip 文件）

[Easydict log 2024-09-18 00-49-41-724.zip](https://github.com/user-attachments/files/17032345/Easydict.log.2024-09-18.00-49-41-724.zip)

### 期望结果

支持macOS15系统

### 设备型号 && 系统版本

Apple M2 macOS 15

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
可能是 macOS 15 限制了浏览器 JavaScript 权限，请尝试手动开启，详情查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。

"You must enable 'Allow JavaScript from Apple Events' in the Developer section of Safari Settings to use 'do JavaScript'."

**Comment by DojaCat8** [comment]
感谢回复。
勾选「允许强制取词」之后可以使用。
