### ISSUE TITLE
快捷键划词后迷你窗口内容为空

### ISSUE THREAD

**Issue by SakuraYuki56** [tisfeng/Easydict#684]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

MacOS 15中仅依靠 Accessibility 无法从大多数应用中获取划词内容，必须要开启强制取词

### 该问题是否可以稳定重现？

可重现

### 重现步骤

快捷键划词后迷你窗口内容为空

### 截图

快捷键划词后迷你窗口内容为空

### 运行日志（zip 文件）

[com.izual.Easydict 2024-09-20--02-42-23-029.log](https://github.com/user-attachments/files/17069358/com.izual.Easydict.2024-09-20--02-42-23-029.log)

### 期望结果

修复该bug

### 设备型号 && 系统版本

Apple M1 pro，MacOS 15.0 (24A335)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by abcvav** [comment]
我也遇到了这个问题

**Comment by tisfeng** [comment]
我最近也升级了 macOS 15，暂时没发现异常，大部分应用都是 Accessibility 取词，这点应用一般不会更改，除非苹果突然修改底层 API。

请问在你电脑上测试，哪些应用发生了改变？

**Comment by abcvav** [comment]
不太确定这个问题是不是更了macos 15才出现的，我印象里好像更新macos 15之前也有这个问题？快捷键取词用不了。是不是辅助功能哪项设置什么时候被关闭掉了导致的呢

**Comment by SakuraYuki56** [comment]
> 我最近也升级了 macOS 15，暂时没发现异常，大部分应用都是 Accessibility 取词，这点应用一般不会更改，除非苹果突然修改底层 API。
> 
> 
> 
> 请问在你电脑上测试，哪些应用发生了改变？

目前测试了chrome、arc、reeder、vscode、adobe全家桶、office全家桶都有这个问题，就备忘录里是正常的

**Comment by franklin184** [comment]
> > 我最近也升级了 macOS 15，暂时没发现异常，大部分应用都是 Accessibility 取词，这点应用一般不会更改，除非苹果突然修改底层 API。
> > 请问在你电脑上测试，哪些应用发生了改变？
> 
> 目前测试了chrome、arc、reeder、vscode、adobe全家桶、office全家桶都有这个问题，就备忘录里是正常的

我也有此同樣問題，只有備忘錄是正常的

**Comment by cooderzeng** [comment]
13.5 也有这个问题

**Comment by mokeyjay** [comment]
我也有同样的问题，划词选中后按快捷键呼出的侧边悬浮窗内空白，只能自己手动复制粘贴进去按回车触发翻译。系统版本 14.6.1 (23G93)

**Comment by isahwn** [comment]
同样的问题。
macOS 15，在 mail、Firefox 等中都无法 Alt+D 选中翻译。（已开启 Easydic 的高级兼容模式）

**Comment by tisfeng** [comment]
2.8.0 版本修改了取词逻辑 https://github.com/tisfeng/Easydict/issues/640#issuecomment-2286322490 ，现在默认需要手动开启允许强制取词。

不少软件确实不支持 Accessibility 取词，例如系统邮件，Reeder 等，需要开启强制取。

**Comment by tisfeng** [comment]
在我电脑上测试，Chrome，Arc 和 VScode 都是支持 Accessibility 的， adobe 和 office 我没怎么使用用，不确定。

Chrome 浏览器还另外支持 AppleScript 取词，请确认是否已开启，请查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。

另外有少数软件比较奇特，不同电脑环境上的表现行为可能不一致，例如 Arc https://github.com/tisfeng/Easydict/issues/622#issuecomment-2298900069 。

总之，取词问题比较复杂，如果想省心，请直接开启【允许强制取词】。

**Comment by forrany** [comment]
我也有同样的问题。。。。MacOS 14.4.1

确实是特定软件里无法获取，包括微信、wps 等等，然后 Chrome 里是可以的

**Comment by ace-express** [comment]
我遇到的问题是 Chrome 体系的所有软件取词无效，开启强制取词后有效果， Chrome 体系的意思就是 VSCode 等等这种使用 electron  技术开发的软件

**Comment by tisfeng** [comment]
这个问题我应该已经解释很清楚了，重复没有意义。

所有有关取词失败的问题，请按以下步骤进行：

1. 确保在设置中开启了【允许强制取词】。
2. 如果是浏览器（Safari, Chrome, Edge），请开启【允许 Apple 事件中的 JavaScript 选项】，并确保授予了 Easydict 执行自动化脚本的权限。

如果确认执行了上述步骤后，还有问题，请参考 https://github.com/tisfeng/Easydict/issues/84 。

**Comment by ace-express** [comment]
我知道解决方案， 也解决了， 只是好奇想知道原因， 几个版本之前 没有开启强制取词也是可以的， 最近几个版本好像不太行了， macOS 升级到15.0之前Chrome也是好的， 但是VSCode 不行， 升级知道所有 Chrome 的都不行了。 

强制取词开启后没有问题

**Comment by tisfeng** [comment]
原因一开始就说了：

2.8.0 版本修改了取词逻辑 https://github.com/tisfeng/Easydict/issues/640#issuecomment-2286322490

> 之前版本为了确保取词成功，快捷键取词会在常规取词失败时使用 Cmd + C 取词，但有用户反馈这样可能会导致剪贴板问题 https://github.com/tisfeng/Easydict/issues/608#issuecomment-2273432100 ，因此，新版本修改了取词逻辑，默认只使用 Accessibility 取词。

**Comment by alexya** [comment]
> > 我最近也升级了 macOS 15，暂时没发现异常，大部分应用都是 Accessibility 取词，这点应用一般不会更改，除非苹果突然修改底层 API。
> > 请问在你电脑上测试，哪些应用发生了改变？
> 
> 目前测试了chrome、arc、reeder、vscode、adobe全家桶、office全家桶都有这个问题，就备忘录里是正常的

我也是的~ 
目前只有 Notes 这个app里面，可以Cmd+D 取词，其它的什么slack, chrome, edge，都不行...... 
我已经按照前面的提示，设置“强制”取词了，重启EasyDict了，还是不行呢。
你们是怎么解决这个问题的？

**Comment by ace-express** [comment]
> > > 我最近也升级了 macOS 15，暂时没发现异常，大部分应用都是 Accessibility 取词，这点应用一般不会更改，除非苹果突然修改底层 API。
> > > 请问在你电脑上测试，哪些应用发生了改变？
> > 
> > 
> > 目前测试了chrome、arc、reeder、vscode、adobe全家桶、office全家桶都有这个问题，就备忘录里是正常的
> 
> 我也是的~ 目前只有 Notes 这个app里面，可以Opt+D 取词，其它的什么slack, chrome, edge，都不行...... 我已经按照前面的提示，设置“强制”取词了，automation那儿，也都打开了，重启EasyDict了，还是不行呢。 你们是怎么解决这个问题的？cc: @ace-express

我猜测大概率是你的某一个权限没有开起来， 如果开启了强制取词后。
可以查看一下这个常见问题的列表做一次检查：https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E6%9F%90%E4%BA%9B%E5%BA%94%E7%94%A8%E4%B8%AD%E5%8F%96%E8%AF%8D%E6%96%87%E6%9C%AC%E4%B8%BA%E7%A9%BA
