### ISSUE TITLE
PopClib的划词貌似没有使用command +c，菜单没有闪，空白处拖拽也没有声音，建议参考一下

### ISSUE THREAD

**Issue by SJ19900113** [tisfeng/Easydict#685]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

划词效果

### 使用场景

划词

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR 实现该功能

**Comment by SJ19900113** [comment]
找了下，我也没有找到，看往年的文章，说它也是command + c， 不理解。。

**Comment by tisfeng** [comment]
我最近找到了另一种取词方法，不使用 Cmd+C，而是直接模拟执行菜单项 copy item 动作，理论上这取词方式不会导致菜单栏闪烁，也不会触发提示音。

暂时不确定这种方式的适配性如何，在我电脑上测试，各种 App 都没有问题，但为了防止异常情况，我将它设置为一个可选项，等新版本发布你可以试试。

<img width="900" alt="image" src="https://github.com/user-attachments/assets/4c9a9410-7370-42ae-92d5-8d4e1241a4b0">

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已修复该问题。
