### ISSUE TITLE
🐞 反馈问题：macos15 edge浏览器划词翻译失效

### ISSUE THREAD

**Issue by mqk98** [tisfeng/Easydict#686]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

macos 15正式版以及目前的15.1b5测试版 在edge浏览器中 划词翻译无法触发 划词以后不显示翻译按钮 macos14的时候正常

### 该问题是否可以稳定重现？

可重现

### 重现步骤

升级到macos15 使用edge浏览器划词

### 截图

![QQ_1727178389489](https://github.com/user-attachments/assets/72bff33e-1c84-49db-b6f3-c050f95e9aeb)

### 运行日志（zip 文件）

[Easydict log 2024-09-24 19-47-05-762.zip](https://github.com/user-attachments/files/17113977/Easydict.log.2024-09-24.19-47-05-762.zip)

### 期望结果

解决划词翻译问题

### 设备型号 && 系统版本

2019款MacBook pro 16寸 i9+5500M macos15

### 是否愿意提交 PR 解决该问题？

- [x] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
这个还有问题吗，没问题就先关闭了。
