### ISSUE TITLE
2.7.2版本 开机自启失效

### ISSUE THREAD

**Issue by olrk** [tisfeng/Easydict#687]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [ ] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

2.7.2版本，勾选了开机自启，但是无法生效。查看自动化设置，没有System Event项。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

尝试卸载重新安装，但不起作用

### 截图

<img width="668" alt="image" src="https://github.com/user-attachments/assets/2f646ca6-a669-4303-a09f-49e65a058453">
<img width="598" alt="image" src="https://github.com/user-attachments/assets/d8d72288-79e3-4c9b-b438-6499bc732caf">

### 运行日志（zip 文件）

[Easydict log 2024-09-25 12-00-00-942.zip](https://github.com/user-attachments/files/17124700/Easydict.log.2024-09-25.12-00-00-942.zip)

### 期望结果

能在不升级macos系统的情况下，实现开机自启动

### 设备型号 && 系统版本

Apple M2，macos 12.5

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
请尝试使用命令重置自动化权限，然后重新打开开机自启动选项。

```
tccutil reset AppleEvents com.izual.Easydict
```

**Comment by olrk** [comment]
> 请尝试使用命令重置自动化权限，然后重新打开开机自启动选项。
> 
> ```
> tccutil reset AppleEvents com.izual.Easydict
> ```

执行reset后重新勾选自启动选项，没有弹出申请权限的窗口，重启电脑后也未自启动。
<img width="211" alt="image" src="https://github.com/user-attachments/assets/83455bc2-a7f9-47e8-a04e-229aff996566">

**Comment by tisfeng** [comment]
重置完后，需要重新打开开机自启动选项，这个才能触发申请权限。

如果还是不行，建议升级 Easydict 到最新版本，或者使用系统的登录项，来实现开机启动。

**Comment by olrk** [comment]
> 重置完后，需要重新打开开机自启动选项，这个才能触发申请权限。
> 
> 如果还是不行，建议升级 Easydict 到最新版本，或者使用系统的登录项，来实现开机启动。

用登录项的方式解决了，感谢
