### ISSUE TITLE
🚀 功能建议：优化台前调度下的窗口位置

### ISSUE THREAD

**Issue by Er1cG1ao** [tisfeng/Easydict#689]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

我个人的dock放在了左边所以台前调度自动跑到了右边。而无论是通过快捷键还是鼠标查词呼出的翻译窗口都会在右侧保持一定距离，我猜这是作者大大有意为之，为台前调度留出空间。但是我希望新增一个选项：选择是否忽略台前调度——即使开启了台前调度并且在右侧，仍可以让翻译窗口默认紧贴屏幕右侧，不保留距离。

### 使用场景

在开启右侧台前调度的情况下，仍可以直接让翻译窗口紧贴右上角，不保留与屏幕右边框之间的距离。

### 实现方案（可选）

我个人不懂swiftUI，但是我猜设置窗口位置并不难。逻辑大概就是：当“忽略台前调度”功能关闭时（默认）：窗口呼出时保留一定距离（就像现在一样）。而当“忽略台前调度”功能开启时：窗口呼出时紧贴右上角，不保留距离。

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
ok，明天我看一下。

**Comment by tisfeng** [comment]
> 而无论是通过快捷键还是鼠标查词呼出的翻译窗口都会在右侧保持一定距离，我猜这是作者大大有意为之，为台前调度留出空间。

不不，这个我们并没有处理，我检查了代码，发现这似乎是苹果系统自己做的特殊处理，在开启台前调度后，窗口坐标会自动偏移。

不清楚是不是什么奇怪 bug，我尝试修复，但没有成功。

暂时不知道如何处理 😑

**Comment by Er1cG1ao** [comment]
好吧好吧😂我回头问问几个苹果开发者 看看他们知不知道吧
