### ISSUE TITLE
dev: Unify colours within each section in Advanced Settings

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#690]
Just want to listen from everyone. Do we want to unify the icon background colour in Advanced Settings per section? Please see Advanced Tab in Arc as an example.

想听一下大家的意见，Advanced Settings 里要不要每个 section 的 icon background 颜色统一，具体设计参考 Arc

<img width="796" alt="截屏2024-10-02 23 19 24" src="https://github.com/user-attachments/assets/84cc7d75-ac37-40b5-bb7d-121fb3fe2b2d">

**Comment by phlpsong** [comment]
I prefer the arc style.

**Comment by tisfeng** [comment]
ok, it seems good. 

This way is also simpler. It's not easy to choose an appropriate color for each item 🥹
