### ISSUE TITLE
🐞 Bug Report: Service model title not display correctly in hover state

### ISSUE THREAD

**Issue by phlpsong** [tisfeng/Easydict#691]
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

The service model button display not correctly

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

1. In main window, change one stream service's model by clicking model button
2. Move mouse to the model button, check the title in hover state

### Screenshot

[screen-capture.webm](https://github.com/user-attachments/assets/3a33d420-10e4-43d5-8c0c-ddcdbc41dee2)

### Runtime log(zip file)

NA

### Expected result

Model title display correct

### Device type and OS version

macOS 15.0

### Are you willing to submit a PR to fix this issue?

- [X] I'm willing to submit a PR to fix this issue

**Comment by tisfeng** [comment]
这是 https://github.com/tisfeng/Easydict/pull/647 导致的问题，只在开发环境有影响，且修复 PR 已合并，就先关闭了。
