### ISSUE TITLE
🐞 反馈问题：对于 slack 的支持貌似不是很完善

### ISSUE THREAD

**Issue by trulymust** [tisfeng/Easydict#692]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

Hello, 毋庸置疑的是 Easydict 是一个很棒的软件，它帮助我解决了很多与国外同事沟通上的困难，谢谢各位开发者。
但是在我实际使用过程中发现对于 slack 的支持貌似不是很好，无论我是否开启强制取词都无法直接进行划词翻译。我不知道这是我的个例还是所有人都这样，希望您可以抽空了解一下这个问题。谢谢

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1. 打开 slack
2. 发送一段文本
3. 选取需要翻译的句子后进行划词翻译

### 截图

https://github.com/user-attachments/assets/79c23a45-65c7-4dea-8c5f-5f71f0173856

### 运行日志（zip 文件）

[Easydict log 2024-10-10 15-54-50-355.zip](https://github.com/user-attachments/files/17324449/Easydict.log.2024-10-10.15-54-50-355.zip)

### 期望结果

slack 可以正常进行划词翻译

### 设备型号 && 系统版本

Apple M2, MacOS 15.0.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
ok，我来看一下。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已修复该问题。

如果快捷键强制取词有问题，请尝试新的菜单栏动作取词。
