### ISSUE TITLE
🚀 功能建议：建议新增pdf格式整理功能

### ISSUE THREAD

**Issue by FDULeolu** [tisfeng/Easydict#695]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

在选中一段文字之后点击翻译，会出现因为pdf格式导致的错误换行分段问题，这时候可能会导致翻译结果有误，建议增加pdf格式整理功能，在使用过后可以去除这种错误换行分段，方便使用
<img width="1356" alt="image" src="https://github.com/user-attachments/assets/2a695e99-6717-49af-ad2b-e1479b1a6c1d">

### 使用场景

参考有道翻译的这个功能（图片左下角），在复制pdf内容之后可以一键整理格式，使得翻译更加准确
<img width="380" alt="image" src="https://github.com/user-attachments/assets/a188ee59-ef58-4065-ad87-fe9f08c17918">

### 是否愿意提交 PR 实现该功能

- [x] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
你是指这个 https://github.com/tisfeng/Easydict/issues/513 吗？
