### ISSUE TITLE
🐞 反馈问题：最新版本，苹果词典，折叠再展开窗口，词典内容会丢失样式

### ISSUE THREAD

**Issue by qq420100523** [tisfeng/Easydict#698]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

最新版本，苹果词典，折叠再展开窗口，词典内容会丢失样式

### 该问题是否可以稳定重现？

可重现

### 重现步骤

随意划词，弹出窗口，在苹果词典右上角点击折叠，再展开，内容样式会丢失。

### 截图
<img width="384" alt="SCR-20241017-sbts" src="https://github.com/user-attachments/assets/2063d238-26b6-4792-b3d1-73748d6ce6ca">

<img width="389" alt="SCR-20241017-rxgu" src="https://github.com/user-attachments/assets/a94950ec-5121-47ce-ace2-f85d11c48757">

### 运行日志（zip 文件）

[Easydict log 2024-10-17 20-47-24-598.zip](https://github.com/user-attachments/files/17412631/Easydict.log.2024-10-17.20-47-24-598.zip)

### 期望结果

能正常折叠展开，不影响内容显示。

### 设备型号 && 系统版本

Apple M2 air macOS 15.0.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
ok，我看一下。

**Comment by tisfeng** [comment]
下版本将会修复该问题。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已修复该问题。
