### ISSUE TITLE
优化运行内存占用

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#7]
## 描述问题
在后台运行时间过长的话，内存占用可能会大幅度增加。
图一（前两天测试的）
<img width="1202" alt="截屏2023-01-25 14 20 56" src="https://user-images.githubusercontent.com/51783873/214999833-bc132f95-4123-4e42-a643-0cd3017b9c34.png">

图二（今天测试的）
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/51783873/214999800-5f88af09-c347-4bf6-b878-e690e2b0344d.png">

**Comment by tisfeng** [comment]
收到，感谢反馈。 

内存泄露确实是个大问题，而且 macOS 平台的开发生态太贫瘠了，都没有类似 iOS 平台那种可以自动检测内存泄露的第三方工具。这个只能我再去仔细检查一遍，就很累。。

目前 Easydict 使用的免费翻译服务，大多不是官方 API，而是我自己用了一些奇技淫巧所实现，类似于暗中加载了一个 web 网页，所以性能上（响应速度和内存）比较差，这方面我看看能不能再优化一下。稍后会另外提供这些翻译服务官方的 API 支持，比如 DeepL 和百度等，那时候速度会很快，也不会吃内存了。

**Comment by tisfeng** [comment]
安装包小，是因为 macOS 系统自带 Web 环境。。

逆向破解 API 有点难，我不太擅长这个，而且有些也不稳定。另一方面，破解如果是自己用还好，公开发布的话，担心会有侵权风险。

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已优化了应用运行时内存占用。 

但内存问题比较复杂，目前我只尽量测试优化了一部分，后面若是再出现内存爆炸情况，可再提相应 issue。
