### ISSUE TITLE
🚀 功能建议：有推出win版的计划吗

### ISSUE THREAD

**Issue by ericxiao417** [tisfeng/Easydict#70]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

体验了两天，特别好用，有开发win版的计划吗

**Comment by tisfeng** [comment]
No, https://github.com/tisfeng/Easydict/issues/57
