### ISSUE TITLE
🚀 功能建议：滑词翻译迷你窗口希望只保留翻译结果

### ISSUE THREAD

**Issue by zhangsan08** [tisfeng/Easydict#700]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

滑词翻译迷你窗口希望只保留翻译结果，或者支持去掉翻译原文的配置
<img width="407" alt="image" src="https://github.com/user-attachments/assets/0f79af8f-7c53-4c11-a7c1-c6d37c95c5b7">

### 使用场景

滑词翻译时，往往只关注翻译结果，并不希望在迷你窗口内展示原文，这样会使迷你窗口变的不再mini

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
行，我尝试一下。

**Comment by tisfeng** [comment]
下个版本将会添加。

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已实现该功能。
