### ISSUE TITLE
🐞 反馈问题：输入翻译偶尔闪退

### ISSUE THREAD

**Issue by 0x2E** [tisfeng/Easydict#706]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

使用快捷键唤出「输入翻译」时偶尔闪退。

「输入翻译」启用了 DeepL、有道、Google、自定义的 OpenAI。

### 该问题是否可以稳定重现？

不可重现

### 重现步骤

无法稳定复现。

### 截图

无

### 运行日志（zip 文件）

[Easydict log 2024-10-28 21-05-39-477.zip](https://github.com/user-attachments/files/17542818/Easydict.log.2024-10-28.21-05-39-477.zip)

### 期望结果

不闪退

### 设备型号 && 系统版本

m1, macOS 15.0.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
看了一下日志，确实有几个崩溃记录，但都比较奇怪，看不到具体的崩溃信息。

有时候是会出现这种问题，但我这边无法复现，没办法排查。

**Comment by tisfeng** [comment]
这个先记下了，暂时只处理能复现的问题。
