### ISSUE TITLE
🐞 反馈问题：DeepL 無法翻譯為繁體中文

### ISSUE THREAD

**Issue by Annxxxxxx** [tisfeng/Easydict#709]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

第一語言設定是繁體中文，可是使用 DeepL 翻譯時，文字介面顯示是繁體，但翻譯內容 (用語) 卻是簡體，
點擊網頁連結也是指向簡體中文，請問該如何解決這個問題，是我應該做哪些設定嗎？謝謝 :)

### 该问题是否可以稳定重现？

可重现

### 重现步骤

選取翻譯

### 截图

<img width="351" alt="截圖 2024-10-30 23 49 04" src="https://github.com/user-attachments/assets/29107385-8306-47e8-9641-2ef1c2a97db6">

### 运行日志（zip 文件）

[Easydict log 2024-10-31 00-48-29-487.zip](https://github.com/user-attachments/files/17576328/Easydict.log.2024-10-31.00-48-29-487.zip)

### 期望结果

翻譯為繁體中文

### 设备型号 && 系统版本

macOS Sequoia 15.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
> 第一語言設定是繁體中文，可是使用 DeepL 翻譯時，文字介面顯示是繁體，但翻譯內容 (用語) 卻是簡體，

没看懂，你截图中 INTERNET 的翻译结果 `互聯網` 不是繁体吗？这有问题吗

**Comment by tisfeng** [comment]
> 點擊網頁連結也是指向簡體中文，請問該如何解決這個問題，是我應該做哪些設定嗎？謝謝 :)

因为之前 DeepL 不区分简体繁体，统一都视作简体中文，所以 Easydict 跳转网页也默认是简体中文。

最近 DeepL 支持了 [繁体中文](https://www.deepl.com/zh/blog/deepl-translator-now-supports-traditional-chinese)，稍后我也添加一下这个吧。

**Comment by Annxxxxxx** [comment]
> > 第一語言設定是繁體中文，可是使用 DeepL 翻譯時，文字介面顯示是繁體，但翻譯內容 (用語) 卻是簡體，
> 
> 没看懂，你截图中 INTERNET 的翻译结果 `互聯網` 不是繁体吗？这有问题吗

就是它只是簡轉繁而已，實際上翻譯的是簡體中文
如果是翻譯為繁體 Chinese (traditional) 的話，應該顯示是網際網路，而不是互聯網
![截圖 2024-10-31 21 34 拷貝](https://github.com/user-attachments/assets/6160ad13-9985-4ca6-b075-21c7dd4fdb89)

好比 Blog 翻譯繁體是"部落格"，但軟體翻譯是"博客"，也就是翻譯的其實是簡體中文 Chinese  (simplified)
<img width="345" alt="截圖 2024-10-31 21 43 27" src="https://github.com/user-attachments/assets/2b8b3c7a-cf8d-4f5e-b0f5-0321a93006b4">
![截圖 2024-10-31 21 34 拷貝01](https://github.com/user-attachments/assets/7a30bf09-5d56-49f3-9a05-8ea66a645b16)

**Comment by tisfeng** [comment]
明白了，其实还是同一个问题，因为之前 DeepL 不区分简体繁体，所以这里 DeepL 的繁体翻译，其实 Easydict 内部自己做的简体和繁体之间转换。

现在 DeepL 也支持了繁体中文，Easydict 适配后就正常了。

<img width="399" alt="image" src="https://github.com/user-attachments/assets/12688c9b-1434-4de9-9030-29f39f6fb5d6">

**Comment by tisfeng** [comment]
你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0)  新版本已修复该问题。

**Comment by Annxxxxxx** [comment]
> 你好，[2.10.0](https://github.com/tisfeng/Easydict/releases/tag/2.10.0) 新版本已修复该问题。

謝謝回覆通知！Easydict 是我目前用過最滿意的翻譯軟體，感謝您用心維護。

**Comment by usb007123-sys** [comment]
新手發問，像是使用API去做翻譯的時候，預設ZH就是簡體中文，有繁體中文zh-TW 的選項嗎?

**Comment by tisfeng** [comment]
> 新手發問，像是使用API去做翻譯的時候，預設ZH就是簡體中文，有繁體中文zh-TW 的選項嗎?

有个繁体中文的语言选项，不同翻译服务的语言代码不一样，对于繁体中文，有些可能是 zh-TW，也可能是 zh-hant，具体看文档。
