### ISSUE TITLE
🚀 功能建议：PopClip 扩展

### ISSUE THREAD

**Issue by hululu1068** [tisfeng/Easydict#71]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

希望像Bob一样支持PopClip 扩展

<img width="348" alt="image" src="https://user-images.githubusercontent.com/68652362/234497894-df95938b-bd7d-454c-acda-7f27d7584871.png">

**Comment by tisfeng** [comment]
一种简便的使用方法： https://github.com/tisfeng/Easydict/tree/dev#%E9%85%8D%E5%90%88-popclip-%E4%BD%BF%E7%94%A8
