### ISSUE TITLE
🚀 功能建议：when user open  build in LLMs validate it useable

### ISSUE THREAD

**Issue by AkaShark** [tisfeng/Easydict#714]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

Build in LLMs quota is used up, but I can open it always. I thinks we shuold  validate build in LLMs when user open it.

![CleanShot 2024-11-04 at 23 43 52@2x](https://github.com/user-attachments/assets/a0734c4b-cf1b-4b4a-b95a-d7997c8d443b)

![CleanShot 2024-11-04 at 23 48 50@2x](https://github.com/user-attachments/assets/ff4eca09-828a-4e5a-b413-1a790646bf4c)

### 使用场景

when user open  build in LLMs 

### 是否愿意提交 PR 实现该功能

- [X] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
That may not be necessary.

We can't shut down this service just because the current request is failing, because this quota is uncertain, it changes dynamically, and even if it's temporarily exhausted, it may be added later and be available again.

**Comment by AkaShark** [comment]
> That may not be necessary.
> 
> We can't shut down this service just because the current request is failing, because this quota is uncertain, it changes dynamically, and even if it's temporarily exhausted, it may be added later and be available again.

Yeah, there may be some misunderstandings. I mean to check and prompt the user when the switch is turned on, not to close the service.

**Comment by tisfeng** [comment]
To avoid misuse of the built-in AI service, so I limit its quota, which I usually replenish periodically.

However, we are using some new models for this update, such as glm-4-flash, and since [one-api](https://github.com/songquanpeng/one-api) defaults to a multiplier of 30, it results in a very high quota cost, which uses up the quota all at once.

Now I have set the credit to unlimited. This problem will not occur again.

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/7239fd54-141d-4b56-8d5f-59c849118ca6">

**Comment by tisfeng** [comment]
> > That may not be necessary.
> > We can't shut down this service just because the current request is failing, because this quota is uncertain, it changes dynamically, and even if it's temporarily exhausted, it may be added later and be available again.
> 
> Yeah, there may be some misunderstandings. I mean to check and prompt the user when the switch is turned on, not to close the service.

You're right, if the currently enabled service is in an unavailable state, we should prompt the user and not allow them to enable this service.

**Comment by tisfeng** [comment]
Closed in [2.10.2](https://github.com/tisfeng/Easydict/releases/tag/2.10.2)
