### ISSUE TITLE
🐞 反馈问题：滑词翻译，选中单词，快捷键吊起mini窗口时，时常翻译框没有任何内容

### ISSUE THREAD

**Issue by zhangsan08** [tisfeng/Easydict#718]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

滑词翻译，选中单词，快捷键吊起mini窗口时，时常翻译框没有任何内容，上个版本没有问题，有办法能回到上个版本吗

### 该问题是否可以稳定重现？

可重现

### 重现步骤

滑词翻译，选中单词，快捷键吊起mini窗口时，时常翻译框没有任何内容

### 截图

<img width="452" alt="image" src="https://github.com/user-attachments/assets/c87167d6-30b4-4023-8304-a55faf5d1b12">

### 运行日志（zip 文件）

滑词翻译，选中单词，快捷键吊起mini窗口时，时常翻译框没有任何内容

### 期望结果

滑词翻译，选中单词，快捷键吊起mini窗口时，时常翻译框没有任何内容

### 设备型号 && 系统版本

m3pro

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
请提供运行日志（zip 文件），这是必须项。

开启了强制划词吗，使用的哪种类型？在哪个应用中取词失败？请提供详细的上下文信息。

**Comment by kukat** [comment]
same issue: #723

**Comment by tisfeng** [comment]
> 开启强制划词可以用，但不太想搞乱剪贴板历史

部分应用必须开启强制划词才能取词成功。

即使开启了强制划词，也不会弄乱剪贴板历史。这个功能只是理论上可能会对剪贴板有影响，但实测几乎不会遇到，除非同时还运行了其他类似强制取词的应用。

**Comment by tisfeng** [comment]
这个 issue 长时间没有反馈，就先关闭。
