### ISSUE TITLE
🐞 反馈问题：怎么自行开发插件?

### ISSUE THREAD

**Issue by dengshenkk** [tisfeng/Easydict#719]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

想要开发一个字典功能, 只能提需求吗?  能不能类似bob自己写插件?

### 该问题是否可以稳定重现？

可重现

### 重现步骤

无

### 截图

无

### 运行日志（zip 文件）

无

### 期望结果

无

### 解决方案（可选）

提供插件功能, 让有能力开发的基于基础自行开发插件

### 设备型号 && 系统版本

macos14

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
> 想要开发一个字典功能, 只能提需求吗? 能不能类似bob自己写插件?

你可以直接来 PR，如果你会 Swift 的话。

目前不支持 JS 编写插件。

**Comment by dengshenkk** [comment]
意思以后也是只支持swift类型的插件吗?

**Comment by tisfeng** [comment]
> 意思以后也是只支持swift类型的插件吗?

这是怎么理解的？？

现在只接受 Swift 的功能 PR，未来可能会支持 JS 编写插件功能。
