### ISSUE TITLE
🚀 功能建议：建议加入ChatGPT翻译功能

### ISSUE THREAD

**Issue by txyelva** [tisfeng/Easydict#72]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

手动添加OpenAI的api后，能用ChatGPT翻译！需要这个功能，建议大佬做这个功能！

**Comment by tisfeng** [comment]
https://github.com/tisfeng/Easydict/issues/28

**Comment by tisfeng** [comment]
马上就发新版了，ChatGPT 翻译会有个测试入口。
 
--- 

今天突然涨了很多星星✨，可以问下你们是从哪里来的吗，是被谁推荐了吗 🧐

**Comment by txyelva** [comment]
一个Telegram订阅频道推的：https://t.me/NewlearnerChannel

**Comment by tisfeng** [comment]
哇，感谢 🤩

**Comment by tisfeng** [comment]
请看 https://github.com/tisfeng/Easydict/issues/28#issuecomment-1527827829

**Comment by todaroroad** [comment]
建议加入chatgpt，这个很关键，电报来的，这个能给你带来更多星星

**Comment by Jerry23011** [comment]
> 建议加入chatgpt，这个很关键，电报来的，这个能给你带来更多星星

实际上你现在也可以用 #28

**Comment by tisfeng** [comment]
> 建议加入chatgpt，这个很关键，电报来的，这个能给你带来更多星星

是被哪个电报频道推荐了吗？给个链接，我去看一眼 👀

**Comment by todaroroad** [comment]
https://t.me/yqc_777 这个吧

**Comment by tisfeng** [comment]
和 issue  https://github.com/tisfeng/Easydict/issues/28 重复，关闭。

**Comment by todaroroad** [comment]
https://t.me/atashare 应该是这个
