### ISSUE TITLE
快捷键方式，无法正常查询

### ISSUE THREAD

**Issue by jiangaq** [tisfeng/Easydict#723]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

选“迷你窗口”，解释不更新：
<img width="561" alt="image" src="https://github.com/user-attachments/assets/01e93f34-b6ec-4ccf-a6d1-9009efa4b906">
<img width="868" alt="image" src="https://github.com/user-attachments/assets/ea3db77a-8327-4d7d-b92c-e130abd28ff4">

换了“侧悬浮窗口”，也不对，你看换个词查也不更新解释：
<img width="549" alt="image" src="https://github.com/user-attachments/assets/3b4bb459-ce86-45af-a825-a376ee2b4c8c">

而且我改了这里，也弹出窗口没更新：
<img width="614" alt="image" src="https://github.com/user-attachments/assets/b070df0e-e7fb-469b-b255-2e5732de34f7">

只有划词弹窗口一切都正常

现在用的是最新版本，好像上一个版本还正常的

### 该问题是否可以稳定重现？

可重现

### 重现步骤

如上

### 截图

如上

### 运行日志（zip 文件）

不会弄

### 期望结果

修复bug

### 解决方案（可选）

没有

### 设备型号 && 系统版本

apple intel os 13

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
请确保开启了强制划词。

> 请提供运行日志，方便开发者排查：菜单图标 -> 帮助 -> 导出日志。（日志目录：~/Library/Caches/com.izual.Easydict/MMLogs）

提供日志的方法都说明了，这个不能理解吗？

**Comment by tisfeng** [comment]
> 换了“侧悬浮窗口”，也不对，你看换个词查也不更新解释：

注意，这里有两种类型的窗口，请注意区分。如果不明白，请只使用侧悬浮窗口。
