### ISSUE TITLE
🐞 反馈问题：選取文本後自動顯示查詢圖示開啟後，Excel筐選異常

### ISSUE THREAD

**Issue by calebweixun** [tisfeng/Easydict#728]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

當啟用 "滑鼠划詞查詢"->"選取文本後自動顯示查詢圖示" 選項時，在 Microsoft Excel 中，框選資料格時，會使選取項自動跳掉。整個看起來像是執行了複製。

關掉＂選取文本後自動顯示查詢圖示＂項目，就正常了。

以下是bug呈現錄影：
https://github.com/user-attachments/assets/fbe1d626-294c-45aa-ac77-336c954c0133

### 该问题是否可以稳定重现？

可重现

### 重现步骤

開啟＂選取文本後自動顯示查詢圖示＂後，在Excel中框選任何資料。

### 截图

https://github.com/user-attachments/assets/fbe1d626-294c-45aa-ac77-336c954c0133

### 运行日志（zip 文件）

[Easydict log 2024-11-20 18-40-49-349.zip](https://github.com/user-attachments/files/17829136/Easydict.log.2024-11-20.18-40-49-349.zip)

### 期望结果

修正？
目前我只有在 Excel 遇到，關閉小圖案用快捷鍵我也是可以的～

### 设备型号 && 系统版本

Apple Macbook Air M1,macOS 15.1

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
你好，你的描述我不是很明白，你说的 Excel 异常具体是指什么问题，是选中文本时，左上角菜单栏的编辑按钮会出现闪烁？

**Comment by calebweixun** [comment]
左上角的菜單編輯按鈕會閃爍沒錯，推測應該是框選的時候自動執行了複製，但我沒按任何的快捷鍵。
關掉＂選取文本後自動顯示查詢圖示＂這個設定後就不會有這狀況了。

**Comment by calebweixun** [comment]
也許可以參考 #502 設置黑/白名單的想法，對應用程式進行特定功能的忽略？

**Comment by tisfeng** [comment]
出现闪烁是意料之中，因为 Excel 不支持 Accessibility 取词，因此这里使用了模拟快捷键复制取词。

你可以修改为菜单栏动作取词，这个不会闪烁。

如果你想禁止某些 App 自动取词，可以在禁止名単中添加。

<img width="900" alt="image" src="https://github.com/user-attachments/assets/fa4f7c4f-b01c-4bfc-91bd-c829383843ac">

**Comment by calebweixun** [comment]
Sorry 我可能過於強調選單欄上的閃爍情況，但其實我表達的問題是在框選後自動複製(變成虛線框)的問題，現階段確實把 Excel 加入停用程式(禁止名單)就解決了。

修改了強制取詞類型後的測試：「強制取詞類型」->「選單欄動作複製取詞」
在 Excel 中框選範圍時，框選處自動閃虛線(Excel中只要Copy,Cut都會閃虛線)，確實菜單欄的編輯不會跳一下。

正常情況：
**關閉**「選取文本後自動顯示查詢圖示」後，框選範圍時不會變成虛線框。
https://github.com/user-attachments/assets/711681b5-464e-4c5c-9b17-c3f2b51291c4


不正常情況
**開啟**「選取文本後自動顯示查詢圖示」後，框選範圍會自動變成虛線框。
https://github.com/user-attachments/assets/cb74f131-3fc1-4b3c-b922-84d27255ff61

**Comment by tisfeng** [comment]
明白了，测试发现确实有这个问题，这似乎是 Excel 的一个 feature，在进行表格复制时，就会出现虚线框。

你可以尝试选中表格，然后点击左上角菜单栏编辑-复制，它就会出现虚线框。

Easydict 强制取词就是模拟这一动作，因此也会这个问题。

暂时没有解决办法。
