### ISSUE TITLE
🚀 功能建议：把Easydict翻译弹窗时做成不抢占焦点(focus)的窗口

### ISSUE THREAD

**Issue by imbigyellow** [tisfeng/Easydict#730]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

有没有可能把Easydict翻译弹窗时做成不抢占焦点(focus)的窗口,可以极大提升使用体验。经常有时候只是要复制东西但是光标不小心扫到了划词翻译感应图标导致弹窗原窗口失焦,这时候我光标已经在粘贴的位置了导致没有复制上,必须回来点击原窗口复制.

### 使用场景

无感弹窗,哟哟哟

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by easypickings** [comment]
> 如果在设置中设置窗口显示输入框，当唤醒 Easydict 窗口时，会自动聚焦输入框，这样是为了方便用户输入查询。
> 
> 如果你不希望 Easydict 自动聚焦，可以关闭文本输入框。
> 
> <img alt="image" width="900" src="https://private-user-images.githubusercontent.com/25194972/388952087-3d0892ed-2b39-4937-a5d0-216b121cf9fa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg3OTI5MzcsIm5iZiI6MTc1ODc5MjYzNywicGF0aCI6Ii8yNTE5NDk3Mi8zODg5NTIwODctM2QwODkyZWQtMmIzOS00OTM3LWE1ZDAtMjE2YjEyMWNmOWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI1VDA5MzAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5N2MzOWNhOTliZDAyMTY3ODFiMzNiOWIzYzdiZTQwODQ1NTE1ZTBiMjQ3M2FhZWQ0YTUwZDI4NjkzZDY5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.js0hVJWWIkKT8hSEfoARf7VRP-S1kgE_zfco_8p0MRw">

@tisfeng 是否可能支持在保留文本输入框时不自动聚焦到输入框呢？或者在取消显示输入框时仍然保留显示原文文本的区域？

**Comment by tisfeng** [comment]
该功能已在 Easydict 2.22.0 Beta 版本 中实现。

请更新至最新版本。若要接收 Beta 更新，请前往 Easydict 设置 → 通用，开启“包括 Beta 版本”。

https://github.com/tisfeng/Easydict/releases/tag/2.22.0
