### ISSUE TITLE
dev: Update sample localization PR & Remove en-CA

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#732]
As discussed in https://github.com/tisfeng/Easydict/pull/727#issuecomment-2486047461

TODOs
- Update documentation to use #668 as the sample PR
- Remove en-CA localization

**Comment by tisfeng** [comment]
ok, please remove en-CA localization.

**Comment by tisfeng** [comment]
Closed in [2.10.2](https://github.com/tisfeng/Easydict/releases/tag/2.10.2)
