### ISSUE TITLE
🐞 反馈问题：raycast插件问题

### ISSUE THREAD

**Issue by Stephencccc** [tisfeng/Easydict#733]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

raycast中的easydict插件其中OCR其中deepl翻译有问题，输入apikey以及APIurl后显示403验证错误，deepl是pro版本，放入easydict主程序里倒没有问题

### 该问题是否可以稳定重现？

可重现

### 重现步骤

重复多次还是一样

### 截图

![telegram-cloud-photo-size-1-5053431454045942229-y](https://github.com/user-attachments/assets/7da2779e-6729-4d24-a81e-d4fc58837a2f)
![telegram-cloud-photo-size-1-5053431454045942230-y](https://github.com/user-attachments/assets/bba6882e-b4a5-4274-b41d-ef1804881de7)
![telegram-cloud-photo-size-1-5053431454045942231-y](https://github.com/user-attachments/assets/88e0a702-8239-4855-a1ef-cf62a9877a17)

### 运行日志（zip 文件）

插件日志没找到呀

### 期望结果

希望能解决下

### 设备型号 && 系统版本

apple m4pro. 15.1

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
它们两个代码逻辑应该是一样，Raycast 插件代码我已经很久没有改过了，既然 Easydict macOS 版正常，按理说插件也不应该有问题。

 DeepL API 我只测试过免费版本，我没有 pro key，方便的话，请邮件发我你的 pro key，我这边测试一下。
