### ISSUE TITLE
🐞 反馈问题：macOS15.0无法打开easydict.app v2.10.0 v2.10.1

### ISSUE THREAD

**Issue by cynicalight** [tisfeng/Easydict#740]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

 macOS15.0无法打开easydict.app v2.10.0 v2.10.1，聚焦启动、终端启动、双击启动均无效，查询控制台没有崩溃信息，活动监视器没有相关进程。

复现：删除低版本easydict.app，安装v2.10.0 v2.10.1

### 该问题是否可以稳定重现？

可重现

### 重现步骤

复现：删除低版本easydict.app，安装v2.10.0 v2.10.1

### 截图

无截图

### 运行日志（zip 文件）

[MMLogs.zip](https://github.com/user-attachments/files/17987053/MMLogs.zip)

### 期望结果

可以打开app

### 设备型号 && 系统版本

M1pro, macos15.0

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by cynicalight** [comment]
崩溃日志：
Signal Exception:
Signal SIGSEGV was raised.
Call Stack:
1   libsystem_platform.dylib            0x000000019dd8a184 _sigtramp + 56
2   Easydict                            0x0000000104c6f3fc Easydict + 1815548
3   Easydict                            0x0000000104c78cb1 Easydict + 1854641
4   Easydict                            0x0000000104c6f625 Easydict + 1816101
5   Easydict                            0x0000000104c6f831 Easydict + 1816625
6   Easydict                            0x0000000104c11141 Easydict + 1429825
7   Easydict                            0x0000000104c102ad Easydict + 1426093
8   Easydict                            0x0000000104b77d0d Easydict + 802061
9   libswift_Concurrency.dylib          0x00000002764088a5 _ZL23completeTaskWithClosurePN5swift12AsyncContextEPNS_10SwiftErrorE + 1
threadInfo:
<NSThread: 0x600001fc88c0>{number = 2, name = (null)}




崩溃日志显示了一个典型的段错误（SIGSEGV），这是由于程序试图访问无效的内存地址。以下是对日志的解释：
崩溃原因
Signal SIGSEGV：表示程序试图访问未分配或受保护的内存区域，导致段错误。
调用栈（Call Stack）
libsystem_platform.dylib：系统库中的信号处理函数_sigtramp被调用，通常用于处理信号。
Easydict：多个函数调用来自Easydict，这是导致崩溃的主要模块。具体函数地址和偏移量显示了调用顺序。
libswift_Concurrency.dylib：Swift并发库中的函数completeTaskWithClosure被调用，可能与异步任务的完成有关。
线程信息
NSThread：崩溃发生在一个没有名称的线程（线程号2）。
可能的解决方法
检查内存访问：查看Easydict模块中相关函数的实现，确保没有非法的内存访问。
调试工具：使用调试器（如LLDB）逐步跟踪程序执行，找出具体的崩溃点。
更新依赖：确保所有库和依赖项都是最新版本，以避免已知的bug。
并发问题：如果涉及并发操作，检查是否有竞争条件或未同步的访问。

**Comment by cynicalight** [comment]
v2.9.0版本可以打开

**Comment by tisfeng** [comment]
很奇怪的问题，似乎应用启动就崩溃了，有崩溃日志记录，但没看到具体的问题原因。

你可以使用 [Xcode 本地运行 Easydict](https://github.com/tisfeng/Easydict?tab=readme-ov-file#%E5%BC%80%E5%8F%91%E8%80%85%E6%9E%84%E5%BB%BA) ，看一下具体的崩溃信息吗

**Comment by cynicalight** [comment]
> 很奇怪的问题，似乎应用启动就崩溃了，有崩溃日志记录，但没看到具体的问题原因。
> 
> 你可以使用 [Xcode 本地运行 Easydict](https://github.com/tisfeng/Easydict?tab=readme-ov-file#%E5%BC%80%E5%8F%91%E8%80%85%E6%9E%84%E5%BB%BA) ，看一下具体的崩溃信息吗

我现在更新到 macOS 15.1.1 之后，没有问题了。应该是系统的问题，我的很多app都在 macOS 15.0 崩溃，另外，感谢开发者提供如此好用的软件。
