### ISSUE TITLE
🐞 反馈问题：自己部署deeplx，服务no work时，报错信息很长，超出了屏幕，无法关闭报错弹窗

### ISSUE THREAD

**Issue by chenqx33** [tisfeng/Easydict#742]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

自己部署deeplx，服务no work时，报错信息很长，超出了屏幕，无法关闭报错弹窗

### 该问题是否可以稳定重现？

可重现

### 重现步骤

作者可以自己mock一个很长的报错文本进行复现

### 截图
<img width="743" alt="image" src="https://github.com/user-attachments/assets/ee02602d-75c4-40dd-8873-9dfffdf2de2a">

### 运行日志（zip 文件）

无

### 期望结果

当报错内容比较多的时候希望可以截断，或者hover上去再展示全量的error msg

### 设备型号 && 系统版本

15.0 (24A335)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
行，我来修复一下。

**Comment by tisfeng** [comment]
[2.10.2](https://github.com/tisfeng/Easydict/releases/tag/2.10.2) 版本已修复该问题。
