### ISSUE TITLE
🚀 功能建议：建议增加字符替换功能 如换行替换为空格

### ISSUE THREAD

**Issue by FairyMeng** [tisfeng/Easydict#75]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

针对划词翻译 好多pdf都会自动换行截断翻译 建议增加功能 可以把换行替换为空格

### 使用场景（可选）

阅读论文pdf时
Bob有一个类似的功能，他好像还可以换其他的字符 没仔细看

### 实现方案（可选）

感觉实现起来应该不太困难 识别到\n就换成\t ？但我也不是特别懂 辛苦作者了
你已经是本论文阅读困难者的光了

**Comment by tisfeng** [comment]
稍后会智能换行的， https://github.com/tisfeng/Easydict/issues/16 

---

马上，今天就发新版！

**Comment by tisfeng** [comment]
你好，新版本已修复该问题  https://github.com/tisfeng/Easydict/releases/tag/1.3.0
