### ISSUE TITLE
🐞 反馈问题： About 页面的按钮无法响应点击事件

### ISSUE THREAD

**Issue by tisfeng** [tisfeng/Easydict#750]
很奇怪，之前 https://github.com/tisfeng/Easydict/pull/739 修改过这里的代码，当时测试是没用问题的，但现在 dev 这几个按钮都无法点击了。

我切到之前的节点 024016ea 测试还是不行，甚至使用 [2.10.1](https://github.com/tisfeng/Easydict/releases/tag/2.10.1) 发布版本也一样。

<img width="900" alt="image" src="https://github.com/user-attachments/assets/b6400aef-08b5-4086-bee1-c8572151c381" />

**Comment by tisfeng** [comment]
突然想起，最近我更新了系统版本 15.2 (24C101)，怀疑是苹果又在偷偷修改 SwiftUI 底层实现 https://github.com/tisfeng/Easydict/pull/683#issuecomment-2365140832 ，搞崩了某些功能 😑

**Comment by tisfeng** [comment]
试了一下，发现和这个页面使用的 [Vortex](https://github.com/twostraws/Vortex) 有关，移除它就正常了。

**Comment by Jerry23011** [comment]
之前版本 Vortex 用 ZStack 还是没问题的，可能确实是 SwiftUI 的改动，看来只能暂时和🎉说再见了🥺

我回头研究研究有没有 workaround

**Comment by tisfeng** [comment]
[2.10.2](https://github.com/tisfeng/Easydict/releases/tag/2.10.2) 版本已修复该问题。
