### ISSUE TITLE
应用程序 “Easydict.app”的这个版 本不能与此版本的macos配合使 用。 您使用的是 macos 12.7.6。该应用程序要 求macOs 13.0 或更高版本。

### ISSUE THREAD

**Issue by lhsaq2009** [tisfeng/Easydict#753]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

应用程序 “Easydict.app”的这个版
本不能与此版本的macos配合使
用。
您使用的是 macos 12.7.6。该应用程序要
求macOs 13.0 或更高版本。

### 该问题是否可以稳定重现？

可重现

### 重现步骤

应用程序 “Easydict.app”的这个版
本不能与此版本的macos配合使
用。
您使用的是 macos 12.7.6。该应用程序要
求macOs 13.0 或更高版本。

### 截图

应用程序 “Easydict.app”的这个版
本不能与此版本的macos配合使
用。
您使用的是 macos 12.7.6。该应用程序要
求macOs 13.0 或更高版本。

### 运行日志（zip 文件）

应用程序 “Easydict.app”的这个版
本不能与此版本的macos配合使
用。
您使用的是 macos 12.7.6。该应用程序要
求macOs 13.0 或更高版本。

### 期望结果

应用程序 “Easydict.app”的这个版
本不能与此版本的macos配合使
用。
您使用的是 macos 12.7.6。该应用程序要
求macOs 13.0 或更高版本。

### 解决方案（可选）

应用程序 “Easydict.app”的这个版
本不能与此版本的macos配合使
用。
您使用的是 macos 12.7.6。该应用程序要
求macOs 13.0 或更高版本。

### 设备型号 && 系统版本

应用程序 “Easydict.app”的这个版 本不能与此版本的macos配合使 用。 您使用的是 macos 12.7.6。该应用程序要 求macOs 13.0 或更高版本。

### 是否愿意提交 PR 解决该问题？

- [X] 我愿意提交 PR 来解决该问题

**Comment by tisfeng** [comment]
系统版本低于 macOS 13.0， 请用 [2.7.2 版本](https://github.com/tisfeng/Easydict/releases/tag/2.7.2)
