### ISSUE TITLE
🐞 反馈问题：网易有道词典翻译时出现Request Failed

### ISSUE THREAD

**Issue by lightumcc** [tisfeng/Easydict#754]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

在调用悬浮窗尝试使用有道词典服务进行翻译的时候，无法显示`释义`，会提示
```
💥 失败: Request failed: internal server error (500)

{"code":1,"msg":"request error"}
```

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1. 打开`有道词典`服务
2. 使用快捷键激活侧悬浮窗口
3. 输入任意内容，任意翻译语言
4. 观察错误

### 截图

<img width="439" alt="image" src="https://github.com/user-attachments/assets/94c1c3e0-0130-4061-bb1c-b0cf1478a153" />

### 运行日志（zip 文件）

[com.izual.Easydict 2024-12-19--10-50-10-574.log](https://github.com/user-attachments/files/18204648/com.izual.Easydict.2024-12-19--10-50-10-574.log)

### 期望结果

如README中截图显示
![README示例](https://raw.githubusercontent.com/tisfeng/ImageBed/main/uPic/Log-1688378715.png)

### 设备型号 && 系统版本

Apple M2 Pro, macOS 15.3 Beta (24D5034f)

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by lightumcc** [comment]
似乎通过调用
```
POST /jsonapi_s?doctype=json&jsonversion=4 HTTP/1.1
Host: dict.youdao.com
Content-Length: 11
Accept: application/json, text/plain, */*
Content-Type: application/x-www-form-urlencoded
Origin: https://dict.youdao.com
Referer: https://dict.youdao.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Priority: u=1, i
Connection: keep-alive

q=translate
```
可以在
```
"syno":{"synos":[{"pos":"vt.","ws":["remove","expound"],"tran":"翻译；转化；解释；转变为；调动"},{"pos":"vi.","ws":["interpret"],"tran":"翻译"}],"word":"translate"},
```
这个节点内获得翻译信息

**Comment by WeiFengWa** [comment]
我也遇到了同样的问题，请求的接口并没有500，但是软件显示500

**Comment by YingxueSec** [comment]
我也遇到了

**Comment by wenhw** [comment]
我也一样

**Comment by Jeffield** [comment]
遇到一样的问题

**Comment by ZvnQiy** [comment]
![image](https://github.com/user-attachments/assets/b09c3a4b-4744-4ffd-9a3f-2ecda9f55ac7)
一样的

**Comment by yangjian1218** [comment]
我也遇到了，请求修复

**Comment by HideNameUser** [comment]
我也遇到了，劳烦开发者有空的时候看看

**Comment by FDULeolu** [comment]
+1，一样的问题

**Comment by tisfeng** [comment]
可能是有道翻译的 API 变了，稍后我看一下。

**Comment by tisfeng** [comment]
简单抓包调试发现，secret key 似乎变了，改用新的 key 后接口就正常了。

<img width="400" alt="image" src="https://github.com/user-attachments/assets/e68c235f-a4de-4d1b-af19-fd4ea00b2b99" />

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/183b89a6-ae6b-40c0-bb27-ac96b0f41784" />

**Comment by chouchouxsl** [comment]
> 简单抓包调试发现，secret key 似乎变了，改用新的 key 后接口就正常了。
> 
> <img alt="image" width="400" src="https://private-user-images.githubusercontent.com/25194972/397981784-e68c235f-a4de-4d1b-af19-fd4ea00b2b99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTc4MDksIm5iZiI6MTczNDkxNzUwOSwicGF0aCI6Ii8yNTE5NDk3Mi8zOTc5ODE3ODQtZTY4YzIzNWYtYTRkZS00ZDFiLWFmMTktZmQ0ZWEwMGIyYjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAxMzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYTE0ODI3YzM1ODdjYTcyZTQyOGVhMWFmNDIwYzQ5MzA5NjRmM2RhNmNjZmYyMzY1NzVmZWI4Y2MyOTNjZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YYgUPTBM5IWzvvsxfIPPATyEm-ztYxrSd7V72H9cFqA"> <img alt="image" width="1668" src="https://private-user-images.githubusercontent.com/25194972/397981708-183b89a6-ae6b-40c0-bb27-ac96b0f41784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTc4MDksIm5iZiI6MTczNDkxNzUwOSwicGF0aCI6Ii8yNTE5NDk3Mi8zOTc5ODE3MDgtMTgzYjg5YTYtYWU2Yi00MGMwLWJiMjctYWM5NmIwZjQxNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAxMzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZWJlNDhlNTBmOTY4ODU2ODA3MTQzZjZlOTc2ZDM1NzkyNDdlN2NlMmJmN2E4MmUyZTQ0OWQwNWMzNGE2ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.021reIRnImUPCLv9cslA0vlcP7lLF_chM2vBH7MmeB8">

大佬什么时候更新呢 也一样的问题

**Comment by Wszhdg** [comment]
> 简单抓包调试发现，secret key 似乎变了，改用新的 key 后接口就正常了。
> 
> <img alt="image" width="400" src="https://private-user-images.githubusercontent.com/25194972/397981784-e68c235f-a4de-4d1b-af19-fd4ea00b2b99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MzA3OTAsIm5iZiI6MTczNDkzMDQ5MCwicGF0aCI6Ii8yNTE5NDk3Mi8zOTc5ODE3ODQtZTY4YzIzNWYtYTRkZS00ZDFiLWFmMTktZmQ0ZWEwMGIyYjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA1MDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MGYzYzlhNTZkYjQ0YzFkZGEyNDU5ZGYzZWY5YzAwZjI4NzUwYWZhY2U1MDdlNTA5MmE5Njc3ZDA5OGE1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5neYt5kgPlCCd44zn-N8bkXKzcyV4sXtl2qu2JSE5fA"> <img alt="image" width="1668" src="https://private-user-images.githubusercontent.com/25194972/397981708-183b89a6-ae6b-40c0-bb27-ac96b0f41784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MzA3OTAsIm5iZiI6MTczNDkzMDQ5MCwicGF0aCI6Ii8yNTE5NDk3Mi8zOTc5ODE3MDgtMTgzYjg5YTYtYWU2Yi00MGMwLWJiMjctYWM5NmIwZjQxNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA1MDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MmMyY2I2MzlhNTYyYWU5NTQ3YjQwZmYxNjA3ODU5MzU0OTk5MzFlZjhhMzY4NTQ3ZDcyMTEyMGQ0ZDc1YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AblUX14KHzVTqlEslQ1UCgVzsNDE82yuNbIWCXwc6Co">

作者大大好，我有个建议，可以通过服务器记录key，每次调用从服务器获取即可，比如有道key为A，存储在咱们得服务器，然后每次更新服务器端的即可，避免类似问题，也能快速修复，加上可以自动更新key这样相当于自动维护，除非他们之后彻底修改网页版查询逻辑

**Comment by tisfeng** [comment]
我明白，这里其实也可以模仿有道网页端，改用接口去获取 secret key。

但这样要添加一个新接口，另外就是有道的网页接口不时会发生变动，之前就改过一次了 https://github.com/tisfeng/Easydict/issues/82 ，这次只是简单改个 secret key 还好，要是改了签名算法就麻烦了。

目前有道接口代码是用 objc 写的，我不想在这上面做过多的修改，等后续有空了直接用 Swift 重写、优化一下。

**Comment by tisfeng** [comment]
明天或后天，我会发布一个更新版本。

**Comment by YingxueSec** [comment]
> 明天或后天，我会发布一个更新版本。

谢谢开发者❤️

**Comment by Wszhdg** [comment]
> 我明白，这里其实也可以模仿有道网页端，改用接口去获取 secret key。
> 
> 但这样要添加一个新接口，另外就是有道的网页接口不时会发生变动，之前就改过一次了 #82 ，这次只是简单改个 secret key 还好，要是改了签名算法就麻烦了。
> 
> 目前有道接口代码是用 objc 写的，我不想在这上面做过多的修改，等后续有空了直接用 Swift 重写、优化一下。

我可以尝试写一个全自动获取，跟随网页版自动更新的，如果没问题，就把key的接口发给您

**Comment by chicogithub** [comment]
俺也一样  等大佬更新

**Comment by xuestrange** [comment]
+1

**Comment by wkl007** [comment]
等大佬更新 🙏

**Comment by tisfeng** [comment]
> > 我明白，这里其实也可以模仿有道网页端，改用接口去获取 secret key。
> > 但这样要添加一个新接口，另外就是有道的网页接口不时会发生变动，之前就改过一次了 #82 ，这次只是简单改个 secret key 还好，要是改了签名算法就麻烦了。
> > 目前有道接口代码是用 objc 写的，我不想在这上面做过多的修改，等后续有空了直接用 Swift 重写、优化一下。
> 
> 我可以尝试写一个全自动获取，跟随网页版自动更新的，如果没问题，就把key的接口发给您

行，稍后你可以直接来 PR。

如果你能写 Swift，直接将有道这部分代码重写也可以。

**Comment by tisfeng** [comment]
在准备了，今晚就发新版本。

**Comment by tisfeng** [comment]
[2.10.2](https://github.com/tisfeng/Easydict/releases/tag/2.10.2) 版本已发布。

**Comment by hitolz** [comment]
2.10.2 版本 有道开启不了
<img width="883" alt="Google Chrome 2024-12-26 16 17 23" src="https://github.com/user-attachments/assets/e766f920-3796-4ca9-89b2-447708a741f9" />

**Comment by wkl007** [comment]
今天早上试着还好，下午又报 500 了。

![image](https://github.com/user-attachments/assets/98a172ae-213b-4b95-9c15-85d721ec6011)

**Comment by tebie6** [comment]
> 今天早上试着还好，下午又报 500 了。
> 
> ![image](https://private-user-images.githubusercontent.com/23228335/398679393-98a172ae-213b-4b95-9c15-85d721ec6011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDU3NzgsIm5iZiI6MTczNTIwNTQ3OCwicGF0aCI6Ii8yMzIyODMzNS8zOTg2NzkzOTMtOThhMTcyYWUtMjEzYi00Yjk1LTljMTUtODVkNzIxZWM2MDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNGMzMTczYzRlYmQwMDhhYjBmM2YwYTg3ZmE5NDczOTMzZGNkNjUzZjBjYWYxZWNlMzUzMDk1YThjMDA0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4YgqUq6W8kPRxPMzqQF0I71crS-ky1ui-BDOx9Lus2o)

key又更新了😂，可以按照大佬提供的方式自已更改一下

**Comment by Jeffield** [comment]
感觉被有道盯上了

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by misslxs** [comment]
> > 今天早上试着还好，下午又报 500 了。
> > ![image](https://private-user-images.githubusercontent.com/23228335/398679393-98a172ae-213b-4b95-9c15-85d721ec6011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDU3NzgsIm5iZiI6MTczNTIwNTQ3OCwicGF0aCI6Ii8yMzIyODMzNS8zOTg2NzkzOTMtOThhMTcyYWUtMjEzYi00Yjk1LTljMTUtODVkNzIxZWM2MDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNGMzMTczYzRlYmQwMDhhYjBmM2YwYTg3ZmE5NDczOTMzZGNkNjUzZjBjYWYxZWNlMzUzMDk1YThjMDA0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4YgqUq6W8kPRxPMzqQF0I71crS-ky1ui-BDOx9Lus2o)
> 
> key又更新了😂，可以按照大佬提供的方式自已更改一下

请问获取到key后 如何在客户端更新呢。

**Comment by tebie6** [comment]
> > > 今天早上试着还好，下午又报 500 了。
> > > ![image](https://private-user-images.githubusercontent.com/23228335/398679393-98a172ae-213b-4b95-9c15-85d721ec6011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDU3NzgsIm5iZiI6MTczNTIwNTQ3OCwicGF0aCI6Ii8yMzIyODMzNS8zOTg2NzkzOTMtOThhMTcyYWUtMjEzYi00Yjk1LTljMTUtODVkNzIxZWM2MDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNGMzMTczYzRlYmQwMDhhYjBmM2YwYTg3ZmE5NDczOTMzZGNkNjUzZjBjYWYxZWNlMzUzMDk1YThjMDA0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4YgqUq6W8kPRxPMzqQF0I71crS-ky1ui-BDOx9Lus2o)
> > 
> > 
> > key又更新了😂，可以按照大佬提供的方式自已更改一下
> 
> 请问获取到key后 如何在客户端更新呢。

把项目clone到本地，用xcode打开编辑，
修改后执行文章中前4步骤即可 https://blog.csdn.net/qq_37523448/article/details/107838678

**Comment by tisfeng** [comment]
新版本 [2.11.0](https://github.com/tisfeng/Easydict/releases/tag/2.11.0) 已修复该问题。
