### ISSUE TITLE
🚀 功能建议：能否支持自定义proxy设置

### ISSUE THREAD

**Issue by telanflow** [tisfeng/Easydict#756]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 功能描述

希望能增加软件内部的proxy设置，这样google翻译等就不会超时了。

类似这种：
<img width="345" alt="image" src="https://github.com/user-attachments/assets/0eebac53-b3f7-45bd-9915-88727ac2acb4" />

### 使用场景

google翻译/openai翻译 等海外接口

### 是否愿意提交 PR 实现该功能

- [ ] 我愿意提交 PR 实现该功能

**Comment by tisfeng** [comment]
https://github.com/tisfeng/Easydict/issues/557
