### ISSUE TITLE
openai的翻译验证可能过于严格导致出现：失败: 未能读取数据，因为它的格式不正确。

### ISSUE THREAD

**Issue by Wszhdg** [tisfeng/Easydict#757]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

我正确的填写了api地址及秘钥，并且通过抓包也返回了正确的结果，在nextchat等流式传输中api也可用，但是在本app上，会出现失败: 未能读取数据，因为它的格式不正确。以下是返回的结果：
data: {"chatgpt_model":"gpt-4o-mini","choices":[{"delta":{"content":"The translation of \""},"finish_reason":null,"index":0,"logprobs":null}],"conversation_id":"6768d152-419c-8003-abfe-6668020ab470","created":"","id":"aa37f3bd-3b86-4740-b836-5ca20bfac855","object":"chat.completion.chunk","usage":null}

data: {"chatgpt_model":"gpt-4o-mini","choices":[{"delta":{"content":"支持手动设置 OpenAI"},"finish_reason":null,"index":0,"logprobs":null}],"conversation_id":"6768d152-419c-8003-abfe-6668020ab470","created":"","id":"aa37f3bd-3b86-4740-b836-5ca20bfac855","object":"chat.completion.chunk","usage":null}

### 该问题是否可以稳定重现？

可重现

### 重现步骤

点击openai翻译即可重现

### 截图

<img width="916" alt="image" src="https://github.com/user-attachments/assets/9c70923d-fc13-475c-854f-53169b3980be" />

### 运行日志（zip 文件）

[com.izual.Easydict 2024-12-23--01-54-46-505.log](https://github.com/user-attachments/files/18224655/com.izual.Easydict.2024-12-23--01-54-46-505.log)

### 期望结果

可以正确的识别api结果

### 设备型号 && 系统版本

macos13.7

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by Wszhdg** [comment]
目前能怀疑的就是回复的请求头不一致，目前回复的请求头为：Content-Type: text/event-stream; charset=utf-8

**Comment by tisfeng** [comment]
Easydict 目前只保证符合 [OpenAI 官方接口](https://platform.openai.com/docs/api-reference/chat/object) 数据格式的请求能成功，对于一些奇怪的第三方接口，验证失败是正常的。

你示例中数据格式，明显和官方不符，例如返回的模型字段名应该是 model，而不是 chatgpt_model，另外，created 字段应该是 integer 而不是 string 类型。

```json
{
    "chatgpt_model": "gpt-4o-mini",
    "choices": [
        {
            "delta": {
                "content": "支持手动设置 OpenAI"
            },
            "finish_reason": null,
            "index": 0,
            "logprobs": null
        }
    ],
    "conversation_id": "6768d152-419c-8003-abfe-6668020ab470",
    "created": "",
    "id": "aa37f3bd-3b86-4740-b836-5ca20bfac855",
    "object": "chat.completion.chunk",
    "usage": null
}
```
