### ISSUE TITLE
🐞 反馈问题：Mac OS 15.2无法获取截图权限,导致无法截图翻译

### ISSUE THREAD

**Issue by junwei-liu** [tisfeng/Easydict#758]
### 请先确认以下事项：

- [X] 请务必查看 [常见问题](https://github.com/tisfeng/Easydict/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到 [最新版本](https://github.com/tisfeng/Easydict/releases)
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

### 问题描述

**### Mac OS 15.2无法获取截图权限

1. 设置里面已经给予截屏和录屏权限，但是截图时，仍然提示无权限
2. 尝试过去掉权限后重新勾选权限，但是还是不行。**

### 该问题是否可以稳定重现？

可重现

### 重现步骤

1. Mac OS升级到15.2
2. 软件更新到最新。
3. 进行截图翻译，提示没有权限。

### 截图

![QQ20241223-114731](https://github.com/user-attachments/assets/9c06bbf8-8997-42e3-bd7a-1e31531dae6c)
![QQ20241223-114731](https://github.com/user-attachments/assets/b225b846-d812-4190-8899-82db99b3be2a)

### 运行日志（zip 文件）

[Easydict log 2024-12-23 11-55-09-515.zip](https://github.com/user-attachments/files/18224892/Easydict.log.2024-12-23.11-55-09-515.zip)

### 期望结果

可以正常的截图翻译

### 设备型号 && 系统版本

Apple M1 Pro,Mac OS 15.2

### 是否愿意提交 PR 解决该问题？

- [ ] 我愿意提交 PR 来解决该问题

**Comment by oxoxoxox** [comment]
点权限页面最下面的减号，先删掉easydict，然后点加号重新添加easydict app并打开权限

**Comment by junwei-liu** [comment]
是的，这个方法可以
