### ISSUE TITLE
🚀 功能建议：划词翻译能否设置一个开关，我复制东西的时候鼠标经常会碰到划词图标

### ISSUE THREAD

**Issue by bihell** [tisfeng/Easydict#76]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

如标题

**Comment by piliming** [comment]
设置里面显示查询图标，把那个勾去掉就行了啊

**Comment by tisfeng** [comment]
看文档，设置页 🫠
