### ISSUE TITLE
🐞 反馈问题：無法翻譯為繁體中文

### ISSUE THREAD

**Issue by ryanwuson** [tisfeng/Easydict#77]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

<img width="436" alt="iShot_2023-04-28_22 33 29" src="https://user-images.githubusercontent.com/20364388/235176639-54e82235-d7a0-43df-be68-017c243c4ef1.png">
升級到最新版本，「劃詞翻譯」無法翻譯為繁體中文，但「輸入翻譯」大部分可以，除了DeepL外
<img width="396" alt="iShot_2023-04-28_22 38 52" src="https://user-images.githubusercontent.com/20364388/235177676-50fffc0c-81e4-4615-903e-5f297bcbaf97.png">

### 重现步骤

無

### 期望结果

希望可以跟前一版一樣能翻譯為繁體中文

**Comment by tisfeng** [comment]
看起来像是出 bug 了，目前是支持繁体中文的， 你这个可能划词翻译的语言类型出了问题，重启 Easydict 试试 😥

<img width="447" alt="image" src="https://user-images.githubusercontent.com/25194972/235178937-58638790-ea47-4714-8779-8ac8f4637eb9.png">

**Comment by ryanwuson** [comment]
劃詞部分我降版後再升級，就可以翻成繁體中文了，但是DeepL在前一版本是可以翻譯成繁中的，但最新版仍然不行，謝謝您

**Comment by tisfeng** [comment]
有吗 😳  

DeepL 一直都不支持繁体中文的

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/25194972/235181985-a05433b5-c73d-45ea-8f83-b678ea105a14.png">

**Comment by chaniatwang** [comment]
> 有吗 😳
> 
> DeepL 一直都不支持繁体中文的
> 
> <img alt="image" width="1485" src="https://user-images.githubusercontent.com/25194972/235181985-a05433b5-c73d-45ea-8f83-b678ea105a14.png">

上一個版本的確可以讓DeepL翻譯成繁體中文
![SCR-20230428-ueop](https://user-images.githubusercontent.com/56515641/235189032-3c5aea02-abea-4006-b0ba-3457abf61c06.png)

**Comment by tisfeng** [comment]
🥹 明天我查一下，这不知是 bug 还是隐藏的 feature

**Comment by ryanwuson** [comment]
謝謝開發者，DeepL能翻譯成繁中是比較好啦！🤩

**Comment by chrisnch** [comment]
遇到一模一样的问题。上一版翻译繁体中文deepL能显示。更新1.3后显示"翻译失败，不支持的语言: Traditional-Chinese"。最近这礼拜一直在用easydict，已经离不开了哈哈。感谢作者开发了这么优势的翻译器，希望能继续用DeepL翻译繁体中文～

**Comment by tisfeng** [comment]
看来不是个例，可能升级后数据兼容出了问题，能详细描述一下重现步骤吗？稍后我去排查一下

**Comment by chrisnch** [comment]
分别测试了1.2.3和1.3版本，均使用相同设定，自动检测->繁体中文。 1.3显示"翻译失败，不支持的语言: Traditional-Chinese"，但是降级到1.2.3能正常显示翻译的繁体中文。另外我对比过1.2.3版本DeepL的繁体译文，是跟DeepL网页版的简体翻译结果一样的，只是简繁的区别。基本可以确定1.2.3 DeepL繁体的结果的确出自DeepL翻译。但是不能完全確定，因為只測試了一段文字。
<img width="681" alt="1 2 3" src="https://user-images.githubusercontent.com/108147436/235378216-eb1c5522-5726-4a07-93e1-51ee01202a99.png">
<img width="681" alt="1 3" src="https://user-images.githubusercontent.com/108147436/235378218-09ae9dc0-b4b7-42e5-963e-1bfd92f3449f.png">

**Comment by LoganLo130** [comment]
同樣遇到問題，之前用 1.2.3 DeepL能正常翻譯成繁體中文，更新成 1.3 以後就不行了。有嘗試重新安裝成 1.2.3 ，但變成要準備用劃詞就會立刻閃退，再麻煩，謝謝！

**Comment by tisfeng** [comment]
查了一下，发现之前 1.2.3 DeepL 确实支持了繁體中文，这个功能是我通过手动将简体中文转成繁体实现的，而 1.3.0 版本改用了新的接口，忘记把这部份逻辑加上去了 😢 

稍后会发个新版本，让 DeepL 支持繁體中文的。

**Comment by tisfeng** [comment]
为了能更好支持 OpenAI 翻译 https://github.com/tisfeng/Easydict/issues/28#issuecomment-1527827829 ，1.3.0 修改了繁体中文的 language id，导致 1.3.0 和之前的版本不兼容，所以升级后可能出现繁体中文报错问题，这种情况下，重启一下应用应该就能解决。如果之前的翻译语言有选择繁体中文，可能要切换一下别的语言，然后再重新选择繁体中文。

**Comment by chrisnch** [comment]
太感谢了 最近真的每天都在用😄

**Comment by tisfeng** [comment]
你好，新版本已修复该问题 https://github.com/tisfeng/Easydict/releases/tag/1.3.1

**Comment by victor7325** [comment]
你好，今天更新1.3.1，仍然有一樣的問題，重啟app也無效。
![SCR-20230523-kwu](https://github.com/tisfeng/Easydict/assets/16221048/f2f37191-eac8-43fd-971f-f7646b40b60e)
