### ISSUE TITLE
🚀 功能建议：请问是否能加入Alfred的Workflow支持？

### ISSUE THREAD

**Issue by NavinChen** [tisfeng/Easydict#78]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

看到Raycast都有插件了，Alfred没有，所以问一下

**Comment by tisfeng** [comment]
自从 Raycast 出来后，我已经很久没用 Alfred 了，而且 Alfred 插件似乎还是收费的？不太清楚，有了解的小伙伴可以来 PR 🤔

**Comment by ychen-97** [comment]
加一，要是能有Alfred的支持就太好了

**Comment by ringlong** [comment]
同求

**Comment by FLIER001** [comment]
用了一段时间raycast，还是回到了alfred，核心的几个功能还是alfred舒服

**Comment by tisfeng** [comment]
收到，不过插件功能似乎需要 Easydict 支持 AppleScript，这个后面我找时间加一下。

**Comment by liziqiang** [comment]
临时使用可以通过下面方式在 alfred 中使用：keyword -> openURL

<img width="354" alt="image" src="https://github.com/tisfeng/Easydict/assets/208130/f68c1632-55e7-47d0-aa74-e8d6d82a536e">


![image](https://github.com/tisfeng/Easydict/assets/208130/e7b9d3f8-ce2a-4167-a02b-923d6e327010)

**Comment by Ran-Xing** [comment]
URL编码问题

我发现文字会自动转成 特殊编码
测试 -> %e6%b5%8b%e8%af%95%0a

**Comment by Ran-Xing** [comment]
@tisfeng

**Comment by tisfeng** [comment]
请改用最新的 URL scheme 尝试一下  https://github.com/tisfeng/Easydict?tab=readme-ov-file#url-scheme

> Easydict 支持 URL scheme 快速查询：easydict://query?text=xxx，如 easydict://query?text=good。

**Comment by Ran-Xing** [comment]
![image](https://github.com/tisfeng/Easydict/assets/73819467/1c40dcaa-6e99-4821-9d43-063922bb7c8c)
![image](https://github.com/tisfeng/Easydict/assets/73819467/766a3afe-5d70-4153-9c8f-202f34ea980c)
![image](https://github.com/tisfeng/Easydict/assets/73819467/1d4b9a42-cd5d-4835-b9ad-738bb310ef60)
@tisfeng 貌似并不友好

**Comment by Ran-Xing** [comment]
[Easydict.alfredworkflow.zip](https://github.com/tisfeng/Easydict/files/13715958/Easydict.alfredworkflow.zip)

**Comment by Ran-Xing** [comment]
query="$1"
if [ -z "${query}" ]; then
    query="$(pbpaste)"
fi
echo "$query"


easydict://query?text={query}

![image](https://github.com/tisfeng/Easydict/assets/73819467/9556fb4b-756f-4aa9-b01a-d1a5d1347bed)


https://github.com/tisfeng/Easydict/assets/73819467/c51b4ad6-4ef8-4743-94c0-8c6902bd985b

**Comment by tisfeng** [comment]
好像是有点问题，稍后我查一下。

**Comment by tisfeng** [comment]
尝试修复了一下，你试试看。

[Easydict.zip](https://github.com/tisfeng/Easydict/files/13717665/Easydict.zip)

**Comment by Ran-Xing** [comment]
搞定哦！
![image](https://github.com/tisfeng/Easydict/assets/73819467/52f3048e-1c01-4162-878d-6a9283259e71)
![image](https://github.com/tisfeng/Easydict/assets/73819467/81675626-cb32-4019-a2ef-30b2a827ae13)

**Comment by WillSuo-Github** [comment]
求完美支持

**Comment by tisfeng** [comment]
我没用 Alfred，不知道这个怎么弄，你们可以先自己用 [URL Scheme](https://github.com/tisfeng/Easydict?tab=readme-ov-file#url-scheme) 糊一下。

后面我尝试让 Easydict 支持本地 HTTP 请求，将查询接口数据暴露出来，然后用户自己去折腾。

**Comment by tisfeng** [comment]
我之前用 [vapor](https://github.com/vapor/vapor) 写过一点 Swift HTTP 服务器，不知道现在是否有别的好用框架，你可以试一下。

**Comment by WillSuo-Github** [comment]
可以哇  所以我们的目标是本地起一个server去相应翻译的请求是吧?  但是我不的不说,最近时间段的我, 并没有太多时间在这个上边, 一天可能有一个小时的样子. 所以可能会进度比较缓慢, 你看可以吗?

**Comment by tisfeng** [comment]
是的，类似 [Ollama API](https://github.com/ollama/ollama/blob/main/docs/api.md) 这种在本地起个服务器，将 Easydict 的一些功能以接口的形式暴露给外面。

这个不是很急，你先简单看一下我们项目代码，有疑问可以在这个 issue  https://github.com/tisfeng/Easydict/issues/580 下面留言交流。

**Comment by llity** [comment]
> 收到，不过插件功能似乎需要 Easydict 支持 AppleScript，这个后面我找时间加一下。

支持 AppleScript 了吗？没看见示例

**Comment by tisfeng** [comment]
还没支持 AppleScript，主要没想到具体 AppleScript 的使用场景。。。

正好对用 Swift 写服务端感兴趣，就直接支持将 Easydict 作为本地服务器，这个应用应该更广泛，也更方便。

现可使用 HTTP 接口调用一些 Easydict 的功能，目前支持 translate 和 ocr 两个接口，文档还没写，这里有示例 https://github.com/tisfeng/Easydict/pull/619

**Comment by tisfeng** [comment]
目前 Easydict 已经完整支持本地 HTTP 接口请求 https://github.com/tisfeng/Easydict/issues/580 ，用法也很简单，感兴趣的可以尝试自己写 Alfred 插件。
