### ISSUE TITLE
🐞 反馈问题：有道翻译接口故障，只能翻译前半句话，无法翻译完整

### ISSUE THREAD

**Issue by Alphabet1226** [tisfeng/Easydict#82]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

<img width="978" alt="image" src="https://user-images.githubusercontent.com/51783873/235455011-2c7d903b-f525-430d-b710-2880b84bd23f.png">

### 重现步骤

OCR识别长段内容，翻译时只会翻译第一句，后面的就不翻译了。

### 期望结果

完整翻译。

**Comment by tisfeng** [comment]
你好，新版本已修复该问题 https://github.com/tisfeng/Easydict/releases/tag/1.3.1
