### ISSUE TITLE
🐞 反馈问题：触发翻译时，mac 声音卡断

### ISSUE THREAD

**Issue by luckyouo** [tisfeng/Easydict#83]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

## 触发翻译时，mac 声音卡断

当我在听歌时，每次使用划词文本翻译时，电脑声音会卡断一下

### 重现步骤

打开听歌软件，spotify 或者 网易云，使用文本划词翻译时，听歌会有明显的间断

### 期望结果

bug修复

### 设备信息 && 操作系统版本（可选）

Macbook pro 14 m1 pro，系统为最新系统

**Comment by tisfeng** [comment]
感谢反馈，之前为了修复拖动窗口出现的空复制提示音  https://github.com/tisfeng/Easydict/issues/41#issuecomment-1495504097 ，采用了一种比较粗暴的实现方式——短暂静音，所以导致了这个问题 😓

暂时没想到办法完美解决，稍后我优化一下，只在用户当前没有播放音频的时候才启用吧，尽量减少对用户的入侵。

**Comment by tisfeng** [comment]
你好，新版本已修复该问题 https://github.com/tisfeng/Easydict/releases/tag/1.3.1

**Comment by yam-liu** [comment]
线上会议时还是会遇到类似的问题，音频会突然音量降低一下。

**Comment by tisfeng** [comment]
这是已知问题，但目前没有很好的解决办法 https://github.com/tisfeng/Easydict/issues/315#issuecomment-1880012908

**Comment by tisfeng** [comment]
[2.7.2](https://github.com/tisfeng/Easydict/releases/tag/2.7.2) 版本已修复该问题。
