### ISSUE TITLE
🚀 功能建议：翻译原文处理

### ISSUE THREAD

**Issue by tshu-w** [tisfeng/Easydict#86]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

翻译原文处理，选择翻译通常会出现翻译原文不在一行，PDF 中以-换行等情况，建议添加类似 Bob 翻译原文处理选项

<img width="323" alt="Screenshot 2023-05-05 at 18 56 53" src="https://user-images.githubusercontent.com/13161779/236441420-08899e22-9e7d-44ff-b20d-ee08200047d7.png">

**Comment by tshu-w** [comment]
> 对翻译原文进行预处理，这个功能感觉可以有。
> 
> 请问这个具体是什么场景，能给几个具体示例吗
> 
> > 选择翻译通常会出现翻译原文不在一行，PDF 中以-换行等情况

举例：
1. 纯文本邮件（需要将换行转换成空格）
<img width="821" alt="Screenshot 2023-05-05 at 21 12 04" src="https://user-images.githubusercontent.com/13161779/236466777-6ce18ff3-f136-4ce5-aee0-6c66688cc873.png">
复制后内容：

```
This paper evaluates the viability of using fixed language models for
training text classification networks on low-end hardware. We combine language
models with a CNN architecture and put together a comprehensive benchmark with
8 datasets covering single-label and multi-label classification of topic,
sentiment, and genre. Our observations are distilled into a list of trade-offs,
concluding that there are scenarios, where not fine-tuning a language model
yields competitive effectiveness at faster training, requiring only a quarter
of the memory compared to fine-tuning.
```

2. PDF 文件 （需要将 「- 空格去掉」）
<img width="282" alt="Screenshot 2023-05-05 at 21 14 24" src="https://user-images.githubusercontent.com/13161779/236467372-aa2e4ea3-f9a1-4b21-97c2-681966c94e06.png">
复制后内容：

```
Methods of machine learning belong to the standard reper- toire of any data analytics endeavour nowadays. However many machine learning algorithms rely on input in the form of dense numerical vectors, which is in stark contrast to the conventional representation of knowledge graphs. To make KGs usable for machine learning tasks Knowledge Graph Embedding approaches are used to encode KG entities (and sometimes relationships) into a lower-dimensional space.
While there are different paradigms of algorithms most embedding approaches score the plausibility of a given tri- ple (h, r, t), i.e. how likely is this statement to be true. The goal of the algorithm is then to compute the embeddings in such a way that positive examples (triples contained in the
```

**Comment by tshu-w** [comment]
> 第一个，你是用 OCR 取词，它没有处理好换行符吗？还是说，直接在邮件中复制的文本，它带了多余的换行符，需要处理？

上面给的例子是直接在邮件中复制文本，其实想 Markdown 或者 LaTeX 中，换行并不代表新的一个段落，需要一个空行才是新起一个段落。另外试了下 OCR 取上面第二章截图也会出现每一行文字都换行的问题。

**Comment by tisfeng** [comment]
我没用过 LaTeX，对这个不太理解，，如果是下面这种情况，你希望如何对它进行处理？将换成符转成空格？

> 像 Markdown 或者 LaTeX 中，换行并不代表新的一个段落，需要一个空行才是新起一个段落

**Comment by tisfeng** [comment]
1.3.0 版本的 OCR 换行处理有时是不对，这个我会逐步优化算法的。 

最新的代码已经能处理它了，稍后会发个新版本。

<img width="400" alt="image" src="https://user-images.githubusercontent.com/25194972/236632465-f7a43952-b6b8-4bd2-9fca-129a99ace017.png">

**Comment by tshu-w** [comment]
> 我没用过 LaTeX，对这个不太理解，，如果是下面这种情况，你希望如何对它进行处理？将换成符转成空格？
> 
> > 像 Markdown 或者 LaTeX 中，换行并不代表新的一个段落，需要一个空行才是新起一个段落

目前想法是和 Bob 一样，「换行符转换成空格」~~（更高级一点是不是可以由用户设置替换，不过感觉这样有点复杂了）~~

**Comment by tisfeng** [comment]
了解了，后面会考虑的。

**Comment by tisfeng** [comment]
昨天碰到一个「换行符」替换为「空格」的使用场景 https://www.mail-archive.com/xz-devel@tukaani.org/msg00566.html

正好目前快捷动作菜单已完成，这个功能可以安排上了。

```
Progress will not happen until there is new maintainer. XZ for C has sparse 
commit log too. Dennis you are better off waiting until new maintainer happens 
or fork yourself. Submitting patches here has no purpose these days. The 
current maintainer lost interest or doesn't care to maintain anymore. It is sad 
to see for a repo like this.
```

<img width="513" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/dda4be99-107b-46b6-baa5-80a18ef8c16e">

**Comment by tisfeng** [comment]
[2.7.0](https://github.com/tisfeng/Easydict/releases/tag/2.7.0) 版本已实现该功能。

**Comment by tshu-w** [comment]
@tisfeng 你好，没有找到设置的位置，是默认开启么？

**Comment by tisfeng** [comment]
我记得代码是设置默认开启的，你去设置页看看这个选项。

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/8ce409f9-deef-4730-a07d-ae8777b07d32">

**Comment by tshu-w** [comment]
感谢，关闭再打开就显示了
