### ISSUE TITLE
🐞 反馈问题：自动翻译或者点击图标翻译都不能调用翻译功能？

### ISSUE THREAD

**Issue by foxllhl** [tisfeng/Easydict#88]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

鼠标划词翻译只能使用快捷键调用翻译，自动翻译或者点击图标翻译都不能调用翻译功能

### 重现步骤

无

### 期望结果

解决问题

**Comment by tisfeng** [comment]
不理解你的问题 😕 

目前支持快捷键取词翻译和鼠标自动取词翻译，请问你是哪一种（另一种呢？），具体的问题是什么？

在哪个应用中使用的？是取词不成功，还是点击查询图标没有响应？方便的话，请录个视频。

> 鼠标划词翻译只能使用快捷键调用翻译，自动翻译或者点击图标翻译都不能调用翻译功能

**Comment by tisfeng** [comment]
你好，如果应用无法取词，请参考一下这个 issue https://github.com/tisfeng/Easydict/issues/84

**Comment by foxllhl** [comment]
[image: 截屏2023-05-07 09.53.26.png]
[image: 截屏2023-05-07 13.35.17.png]
在这个选择下面，出现上面的情况，但是用快捷键调用就是正常的

Tisfeng ***@***.***> 于2023年5月7日周日 11:58写道：

**Comment by foxllhl** [comment]
旧版本使用点击图标翻译是正常的，

foxlhl Fancy ***@***.***> 于2023年5月7日周日 13:37写道：

**Comment by tisfeng** [comment]
旧版本使用的取词方式很粗暴，可能更有效，但也可能导致一些问题，所以新版本修改了取词方式，目前可能存在类似的问题 https://github.com/tisfeng/Easydict/issues/84

你上传的图片还是视频，好像有问题，看不到。

**Comment by foxllhl** [comment]
我是截图的

Tisfeng ***@***.***> 于2023年5月7日周日 14:40写道：

**Comment by foxllhl** [comment]
词汇能选中，但是不能调出翻译引擎，或者翻译识别不正常，其他方式的翻译都是正常的

foxlhl Fancy ***@***.***> 于2023年5月7日周日 15:17写道：

**Comment by tisfeng** [comment]
不能调出翻译引擎，具体是指什么，鼠标选词后没有显示查询图标？

翻译识别不正常，又是指什么？ 能描述清晰，详细一点吗 😕

前面截图看不到，能重新发一下吗？

> 词汇能选中，但是不能调出翻译引擎，或者翻译识别不正常

**Comment by foxllhl** [comment]
[image: 截屏2023-05-07 09.53.26.png]
通过鼠标划词操作所有词典没有输出结果，
但是通过快捷键输出是正常的。

Tisfeng ***@***.***> 于2023年5月7日周日 17:30写道：

**Comment by foxllhl** [comment]
[image: 截屏2023-05-07 22.05.44.png]
不知道能不能看得见！

foxlhl Fancy ***@***.***> 于2023年5月7日周日 22:04写道：

**Comment by tisfeng** [comment]
你还是换种方式发图片吧，直接用官方客户端，或者网页版。

<img width="977" alt="image" src="https://user-images.githubusercontent.com/25194972/236678383-8981b983-ef3a-4161-b992-069ba41f6b8f.png">

**Comment by foxllhl** [comment]
<img width="1429" alt="截屏2023-05-07 22 05 44" src="https://user-images.githubusercontent.com/66822197/236748106-522c8458-8f95-48fb-812d-b15e4675d459.png">
<img width="568" alt="截屏2023-05-07 13 35 17" src="https://user-images.githubusercontent.com/66822197/236748129-4f9483bc-8f93-437a-8052-015b6e401020.png">

**Comment by foxllhl** [comment]
我前面都是在邮箱里直接回复的，所以看不到图

**Comment by foxllhl** [comment]
今天使用恢复正常了！
