### ISSUE TITLE
icon 圆角边缘有些模糊

### ISSUE THREAD

**Issue by Jerry23011** [tisfeng/Easydict#9]
## 描述问题

应用 icon 的圆角边缘似乎有些模糊（请看下方截图）
<img width="296" alt="截屏2023-02-04 13 34 01" src="https://user-images.githubusercontent.com/89069957/216750737-c87f78e5-7593-4f6f-bab1-fa3564e873d1.png">

## 运行环境

- Device: MacBook Pro 14‘
- macOS:  13.2
- Easydict Version:  1.2.1

**Comment by tisfeng** [comment]
收到，感谢反馈。

**Comment by tisfeng** [comment]
尝试优化了一下，看起来好了一些，虽然图标还是有点糊，但没办法，我不会设计 UI，只能先用土办法弄个将就一下 😭 

后续希望能有 UI 大佬帮忙重新设计一下 🥺

<img width="435" alt="image" src="https://user-images.githubusercontent.com/25194972/218236013-e6f79dab-123a-4e7a-b067-d13006565959.png">

**Comment by Jerry23011** [comment]
我知道一个，我问问ta愿不愿意

**Comment by Jerry23011** [comment]
@Keldos-Li 大佬有时间帮忙设计一个 icon 吗？

**Comment by Keldos-Li** [comment]
诶真的有人找我做吗🥹 我下午可以给你们做一做。

或者把你们原来图标的原稿jpg/png给我，我帮你们把圆角的问题修一下。

**Comment by tisfeng** [comment]
好的，非常感谢 🤗

目前这个圆角是我用软件自动生成的，不确定是否符合苹果设计。另外，它生成的圆角图不知道为啥变模糊了 😭

苹果设计文档：https://developer.apple.com/design/resources/#macos-apps

原图：
<img width="745" alt="iShot_2022-11-16_10 08 21" src="https://user-images.githubusercontent.com/25194972/218247363-c8781fd9-0dd9-4f40-91a1-415af18bd126.png">

圆角：
![Easydict-1024](https://user-images.githubusercontent.com/25194972/218247232-e6b27c50-1e3a-4f1a-9ab7-aee552f6da69.png)

**Comment by Keldos-Li** [comment]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/23137268/218248711-d375c2b2-687c-4bad-93c2-365437d53fb1.png">
或许应该用iconset把这个好好填完整？最早的图标应该是圆角非平滑圆角所以糊了，新的貌似没什么问题……不过我还是用苹果提供的蒙版重新导出了一版。

下载iconset：[icons.iconset.zip](https://github.com/tisfeng/Easydict/files/10712970/icons.iconset.zip)
下载icon.icns：[icon.icns.zip](https://github.com/tisfeng/Easydict/files/10712974/icon.icns.zip)

![icon_1024x1024](https://user-images.githubusercontent.com/23137268/218248787-8bd24727-cf9b-4d4d-940c-f78c10938dcc.png)

**Comment by tisfeng** [comment]
好的！我去试试看效果

**Comment by tisfeng** [comment]
感谢，圆角效果看起来差不多了

<img width="448" alt="image" src="https://user-images.githubusercontent.com/25194972/218263252-331c7245-d97e-4f34-b02c-a7ed437684e1.png">

但是总感觉圆角后的图片有点糊，尤其是把图标与旁边苹果的无边记一对比，不确定是不是我的原图制作方式有问题，所以缩小后糊得比较明显 😑

如果没办法了，暂时就这样吧。

1490*1490
![](https://user-images.githubusercontent.com/25194972/218247363-c8781fd9-0dd9-4f40-91a1-415af18bd126.png)

1024*1024
![](https://user-images.githubusercontent.com/23137268/218248787-8bd24727-cf9b-4d4d-940c-f78c10938dcc.png)

128*128
![icon_128x128](https://user-images.githubusercontent.com/25194972/218263884-66d58e0b-726e-4c87-951e-a29e6b5781cd.png)

**Comment by Keldos-Li** [comment]
你是不是分辨率哪里放错了？我在Xcode里把我的一个项目的图标改成了你这个，打包测试都没你截的那么糊啊……
<img width="547" alt="image" src="https://user-images.githubusercontent.com/23137268/218266378-e5012502-3a3f-4910-a078-4f1fc5c9916b.png">

**Comment by tisfeng** [comment]
不太确定。。第一次开发 macOS App，我就是把你给的图标直接放进去的 😔

<img width="1710" alt="image" src="https://user-images.githubusercontent.com/25194972/218266707-a65b0f9b-443b-48bd-825d-33ee6d9be6a6.png">

或者你帮忙直接跑最新 [dev](https://github.com/tisfeng/Easydict/tree/dev) 分支，看我是不是哪里弄错了

**Comment by Keldos-Li** [comment]
奇怪……我fork一份看看

**Comment by tisfeng** [comment]
> 你是不是分辨率哪里放错了？我在Xcode里把我的一个项目的图标改成了你这个，打包测试都没你截的那么糊啊…… <img alt="image" width="547" src="https://user-images.githubusercontent.com/23137268/218266378-e5012502-3a3f-4910-a078-4f1fc5c9916b.png">
> 
> 参考： <img alt="image" width="1219" src="https://user-images.githubusercontent.com/23137268/218266906-bb614a47-0aeb-48b5-8d19-fe8d380a746a.png"> 或者其实你就只填最后一个图（实际1024x1024）然后直接打包也行啊……不应该这么模糊的。

你这个图标效果看起来才正常。我是直接把所有图片直接拖进去，Xcode 自动填充的，我看了一下也没问题，是对齐的啊。这个会不会和设备型号有关 😯
<img width="316" alt="image" src="https://user-images.githubusercontent.com/25194972/218267415-febdfae6-5057-41da-90ef-4d05f8b94c5d.png">

**Comment by Keldos-Li** [comment]
真的奇怪，我看你放的也没问题啊……不过我自己这儿没装过Cocoa编译不了，就不跑测试了。

我是老的Intel机型，但这个应该没影响吧…………太奇怪了太奇怪了太神奇了。我不理解。
你把跑出来的app显示包内容，Contents/Resources，看看里面的icns文件是啥样的？图标理论上都是由Xcode自动生成的，第一个图标尺寸应该是 256x256像素，144dpi。

或者你清除一下Xcode缓存重新编译试试？

**Comment by tisfeng** [comment]
看了一下 App 包内容，也没问题啊，清空后再次编译也还是一样。。这里面可能有坑，我不理解 🙃
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/25194972/218289277-46c966a6-a921-4e1f-8805-d90af494f2c1.png">

**Comment by tisfeng** [comment]
你能把你的图标测试项目发给我试一下吗？或者你不用跑起来，就帮忙重新配置一下我项目的图标，在 dev 分支提个 PR 就好。

**Comment by Keldos-Li** [comment]
我发了一份到您的commit邮箱。

重新配置图标……可能没法commit提交pr，因为git检测不出改动……要么我给图标文件都换个文件名试试？

**Comment by tisfeng** [comment]
都行，或者你就把你的图标 appiconset 导出给我试试 

<img width="1707" alt="image" src="https://user-images.githubusercontent.com/25194972/218291067-ccb3643b-f805-423d-b51f-44ee301b1c04.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/25194972/218291092-12edc439-defe-4b3a-b642-d3938dadcebf.png">

**Comment by Keldos-Li** [comment]
[white-black-icon.appiconset.zip](https://github.com/tisfeng/Easydict/files/10715242/white-black-icon.appiconset.zip)
您试试？虽然我感觉用处不大……怀疑是Xcode的奇怪的坑、、、、

**Comment by tisfeng** [comment]
还是一样，，头疼，没办法了，这个问题暂时先放着吧 😔

**Comment by Keldos-Li** [comment]
额，我发的邮件竟然被退信了……
那我把我自己打包的测试app贴到这里吧……
[ChuanhuWallpaper-2023-02-12.app.zip](https://github.com/tisfeng/Easydict/files/10715247/ChuanhuWallpaper-2023-02-12.app.zip)

> 这是我和另一位开发者朋友在做的app，然后把你的图标放上去archive出来的……
> （另 这些改动是在我自己的分支上做的，里面有一些我还没push到主分支的新特性~~和新bug~~）
> 也欢迎支持我们的项目：[Chuanhu Wallpaper](https://github.com/GaiZhenbiao/ChuanhuWallpaper)。

**Comment by tisfeng** [comment]
果然，你这个图标在我这显示效果也正常，感觉可能是我的项目配置哪里出了问题 🧐

你可以给个原始项目工程而不是 zip 吗，我想在本地编译打包试试。

<img width="665" alt="image" src="https://user-images.githubusercontent.com/25194972/218298602-3ccead87-9d1d-4df0-bb1c-6c3dcecaac4b.png">

**Comment by tisfeng** [comment]
重置，重新配置了一下图标，可以了 😤

<img width="434" alt="image" src="https://user-images.githubusercontent.com/25194972/218301386-2eb6b43a-01c2-4c6c-8692-79ebc744e06f.png">

**Comment by Jerry23011** [comment]
辛苦🫡

**Comment by tisfeng** [comment]
[新版本 1.2.2 ](https://github.com/tisfeng/Easydict/releases) 已修复了应用图标模糊问题。

**Comment by Keldos-Li** [comment]
Hi, 最近真正从 Bob 转到 EasyDict，又想到这个 issue，觉得 icon 在原来的基础上有不少优化的空间，于是在原图标的基础上稍微重画了一下，不知你们觉得这样是否可好：

![icon_512x512@2x](https://github.com/user-attachments/assets/c2033b40-6d93-4420-ac12-db918e4399e7)

与原图标对比：

<img width="889" alt="image" src="https://github.com/user-attachments/assets/539db912-206f-4fe6-81b0-b460672e3965">

（似乎再开一个issue不太合适，便在这个thread里继续了qwq，如果你们觉得OK我开一个PR，更多修改可以到时候再跟进(´・ω・`)）

**Comment by tisfeng** [comment]
@Keldos-Li ok，你这个图标设计看起来不错 😊

我不会切图，其实原图标是我在网上简单制作，然后用工具切成圆角的，你能进行优化自然是很好。

可以，你开一个 PR，我们来看看效果。

<img width="598" alt="56867" src="https://github.com/user-attachments/assets/d2775b67-64bf-46ea-bd28-80fdb1a9c7c8">
