### ISSUE TITLE
🐞 反馈问题：Easydict在pdf expert不能自动抓取选中的文字

### ISSUE THREAD

**Issue by yinan-c** [tisfeng/Easydict#92]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

我用的是shortcuts ⌥ + D 唤起easydict，虽然可以唤起窗口但是没有抓取pdf expert 3 中的文字，同样的 query icon在pdf expert中也不会出现

### 重现步骤

在pdf中选中文字，然后⌥ + D

### 期望结果

抓取文字并且翻译

**Comment by Jerry23011** [comment]
我可以复现，这个问题可以看一下 #84 
应该是 PDF Expert （bundle id `com.readdle.PDFExpert-Mac`）不支持 macOS Auxiliary 取词导致的，我身边有一台 Mac 上有这款软件，我回头测试一下

**Comment by Jerry23011** [comment]
Debug info:
```2023-05-11 12:12:54.540114+0800 Easydict-Debug[33871:1931344] [EZEventMonitor ● 368 ● I] -[EZEventMonitor getSelectedTextByAuxiliary:] ● Auxiliary error: -25205```

**Comment by tisfeng** [comment]
取词失败这类问题，数量比我想象中的要多 🤔

恰好最近也找到了新思路， 稍后我会优化一下取词动作：

1. 使用快捷键取词时，若 Auxiliary 取词失败， 则直接使用模拟快捷键 Cmd+C 取词，确保能获取到取词文本。
2. 使用鼠标自动取词的逻辑保持不变，遇到不支持的应用，暂时仍使用手动添加白名单方式。

主要是目前鼠标自动取词的判定条件可能有误，如果当前没有选中文本，误判取词空复制可能会有提示音 https://github.com/tisfeng/Easydict/issues/83#issuecomment-1532379361

**Comment by tisfeng** [comment]
你好，新版本已修复该问题 https://github.com/tisfeng/Easydict/releases/tag/1.3.1
