### ISSUE TITLE
🐞 反馈问题：调用系统翻译时报错 “Shortcuts Events”遇到一个错误：未能完成该操作。操作不被允许 

### ISSUE THREAD

**Issue by KenChen1998** [tisfeng/Easydict#94]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

按照文档安装了快捷指令没有进行改动

<img width="324" alt="image" src="https://github.com/tisfeng/Easydict/assets/53257544/a03ecc29-efec-4c53-8212-ac83b8837bee">

尝试使用系统翻译报错
<img width="606" alt="image" src="https://github.com/tisfeng/Easydict/assets/53257544/15ef1729-c4bb-49ab-b968-b4cbfdc99a5c">

### 重现步骤

无

### 期望结果

解决问题

### 设备信息 && 操作系统版本（可选）

Apple M1 Pro， Ventura 13.3.1

**Comment by KenChen1998** [comment]
经测试与第三方内核扩展冲突，已解决

**Comment by dluffymonkey** [comment]
可以问下怎么解决的吗，看不出来与哪个冲突了
