### ISSUE TITLE
🐞 反馈问题：在zotero上无法正常使用划词翻译

### ISSUE THREAD

**Issue by Mokuroh0924** [tisfeng/Easydict#98]
### 请先确认以下事项：

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过问题（包括已关闭的 issue），但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

你好，我使用的是app版本的easydict, 在zotero上无法正常使用划词翻译，但是在raycast版本上可以正常运行，请问是什么原因呢

### 重现步骤

无

### 期望结果

期待反馈！

**Comment by Jerry23011** [comment]
Hi，这个问题可以参考一下 #84 和 #92 

如果可以的话，你可以用 [dev](https://github.com/tisfeng/Easydict/tree/dev) 断点调试一下，看看 Zotero 这个取词错误 error 的值吗
https://github.com/tisfeng/Easydict/blob/4ad7b162c51f2d2290b1b8c51b0468fd599ef297/Easydict/Feature/EventMonitor/EZEventMonitor.m#L437

**Comment by Jerry23011** [comment]
#### App Info
- Zotero 6.0.26
- bundle id `org.zotero.zotero`
#### Debug Info
```2023-05-19 17:53:23.713862+0800 Easydict-Debug[91424:8178206] [EZEventMonitor ● 395 ● I] -[EZEventMonitor getSelectedTextByAuxiliary:] ● Auxiliary error: -25205```

**Comment by tisfeng** [comment]
你好，新版本已修复该问题 https://github.com/tisfeng/Easydict/releases/tag/1.3.1

**Comment by xllgit** [comment]
你好，我使用的是app版本的easydict, 在zotero上无法正常使用划词翻译，在其他应用上没问题

easydict：2.7.2
zotero： 6.0.37
macos：12.7.5

**Comment by Jerry23011** [comment]
@xllgit 我这边测试是好用的，如果是鼠标划词，可以看一下设置中“自动划词失败时，强制划词”这个开没开，如果开了后还是不好用可以重置一下辅助功能权限

**Comment by xllgit** [comment]
> @xllgit 我这边测试是好用的，如果是鼠标划词，可以看一下设置中“自动划词失败时，强制划词”这个开没开，如果开了后还是不好用可以重置一下辅助功能权限

开了强制划词可以了，多谢
