### ISSUE TITLE
🚀 功能建议：允许设置在特定应用中不进行划词翻译

### ISSUE THREAD

**Issue by Kerinlin** [tisfeng/Easydict#99]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Easydict/issues) 页面搜索过（包括已关闭的 issue），未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

允许设置在特定环境或者应用中不进行划词翻译，不会识别选中事件

### 使用场景（可选）

在vscode中，有时候划词软件会影响复制剪贴操作，导致无法正常剪贴(command + x command+v),需要经常(command+c command+x command+v)，我希望的一个效果是当我在某个应用中时，划词翻译不会识别到我的划词行为。

**Comment by Kerinlin** [comment]
或者还有一个想法是，划词翻译是一个开关项，可以自己通过状态栏启用或者关闭划词翻译

**Comment by Jerry23011** [comment]
> 或者还有一个想法是，划词翻译是一个开关项，可以自己通过状态栏启用或者关闭划词翻译

Hi，你说的开关项是指这个吗？
<img width="690" alt="SCR-20230519-jtii" src="https://github.com/tisfeng/Easydict/assets/89069957/5132ac31-992d-4eb6-8681-c2fbc95793fe">

**Comment by Kerinlin** [comment]
> > 或者还有一个想法是，划词翻译是一个开关项，可以自己通过状态栏启用或者关闭划词翻译
> 
> Hi，你说的开关项是指这个吗？ <img alt="SCR-20230519-jtii" width="690" src="https://user-images.githubusercontent.com/89069957/239423067-5132ac31-992d-4eb6-8681-c2fbc95793fe.png">

现在划词在某些场景是不是会模拟ctrl+c操作？我是想他不检测我的划词操作，不会自动ctrl+c

**Comment by Jerry23011** [comment]
> 现在划词在某些场景是不是会模拟ctrl+c操作？我是想他不检测我的划词操作，不会自动ctrl+c

是的，对于一些不支持 Auxiliary 取词的 app 会使用模拟 Cmd+C，但是如果不想在使用光标划词的时候检测可以在设置中关闭划词后自动显示查询图标

> 我希望的一个效果是当我在某个应用中时，划词翻译不会识别到我的划词行为

这个需要一个应用白名单实现

**Comment by leafney** [comment]
遇到了同样的困惑，也是在vscode中遇到 command+c/v 命令出现偶然的无法复制粘贴情况

目前也是在设置中将 `显示查询图标` 这一项给取消勾选了，仅通过快捷键来进行翻译操作

有一个想法：是否可以将菜单栏的图标设置成鼠标左键点击自动获取剪贴板内容进行翻译，右击才打开菜单列表。不过这样操作上确实没有快捷键来的舒服，但也是一种 `能够自主控制是否进行翻译` 的解决方法

**Comment by tisfeng** [comment]
你好，[2.0.1](https://github.com/tisfeng/Easydict/releases/tag/2.0.1) 版本已实现该功能。

> 允许在某些特定应用中不进行鼠标划词，即不显示查询图标，可在【设置-禁止名单】添加。 https://github.com/tisfeng/Easydict/issues/99
